php ./wiki2xml/php/wiki2xml_command.php ../out/00/46/Charles_Farrar_Browne.txt ../out/00/46/Charles_Farrar_Browne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/0b/Symphony_No._9_%28Beethoven%29.txt ../out/01/0b/Symphony_No._9_%28Beethoven%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/b9/Aster_CT-80.txt ../out/01/b9/Aster_CT-80.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/4e/Andy_Warhol.txt ../out/02/4e/Andy_Warhol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/17/Bastille_Day.txt ../out/03/17/Bastille_Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/b1/Bonn.txt ../out/03/b1/Bonn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/4d/ConsequentialIsm.txt ../out/04/4d/ConsequentialIsm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/ca/ArthurKoestler.txt ../out/04/ca/ArthurKoestler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/5e/Afterlife.txt ../out/05/5e/Afterlife.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/d9/Detroit_Tigers.txt ../out/05/d9/Detroit_Tigers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/8a/Brussels.txt ../out/06/8a/Brussels.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/27/Chess.txt ../out/07/27/Chess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/07/Arapawa_Island.txt ../out/08/07/Arapawa_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/98/October_2003.txt ../out/08/98/October_2003.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/37/List_of_English-language_poets.txt ../out/09/37/List_of_English-language_poets.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/0f/Cuauht%C3%A9moc.txt ../out/0a/0f/Cuauht%C3%A9moc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/9d/Arminianism.txt ../out/0a/9d/Arminianism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/44/ANOVA.txt ../out/0b/44/ANOVA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/b6/Abd_al-Latif_al-Baghdadi_%28medieval_writer%29.txt ../out/0b/b6/Abd_al-Latif_al-Baghdadi_%28medieval_writer%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/52/Capricornus.txt ../out/0c/52/Capricornus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/13/Chinese_five_spice.txt ../out/0d/13/Chinese_five_spice.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/d6/DisRuption.txt ../out/0d/d6/DisRuption.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/81/Content-control_software.txt ../out/0e/81/Content-control_software.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/31/Chinese_Remainder_Theorem.txt ../out/0f/31/Chinese_Remainder_Theorem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/e5/Aesthetics.txt ../out/0f/e5/Aesthetics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/f7/Draught_beer.txt ../out/10/f7/Draught_beer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/95/Caelum.txt ../out/11/95/Caelum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/3c/Afghan_Turkestan.txt ../out/12/3c/Afghan_Turkestan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/bd/Roman_Breviary.txt ../out/12/bd/Roman_Breviary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/70/December_21.txt ../out/13/70/December_21.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/04/Albertosaurus.txt ../out/14/04/Albertosaurus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/cd/Australian_Capital_Territory.txt ../out/14/cd/Australian_Capital_Territory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/3a/Centromere.txt ../out/15/3a/Centromere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/fc/Entropy.txt ../out/15/fc/Entropy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/a8/Euripides.txt ../out/16/a8/Euripides.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/71/Discriminatory.txt ../out/17/71/Discriminatory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/28/Cadillac_%28disambiguation%29.txt ../out/18/28/Cadillac_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/ac/Advanced_Micro_Devices.txt ../out/18/ac/Advanced_Micro_Devices.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/4b/Casa_Batll%C3%B3.txt ../out/19/4b/Casa_Batll%C3%B3.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/c2/ETA_%28separatist_group%29.txt ../out/19/c2/ETA_%28separatist_group%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/66/Corona_Australis.txt ../out/1a/66/Corona_Australis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/f2/Edvard_Munch.txt ../out/1a/f2/Edvard_Munch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/89/Das_Boot.txt ../out/1b/89/Das_Boot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/06/Antigen.txt ../out/1c/06/Antigen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/94/Dave_Brubeck.txt ../out/1c/94/Dave_Brubeck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/29/Evolutionarily_stable_strategy.txt ../out/1d/29/Evolutionarily_stable_strategy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/db/Bestiary.txt ../out/1d/db/Bestiary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/62/Casino_game.txt ../out/1e/62/Casino_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/f4/Examples_of_differential_equations.txt ../out/1e/f4/Examples_of_differential_equations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/d8/DSM-IV.txt ../out/1f/d8/DSM-IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/82/Dimmu_Borgir.txt ../out/20/82/Dimmu_Borgir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/1c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FF.txt ../out/21/1c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FF.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/20/April_30.txt ../out/22/20/April_30.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/b4/Abba_Mari.txt ../out/22/b4/Abba_Mari.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/7c/Charles_Baxter_%28author%29.txt ../out/23/7c/Charles_Baxter_%28author%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/16/Execution_unit.txt ../out/24/16/Execution_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/a5/Catholcism.txt ../out/24/a5/Catholcism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/65/Abatement_in_heraldry.txt ../out/25/65/Abatement_in_heraldry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/12/Biosphere.txt ../out/26/12/Biosphere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/ae/City_University_of_New_York.txt ../out/26/ae/City_University_of_New_York.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/4c/Acorn_Electron.txt ../out/27/4c/Acorn_Electron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/f9/Geography_of_El_Salvador.txt ../out/27/f9/Geography_of_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/89/DDT.txt ../out/28/89/DDT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/53/Elliptical_Curve_Cryptography.txt ../out/29/53/Elliptical_Curve_Cryptography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/f9/Atari_Lynx.txt ../out/29/f9/Atari_Lynx.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/7a/Amos_Bronson_Alcott.txt ../out/2a/7a/Amos_Bronson_Alcott.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/5b/BiologicalScience.txt ../out/2b/5b/BiologicalScience.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/e7/Carl_Gustav_XVI.txt ../out/2b/e7/Carl_Gustav_XVI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/7d/Catharism.txt ../out/2c/7d/Catharism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/27/Europe_of_Democracies_and_Diversities.txt ../out/2d/27/Europe_of_Democracies_and_Diversities.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/ec/Expellees.txt ../out/2d/ec/Expellees.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/8f/Comic_books.txt ../out/2e/8f/Comic_books.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/4d/Wikipedia%3AEditing_policy.txt ../out/2f/4d/Wikipedia%3AEditing_policy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/52/Foreign_relations_of_the_Cayman_Islands.txt ../out/30/52/Foreign_relations_of_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/f5/Catapult.txt ../out/30/f5/Catapult.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/99/%CE%94T.txt ../out/31/99/%CE%94T.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/95/December_18.txt ../out/32/95/December_18.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/09/Device_driver.txt ../out/33/09/Device_driver.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/26/Bartolomeo_Ammannati.txt ../out/34/26/Bartolomeo_Ammannati.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/d5/Decision_problem.txt ../out/34/d5/Decision_problem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/65/Christianity_and_antisemitism.txt ../out/35/65/Christianity_and_antisemitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/21/Algeria%2FTransnational_Issues.txt ../out/36/21/Algeria%2FTransnational_Issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/f4/Canis_rufus.txt ../out/36/f4/Canis_rufus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/6a/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FR.txt ../out/37/6a/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/ed/Dideoxy_sequencing.txt ../out/37/ed/Dideoxy_sequencing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/4b/Christian_antisemitism.txt ../out/38/4b/Christian_antisemitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/5a/British_Prime_Minister.txt ../out/39/5a/British_Prime_Minister.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/f7/Big_rig.txt ../out/39/f7/Big_rig.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/65/Aspartame.txt ../out/3a/65/Aspartame.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/16/Alfonso_III_of_Aragon.txt ../out/3b/16/Alfonso_III_of_Aragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/88/Cosmic_microwave_background.txt ../out/3b/88/Cosmic_microwave_background.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/f4/Capital_punishment.txt ../out/3b/f4/Capital_punishment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/c5/Articolo_31.txt ../out/3c/c5/Articolo_31.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/54/Foreign_relations_of_the_Comoros.txt ../out/3d/54/Foreign_relations_of_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/1a/Apatosaurus.txt ../out/3e/1a/Apatosaurus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/ab/ChordaTa.txt ../out/3e/ab/ChordaTa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/23/CountriesA.txt ../out/3f/23/CountriesA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/ae/Coriander_%28plant%29.txt ../out/3f/ae/Coriander_%28plant%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/5d/Dynamics.txt ../out/40/5d/Dynamics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/eb/Alfred_Russel_Wallace.txt ../out/40/eb/Alfred_Russel_Wallace.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/b0/Atomic_physics.txt ../out/41/b0/Atomic_physics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/f9/Blue_whale.txt ../out/41/f9/Blue_whale.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/82/Clipperton_Island.txt ../out/42/82/Clipperton_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/32/Alcohol_intoxication.txt ../out/43/32/Alcohol_intoxication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/b8/Chandrasekhar_limit.txt ../out/43/b8/Chandrasekhar_limit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/75/Transport_in_the_Democratic_Republic_of_the_Congo.txt ../out/44/75/Transport_in_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/f0/Coast.txt ../out/44/f0/Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/99/Alkane.txt ../out/45/99/Alkane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/4b/Bosnia_Herzegovina.txt ../out/46/4b/Bosnia_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/18/Epistle_to_the_Philippians.txt ../out/47/18/Epistle_to_the_Philippians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/b9/Chinese_Islamic_cuisine.txt ../out/47/b9/Chinese_Islamic_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/86/Clam_Dip.txt ../out/48/86/Clam_Dip.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/1c/Aberfoyle%2C_Stirling.txt ../out/49/1c/Aberfoyle%2C_Stirling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/c4/Artillery.txt ../out/49/c4/Artillery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/7b/AMD_Athlon.txt ../out/4a/7b/AMD_Athlon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/08/Defense.txt ../out/4b/08/Defense.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/b5/Architect.txt ../out/4b/b5/Architect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/2e/Daisy_Duck.txt ../out/4c/2e/Daisy_Duck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/dd/Cook_Islands.txt ../out/4c/dd/Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/86/Amalric_of_Bena.txt ../out/4d/86/Amalric_of_Bena.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/05/Coma.txt ../out/4e/05/Coma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/b7/Billy_Crystal.txt ../out/4e/b7/Billy_Crystal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/59/Wikipedia%3ACooking_basic_topics.txt ../out/4f/59/Wikipedia%3ACooking_basic_topics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/04/Freescale_DragonBall.txt ../out/50/04/Freescale_DragonBall.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/f3/%CE%92-Lactam.txt ../out/50/f3/%CE%92-Lactam.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/73/Charge.txt ../out/51/73/Charge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/08/Alphonso_VII.txt ../out/52/08/Alphonso_VII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/d5/Alcoholics_Anonymous.txt ../out/52/d5/Alcoholics_Anonymous.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/45/Adrenal_gland.txt ../out/53/45/Adrenal_gland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/f3/Bloody_Sunday_%281972%29.txt ../out/53/f3/Bloody_Sunday_%281972%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/6c/Bowls.txt ../out/54/6c/Bowls.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/06/Civil_rights_history.txt ../out/55/06/Civil_rights_history.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/c2/Catalyst.txt ../out/55/c2/Catalyst.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/89/Aimoin.txt ../out/56/89/Aimoin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/5a/Communications_in_Afghanistan.txt ../out/57/5a/Communications_in_Afghanistan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/2c/Athena.txt ../out/58/2c/Athena.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/c0/British_Rail.txt ../out/58/c0/British_Rail.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/37/Telecommunications_in_Burkina_Faso.txt ../out/59/37/Telecommunications_in_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/d1/Bal_Thackeray.txt ../out/59/d1/Bal_Thackeray.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/70/Derry.txt ../out/5a/70/Derry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/de/Dual_space.txt ../out/5a/de/Dual_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/97/Elizabeth_Barrett_Browning.txt ../out/5b/97/Elizabeth_Barrett_Browning.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/3d/Corporate_Police_State.txt ../out/5c/3d/Corporate_Police_State.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/fe/Design_of_experiments.txt ../out/5c/fe/Design_of_experiments.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/e9/National_Baseball_Hall_of_Fame_and_Museum.txt ../out/5d/e9/National_Baseball_Hall_of_Fame_and_Museum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/68/Conservation_law.txt ../out/5e/68/Conservation_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/fe/Cyprinidae.txt ../out/5e/fe/Cyprinidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/e6/Eindhoven.txt ../out/5f/e6/Eindhoven.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/7f/Abel.txt ../out/60/7f/Abel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/32/Alpha.txt ../out/61/32/Alpha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/b5/Berkeley_DB.txt ../out/61/b5/Berkeley_DB.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/7d/Continental_Europe.txt ../out/62/7d/Continental_Europe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/48/Asociaci%C3%B3n_Alumni.txt ../out/63/48/Asociaci%C3%B3n_Alumni.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/2f/AfghanistanPeople.txt ../out/64/2f/AfghanistanPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/e5/Constitution_of_Canada%2F1867_V_Provincial_Constitutions.txt ../out/64/e5/Constitution_of_Canada%2F1867_V_Provincial_Constitutions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/6a/Demographics_of_Cambodia.txt ../out/65/6a/Demographics_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/eb/Apollo_Program.txt ../out/65/eb/Apollo_Program.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/5f/AD_%28disambiguation%29.txt ../out/66/5f/AD_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/09/Djibouti_Armed_Forces.txt ../out/67/09/Djibouti_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/c8/Calvinism.txt ../out/67/c8/Calvinism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/3f/Canis_Major.txt ../out/68/3f/Canis_Major.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/f0/Digital_Versatile_Disc.txt ../out/68/f0/Digital_Versatile_Disc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/c6/Cyril.txt ../out/69/c6/Cyril.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/58/All_Saints_Day.txt ../out/6a/58/All_Saints_Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/e2/Amicable_numbers.txt ../out/6a/e2/Amicable_numbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/8a/Disco.txt ../out/6b/8a/Disco.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/16/Demographics_of_Cameroon.txt ../out/6c/16/Demographics_of_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/7e/Aircraft_hijacking.txt ../out/6c/7e/Aircraft_hijacking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/25/Binary_operation.txt ../out/6d/25/Binary_operation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/ca/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FT.txt ../out/6d/ca/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/74/Allocution.txt ../out/6e/74/Allocution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/de/Epsilon_Ursae_Majoris.txt ../out/6e/de/Epsilon_Ursae_Majoris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/62/Antigua_and_Barbuda%2FTransnational_issues.txt ../out/6f/62/Antigua_and_Barbuda%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/41/Alicante.txt ../out/70/41/Alicante.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/02/Aidan_of_Dalriada.txt ../out/71/02/Aidan_of_Dalriada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/c5/AlJazeera.txt ../out/71/c5/AlJazeera.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/5c/Code_of_Hammurabi.txt ../out/72/5c/Code_of_Hammurabi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/1d/Edgar_Allan_Poe.txt ../out/73/1d/Edgar_Allan_Poe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/f4/Drug_of_abuse.txt ../out/73/f4/Drug_of_abuse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/61/CountriesS.txt ../out/74/61/CountriesS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/c3/American_Airlines.txt ../out/74/c3/American_Airlines.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/79/Al_Qaeda.txt ../out/75/79/Al_Qaeda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/43/Carson_City%2C_Nevada.txt ../out/76/43/Carson_City%2C_Nevada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/d3/Creation_science.txt ../out/76/d3/Creation_science.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/7c/Cerberus.txt ../out/77/7c/Cerberus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/41/%C3%81satr%C3%BA_in_the_United_States.txt ../out/78/41/%C3%81satr%C3%BA_in_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/cc/Espagnole_sauce.txt ../out/78/cc/Espagnole_sauce.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/77/Computer_music.txt ../out/79/77/Computer_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/09/Associative_algebra.txt ../out/7a/09/Associative_algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/81/AnchorageAlaska.txt ../out/7a/81/AnchorageAlaska.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/d6/C.E.txt ../out/7a/d6/C.E.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/b0/AbbesS.txt ../out/7b/b0/AbbesS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/4d/Expander_graph.txt ../out/7c/4d/Expander_graph.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/08/Chinese_remainder_theorem.txt ../out/7d/08/Chinese_remainder_theorem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/99/Anbar_%28town%29.txt ../out/7d/99/Anbar_%28town%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/4f/Azores.txt ../out/7e/4f/Azores.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/f3/Alfonso_I.txt ../out/7e/f3/Alfonso_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/a4/Argon.txt ../out/7f/a4/Argon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/05/Braille_embosser.txt ../out/80/05/Braille_embosser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/96/Czar_Nicholas_II.txt ../out/80/96/Czar_Nicholas_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/34/Artistic_revolution.txt ../out/81/34/Artistic_revolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/d3/Bearing.txt ../out/81/d3/Bearing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/a4/Autism.txt ../out/82/a4/Autism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/6f/December_7.txt ../out/83/6f/December_7.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/1a/Economy_of_Benin.txt ../out/84/1a/Economy_of_Benin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/fd/Althusser.txt ../out/84/fd/Althusser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/75/Telecommunications_in_Brunei.txt ../out/85/75/Telecommunications_in_Brunei.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/13/American_League_Championship_Series.txt ../out/86/13/American_League_Championship_Series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/c6/Coprophagia.txt ../out/86/c6/Coprophagia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/46/Bahais.txt ../out/87/46/Bahais.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/15/Afghanistan%2FEconomy.txt ../out/88/15/Afghanistan%2FEconomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/d5/Conditional_proof.txt ../out/88/d5/Conditional_proof.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/70/Canis_familiaris.txt ../out/89/70/Canis_familiaris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/07/Biotechnology.txt ../out/8a/07/Biotechnology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/be/Civil_law.txt ../out/8a/be/Civil_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/6b/Ascending_Chain_Condition.txt ../out/8b/6b/Ascending_Chain_Condition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/1f/Alhazen.txt ../out/8c/1f/Alhazen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/b2/Piano_Trios%2C_Op._1_%28Beethoven%29.txt ../out/8c/b2/Piano_Trios%2C_Op._1_%28Beethoven%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/21/Albert%2C_Duke_of_Prussia.txt ../out/8d/21/Albert%2C_Duke_of_Prussia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/2a/Diaeresis.txt ../out/8e/2a/Diaeresis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/da/Arcturus.txt ../out/8e/da/Arcturus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/87/Absalon.txt ../out/8f/87/Absalon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/36/Coriolis_effect.txt ../out/90/36/Coriolis_effect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/0c/Collective_nouns%2FAll_sorted_by_collective_term.txt ../out/91/0c/Collective_nouns%2FAll_sorted_by_collective_term.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/f4/Constantine_the_Great.txt ../out/91/f4/Constantine_the_Great.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/d4/Brigham_Young.txt ../out/92/d4/Brigham_Young.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/8b/Family_International.txt ../out/93/8b/Family_International.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/18/American_indian.txt ../out/94/18/American_indian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/23/Coriolis_force.txt ../out/95/23/Coriolis_force.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/90/Color%2Fwhite.txt ../out/95/90/Color%2Fwhite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/54/Central_Asia.txt ../out/96/54/Central_Asia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/07/Bank_of_England.txt ../out/97/07/Bank_of_England.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/82/EsperantoLanguage.txt ../out/97/82/EsperantoLanguage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/30/Cranberry.txt ../out/98/30/Cranberry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/7e/Anthropic_Principle.txt ../out/98/7e/Anthropic_Principle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/27/Agnes_of_Merania.txt ../out/99/27/Agnes_of_Merania.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/a6/Battle_of_Jutland.txt ../out/99/a6/Battle_of_Jutland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/42/Amhrann_na_bhFiann.txt ../out/9a/42/Amhrann_na_bhFiann.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/a6/Cocktail.txt ../out/9a/a6/Cocktail.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/62/Ambrosia.txt ../out/9b/62/Ambrosia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/f9/Centers_for_Disease_Control_and_Prevention.txt ../out/9b/f9/Centers_for_Disease_Control_and_Prevention.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/7d/Cauchy%E2%80%93Riemann_equations.txt ../out/9c/7d/Cauchy%E2%80%93Riemann_equations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/1f/Candidiasis.txt ../out/9d/1f/Candidiasis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/92/A.C._Chievo_Verona.txt ../out/9d/92/A.C._Chievo_Verona.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/32/ACE_inhibitor.txt ../out/9e/32/ACE_inhibitor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/2d/August_1.txt ../out/9f/2d/August_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/da/Aldine_Press.txt ../out/9f/da/Aldine_Press.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/69/Dewey_Decimal_Classification.txt ../out/a0/69/Dewey_Decimal_Classification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/38/Barrister.txt ../out/a1/38/Barrister.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/33/Cell_wall.txt ../out/a2/33/Cell_wall.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/d0/DrewBarrymore.txt ../out/a2/d0/DrewBarrymore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/8d/Ambrosius_Bosschaert.txt ../out/a3/8d/Ambrosius_Bosschaert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/32/Accountancy.txt ../out/a4/32/Accountancy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/d2/Bill_Atkinson.txt ../out/a4/d2/Bill_Atkinson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/47/Altair.txt ../out/a5/47/Altair.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/ae/Californium.txt ../out/a5/ae/Californium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/76/Bruce_Sterling.txt ../out/a6/76/Bruce_Sterling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/17/The_Bronx.txt ../out/a7/17/The_Bronx.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/d2/Mouse_%28computing%29.txt ../out/a7/d2/Mouse_%28computing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/9b/Civil_Rights_Act.txt ../out/a8/9b/Civil_Rights_Act.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/6f/Bram_Stoker.txt ../out/a9/6f/Bram_Stoker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/2d/A_Modest_Proposal.txt ../out/aa/2d/A_Modest_Proposal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/a5/Anxiolytic.txt ../out/aa/a5/Anxiolytic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/2d/County_town.txt ../out/ab/2d/County_town.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/c2/Economy%2FInflation.txt ../out/ab/c2/Economy%2FInflation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/67/Alfred_Lawson.txt ../out/ac/67/Alfred_Lawson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/c4/ErnestHemingway%2FTheEndlessDarkNothingness.txt ../out/ac/c4/ErnestHemingway%2FTheEndlessDarkNothingness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/7c/Bioterrorism.txt ../out/ad/7c/Bioterrorism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/26/Eocene.txt ../out/ae/26/Eocene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/bc/Climbing.txt ../out/ae/bc/Climbing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/78/Molecular_diffusion.txt ../out/af/78/Molecular_diffusion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/fc/Aga_Khan_III.txt ../out/af/fc/Aga_Khan_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/5a/Angular_momentum.txt ../out/b0/5a/Angular_momentum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/37/COINTELPRO.txt ../out/b1/37/COINTELPRO.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/be/Ashmore_and_Cartier_Islands%2FTransportation.txt ../out/b1/be/Ashmore_and_Cartier_Islands%2FTransportation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/2f/Audio.txt ../out/b2/2f/Audio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/46/Economy_of_Bhutan.txt ../out/b3/46/Economy_of_Bhutan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/ee/Alboin.txt ../out/b3/ee/Alboin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/8e/CVBG.txt ../out/b4/8e/CVBG.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/cb/AppleTalk.txt ../out/b4/cb/AppleTalk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/34/Afrocelt_Sound_System.txt ../out/b5/34/Afrocelt_Sound_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/c7/Alexander_Kerensky.txt ../out/b5/c7/Alexander_Kerensky.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/6a/Diene.txt ../out/b6/6a/Diene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/67/Anti-Terrorism_and_Effective_Death_Penalty_Act.txt ../out/b7/67/Anti-Terrorism_and_Effective_Death_Penalty_Act.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/d1/Ada_%28programming_language%29.txt ../out/b7/d1/Ada_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/68/Church_of_England.txt ../out/b8/68/Church_of_England.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/2d/Central_Europe.txt ../out/b9/2d/Central_Europe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/ea/Dark_Star.txt ../out/b9/ea/Dark_Star.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/b3/AutoMorphism.txt ../out/ba/b3/AutoMorphism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/3b/Curling.txt ../out/bb/3b/Curling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/c9/Cardiac_arrhythmia%2Ftachycardia.txt ../out/bb/c9/Cardiac_arrhythmia%2Ftachycardia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/5b/Beryllium_aluminium_meta-silicate.txt ../out/bc/5b/Beryllium_aluminium_meta-silicate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/f4/Consilience.txt ../out/bc/f4/Consilience.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/b9/Wikipedia%3ABuilding_Wikipedia_membership%2FAnother_sample_solicitation.txt ../out/bd/b9/Wikipedia%3ABuilding_Wikipedia_membership%2FAnother_sample_solicitation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/7c/Bangladesh%2FForeign_relations.txt ../out/be/7c/Bangladesh%2FForeign_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/2f/DBMS.txt ../out/bf/2f/DBMS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/e1/BodyBuilding.txt ../out/bf/e1/BodyBuilding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/97/Rise_and_Fall_of_the_City_of_Mahagonny.txt ../out/c0/97/Rise_and_Fall_of_the_City_of_Mahagonny.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/55/Distillation.txt ../out/c1/55/Distillation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/f4/American_League_Division_Series.txt ../out/c1/f4/American_League_Division_Series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/e5/DwGriffith.txt ../out/c2/e5/DwGriffith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/9f/Clay_math_prize.txt ../out/c3/9f/Clay_math_prize.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/20/Albania.txt ../out/c4/20/Albania.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/a2/Basil_the_Great.txt ../out/c4/a2/Basil_the_Great.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/9c/American_Airlines_flight_77.txt ../out/c5/9c/American_Airlines_flight_77.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/2a/Belgium%2FBelgie.txt ../out/c6/2a/Belgium%2FBelgie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/17/Desertification.txt ../out/c7/17/Desertification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/c7/Ain%27t_I_a_Woman%3F_%28book%29.txt ../out/c7/c7/Ain%27t_I_a_Woman%3F_%28book%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/6e/Politics_of_Chile.txt ../out/c8/6e/Politics_of_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/40/Brabham.txt ../out/c9/40/Brabham.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/b9/Compact_disc.txt ../out/c9/b9/Compact_disc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/3d/Wikipedia%3ABuilding_Wikipedia_membership%2FSample_solicitation.txt ../out/ca/3d/Wikipedia%3ABuilding_Wikipedia_membership%2FSample_solicitation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/32/Cantigas_de_Santa_Maria.txt ../out/cb/32/Cantigas_de_Santa_Maria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/cb/Context_switch.txt ../out/cb/cb/Context_switch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/bb/N%2CN-Dimethyltryptamine.txt ../out/cc/bb/N%2CN-Dimethyltryptamine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/34/Capcom.txt ../out/cd/34/Capcom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/d2/Andr%C3%A9_Gide.txt ../out/cd/d2/Andr%C3%A9_Gide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/b4/Context_free_grammars.txt ../out/ce/b4/Context_free_grammars.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/53/Dual.txt ../out/cf/53/Dual.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/04/Earley_parser.txt ../out/d0/04/Earley_parser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/f6/Cretinism.txt ../out/d0/f6/Cretinism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/5d/Domitian.txt ../out/d1/5d/Domitian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/4b/Military_of_Equatorial_Guinea.txt ../out/d2/4b/Military_of_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/cd/ASCII.txt ../out/d2/cd/ASCII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/85/Commodore_International.txt ../out/d3/85/Commodore_International.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/36/Liberal_Party_%28UK%29.txt ../out/d4/36/Liberal_Party_%28UK%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/f1/Alessandro_Scarlatti.txt ../out/d4/f1/Alessandro_Scarlatti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/9a/CombinaTorics.txt ../out/d5/9a/CombinaTorics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/50/History_of_Colombia.txt ../out/d6/50/History_of_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/df/Arsenal_F.C..txt ../out/d6/df/Arsenal_F.C..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/55/Belgian_Blue.txt ../out/d7/55/Belgian_Blue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/13/CryptanalysiS.txt ../out/d8/13/CryptanalysiS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/e8/Demographics_of_the_Dominican_Republic.txt ../out/d8/e8/Demographics_of_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/90/Charlize_Theron%2FFilmography.txt ../out/d9/90/Charlize_Theron%2FFilmography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/23/December_16.txt ../out/da/23/December_16.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/c2/Chick_Publications.txt ../out/da/c2/Chick_Publications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/46/Optical_audio_disc.txt ../out/db/46/Optical_audio_disc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/0a/Choctaw.txt ../out/dc/0a/Choctaw.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/8c/Don_McLean.txt ../out/dc/8c/Don_McLean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/39/CID.txt ../out/dd/39/CID.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/d0/EdwinAustinAbbey.txt ../out/dd/d0/EdwinAustinAbbey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/85/Bridge.txt ../out/de/85/Bridge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/1e/BCS_theory.txt ../out/df/1e/BCS_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/0f/Anastasius_IV.txt ../out/e0/0f/Anastasius_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/c6/Benoit_Mandelbrot.txt ../out/e0/c6/Benoit_Mandelbrot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/8c/Computer_security.txt ../out/e1/8c/Computer_security.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/26/Christian_theosophy.txt ../out/e2/26/Christian_theosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/eb/Crew.txt ../out/e2/eb/Crew.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/70/Electric_light.txt ../out/e3/70/Electric_light.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/11/Diploidy.txt ../out/e4/11/Diploidy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/ea/Consequentialism.txt ../out/e4/ea/Consequentialism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/68/CountriesT.txt ../out/e5/68/CountriesT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/05/Conjugation.txt ../out/e6/05/Conjugation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/c7/Teochew_cuisine.txt ../out/e6/c7/Teochew_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/92/Amakusa.txt ../out/e7/92/Amakusa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/2d/Easter.txt ../out/e8/2d/Easter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/df/Batman_%26_Robin_%28film%29.txt ../out/e8/df/Batman_%26_Robin_%28film%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/56/List_of_dog_breeds.txt ../out/e9/56/List_of_dog_breeds.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/d1/Battlecruiser.txt ../out/e9/d1/Battlecruiser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/56/Alumna.txt ../out/ea/56/Alumna.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/1c/Bouldering.txt ../out/eb/1c/Bouldering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/ca/Blitzkrieg.txt ../out/eb/ca/Blitzkrieg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/91/Curl_%28mathematics%29.txt ../out/ec/91/Curl_%28mathematics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/6f/Chirality_%28disambiguation%29.txt ../out/ed/6f/Chirality_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/e6/Acantharea.txt ../out/ed/e6/Acantharea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/83/Egyptian_Armed_Forces.txt ../out/ee/83/Egyptian_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/33/Colombia.txt ../out/ef/33/Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/a4/Ark.txt ../out/ef/a4/Ark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/4c/Abipones.txt ../out/f0/4c/Abipones.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/27/Breast.txt ../out/f1/27/Breast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/ef/Aachen.txt ../out/f1/ef/Aachen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/e9/Politics_of_Armenia.txt ../out/f2/e9/Politics_of_Armenia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/ac/Bethlehem.txt ../out/f3/ac/Bethlehem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/81/Atheists.txt ../out/f4/81/Atheists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/3f/Geography_of_Eritrea.txt ../out/f5/3f/Geography_of_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/e4/Acapulco.txt ../out/f5/e4/Acapulco.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/b3/Benny_Andersson.txt ../out/f6/b3/Benny_Andersson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/24/Politics_of_the_Central_African_Republic.txt ../out/f7/24/Politics_of_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/b4/Ambrosius_Aurelianus.txt ../out/f7/b4/Ambrosius_Aurelianus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/94/Deicide_%28band%29.txt ../out/f8/94/Deicide_%28band%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/00/Destroyer.txt ../out/f9/00/Destroyer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/89/An_American_in_Paris.txt ../out/f9/89/An_American_in_Paris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/0e/Afroasiatic_languages.txt ../out/fa/0e/Afroasiatic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/b2/Al-Qaeda.txt ../out/fa/b2/Al-Qaeda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/5a/BGP.txt ../out/fb/5a/BGP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/f0/Avicenna.txt ../out/fb/f0/Avicenna.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/fc/List_of_recently_extinct_birds.txt ../out/fc/fc/List_of_recently_extinct_birds.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/9f/Brownian_movement.txt ../out/fd/9f/Brownian_movement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/5c/Abettor.txt ../out/fe/5c/Abettor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/ef/Bachelor.txt ../out/fe/ef/Bachelor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/72/Andrew_Wiles.txt ../out/ff/72/Andrew_Wiles.xml
