php ./wiki2xml/php/wiki2xml_command.php ../out/00/65/Demographics_of_the_Cayman_Islands.txt ../out/00/65/Demographics_of_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/26/BCG_vaccine.txt ../out/01/26/BCG_vaccine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/bb/Cyrillic_script.txt ../out/01/bb/Cyrillic_script.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/54/DualIsm.txt ../out/02/54/DualIsm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/29/AbeL.txt ../out/03/29/AbeL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/bc/Aeneas.txt ../out/03/bc/Aeneas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/4e/Annealing.txt ../out/04/4e/Annealing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/cf/Belgium%2Ffacts.txt ../out/04/cf/Belgium%2Ffacts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/62/BLM.txt ../out/05/62/BLM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/df/Direct_product.txt ../out/05/df/Direct_product.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/a8/Alfonso_XII_of_Spain.txt ../out/06/a8/Alfonso_XII_of_Spain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/2c/Almost_all.txt ../out/07/2c/Almost_all.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/0a/Ernest_Hemingway%2FRobert_Jordan.txt ../out/08/0a/Ernest_Hemingway%2FRobert_Jordan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/a2/Cane_toad.txt ../out/08/a2/Cane_toad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/5a/Base.txt ../out/09/5a/Base.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/15/Cocaine.txt ../out/0a/15/Cocaine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/a0/Ethiopian_National_Defense_Force.txt ../out/0a/a0/Ethiopian_National_Defense_Force.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/47/Duck_Hunt.txt ../out/0b/47/Duck_Hunt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/b8/Coordination_complex.txt ../out/0b/b8/Coordination_complex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/63/Baghdad.txt ../out/0c/63/Baghdad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/21/Atom.txt ../out/0d/21/Atom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/da/Complete_works_of_Plato.txt ../out/0d/da/Complete_works_of_Plato.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/81/Electromagnetic_interaction.txt ../out/0e/81/Electromagnetic_interaction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/31/Diode.txt ../out/0f/31/Diode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/eb/Extraterrestrial_life.txt ../out/0f/eb/Extraterrestrial_life.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/f9/Ducati.txt ../out/10/f9/Ducati.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/95/Ellipse.txt ../out/11/95/Ellipse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/44/Errol_Morris.txt ../out/12/44/Errol_Morris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/db/Chronicle.txt ../out/12/db/Chronicle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/74/Arbeit_macht_frei.txt ../out/13/74/Arbeit_macht_frei.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/13/CCIR.txt ../out/14/13/CCIR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/d1/Aegean_Sea.txt ../out/14/d1/Aegean_Sea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/49/Ambrose_of_Alexandria.txt ../out/15/49/Ambrose_of_Alexandria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/0f/DeniseRichards.txt ../out/16/0f/DeniseRichards.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/aa/Acute_disseminated_encephalomyelitis.txt ../out/16/aa/Acute_disseminated_encephalomyelitis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/97/Economy_of_Alberta.txt ../out/17/97/Economy_of_Alberta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/29/Outline_of_chemistry.txt ../out/18/29/Outline_of_chemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/b6/Economy_of_Egypt.txt ../out/18/b6/Economy_of_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/55/EucliD.txt ../out/19/55/EucliD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/d8/Augustine.txt ../out/19/d8/Augustine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/8b/Diffusion_pump.txt ../out/1a/8b/Diffusion_pump.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/f7/Apple_Airport.txt ../out/1a/f7/Apple_Airport.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/90/Adaptive_expectations.txt ../out/1b/90/Adaptive_expectations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/09/European_Free_Trade_Association.txt ../out/1c/09/European_Free_Trade_Association.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/97/Anthony_the_Great.txt ../out/1c/97/Anthony_the_Great.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/2a/Electrical_telegraph.txt ../out/1d/2a/Electrical_telegraph.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/e4/Politics_of_El_Salvador.txt ../out/1d/e4/Politics_of_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/86/Defensive_team.txt ../out/1e/86/Defensive_team.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/1b/Alexander_III_of_Scotland.txt ../out/1f/1b/Alexander_III_of_Scotland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/f9/Brick.txt ../out/1f/f9/Brick.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/8e/Apocrypha%2FTanakh.txt ../out/20/8e/Apocrypha%2FTanakh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/1e/Baralong_incidents.txt ../out/21/1e/Baralong_incidents.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/21/Controversy.txt ../out/22/21/Controversy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/cb/Charles_Martel.txt ../out/22/cb/Charles_Martel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/80/IBM_AIX.txt ../out/23/80/IBM_AIX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/17/Leg_theory.txt ../out/24/17/Leg_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/b8/Anaxagoras.txt ../out/24/b8/Anaxagoras.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/8a/Antonio_Salieri.txt ../out/25/8a/Antonio_Salieri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/15/Compound.txt ../out/26/15/Compound.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/b1/David_Brewster.txt ../out/26/b1/David_Brewster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/65/Dye.txt ../out/27/65/Dye.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/fd/Angry_Brigade.txt ../out/27/fd/Angry_Brigade.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/8a/Cardiff.txt ../out/28/8a/Cardiff.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/54/Ciliates.txt ../out/29/54/Ciliates.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/06/Escape_from_New_York.txt ../out/2a/06/Escape_from_New_York.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/ce/Alexandria_Troas.txt ../out/2a/ce/Alexandria_Troas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/5b/The_Canterbury_Tales.txt ../out/2b/5b/The_Canterbury_Tales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/08/Cornwall_Wildlife_Trust.txt ../out/2c/08/Cornwall_Wildlife_Trust.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/82/Ammonius_Grammaticus.txt ../out/2c/82/Ammonius_Grammaticus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/31/Cincinnati_Bengals.txt ../out/2d/31/Cincinnati_Bengals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/ef/Sideroxylon_grandiflorum.txt ../out/2d/ef/Sideroxylon_grandiflorum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/9d/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FC2.txt ../out/2e/9d/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FC2.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/52/Charles_V.txt ../out/2f/52/Charles_V.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/62/Definable_real_number.txt ../out/30/62/Definable_real_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/03/Deforestation.txt ../out/31/03/Deforestation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/b8/Dungeons_%26_Dragons.txt ../out/31/b8/Dungeons_%26_Dragons.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/9e/Alexander_II.txt ../out/32/9e/Alexander_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/0e/Ballad.txt ../out/33/0e/Ballad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/33/Climate_Change_1995.txt ../out/34/33/Climate_Change_1995.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/d8/Crankshaft.txt ../out/34/d8/Crankshaft.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/67/California.txt ../out/35/67/California.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/26/Apparent_magnitude.txt ../out/36/26/Apparent_magnitude.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/05/Wikipedia%3AStatus_of_the_porting_of_U.S._Dept_of_State_info.txt ../out/37/05/Wikipedia%3AStatus_of_the_porting_of_U.S._Dept_of_State_info.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/6c/Bille_August.txt ../out/37/6c/Bille_August.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/ee/Communications_in_Christmas_Island.txt ../out/37/ee/Communications_in_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/53/AIM-120_AMRAAM.txt ../out/38/53/AIM-120_AMRAAM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/6b/Dipole%E2%80%93dipole_attraction.txt ../out/39/6b/Dipole%E2%80%93dipole_attraction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/1e/DASS2.txt ../out/3a/1e/DASS2.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/6a/Chinese_input_methods_for_computers.txt ../out/3a/6a/Chinese_input_methods_for_computers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/1b/Dilbert.txt ../out/3b/1b/Dilbert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/92/Acceleration.txt ../out/3b/92/Acceleration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/18/Book_of_Obadiah.txt ../out/3c/18/Book_of_Obadiah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/ce/Eurocard_%28printed_circuit_board%29.txt ../out/3c/ce/Eurocard_%28printed_circuit_board%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/56/Abd_ar-Rahman_IV.txt ../out/3d/56/Abd_ar-Rahman_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/1d/Cache_%28computing%29.txt ../out/3e/1d/Cache_%28computing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/ac/Eris_%28mythology%29.txt ../out/3e/ac/Eris_%28mythology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/25/Coin_collecting.txt ../out/3f/25/Coin_collecting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/af/Big_Apple.txt ../out/3f/af/Big_Apple.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/5d/Dyula_language.txt ../out/40/5d/Dyula_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/ef/ATP.txt ../out/40/ef/ATP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/ba/August.txt ../out/41/ba/August.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/0f/Extravehicular_activity.txt ../out/42/0f/Extravehicular_activity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/88/Aquaculture.txt ../out/42/88/Aquaculture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/4c/DEC_Alpha.txt ../out/43/4c/DEC_Alpha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/ba/April_26.txt ../out/43/ba/April_26.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/89/Beadwork.txt ../out/44/89/Beadwork.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/fa/Axiom_of_choice.txt ../out/44/fa/Axiom_of_choice.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/c9/European_influence_in_Afghanistan.txt ../out/45/c9/European_influence_in_Afghanistan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/4e/David.txt ../out/46/4e/David.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/22/AbalonE.txt ../out/47/22/AbalonE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/c1/Benelux.txt ../out/47/c1/Benelux.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/8c/David_Hume.txt ../out/48/8c/David_Hume.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/1c/Bilinear_transform.txt ../out/49/1c/Bilinear_transform.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/cb/Amber_Road.txt ../out/49/cb/Amber_Road.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/7d/Christ.txt ../out/4a/7d/Christ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/16/Economy_of_the_Dominican_Republic.txt ../out/4b/16/Economy_of_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/b6/Alliance_of_Liberals_and_Democrats_for_Europe_Party.txt ../out/4b/b6/Alliance_of_Liberals_and_Democrats_for_Europe_Party.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/3f/Lists_of_deities.txt ../out/4c/3f/Lists_of_deities.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/0f/Battle_of_Abritus.txt ../out/4d/0f/Battle_of_Abritus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/88/St._Ambrose_Traversari.txt ../out/4d/88/St._Ambrose_Traversari.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/06/ANS.txt ../out/4e/06/ANS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/be/Briscoe_County%2C_Jr..txt ../out/4e/be/Briscoe_County%2C_Jr..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/69/Don_Tennant.txt ../out/4f/69/Don_Tennant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/1c/Dragonball_Z.txt ../out/50/1c/Dragonball_Z.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/fc/Black_Sabbath.txt ../out/50/fc/Black_Sabbath.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/78/American_shot.txt ../out/51/78/American_shot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/15/From_Reality_to_Fiction_A_Farewell_to_Arms.txt ../out/52/15/From_Reality_to_Fiction_A_Farewell_to_Arms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/d8/%C3%81lfheimr.txt ../out/52/d8/%C3%81lfheimr.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/4d/Sacrifice_fly.txt ../out/53/4d/Sacrifice_fly.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/f5/European_Convention_on_Human_Rights.txt ../out/53/f5/European_Convention_on_Human_Rights.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/7a/Analog_signal.txt ../out/54/7a/Analog_signal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/0d/Barcelona.txt ../out/55/0d/Barcelona.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/c8/Chemical_thermodynamics.txt ../out/55/c8/Chemical_thermodynamics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/8b/Americans_with_Disabilities_Act_of_1990%2FDefinitions.txt ../out/56/8b/Americans_with_Disabilities_Act_of_1990%2FDefinitions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/5a/CORAL66.txt ../out/57/5a/CORAL66.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/2d/Ballet_dance.txt ../out/58/2d/Ballet_dance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/c4/Cinquain.txt ../out/58/c4/Cinquain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/42/Book_of_Zecharaiah.txt ../out/59/42/Book_of_Zecharaiah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/d7/Anthony_Hopkins.txt ../out/59/d7/Anthony_Hopkins.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/71/History_of_Chad.txt ../out/5a/71/History_of_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/e5/Donald_E_Knuth.txt ../out/5a/e5/Donald_E_Knuth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/aa/Abencerrages.txt ../out/5b/aa/Abencerrages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/45/August_31.txt ../out/5c/45/August_31.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/11/Digital_Video.txt ../out/5d/11/Digital_Video.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/eb/Antipope_Victor_IV.txt ../out/5d/eb/Antipope_Victor_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/6e/Banshee.txt ../out/5e/6e/Banshee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/00/DNA_replication.txt ../out/5f/00/DNA_replication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/ed/Dorians.txt ../out/5f/ed/Dorians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/8c/Candela.txt ../out/60/8c/Candela.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/32/B._F._Skinner.txt ../out/61/32/B._F._Skinner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/b8/Classical_liberal.txt ../out/61/b8/Classical_liberal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/82/Ann_Widdecombe.txt ../out/62/82/Ann_Widdecombe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/4f/Actium.txt ../out/63/4f/Actium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/42/Barrel_%28disambiguation%29.txt ../out/64/42/Barrel_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/f6/England.txt ../out/64/f6/England.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/6a/Major_depressive_disorder.txt ../out/65/6a/Major_depressive_disorder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/eb/Arno.txt ../out/65/eb/Arno.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/7e/Timeline_of_computing.txt ../out/66/7e/Timeline_of_computing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/10/Denver.txt ../out/67/10/Denver.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/d3/Brion_Gysin.txt ../out/67/d3/Brion_Gysin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/50/Cartoon.txt ../out/68/50/Cartoon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/1a/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FI.txt ../out/69/1a/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/cc/Applied_ethics.txt ../out/69/cc/Applied_ethics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/58/Cowboy_Bebop.txt ../out/6a/58/Cowboy_Bebop.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/e7/Coral_Sea_Islands%2FPeople.txt ../out/6a/e7/Coral_Sea_Islands%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/92/Electromagnectic_radiation.txt ../out/6b/92/Electromagnectic_radiation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/22/Anaximenes_of_Miletus.txt ../out/6c/22/Anaximenes_of_Miletus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/8d/Alloy.txt ../out/6c/8d/Alloy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/36/Beowulf.txt ../out/6d/36/Beowulf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/d2/B%C3%A9la_Bart%C3%B3k.txt ../out/6d/d2/B%C3%A9la_Bart%C3%B3k.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/80/Christian_countercult_movement.txt ../out/6e/80/Christian_countercult_movement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/e3/Adware.txt ../out/6e/e3/Adware.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/73/Cambridge_%28disambiguation%29.txt ../out/6f/73/Cambridge_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/69/ErnestHemingway%2FWhyItWentWrong.txt ../out/70/69/ErnestHemingway%2FWhyItWentWrong.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/02/Aloe.txt ../out/71/02/Aloe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/ca/Archduke_Charles%2C_Duke_of_Teschen.txt ../out/71/ca/Archduke_Charles%2C_Duke_of_Teschen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/63/Apollo_7.txt ../out/72/63/Apollo_7.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/2d/BBC_News_%28TV_channel%29.txt ../out/73/2d/BBC_News_%28TV_channel%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/02/Bisexual_%28disambiguation%29.txt ../out/74/02/Bisexual_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/62/Geography_of_the_Cook_Islands.txt ../out/74/62/Geography_of_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/c6/Australian_Prime_Ministers.txt ../out/74/c6/Australian_Prime_Ministers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/80/Alexander_Balas.txt ../out/75/80/Alexander_Balas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/44/Adin_Steinsaltz.txt ../out/76/44/Adin_Steinsaltz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/d7/Assembly_language.txt ../out/76/d7/Assembly_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/9a/Breidablik.txt ../out/77/9a/Breidablik.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/43/Aorta.txt ../out/78/43/Aorta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/cd/Claudio_Monteverdi.txt ../out/78/cd/Claudio_Monteverdi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/8a/Aristotle.txt ../out/79/8a/Aristotle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/17/Chaos_Computer_Club.txt ../out/7a/17/Chaos_Computer_Club.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/85/Bosons.txt ../out/7a/85/Bosons.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/d9/Bassas_da_India.txt ../out/7a/d9/Bassas_da_India.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/b8/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FP.txt ../out/7b/b8/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/5b/Director.txt ../out/7c/5b/Director.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/18/Android_%28robot%29.txt ../out/7d/18/Android_%28robot%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/a1/Chomsky_hierarchy.txt ../out/7d/a1/Chomsky_hierarchy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/52/Charles_Williams_%28British_writer%29.txt ../out/7e/52/Charles_Williams_%28British_writer%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/f3/Discus_throw.txt ../out/7e/f3/Discus_throw.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/a6/Atomic_orbital.txt ../out/7f/a6/Atomic_orbital.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/0a/Dwight_L._Moody.txt ../out/80/0a/Dwight_L._Moody.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/9a/Colombia%2FTransnational_issues.txt ../out/80/9a/Colombia%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/37/Ecliptic.txt ../out/81/37/Ecliptic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/f2/Battle_of_Stalingrad.txt ../out/81/f2/Battle_of_Stalingrad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/a5/ESR.txt ../out/82/a5/ESR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/79/Achiltibuie.txt ../out/83/79/Achiltibuie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/1c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FQ.txt ../out/84/1c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FQ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/00/Acquired_immunodeficiency_syndrome.txt ../out/85/00/Acquired_immunodeficiency_syndrome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/76/Achaeans_%28Homer%29.txt ../out/85/76/Achaeans_%28Homer%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/18/Decca_Navigator_System.txt ../out/86/18/Decca_Navigator_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/cc/Australian_rules_football.txt ../out/86/cc/Australian_rules_football.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/50/Computer_programming.txt ../out/87/50/Computer_programming.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/2b/Control_character.txt ../out/88/2b/Control_character.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/e8/Compression_ratio.txt ../out/88/e8/Compression_ratio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/81/Esperanto.txt ../out/89/81/Esperanto.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/0e/Despina.txt ../out/8a/0e/Despina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/c8/Abercarn.txt ../out/8a/c8/Abercarn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/6d/Anatole_France.txt ../out/8b/6d/Anatole_France.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/22/Danforth_Quayle.txt ../out/8c/22/Danforth_Quayle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/b7/Chuck-a-luck.txt ../out/8c/b7/Chuck-a-luck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/24/Childe%27s_Tomb.txt ../out/8d/24/Childe%27s_Tomb.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/2e/Colin_Fulcher.txt ../out/8e/2e/Colin_Fulcher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/de/Amalthea.txt ../out/8e/de/Amalthea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/9b/Christian_eschatology.txt ../out/8f/9b/Christian_eschatology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/43/Chaco_Canyon.txt ../out/90/43/Chaco_Canyon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/10/Carotene.txt ../out/91/10/Carotene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/10/Andersonville%2C_Georgia.txt ../out/92/10/Andersonville%2C_Georgia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/d5/Astronomer_Royal.txt ../out/92/d5/Astronomer_Royal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/8c/Attila.txt ../out/93/8c/Attila.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/31/Crux.txt ../out/94/31/Crux.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/23/Cuban_Missile_Crisis.txt ../out/95/23/Cuban_Missile_Crisis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/94/Blue.txt ../out/95/94/Blue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/55/Augustin-Louis_Cauchy.txt ../out/96/55/Augustin-Louis_Cauchy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/09/Telecommunications_in_Antigua_and_Barbuda.txt ../out/97/09/Telecommunications_in_Antigua_and_Barbuda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/8d/Art.txt ../out/97/8d/Art.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/33/Babrak_Karmal.txt ../out/98/33/Babrak_Karmal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/a7/EFTA_%28disambiguation%29.txt ../out/98/a7/EFTA_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/29/Cartography.txt ../out/99/29/Cartography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/a8/Balance.txt ../out/99/a8/Balance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/46/Anita_Hill.txt ../out/9a/46/Anita_Hill.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/ba/BillClinton.txt ../out/9a/ba/BillClinton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/7f/Didgeridoo.txt ../out/9b/7f/Didgeridoo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/f9/Context-sensitive_grammar.txt ../out/9b/f9/Context-sensitive_grammar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/7f/Autosome.txt ../out/9c/7f/Autosome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/1f/Claudio_Zuan_Antonio_Monteverdi.txt ../out/9d/1f/Claudio_Zuan_Antonio_Monteverdi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/96/Claude_Auchinleck.txt ../out/9d/96/Claude_Auchinleck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/5b/Burroughs_Corporation.txt ../out/9e/5b/Burroughs_Corporation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/3f/Color%2FOrange.txt ../out/9f/3f/Color%2FOrange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/de/Blindness_in_literature.txt ../out/9f/de/Blindness_in_literature.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/76/BinomialDistribution.txt ../out/a0/76/BinomialDistribution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/57/Carbon_dioxide.txt ../out/a1/57/Carbon_dioxide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/40/Bacillus_Thuringiensis.txt ../out/a2/40/Bacillus_Thuringiensis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/d1/Corrado_Gini.txt ../out/a2/d1/Corrado_Gini.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/95/Astounding_magazine.txt ../out/a3/95/Astounding_magazine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/45/Coronation_Street.txt ../out/a4/45/Coronation_Street.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/e5/Bubble_tea.txt ../out/a4/e5/Bubble_tea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/48/Foreign_relations_of_Bosnia_and_Herzegovina.txt ../out/a5/48/Foreign_relations_of_Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/b4/Albert_I.txt ../out/a5/b4/Albert_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/84/Electric_charge.txt ../out/a6/84/Electric_charge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/1c/ACID_properties.txt ../out/a7/1c/ACID_properties.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/e4/Connected_space.txt ../out/a7/e4/Connected_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/a0/DeweyDecimalSystem.txt ../out/a8/a0/DeweyDecimalSystem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/75/Europium.txt ../out/a9/75/Europium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/32/Bilinear_map.txt ../out/aa/32/Bilinear_map.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/ad/Aba.txt ../out/aa/ad/Aba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/3a/Cognitive_behavioral_therapy.txt ../out/ab/3a/Cognitive_behavioral_therapy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/c8/Cem_Karaca.txt ../out/ab/c8/Cem_Karaca.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/70/Document_type_definition.txt ../out/ac/70/Document_type_definition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/d1/A.A._Milne.txt ../out/ac/d1/A.A._Milne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/87/Computer_file.txt ../out/ad/87/Computer_file.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/35/History_of_China.txt ../out/ae/35/History_of_China.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/bd/Lory_%28disambiguation%29.txt ../out/ae/bd/Lory_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/7d/Carl_Barks.txt ../out/af/7d/Carl_Barks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/06/The_Amazing_Spider-Man.txt ../out/b0/06/The_Amazing_Spider-Man.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/66/Army.txt ../out/b0/66/Army.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/39/Binary_Synchronous_Transmission.txt ../out/b1/39/Binary_Synchronous_Transmission.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/c6/Declaration_of_the_Rights_of_Man_and_of_the_Citizen.txt ../out/b1/c6/Declaration_of_the_Rights_of_Man_and_of_the_Citizen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/4a/Agner_Krarup_Erlang.txt ../out/b2/4a/Agner_Krarup_Erlang.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/5e/Chess_Board.txt ../out/b3/5e/Chess_Board.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/f1/Charles_Proteus_Steinmetz.txt ../out/b3/f1/Charles_Proteus_Steinmetz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/91/DavidHume.txt ../out/b4/91/DavidHume.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/ce/Bookkeeping.txt ../out/b4/ce/Bookkeeping.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/3d/Dumpster_diving.txt ../out/b5/3d/Dumpster_diving.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/d5/Brassicales.txt ../out/b5/d5/Brassicales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/6b/Danse_Macabre.txt ../out/b6/6b/Danse_Macabre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/7a/Dynamite.txt ../out/b7/7a/Dynamite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/e1/Ancient_Egypt.txt ../out/b7/e1/Ancient_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/6c/Clade.txt ../out/b8/6c/Clade.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/50/Aircraft.txt ../out/b9/50/Aircraft.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/ed/Natives_of_Arizona.txt ../out/b9/ed/Natives_of_Arizona.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/b3/Bob_Hawke.txt ../out/ba/b3/Bob_Hawke.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/3d/Economy_of_Brazil.txt ../out/bb/3d/Economy_of_Brazil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/c9/List_of_major_biblical_figures.txt ../out/bb/c9/List_of_major_biblical_figures.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/62/A_Fire_Upon_the_Deep.txt ../out/bc/62/A_Fire_Upon_the_Deep.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/03/Diatessaron.txt ../out/bd/03/Diatessaron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/bf/Bocce.txt ../out/bd/bf/Bocce.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/91/Bill_Gates.txt ../out/be/91/Bill_Gates.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/3d/Baruch_Spinoza.txt ../out/bf/3d/Baruch_Spinoza.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/e5/Bentley.txt ../out/bf/e5/Bentley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/a5/Chechnya.txt ../out/c0/a5/Chechnya.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/59/Constitution_of_Canada%2F1867_III_Executive_Power.txt ../out/c1/59/Constitution_of_Canada%2F1867_III_Executive_Power.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/f9/Cnidaria.txt ../out/c1/f9/Cnidaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/ed/Ecstacy.txt ../out/c2/ed/Ecstacy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/a0/Bahamas%2FMilitary.txt ../out/c3/a0/Bahamas%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/20/Aquinas.txt ../out/c4/20/Aquinas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/ac/Brownian_motion.txt ../out/c4/ac/Brownian_motion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/b3/Canis_latrans.txt ../out/c5/b3/Canis_latrans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/2c/Cartesian.txt ../out/c6/2c/Cartesian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/1a/Autochthones.txt ../out/c7/1a/Autochthones.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/cd/Telecommunications_in_Chile.txt ../out/c7/cd/Telecommunications_in_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/7d/Diprotodon.txt ../out/c8/7d/Diprotodon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/47/Geography_of_Africa.txt ../out/c9/47/Geography_of_Africa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/c8/Tech_bubble.txt ../out/c9/c8/Tech_bubble.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/46/DoD.txt ../out/ca/46/DoD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/36/Barnard_College.txt ../out/cb/36/Barnard_College.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/da/CPM.txt ../out/cb/da/CPM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/bf/Alexander_Graham_Bell.txt ../out/cc/bf/Alexander_Graham_Bell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/39/Axiom_of_regularity.txt ../out/cd/39/Axiom_of_regularity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/e2/Dar_es_Salaam.txt ../out/cd/e2/Dar_es_Salaam.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/bf/Battle_of_Poitiers.txt ../out/ce/bf/Battle_of_Poitiers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/87/Anguilla%2FTransnational_issues.txt ../out/cf/87/Anguilla%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/13/Deism.txt ../out/d0/13/Deism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/01/Elias_Canetti.txt ../out/d1/01/Elias_Canetti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/71/Code_division_multiple_access.txt ../out/d1/71/Code_division_multiple_access.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/55/Channel_Islands.txt ../out/d2/55/Channel_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/de/Barb_Wire.txt ../out/d2/de/Barb_Wire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/8f/B-tree.txt ../out/d3/8f/B-tree.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/41/Diedrich_Westermann.txt ../out/d4/41/Diedrich_Westermann.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/fd/Anime.txt ../out/d4/fd/Anime.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/a7/Military_of_the_Czech_Republic.txt ../out/d5/a7/Military_of_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/52/Abdur_Rahman_Khan.txt ../out/d6/52/Abdur_Rahman_Khan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/df/Deed_poll.txt ../out/d6/df/Deed_poll.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/69/Control_store.txt ../out/d7/69/Control_store.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/15/Accumulator_%28computing%29.txt ../out/d8/15/Accumulator_%28computing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/e9/Columbia%2C_Missouri.txt ../out/d8/e9/Columbia%2C_Missouri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/9a/Concept.txt ../out/d9/9a/Concept.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/27/European_Democrats.txt ../out/da/27/European_Democrats.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/c3/Adam_of_Bremen.txt ../out/da/c3/Adam_of_Bremen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/47/Duodecimal.txt ../out/db/47/Duodecimal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/14/CIT.txt ../out/dc/14/CIT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/98/Bass_%28sound%29.txt ../out/dc/98/Bass_%28sound%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/51/Dale_Earnhardt.txt ../out/dd/51/Dale_Earnhardt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/d3/Dan_Simmons.txt ../out/dd/d3/Dan_Simmons.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/88/ABBA.txt ../out/de/88/ABBA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/4a/Eric_Arthur_Blair.txt ../out/df/4a/Eric_Arthur_Blair.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/0f/Annapolis_Valley.txt ../out/e0/0f/Annapolis_Valley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/d4/Abdul_Rashid_Dostum.txt ../out/e0/d4/Abdul_Rashid_Dostum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/92/Agarose.txt ../out/e1/92/Agarose.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/2d/Professor_X.txt ../out/e2/2d/Professor_X.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/f5/ATC_classification.txt ../out/e2/f5/ATC_classification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/77/Communications_in_Bassas_da_India.txt ../out/e3/77/Communications_in_Bassas_da_India.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/19/Abatement_of_false_lights.txt ../out/e4/19/Abatement_of_false_lights.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/f1/Alien_and_Sedition_Acts.txt ../out/e4/f1/Alien_and_Sedition_Acts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/74/Commutator_subgroup.txt ../out/e5/74/Commutator_subgroup.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/0a/Centrohelids.txt ../out/e6/0a/Centrohelids.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/c9/Charcot%E2%80%93Marie%E2%80%93Tooth_disease.txt ../out/e6/c9/Charcot%E2%80%93Marie%E2%80%93Tooth_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/97/Digimon.txt ../out/e7/97/Digimon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/38/Endomorphism.txt ../out/e8/38/Endomorphism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/e2/Archbishopric_of_Riga.txt ../out/e8/e2/Archbishopric_of_Riga.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/6d/El_Salvador.txt ../out/e9/6d/El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/ea/Book_of_Ezra.txt ../out/e9/ea/Book_of_Ezra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/57/Cantonese_cuisine.txt ../out/ea/57/Cantonese_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/2a/Diesel_engines.txt ../out/eb/2a/Diesel_engines.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/cf/Baltic_Sea%2FGdanzk.txt ../out/eb/cf/Baltic_Sea%2FGdanzk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/a0/Dirt_speedway_racing.txt ../out/ec/a0/Dirt_speedway_racing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/77/Articles_of_Faith.txt ../out/ed/77/Articles_of_Faith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/f4/Cauchy_sequence.txt ../out/ed/f4/Cauchy_sequence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/97/ColdWar.txt ../out/ee/97/ColdWar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/38/Dr_Suess.txt ../out/ef/38/Dr_Suess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/b5/Apollo_17.txt ../out/ef/b5/Apollo_17.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/66/Exploit_%28computer_security%29.txt ../out/f0/66/Exploit_%28computer_security%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/30/Basic_English.txt ../out/f1/30/Basic_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/09/Alfonso_II.txt ../out/f2/09/Alfonso_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/fe/Basques.txt ../out/f2/fe/Basques.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/c7/Bavarii.txt ../out/f3/c7/Bavarii.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/8e/Crossfire.txt ../out/f4/8e/Crossfire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/6d/Craps.txt ../out/f5/6d/Craps.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/f7/Aberdeen.txt ../out/f5/f7/Aberdeen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/b8/Burma%2FCommunications.txt ../out/f6/b8/Burma%2FCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/2a/Eriocaulales.txt ../out/f7/2a/Eriocaulales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/cb/Bactericide.txt ../out/f7/cb/Bactericide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/96/Ennius.txt ../out/f8/96/Ennius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/08/Damascus.txt ../out/f9/08/Damascus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/8c/Disruption.txt ../out/f9/8c/Disruption.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/0f/Convolution.txt ../out/fa/0f/Convolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/b8/District_of_Columbia.txt ../out/fa/b8/District_of_Columbia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/5e/Ambiorix.txt ../out/fb/5e/Ambiorix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/f2/Astronomical_year_numbering.txt ../out/fb/f2/Astronomical_year_numbering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/08/Comment_%28computing%29.txt ../out/fd/08/Comment_%28computing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/b8/AxiomOfChoice.txt ../out/fd/b8/AxiomOfChoice.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/62/Environmental_Modification_Convention.txt ../out/fe/62/Environmental_Modification_Convention.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/f9/Geography_of_Bosnia_and_Herzegovina.txt ../out/fe/f9/Geography_of_Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/75/Book_of_Hosea.txt ../out/ff/75/Book_of_Hosea.xml
