php ./wiki2xml/php/wiki2xml_command.php ../out/00/79/Transnational_issues_of_the_British_Virgin_Islands.txt ../out/00/79/Transnational_issues_of_the_British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/37/Big_Brother_%28franchise%29.txt ../out/01/37/Big_Brother_%28franchise%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/cb/BT_Group.txt ../out/01/cb/BT_Group.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/9d/Declension.txt ../out/02/9d/Declension.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/3c/DASS1.txt ../out/03/3c/DASS1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/cf/Edinburgh.txt ../out/03/cf/Edinburgh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/62/Communist_Party_of_China.txt ../out/04/62/Communist_Party_of_China.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/03/Beatles.txt ../out/05/03/Beatles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/78/Cheddar%2C_Somerset.txt ../out/05/78/Cheddar%2C_Somerset.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/01/Geography_of_Estonia.txt ../out/06/01/Geography_of_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/ce/Distributism.txt ../out/06/ce/Distributism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/5e/Dunstan.txt ../out/07/5e/Dunstan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/30/Director%27s_cut.txt ../out/08/30/Director%27s_cut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/af/Commonwealth_of_England.txt ../out/08/af/Commonwealth_of_England.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/7d/Acropolis_of_Athens.txt ../out/09/7d/Acropolis_of_Athens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/40/AI.txt ../out/0a/40/AI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/b3/Caustic_soda.txt ../out/0a/b3/Caustic_soda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/84/Expert.txt ../out/0b/84/Expert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/d3/Bing_Crosby.txt ../out/0b/d3/Bing_Crosby.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/82/Arab_countries.txt ../out/0c/82/Arab_countries.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/3a/Clyde_Tombaugh.txt ../out/0d/3a/Clyde_Tombaugh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/04/Action_Against_Hunger.txt ../out/0e/04/Action_Against_Hunger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/ac/Czechoslovakia.txt ../out/0e/ac/Czechoslovakia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/4d/Continuation_War.txt ../out/0f/4d/Continuation_War.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/0d/Book_of_Zephaniah.txt ../out/10/0d/Book_of_Zephaniah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/0e/Counter_Point.txt ../out/11/0e/Counter_Point.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/c3/Bastarnae.txt ../out/11/c3/Bastarnae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/5d/Americans_with_Disabilities_Act_of_1990.txt ../out/12/5d/Americans_with_Disabilities_Act_of_1990.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/fb/Berry_paradox.txt ../out/12/fb/Berry_paradox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/7d/Binary_function.txt ../out/13/7d/Binary_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/2f/Craig_Venter.txt ../out/14/2f/Craig_Venter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/eb/COBOL.txt ../out/14/eb/COBOL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/60/Classical_order.txt ../out/15/60/Classical_order.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/38/Brittonic.txt ../out/16/38/Brittonic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/c0/British_Airways.txt ../out/16/c0/British_Airways.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/b6/Politics_of_Cambodia.txt ../out/17/b6/Politics_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/4d/Dragoon.txt ../out/18/4d/Dragoon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/d5/April_11.txt ../out/18/d5/April_11.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/5d/Boston_Herald.txt ../out/19/5d/Boston_Herald.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/f7/COPPA.txt ../out/19/f7/COPPA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/9a/Boeing_747.txt ../out/1a/9a/Boeing_747.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/08/Anabaptists.txt ../out/1b/08/Anabaptists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/a4/Evolutionary_psychology.txt ../out/1b/a4/Evolutionary_psychology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/28/Cuisine.txt ../out/1c/28/Cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/af/The_Beano.txt ../out/1c/af/The_Beano.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/3a/Abiword.txt ../out/1d/3a/Abiword.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/ee/Arthur_Phillip.txt ../out/1d/ee/Arthur_Phillip.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/8b/Cave.txt ../out/1e/8b/Cave.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/54/Double_bass.txt ../out/1f/54/Double_bass.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/17/Algebraic_number.txt ../out/20/17/Algebraic_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/b7/Collagen.txt ../out/20/b7/Collagen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/50/Cadillac%2C_Michigan.txt ../out/21/50/Cadillac%2C_Michigan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/53/Chiliasm.txt ../out/22/53/Chiliasm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/e9/Abandonment_of_domicile.txt ../out/22/e9/Abandonment_of_domicile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/90/Argot.txt ../out/23/90/Argot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/26/Electronic_paper.txt ../out/24/26/Electronic_paper.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/dd/Blue_law.txt ../out/24/dd/Blue_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/ad/Columba.txt ../out/25/ad/Columba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/35/April_10.txt ../out/26/35/April_10.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/ef/AcademyAwards.txt ../out/26/ef/AcademyAwards.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/90/Berkeley%2C_California.txt ../out/27/90/Berkeley%2C_California.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/2e/Geography_of_Canada.txt ../out/28/2e/Geography_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/bb/Dave_Grohl.txt ../out/28/bb/Dave_Grohl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/77/Czech_republic%2FTransnational_issues.txt ../out/29/77/Czech_republic%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/1d/Aberdeen%2C_South_Dakota.txt ../out/2a/1d/Aberdeen%2C_South_Dakota.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/de/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FS2.txt ../out/2a/de/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FS2.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/74/Cooking%2FBlanching.txt ../out/2b/74/Cooking%2FBlanching.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/28/Battle_of_Bosworth_Field.txt ../out/2c/28/Battle_of_Bosworth_Field.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/ac/Asian_Development_Bank.txt ../out/2c/ac/Asian_Development_Bank.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/4d/Cape_Breton_Island.txt ../out/2d/4d/Cape_Breton_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/13/American_sign_language.txt ../out/2e/13/American_sign_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/d5/Anthemius_of_Tralles.txt ../out/2e/d5/Anthemius_of_Tralles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/86/CGMP.txt ../out/2f/86/CGMP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/89/Dentistry.txt ../out/30/89/Dentistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/12/Books_of_Kings.txt ../out/31/12/Books_of_Kings.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/d9/Telecommunications_in_Belarus.txt ../out/31/d9/Telecommunications_in_Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/c8/Clutch.txt ../out/32/c8/Clutch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/41/Classical_element.txt ../out/33/41/Classical_element.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/4e/Government_of_Barbados.txt ../out/34/4e/Government_of_Barbados.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/e6/Anthrosophy.txt ../out/34/e6/Anthrosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/85/Man_Booker_Prize.txt ../out/35/85/Man_Booker_Prize.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/5c/American_Samoa%2FMilitary.txt ../out/36/5c/American_Samoa%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/1f/Bassoon.txt ../out/37/1f/Bassoon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/8d/Barry_Lyndon.txt ../out/37/8d/Barry_Lyndon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/0a/Chaos_theory.txt ../out/38/0a/Chaos_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/75/Babe_Ruth.txt ../out/38/75/Babe_Ruth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/91/Coleridge.txt ../out/39/91/Coleridge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/25/DNA_chip.txt ../out/3a/25/DNA_chip.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/81/Commodore_1571.txt ../out/3a/81/Commodore_1571.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/28/Abner_Doubleday.txt ../out/3b/28/Abner_Doubleday.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/b4/Abbreviations.txt ../out/3b/b4/Abbreviations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/2a/Cordwainer_Smith.txt ../out/3c/2a/Cordwainer_Smith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/f2/Cell_incubator.txt ../out/3c/f2/Cell_incubator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/79/Astronomical_Units.txt ../out/3d/79/Astronomical_Units.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/2c/Alpha_helix.txt ../out/3e/2c/Alpha_helix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/c0/Commonwealth_Heads_of_Government_Meeting.txt ../out/3e/c0/Commonwealth_Heads_of_Government_Meeting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/2b/Difference_engine.txt ../out/3f/2b/Difference_engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/e4/Abydos%2C_Egypt.txt ../out/3f/e4/Abydos%2C_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/89/Cairn.txt ../out/40/89/Cairn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/31/Albert_Arnold_Gore%2FCriticisms.txt ../out/41/31/Albert_Arnold_Gore%2FCriticisms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/c3/Atomic_orbitals.txt ../out/41/c3/Atomic_orbitals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/16/D%C3%A9j%C3%A0_vu.txt ../out/42/16/D%C3%A9j%C3%A0_vu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/9a/Edna_St._Vincent_Millay.txt ../out/42/9a/Edna_St._Vincent_Millay.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/76/Astrometry.txt ../out/43/76/Astrometry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/0a/Demographics_of_the_Cook_Islands.txt ../out/44/0a/Demographics_of_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/92/Battery_Park_City.txt ../out/44/92/Battery_Park_City.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/2a/Belgian_hip_hop.txt ../out/45/2a/Belgian_hip_hop.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/f4/Angle.txt ../out/45/f4/Angle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/63/Astronaut.txt ../out/46/63/Astronaut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/49/Abu_Sayyaf.txt ../out/47/49/Abu_Sayyaf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/ec/Bignum.txt ../out/47/ec/Bignum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/a6/Bulldogging.txt ../out/48/a6/Bulldogging.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/32/Business_ethics.txt ../out/49/32/Business_ethics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/dd/Book_of_Judges.txt ../out/49/dd/Book_of_Judges.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/9a/Chromosome_walking.txt ../out/4a/9a/Chromosome_walking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/32/Donald_Campbell.txt ../out/4b/32/Donald_Campbell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/d8/Camouflage.txt ../out/4b/d8/Camouflage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/50/Class_envy.txt ../out/4c/50/Class_envy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/32/Cruise_missile.txt ../out/4d/32/Cruise_missile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/99/Telecommunications_in_El_Salvador.txt ../out/4d/99/Telecommunications_in_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/33/Geography_of_Burkina_Faso.txt ../out/4e/33/Geography_of_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/db/BiblicalInterpretation.txt ../out/4e/db/BiblicalInterpretation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/7b/American_National_Standards_Institute.txt ../out/4f/7b/American_National_Standards_Institute.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/40/Ares.txt ../out/50/40/Ares.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/05/Transport_in_Botswana.txt ../out/51/05/Transport_in_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/8f/AbbadideS.txt ../out/51/8f/AbbadideS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/40/Book_of_Mormon.txt ../out/52/40/Book_of_Mormon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/fd/Beechcraft.txt ../out/52/fd/Beechcraft.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/7c/Celebrity_atheists.txt ../out/53/7c/Celebrity_atheists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/07/Bead.txt ../out/54/07/Bead.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/95/Telecommunications_in_Cameroon.txt ../out/54/95/Telecommunications_in_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/1c/Economy_of_Bulgaria.txt ../out/55/1c/Economy_of_Bulgaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/e4/Aix-la-Chapelle.txt ../out/55/e4/Aix-la-Chapelle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/ca/Basic_Role-Playing.txt ../out/56/ca/Basic_Role-Playing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/7d/Alexander_Grothendieck.txt ../out/57/7d/Alexander_Grothendieck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/39/Convention_on_Long-Range_Transboundary_Air_Pollution.txt ../out/58/39/Convention_on_Long-Range_Transboundary_Air_Pollution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/d8/Eiffel.txt ../out/58/d8/Eiffel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/53/Geography_of_the_Czech_Republic.txt ../out/59/53/Geography_of_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/f0/Apollo_8.txt ../out/59/f0/Apollo_8.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/85/Classical_Music.txt ../out/5a/85/Classical_Music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/01/Bourbon.txt ../out/5b/01/Bourbon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/bf/Calorie.txt ../out/5b/bf/Calorie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/72/Endomembrane_system.txt ../out/5c/72/Endomembrane_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/29/Apicomplexa.txt ../out/5d/29/Apicomplexa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/0d/Absalom.txt ../out/5e/0d/Absalom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/82/Astronomical_Unit.txt ../out/5e/82/Astronomical_Unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/2c/Daoism%E2%80%93Taoism_romanization_issue.txt ../out/5f/2c/Daoism%E2%80%93Taoism_romanization_issue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/fb/Foreign_relations_of_Cameroon.txt ../out/5f/fb/Foreign_relations_of_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/a0/Andocides.txt ../out/60/a0/Andocides.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/65/Bunnies_%26_Burrows.txt ../out/61/65/Bunnies_%26_Burrows.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/c3/Brian_de_Palma.txt ../out/61/c3/Brian_de_Palma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/a4/Esperantujo.txt ../out/62/a4/Esperantujo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/89/ClusterSampling.txt ../out/63/89/ClusterSampling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/8c/Critical_point.txt ../out/64/8c/Critical_point.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/19/Developmental_biology.txt ../out/65/19/Developmental_biology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/7b/CoSims.txt ../out/65/7b/CoSims.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/fc/Associate_Justice_of_the_Supreme_Court_of_the_United_States.txt ../out/65/fc/Associate_Justice_of_the_Supreme_Court_of_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/ab/Anxiety.txt ../out/66/ab/Anxiety.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/1c/Azawakh.txt ../out/67/1c/Azawakh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/e2/Hymn_to_Proserpine.txt ../out/67/e2/Hymn_to_Proserpine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/74/Andorra.txt ../out/68/74/Andorra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/41/Alexios_II_Komnenos.txt ../out/69/41/Alexios_II_Komnenos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/ec/Blind_drunk.txt ../out/69/ec/Blind_drunk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/90/Distributed_computing.txt ../out/6a/90/Distributed_computing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/ff/Allegiance.txt ../out/6a/ff/Allegiance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/a4/Military_of_the_Democratic_Republic_of_the_Congo.txt ../out/6b/a4/Military_of_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/3e/ConsciousNess.txt ../out/6c/3e/ConsciousNess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/ad/Companies_law.txt ../out/6c/ad/Companies_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/49/Abergavenny.txt ../out/6d/49/Abergavenny.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/df/Centromer.txt ../out/6d/df/Centromer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/8b/The_Plague.txt ../out/6e/8b/The_Plague.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/f0/History_of_the_Cocos_%28Keeling%29_Islands.txt ../out/6e/f0/History_of_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/ad/Clabbers.txt ../out/6f/ad/Clabbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/8c/Devanagiri.txt ../out/70/8c/Devanagiri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/44/Estruscan_alphabet.txt ../out/71/44/Estruscan_alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/f6/Adobe.txt ../out/71/f6/Adobe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/80/Clerihew.txt ../out/72/80/Clerihew.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/59/Air_conditioner.txt ../out/73/59/Air_conditioner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/16/Archimedean_solid.txt ../out/74/16/Archimedean_solid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/73/Epistle_to_the_Galatians.txt ../out/74/73/Epistle_to_the_Galatians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/f4/Carroll_OConnor.txt ../out/74/f4/Carroll_OConnor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/97/Common_descent.txt ../out/75/97/Common_descent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/65/British_Isles.txt ../out/76/65/British_Isles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/f7/Dolphin.txt ../out/76/f7/Dolphin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/a9/Antisemitism.txt ../out/77/a9/Antisemitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/54/Columbium.txt ../out/78/54/Columbium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/d6/COFDM.txt ../out/78/d6/COFDM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/95/Book_of_Hebrews.txt ../out/79/95/Book_of_Hebrews.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/2d/Down_syndrome.txt ../out/7a/2d/Down_syndrome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/8e/CountriesD.txt ../out/7a/8e/CountriesD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/e5/Dance.txt ../out/7a/e5/Dance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/f3/Asteroid.txt ../out/7b/f3/Asteroid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/9a/Albert_Archilles.txt ../out/7c/9a/Albert_Archilles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/20/Foreign_relations_of_the_Central_African_Republic.txt ../out/7d/20/Foreign_relations_of_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/b5/Analysis_of_variance%2FDegrees_of_freedom.txt ../out/7d/b5/Analysis_of_variance%2FDegrees_of_freedom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/5b/Dubbing_%28filmmaking%29.txt ../out/7e/5b/Dubbing_%28filmmaking%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/0c/Extinct_political_countries%2C_empires%2C_etc..txt ../out/7f/0c/Extinct_political_countries%2C_empires%2C_etc..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/b1/Drew_Barrymore.txt ../out/7f/b1/Drew_Barrymore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/21/Bertrand_Russell.txt ../out/80/21/Bertrand_Russell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/ad/Anna_Kournikova.txt ../out/80/ad/Anna_Kournikova.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/76/Ahmed_I.txt ../out/81/76/Ahmed_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/fd/Ceramic.txt ../out/81/fd/Ceramic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/e4/Dartmouth%2C_Devon.txt ../out/82/e4/Dartmouth%2C_Devon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/a7/Aegean_civilizations.txt ../out/83/a7/Aegean_civilizations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/52/Anti-depressant.txt ../out/84/52/Anti-depressant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/2f/Bilateral_symetry.txt ../out/85/2f/Bilateral_symetry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/97/B%2A-algebra.txt ../out/85/97/B%2A-algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/27/Diesel_Engine.txt ../out/86/27/Diesel_Engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/df/David_Beatty%2C_1st_Earl_Beatty.txt ../out/86/df/David_Beatty%2C_1st_Earl_Beatty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/59/Geography_of_American_Samoa.txt ../out/87/59/Geography_of_American_Samoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/75/Coprime_integers.txt ../out/88/75/Coprime_integers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/0c/EsperantujO.txt ../out/89/0c/EsperantujO.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/92/Geography_of_Colombia.txt ../out/89/92/Geography_of_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/16/Declarative_memory.txt ../out/8a/16/Declarative_memory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/09/Columbanus.txt ../out/8b/09/Columbanus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/9d/Claudius_Aelianus.txt ../out/8b/9d/Claudius_Aelianus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/58/History_of_the_Central_African_Republic.txt ../out/8c/58/History_of_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/c2/Dramaturge.txt ../out/8c/c2/Dramaturge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/2e/Balfour_Declaration_of_1926.txt ../out/8d/2e/Balfour_Declaration_of_1926.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/3c/Battle_of_Okinawa.txt ../out/8e/3c/Battle_of_Okinawa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/00/Alfonso_III.txt ../out/8f/00/Alfonso_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/c3/Dartmouth_College.txt ../out/8f/c3/Dartmouth_College.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/b8/DagnyTaggart.txt ../out/90/b8/DagnyTaggart.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/28/Demographics_of_Armenia.txt ../out/91/28/Demographics_of_Armenia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/36/Telecommunications_in_Cambodia.txt ../out/92/36/Telecommunications_in_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/eb/Determinant.txt ../out/92/eb/Determinant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/9a/Confederate_States_of_America.txt ../out/93/9a/Confederate_States_of_America.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/77/Ben_Nevis.txt ../out/94/77/Ben_Nevis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/26/Elegiac_couplet.txt ../out/95/26/Elegiac_couplet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/b1/Data_compression_ratio.txt ../out/95/b1/Data_compression_ratio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/8f/Aristophanes.txt ../out/96/8f/Aristophanes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/27/Delaware_General_Corporation_Law.txt ../out/97/27/Delaware_General_Corporation_Law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/b0/Congo-Brazzaville.txt ../out/97/b0/Congo-Brazzaville.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/46/Byzantium.txt ../out/98/46/Byzantium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/c6/Electronic_Music%2FDrum_and_Bass.txt ../out/98/c6/Electronic_Music%2FDrum_and_Bass.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/43/Dualistic_interactionism.txt ../out/99/43/Dualistic_interactionism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/bf/CPD.txt ../out/99/bf/CPD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/52/Continuum_hypothesis.txt ../out/9a/52/Continuum_hypothesis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/ca/CategoryTheory.txt ../out/9a/ca/CategoryTheory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/8f/Arithmetic.txt ../out/9b/8f/Arithmetic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/0d/Anton_Chekhov.txt ../out/9c/0d/Anton_Chekhov.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/9d/CharlieChaplin.txt ../out/9c/9d/CharlieChaplin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/33/Cardiac_glycoside.txt ../out/9d/33/Cardiac_glycoside.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/b9/Cyborgs_in_fiction.txt ../out/9d/b9/Cyborgs_in_fiction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/74/AlexanderTheGreat.txt ../out/9e/74/AlexanderTheGreat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/5b/Carmilla.txt ../out/9f/5b/Carmilla.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/f4/Egoism.txt ../out/9f/f4/Egoism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/a6/Agasias.txt ../out/a0/a6/Agasias.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/68/Client%E2%80%93server_model.txt ../out/a1/68/Client%E2%80%93server_model.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/51/Aw.txt ../out/a2/51/Aw.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/f7/CryptographY%2FHashfunctions.txt ../out/a2/f7/CryptographY%2FHashfunctions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/ab/Afghanistan%2FHistory.txt ../out/a3/ab/Afghanistan%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/75/Catan%3A_Seafarers.txt ../out/a4/75/Catan%3A_Seafarers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/ed/Agent_Orange.txt ../out/a4/ed/Agent_Orange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/67/Cajun_cuisine.txt ../out/a5/67/Cajun_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/c2/Draft%3ATo_code_for.txt ../out/a5/c2/Draft%3ATo_code_for.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/bc/Alexandria.txt ../out/a6/bc/Alexandria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/33/Subspecies_of_Canis_lupus.txt ../out/a7/33/Subspecies_of_Canis_lupus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/13/Auteur_Theory_Film.txt ../out/a8/13/Auteur_Theory_Film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/ca/Anderida.txt ../out/a8/ca/Anderida.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/8c/Balmoral_Castle.txt ../out/a9/8c/Balmoral_Castle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/4d/Economy_of_Ethiopia.txt ../out/aa/4d/Economy_of_Ethiopia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/bc/Cost-push_inflation.txt ../out/aa/bc/Cost-push_inflation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/43/List_of_decades.txt ../out/ab/43/List_of_decades.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/f4/Antisymmetric_relation.txt ../out/ab/f4/Antisymmetric_relation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/85/Albert_of_Mainz.txt ../out/ac/85/Albert_of_Mainz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/df/Docklands_Light_Railway.txt ../out/ac/df/Docklands_Light_Railway.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/b8/Dutch_hip_hop.txt ../out/ad/b8/Dutch_hip_hop.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/5c/Cepheus.txt ../out/ae/5c/Cepheus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/f8/Br%C3%ADsingamen.txt ../out/ae/f8/Br%C3%ADsingamen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/88/Chicago_Cubs.txt ../out/af/88/Chicago_Cubs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/19/August_Derleth.txt ../out/b0/19/August_Derleth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/c4/Cytoprotectant.txt ../out/b0/c4/Cytoprotectant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/61/Bakassi.txt ../out/b1/61/Bakassi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/da/Book_of_Habakkuk.txt ../out/b1/da/Book_of_Habakkuk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/60/London_Borough_of_Croydon.txt ../out/b2/60/London_Borough_of_Croydon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/94/Cascade_Mountain_Range.txt ../out/b3/94/Cascade_Mountain_Range.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/3a/December_17.txt ../out/b4/3a/December_17.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/a2/Bi-directional_text.txt ../out/b4/a2/Bi-directional_text.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/d3/Epistemology.txt ../out/b4/d3/Epistemology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/52/America_the_Beautiful.txt ../out/b5/52/America_the_Beautiful.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/ec/Carl_Friedrich_Gauss.txt ../out/b5/ec/Carl_Friedrich_Gauss.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/a9/Asynchronous_Digital_Subscriber_Line.txt ../out/b6/a9/Asynchronous_Digital_Subscriber_Line.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/93/Cathode_ray.txt ../out/b7/93/Cathode_ray.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/16/Archeoastronomy.txt ../out/b8/16/Archeoastronomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/97/Amerigo_Vespucci.txt ../out/b8/97/Amerigo_Vespucci.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/80/Apollo_program.txt ../out/b9/80/Apollo_program.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/1b/Baseball%2FHistory_of_baseball.txt ../out/ba/1b/Baseball%2FHistory_of_baseball.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/c3/Dysprosium.txt ../out/ba/c3/Dysprosium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/64/Analog_Magazine.txt ../out/bb/64/Analog_Magazine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/eb/Amputation.txt ../out/bb/eb/Amputation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/71/Betting.txt ../out/bc/71/Betting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/40/Republic_of_Croatia_Armed_Forces.txt ../out/bd/40/Republic_of_Croatia_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/f3/Abyssinia.txt ../out/bd/f3/Abyssinia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/c2/History_of_the_Soviet_Union_%281982%E2%80%9391%29.txt ../out/be/c2/History_of_the_Soviet_Union_%281982%E2%80%9391%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/52/Empire_State_Building.txt ../out/bf/52/Empire_State_Building.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/fb/Alan_Ayckbourn%2FPlays.txt ../out/bf/fb/Alan_Ayckbourn%2FPlays.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/b7/Traditional_Chinese_medicine.txt ../out/c0/b7/Traditional_Chinese_medicine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/74/European_People%27s_Party_Group.txt ../out/c1/74/European_People%27s_Party_Group.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/41/Alternate_history.txt ../out/c2/41/Alternate_history.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/0d/Andronikos_II_Palaiologos.txt ../out/c3/0d/Andronikos_II_Palaiologos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/b0/Bacillus_thuringiensis.txt ../out/c3/b0/Bacillus_thuringiensis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/3d/Asteraceae.txt ../out/c4/3d/Asteraceae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/e8/Constantius_II.txt ../out/c4/e8/Constantius_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/e0/Berry_Berenson.txt ../out/c5/e0/Berry_Berenson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/7a/Cypress_Hill.txt ../out/c6/7a/Cypress_Hill.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/28/Ab_urbe_condita.txt ../out/c7/28/Ab_urbe_condita.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/eb/Crystallography.txt ../out/c7/eb/Crystallography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/b0/Brooklyn_Historic_Railway_Association.txt ../out/c8/b0/Brooklyn_Historic_Railway_Association.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/53/Chondrichthyes.txt ../out/c9/53/Chondrichthyes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/e6/De_Havilland_Mosquito.txt ../out/c9/e6/De_Havilland_Mosquito.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/6a/Bruce_Campbell.txt ../out/ca/6a/Bruce_Campbell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/5a/Buddy_Holly.txt ../out/cb/5a/Buddy_Holly.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/0f/Barbados%2FTransnational_issues.txt ../out/cc/0f/Barbados%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/e1/British_English.txt ../out/cc/e1/British_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/54/APL.txt ../out/cd/54/APL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/eb/Chives.txt ../out/cd/eb/Chives.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/df/At_bat.txt ../out/ce/df/At_bat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/8f/Dyslectic.txt ../out/cf/8f/Dyslectic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/30/Amiga_500.txt ../out/d0/30/Amiga_500.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/20/Chemotherapy.txt ../out/d1/20/Chemotherapy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/7d/Athanasian_Creed.txt ../out/d1/7d/Athanasian_Creed.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/79/David_Hilbert.txt ../out/d2/79/David_Hilbert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/0a/Euclidean_geometry.txt ../out/d3/0a/Euclidean_geometry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/a5/Canton.txt ../out/d3/a5/Canton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/85/Beta-lactamase.txt ../out/d4/85/Beta-lactamase.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/14/Concubinage.txt ../out/d5/14/Concubinage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/b1/Deuterium.txt ../out/d5/b1/Deuterium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/6d/Abaris.txt ../out/d6/6d/Abaris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/ef/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FA.txt ../out/d6/ef/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/8b/Abscess.txt ../out/d7/8b/Abscess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/42/AVL_tree.txt ../out/d8/42/AVL_tree.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/f7/Lhop_people.txt ../out/d8/f7/Lhop_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/ad/Black_Sea.txt ../out/d9/ad/Black_Sea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/67/Escort_carrier.txt ../out/da/67/Escort_carrier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/f0/File_archiver.txt ../out/da/f0/File_archiver.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/6e/African_rap_in_France.txt ../out/db/6e/African_rap_in_France.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/25/European_Strategic_Program_on_Research_in_Information_Technology.txt ../out/dc/25/European_Strategic_Program_on_Research_in_Information_Technology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/b0/Black_people.txt ../out/dc/b0/Black_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/74/Balsall_Heath.txt ../out/dd/74/Balsall_Heath.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/dd/Antimatter.txt ../out/dd/dd/Antimatter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/ab/Apadrayva_piercing.txt ../out/de/ab/Apadrayva_piercing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/61/Amber_Diceless_Roleplaying_Game.txt ../out/df/61/Amber_Diceless_Roleplaying_Game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/25/Bob_Dylans_Debut.txt ../out/e0/25/Bob_Dylans_Debut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/fb/August_7.txt ../out/e0/fb/August_7.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/a6/Chambered_cairn.txt ../out/e1/a6/Chambered_cairn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/66/Caitlin_Clarke.txt ../out/e2/66/Caitlin_Clarke.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/01/Continuum_mechanics.txt ../out/e3/01/Continuum_mechanics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/9d/Ceres.txt ../out/e3/9d/Ceres.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/43/Cesare_Borgia.txt ../out/e4/43/Cesare_Borgia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/02/Colin_Kapp.txt ../out/e5/02/Colin_Kapp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/ad/April_12.txt ../out/e5/ad/April_12.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/1e/December_30.txt ../out/e6/1e/December_30.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/06/Cheliceriformes.txt ../out/e7/06/Cheliceriformes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/c5/NYSE_MKT.txt ../out/e7/c5/NYSE_MKT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/56/Charles_Tupper.txt ../out/e8/56/Charles_Tupper.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/f8/AOL_Instant_Messanger.txt ../out/e8/f8/AOL_Instant_Messanger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/7c/Collation.txt ../out/e9/7c/Collation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/ff/April_21.txt ../out/e9/ff/April_21.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/94/Baseball.txt ../out/ea/94/Baseball.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/49/August_5.txt ../out/eb/49/August_5.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/e4/Bird.txt ../out/eb/e4/Bird.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/d0/Crossbow.txt ../out/ec/d0/Crossbow.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/8d/Death_factory.txt ../out/ed/8d/Death_factory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/ff/Battle_of_Blenheim.txt ../out/ed/ff/Battle_of_Blenheim.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/b3/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FK.txt ../out/ee/b3/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FK.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/47/Cilantro.txt ../out/ef/47/Cilantro.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/d1/Dr_Seuss.txt ../out/ef/d1/Dr_Seuss.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/8c/House_of_Bonaparte.txt ../out/f0/8c/House_of_Bonaparte.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/52/Electronvolt.txt ../out/f1/52/Electronvolt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/4b/Country_music.txt ../out/f2/4b/Country_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/2a/CNS.txt ../out/f3/2a/CNS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/d4/Ajax_of_Locris.txt ../out/f3/d4/Ajax_of_Locris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/b0/Byrd%2C_Robert.txt ../out/f4/b0/Byrd%2C_Robert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/7a/Cy_Young_Award.txt ../out/f5/7a/Cy_Young_Award.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/0a/Buffalo.txt ../out/f6/0a/Buffalo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/c3/Baryon.txt ../out/f6/c3/Baryon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/48/Computer_peripheral.txt ../out/f7/48/Computer_peripheral.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/11/Depeche_Mode.txt ../out/f8/11/Depeche_Mode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/ae/Miss_Marple.txt ../out/f8/ae/Miss_Marple.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/22/Animal_Farm.txt ../out/f9/22/Animal_Farm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/ba/Geography_of_Cambodia.txt ../out/f9/ba/Geography_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/37/Bay_%28disambiguation%29.txt ../out/fa/37/Bay_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/cc/Aikido.txt ../out/fa/cc/Aikido.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/71/Atlas_Autocode.txt ../out/fb/71/Atlas_Autocode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/19/Carlo_Collodi.txt ../out/fc/19/Carlo_Collodi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/30/Automatic_number_announcement_circuit.txt ../out/fd/30/Automatic_number_announcement_circuit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/d5/Alaska_Native_Claims_Settlement_Act.txt ../out/fd/d5/Alaska_Native_Claims_Settlement_Act.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/92/Boris_Pasternak.txt ../out/fe/92/Boris_Pasternak.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/36/Empirical_research.txt ../out/ff/36/Empirical_research.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/88/Dissociation_constant.txt ../out/ff/88/Dissociation_constant.xml
