php ./wiki2xml/php/wiki2xml_command.php ../out/00/23/Dravidian_languages.txt ../out/00/23/Dravidian_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/00/f4/Dog_tag.txt ../out/00/f4/Dog_tag.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/a9/Delaunay_triangulation.txt ../out/01/a9/Delaunay_triangulation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/3b/ASIC_%28disambiguation%29.txt ../out/02/3b/ASIC_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/f2/Aeon.txt ../out/02/f2/Aeon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/93/College_football.txt ../out/03/93/College_football.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/2b/Geography_of_Botswana.txt ../out/04/2b/Geography_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/a5/ExistencE.txt ../out/04/a5/ExistencE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/4f/Diego_Maradona.txt ../out/05/4f/Diego_Maradona.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/bf/Arthritus.txt ../out/05/bf/Arthritus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/76/Afghanistan%2FCommunications.txt ../out/06/76/Afghanistan%2FCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/07/Arian_%28disambiguation%29.txt ../out/07/07/Arian_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/d8/Afghan.txt ../out/07/d8/Afghan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/8d/AC_Milan.txt ../out/08/8d/AC_Milan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/0c/Erasmus_Alberus.txt ../out/09/0c/Erasmus_Alberus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/ff/Charles_Mingus.txt ../out/09/ff/Charles_Mingus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/8e/August_29.txt ../out/0a/8e/August_29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/37/Telecommunications_in_the_Cook_Islands.txt ../out/0b/37/Telecommunications_in_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/a5/Afonso_II_of_Portugal.txt ../out/0b/a5/Afonso_II_of_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/1c/Chinese_cuisine.txt ../out/0c/1c/Chinese_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/f7/Austroasiatic_languages.txt ../out/0c/f7/Austroasiatic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/c2/Antibody.txt ../out/0d/c2/Antibody.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/53/Antoine_Laurent_Lavoisier.txt ../out/0e/53/Antoine_Laurent_Lavoisier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/f1/Continuous_function.txt ../out/0e/f1/Continuous_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/ac/Cyberpunk.txt ../out/0f/ac/Cyberpunk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/c0/Chet_Atkins.txt ../out/10/c0/Chet_Atkins.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/76/Diablo_II_Lord_of_Destruction.txt ../out/11/76/Diablo_II_Lord_of_Destruction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/06/Detroit.txt ../out/12/06/Detroit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/a6/Arlo_Guthrie.txt ../out/12/a6/Arlo_Guthrie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/5a/Catalan_language.txt ../out/13/5a/Catalan_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/c6/Denary.txt ../out/13/c6/Denary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/96/Eskilstuna_Municipality.txt ../out/14/96/Eskilstuna_Municipality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/2c/List_of_country_calling_codes.txt ../out/15/2c/List_of_country_calling_codes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/e0/Foreign_relations_of_the_Dominican_Republic.txt ../out/15/e0/Foreign_relations_of_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/8b/Chris_Marker.txt ../out/16/8b/Chris_Marker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/61/Datsun.txt ../out/17/61/Datsun.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/11/Beetle.txt ../out/18/11/Beetle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/97/Andr%C3%A9-Marie_Amp%C3%A8re.txt ../out/18/97/Andr%C3%A9-Marie_Amp%C3%A8re.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/1d/Descriptive_statistics.txt ../out/19/1d/Descriptive_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/ae/Transport_in_the_Czech_Republic.txt ../out/19/ae/Transport_in_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/50/Abdul_Rashid_Dostam.txt ../out/1a/50/Abdul_Rashid_Dostam.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/dc/Chasidic_Judaism.txt ../out/1a/dc/Chasidic_Judaism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/64/Abraham_Joshua_Heschel.txt ../out/1b/64/Abraham_Joshua_Heschel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/f0/Catholicism%2FCouncil_of_Trent.txt ../out/1b/f0/Catholicism%2FCouncil_of_Trent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/7c/Duke_of_Marlborough_%28title%29.txt ../out/1c/7c/Duke_of_Marlborough_%28title%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/f1/Apollo_13.txt ../out/1c/f1/Apollo_13.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/a2/David_Lynch.txt ../out/1d/a2/David_Lynch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/42/Audio_codecs.txt ../out/1e/42/Audio_codecs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/b8/Carrier_battle_group.txt ../out/1e/b8/Carrier_battle_group.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/b6/Civilization%2Fvideo_game.txt ../out/1f/b6/Civilization%2Fvideo_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/59/E._B._White.txt ../out/20/59/E._B._White.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/0a/Burgundian.txt ../out/21/0a/Burgundian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/e2/Dredgers.txt ../out/21/e2/Dredgers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/98/Abgar.txt ../out/22/98/Abgar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/28/Atanasoff%E2%80%93Berry_computer.txt ../out/23/28/Atanasoff%E2%80%93Berry_computer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/06/Chinese_checkers.txt ../out/24/06/Chinese_checkers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/86/Geography_of_Bulgaria.txt ../out/24/86/Geography_of_Bulgaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/4b/Boomer.txt ../out/25/4b/Boomer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/02/Adoptionism.txt ../out/26/02/Adoptionism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/80/Canonization.txt ../out/26/80/Canonization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/3a/EconomicS.txt ../out/27/3a/EconomicS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/e6/Decibel.txt ../out/27/e6/Decibel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/7f/Northrop_Grumman_B-2_Spirit.txt ../out/28/7f/Northrop_Grumman_B-2_Spirit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/21/Clement_of_Alexandria.txt ../out/29/21/Clement_of_Alexandria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/a7/Antwerp_%28disambiguation%29.txt ../out/29/a7/Antwerp_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/5b/Abu_al-Faraj_al-Isfahani.txt ../out/2a/5b/Abu_al-Faraj_al-Isfahani.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/4d/Albert_Pike.txt ../out/2b/4d/Albert_Pike.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/d0/Einsteinium.txt ../out/2b/d0/Einsteinium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/71/Abydos.txt ../out/2c/71/Abydos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/19/Christmas_tree.txt ../out/2d/19/Christmas_tree.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/d6/Constitutional_monarchy.txt ../out/2d/d6/Constitutional_monarchy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/69/Geography_of_the_Dominican_Republic.txt ../out/2e/69/Geography_of_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/3e/Actaeon.txt ../out/2f/3e/Actaeon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/36/Devo.txt ../out/30/36/Devo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/e7/Akira_Kurosawa.txt ../out/30/e7/Akira_Kurosawa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/82/December_13.txt ../out/31/82/December_13.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/82/Carinatae.txt ../out/32/82/Carinatae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/f1/Control_unit.txt ../out/32/f1/Control_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/e8/Eschatology.txt ../out/33/e8/Eschatology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/c2/April_29.txt ../out/34/c2/April_29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/51/Alexander_of_Greece_%28disambiguation%29.txt ../out/35/51/Alexander_of_Greece_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/e2/December_6.txt ../out/35/e2/December_6.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/e6/Devil.txt ../out/36/e6/Devil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/57/Canopus_%28disambiguation%29.txt ../out/37/57/Canopus_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/d7/Colin_Maclaurin.txt ../out/37/d7/Colin_Maclaurin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/41/Amphibian_%28disambiguation%29.txt ../out/38/41/Amphibian_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/3a/Crannog.txt ../out/39/3a/Crannog.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/d9/Calypso.txt ../out/39/d9/Calypso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/5f/Alien.txt ../out/3a/5f/Alien.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/e0/Dna.txt ../out/3a/e0/Dna.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/7d/Cellular_digital_packet_data.txt ../out/3b/7d/Cellular_digital_packet_data.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/d5/Beacon.txt ../out/3b/d5/Beacon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/83/Colin_Powell.txt ../out/3c/83/Colin_Powell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/3e/Dockyard.txt ../out/3d/3e/Dockyard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/f0/Basque_Fatherland_and_Liberty.txt ../out/3d/f0/Basque_Fatherland_and_Liberty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/9e/Abated.txt ../out/3e/9e/Abated.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/14/CPAN.txt ../out/3f/14/CPAN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/8b/Ergative_case.txt ../out/3f/8b/Ergative_case.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/51/Yangtze.txt ../out/40/51/Yangtze.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/d2/Charles_McCarry.txt ../out/40/d2/Charles_McCarry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/9f/August_17.txt ../out/41/9f/August_17.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/f1/Carcinogen.txt ../out/41/f1/Carcinogen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/53/Brazil.txt ../out/42/53/Brazil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/1b/Book_of_Deuteronomy.txt ../out/43/1b/Book_of_Deuteronomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/a9/Coral_Sea_Islands%2FCommunications.txt ../out/43/a9/Coral_Sea_Islands%2FCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/6f/David_Grinnell.txt ../out/44/6f/David_Grinnell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/be/Bernthia_Perkins.txt ../out/44/be/Bernthia_Perkins.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/7d/Love_and_Theft_%28Bob_Dylan_album%29.txt ../out/45/7d/Love_and_Theft_%28Bob_Dylan_album%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/13/Centaur.txt ../out/46/13/Centaur.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/ff/Cosine.txt ../out/46/ff/Cosine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/9d/DNA_ligase.txt ../out/47/9d/DNA_ligase.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/77/Euclid.txt ../out/48/77/Euclid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/07/Media_in_Belarus.txt ../out/49/07/Media_in_Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/b9/Compilers.txt ../out/49/b9/Compilers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/62/Egyptian_Lover.txt ../out/4a/62/Egyptian_Lover.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/f9/Braille.txt ../out/4a/f9/Braille.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/a5/Delocalised.txt ../out/4b/a5/Delocalised.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/25/C._L._Moore.txt ../out/4c/25/C._L._Moore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/95/Cemetery_H_culture.txt ../out/4c/95/Cemetery_H_culture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/60/Compressed.txt ../out/4d/60/Compressed.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/fd/Antipope.txt ../out/4d/fd/Antipope.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/97/Binary_search_algorithm.txt ../out/4e/97/Binary_search_algorithm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/21/EastEnders.txt ../out/4f/21/EastEnders.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/ea/Eve_%28disambiguation%29.txt ../out/4f/ea/Eve_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/8c/Class_action.txt ../out/50/8c/Class_action.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/63/Conservative_Judaism.txt ../out/51/63/Conservative_Judaism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/eb/Atari_5200.txt ../out/51/eb/Atari_5200.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/92/Aetiology.txt ../out/52/92/Aetiology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/2c/CNO.txt ../out/53/2c/CNO.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/d6/August_14.txt ../out/53/d6/August_14.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/4e/Andr%C3%A9_the_Giant.txt ../out/54/4e/Andr%C3%A9_the_Giant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/dc/Adaptive_radiation.txt ../out/54/dc/Adaptive_radiation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/96/Algol.txt ../out/55/96/Algol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/32/Edward_Bellamy.txt ../out/56/32/Edward_Bellamy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/42/Atmosphere_%28disambiguation%29.txt ../out/57/42/Atmosphere_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/ee/Comic_book.txt ../out/57/ee/Comic_book.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/82/Costa_Rica.txt ../out/58/82/Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/22/English_in_the_Commonwealth_of_Nations.txt ../out/59/22/English_in_the_Commonwealth_of_Nations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/c7/Abdulaziz_al-Omari.txt ../out/59/c7/Abdulaziz_al-Omari.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/63/Academic_elitism.txt ../out/5a/63/Academic_elitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/d7/Dasyproctidae.txt ../out/5a/d7/Dasyproctidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/74/Apostolic_succession.txt ../out/5b/74/Apostolic_succession.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/34/Constans.txt ../out/5c/34/Constans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/db/Compaq.txt ../out/5c/db/Compaq.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/d0/AfghanistanTransnationalIssues.txt ../out/5d/d0/AfghanistanTransnationalIssues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/58/Aardvark.txt ../out/5e/58/Aardvark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/cb/Alfonso_II_of_Asturias.txt ../out/5e/cb/Alfonso_II_of_Asturias.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/c9/Brabant.txt ../out/5f/c9/Brabant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/45/Bob_Diamond.txt ../out/60/45/Bob_Diamond.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/18/Creed.txt ../out/61/18/Creed.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/9a/Arable_land.txt ../out/61/9a/Arable_land.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/31/Belfast.txt ../out/62/31/Belfast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/2a/Arianism.txt ../out/63/2a/Arianism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/fa/Basic_taste.txt ../out/63/fa/Basic_taste.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/c9/DefinitionOfPhilosophy.txt ../out/64/c9/DefinitionOfPhilosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/4a/Einstein.txt ../out/65/4a/Einstein.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/e0/Aleksandr_Solzhenitsyn.txt ../out/65/e0/Aleksandr_Solzhenitsyn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/40/Abstraction_in_object-oriented_programming.txt ../out/66/40/Abstraction_in_object-oriented_programming.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/fd/Alford_plea.txt ../out/66/fd/Alford_plea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/7e/Aberdeen_%28disambiguation%29.txt ../out/67/7e/Aberdeen_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/1d/Drawing.txt ../out/68/1d/Drawing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/bf/Telecommunications_in_Belgium.txt ../out/68/bf/Telecommunications_in_Belgium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/97/Dartmoor_Preservation_Association.txt ../out/69/97/Dartmoor_Preservation_Association.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/46/United_Kingdom_general_election%2C_2001.txt ../out/6a/46/United_Kingdom_general_election%2C_2001.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/ce/European_Commission.txt ../out/6a/ce/European_Commission.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/61/Carthage.txt ../out/6b/61/Carthage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/ff/Government_of_Christmas_Island.txt ../out/6b/ff/Government_of_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/72/Essenes.txt ../out/6c/72/Essenes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/f5/Branch_prediction.txt ../out/6c/f5/Branch_prediction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/b8/Military_of_Cambodia.txt ../out/6d/b8/Military_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/5a/Eiffel_Tower.txt ../out/6e/5a/Eiffel_Tower.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/c5/Aramaic_language.txt ../out/6e/c5/Aramaic_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/4d/Constitution_of_Canada%2F1867_VI_Distribution_of_Legislative_Powers.txt ../out/6f/4d/Constitution_of_Canada%2F1867_VI_Distribution_of_Legislative_Powers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/1e/Autoerotic_asphyxiation.txt ../out/70/1e/Autoerotic_asphyxiation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/d3/Building_society.txt ../out/70/d3/Building_society.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/b9/Acamthocephala.txt ../out/71/b9/Acamthocephala.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/4f/Classical_liberalism.txt ../out/72/4f/Classical_liberalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/06/Bradycardia.txt ../out/73/06/Bradycardia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/ac/Christendom.txt ../out/73/ac/Christendom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/56/England%2FCity.txt ../out/74/56/England%2FCity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/ad/Bose%E2%80%93Einstein_condensate.txt ../out/74/ad/Bose%E2%80%93Einstein_condensate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/66/ConsolationOfPhilosophy.txt ../out/75/66/ConsolationOfPhilosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/27/Dipole.txt ../out/76/27/Dipole.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/ad/Domain_Name_System.txt ../out/76/ad/Domain_Name_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/70/Hanukkah_rituals.txt ../out/77/70/Hanukkah_rituals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/25/Eight-ball.txt ../out/78/25/Eight-ball.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/b8/Aarons_rod.txt ../out/78/b8/Aarons_rod.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/70/Batman_Returns.txt ../out/79/70/Batman_Returns.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/d6/Bangladesh%2FTransnational_issues.txt ../out/79/d6/Bangladesh%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/7d/Bo_Diddley.txt ../out/7a/7d/Bo_Diddley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/ce/Dylan.txt ../out/7a/ce/Dylan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/72/AnarchY.txt ../out/7b/72/AnarchY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/39/Den_Haag.txt ../out/7c/39/Den_Haag.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/f6/Auschwitz_concentration_camp.txt ../out/7c/f6/Auschwitz_concentration_camp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/67/Azerbaijani_Armed_Forces.txt ../out/7d/67/Azerbaijani_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/2e/Andronikos_I_Komnenos.txt ../out/7e/2e/Andronikos_I_Komnenos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/cf/Colonies.txt ../out/7e/cf/Colonies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/93/Apollo_11.txt ../out/7f/93/Apollo_11.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/f6/Cabal.txt ../out/7f/f6/Cabal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/50/Christian_anti-semitism.txt ../out/80/50/Christian_anti-semitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/16/Atlantic_%28disambiguation%29.txt ../out/81/16/Atlantic_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/b6/Christmas.txt ../out/81/b6/Christmas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/73/BIPM.txt ../out/82/73/BIPM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/52/Cretaceous-Tertiary_Extinction_Event.txt ../out/83/52/Cretaceous-Tertiary_Extinction_Event.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/e8/Coracinus_capensis.txt ../out/83/e8/Coracinus_capensis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/db/Endoplasmic_reticulum.txt ../out/84/db/Endoplasmic_reticulum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/6d/Minute_and_second_of_arc.txt ../out/85/6d/Minute_and_second_of_arc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/f8/Albrecht_Altdorfer.txt ../out/85/f8/Albrecht_Altdorfer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/89/Erik_Satie.txt ../out/86/89/Erik_Satie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/2e/Bishopric_of_Brandenburg.txt ../out/87/2e/Bishopric_of_Brandenburg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/01/Economy_of_Croatia.txt ../out/88/01/Economy_of_Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/bc/Anguilla%2FMilitary.txt ../out/88/bc/Anguilla%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/48/Economy_of_the_British_Virgin_Islands.txt ../out/89/48/Economy_of_the_British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/f9/Cheerleading.txt ../out/89/f9/Cheerleading.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/97/Ellipsis.txt ../out/8a/97/Ellipsis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/57/The_Beverly_Hillbillies.txt ../out/8b/57/The_Beverly_Hillbillies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/04/Cyperales.txt ../out/8c/04/Cyperales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/9f/Bahrain%2FGeography.txt ../out/8c/9f/Bahrain%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/18/%27Abd_al-Rahman_I.txt ../out/8d/18/%27Abd_al-Rahman_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/e1/Alfonso_Leng.txt ../out/8d/e1/Alfonso_Leng.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/a8/Ambergris.txt ../out/8e/a8/Ambergris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/75/CRESU_experiment.txt ../out/8f/75/CRESU_experiment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/27/Basque_language.txt ../out/90/27/Basque_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/f8/Apus.txt ../out/90/f8/Apus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/bb/Alice_Sheldon.txt ../out/91/bb/Alice_Sheldon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/af/List_of_equations_in_classical_mechanics.txt ../out/92/af/List_of_equations_in_classical_mechanics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/73/Altaic_languages.txt ../out/93/73/Altaic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/f5/Callitrichidae.txt ../out/93/f5/Callitrichidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/0d/Ciprofloxacin.txt ../out/95/0d/Ciprofloxacin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/7b/Canadian_English.txt ../out/95/7b/Canadian_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/29/CountriesY.txt ../out/96/29/CountriesY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/eb/Climate.txt ../out/96/eb/Climate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/70/Dhrystone.txt ../out/97/70/Dhrystone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/08/Daimler-Chrysler.txt ../out/98/08/Daimler-Chrysler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/64/Military_of_Canada.txt ../out/98/64/Military_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/10/Chupacabra.txt ../out/99/10/Chupacabra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/9d/CATV.txt ../out/99/9d/CATV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/23/Cryptography%2FHashfunction.txt ../out/9a/23/Cryptography%2FHashfunction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/88/Actinophryid.txt ../out/9a/88/Actinophryid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/2d/British_Steel.txt ../out/9b/2d/British_Steel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/db/Detroit_Red_Wings.txt ../out/9b/db/Detroit_Red_Wings.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/5e/Amplify.txt ../out/9c/5e/Amplify.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/fe/Amateur_astronomy.txt ../out/9c/fe/Amateur_astronomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/7c/Drunkeness.txt ../out/9d/7c/Drunkeness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/0e/Dimension.txt ../out/9e/0e/Dimension.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/09/Carbide.txt ../out/9f/09/Carbide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/b6/ASP.txt ../out/9f/b6/ASP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/51/December_26.txt ../out/a0/51/December_26.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/24/Cell_phone.txt ../out/a1/24/Cell_phone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/f1/ErnestHemingway%2FYoungandInnocent.txt ../out/a1/f1/ErnestHemingway%2FYoungandInnocent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/bf/Eadgyth.txt ../out/a2/bf/Eadgyth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/58/Royal_Antigua_and_Barbuda_Defence_Force.txt ../out/a3/58/Royal_Antigua_and_Barbuda_Defence_Force.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/11/Bacardi.txt ../out/a4/11/Bacardi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/c3/Abimelech.txt ../out/a4/c3/Abimelech.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/19/Combustion.txt ../out/a5/19/Combustion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/a4/Alger_of_Li%C3%A8ge.txt ../out/a5/a4/Alger_of_Li%C3%A8ge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/54/Cutter_Expansive_Classification.txt ../out/a6/54/Cutter_Expansive_Classification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/fb/April_16.txt ../out/a6/fb/April_16.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/c4/Abd%C3%BClaziz_of_the_Ottoman_Empire.txt ../out/a7/c4/Abd%C3%BClaziz_of_the_Ottoman_Empire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/8d/Christian_Goldbach.txt ../out/a8/8d/Christian_Goldbach.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/5b/Britain.txt ../out/a9/5b/Britain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/12/Bogie.txt ../out/aa/12/Bogie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/99/Edward_Waring.txt ../out/aa/99/Edward_Waring.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/10/Estonia_disaster.txt ../out/ab/10/Estonia_disaster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/a1/Coelenterates.txt ../out/ab/a1/Coelenterates.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/4f/April_17.txt ../out/ac/4f/April_17.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/a8/Politics_of_Costa_Rica.txt ../out/ac/a8/Politics_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/53/Dandy.txt ../out/ad/53/Dandy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/0d/Economy_of_Equatorial_Guinea.txt ../out/ae/0d/Economy_of_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/9e/Athanasius_of_Alexandria.txt ../out/ae/9e/Athanasius_of_Alexandria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/3a/Boolean_algebra_%28structure%29.txt ../out/af/3a/Boolean_algebra_%28structure%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/d0/Battle_of_Ramillies.txt ../out/af/d0/Battle_of_Ramillies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/4f/Card_game.txt ../out/b0/4f/Card_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/1b/Major_League_Baseball_Most_Valuable_Player_Award.txt ../out/b1/1b/Major_League_Baseball_Most_Valuable_Player_Award.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/b0/Bacteriostat.txt ../out/b1/b0/Bacteriostat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/16/Alpha_ray.txt ../out/b2/16/Alpha_ray.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/f2/Battle_of_Zarnowiec.txt ../out/b2/f2/Battle_of_Zarnowiec.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/d8/Amino_acid.txt ../out/b3/d8/Amino_acid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/6b/List_of_former_sovereign_states.txt ../out/b4/6b/List_of_former_sovereign_states.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/c7/CountriesN.txt ../out/b4/c7/CountriesN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/31/C.S._Lewis.txt ../out/b5/31/C.S._Lewis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/9f/Transport_in_the_British_Virgin_Islands.txt ../out/b5/9f/Transport_in_the_British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/3a/Cyril_of_Alexandria.txt ../out/b6/3a/Cyril_of_Alexandria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/34/Delicate_Arch.txt ../out/b7/34/Delicate_Arch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/c5/Columbus%2C_Ohio.txt ../out/b7/c5/Columbus%2C_Ohio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/5d/Christopher_Marlowe.txt ../out/b8/5d/Christopher_Marlowe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/f2/Book_of_Nehemiah.txt ../out/b8/f2/Book_of_Nehemiah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/d8/Alexandra.txt ../out/b9/d8/Alexandra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/79/Bodybuilding.txt ../out/ba/79/Bodybuilding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/27/EigenValue.txt ../out/bb/27/EigenValue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/94/Amway.txt ../out/bb/94/Amway.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/32/Sid_Meier%27s_Alpha_Centauri.txt ../out/bc/32/Sid_Meier%27s_Alpha_Centauri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/dc/Carnot_heat_engine.txt ../out/bc/dc/Carnot_heat_engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/ad/Astable.txt ../out/bd/ad/Astable.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/66/Caligula.txt ../out/be/66/Caligula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/1a/Centrifugal_force_%28rotating_reference_frame%29.txt ../out/bf/1a/Centrifugal_force_%28rotating_reference_frame%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/c3/Dean_Kamen.txt ../out/bf/c3/Dean_Kamen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/7d/East_Berlin.txt ../out/c0/7d/East_Berlin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/52/AOL.txt ../out/c1/52/AOL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/d0/Damascus_steel.txt ../out/c1/d0/Damascus_steel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/9a/Ahmed_II.txt ../out/c2/9a/Ahmed_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/76/Afghanistan%2FTransnational_Issues.txt ../out/c3/76/Afghanistan%2FTransnational_Issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/04/Telecommunications_in_Canada.txt ../out/c4/04/Telecommunications_in_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/7f/Acropolis.txt ../out/c4/7f/Acropolis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/41/Costa_Smeralda.txt ../out/c5/41/Costa_Smeralda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/1d/Ana%C3%AFs_Nin.txt ../out/c6/1d/Ana%C3%AFs_Nin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/ea/Afghanistan%2FGeography.txt ../out/c6/ea/Afghanistan%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/85/Arbroath_Abbey.txt ../out/c7/85/Arbroath_Abbey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/44/ANSI_C.txt ../out/c8/44/ANSI_C.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/2a/Beast_of_bodmin.txt ../out/c9/2a/Beast_of_bodmin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/a0/Al_Gore%2FCriticisms.txt ../out/c9/a0/Al_Gore%2FCriticisms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/33/United_Kingdom_general_election.txt ../out/ca/33/United_Kingdom_general_election.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/08/ABCD.txt ../out/cb/08/ABCD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/a8/BuddHa.txt ../out/cb/a8/BuddHa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/94/Chemical_Evolution.txt ../out/cc/94/Chemical_Evolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/23/Eric_Hoffer.txt ../out/cd/23/Eric_Hoffer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/b0/History_of_baseball_in_the_United_States.txt ../out/cd/b0/History_of_baseball_in_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/96/Afonso_I_of_Portugal.txt ../out/ce/96/Afonso_I_of_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/31/Baltimore_Orioles.txt ../out/cf/31/Baltimore_Orioles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/f1/Appendix.txt ../out/cf/f1/Appendix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/d2/EasyWriter.txt ../out/d0/d2/EasyWriter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/57/Aberration_of_light.txt ../out/d1/57/Aberration_of_light.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/1a/Accounting_and_Bookkeeping.txt ../out/d2/1a/Accounting_and_Bookkeeping.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/be/ChristianIty.txt ../out/d2/be/ChristianIty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/6a/Charon.txt ../out/d3/6a/Charon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/f5/Corundum.txt ../out/d3/f5/Corundum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/d5/Czech_republic%2FGovernment.txt ../out/d4/d5/Czech_republic%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/6a/April_5.txt ../out/d5/6a/April_5.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/14/Causes_of_sexual_orientation.txt ../out/d6/14/Causes_of_sexual_orientation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/b4/DramaFilm.txt ../out/d6/b4/DramaFilm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/3f/Albigenses.txt ../out/d7/3f/Albigenses.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/f7/Alfred_Ernest_Albert.txt ../out/d7/f7/Alfred_Ernest_Albert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/dd/Coffea.txt ../out/d8/dd/Coffea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/59/Calendar_year.txt ../out/d9/59/Calendar_year.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/f2/Churches_Uniting_In_Christ.txt ../out/d9/f2/Churches_Uniting_In_Christ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/a1/Biconditional_introduction.txt ../out/da/a1/Biconditional_introduction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/21/Chiang_Kai-shek.txt ../out/db/21/Chiang_Kai-shek.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/e5/Economy_of_Burundi.txt ../out/db/e5/Economy_of_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/84/Ashoka.txt ../out/dc/84/Ashoka.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/17/Christianity%2FFish.txt ../out/dd/17/Christianity%2FFish.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/a0/Achilles.txt ../out/dd/a0/Achilles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/78/British_Army.txt ../out/de/78/British_Army.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/13/Accessible_computing.txt ../out/df/13/Accessible_computing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/fc/Amnon.txt ../out/df/fc/Amnon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/98/Doraemon.txt ../out/e0/98/Doraemon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/58/Century.txt ../out/e1/58/Century.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/05/Alfred_Hitchcock.txt ../out/e2/05/Alfred_Hitchcock.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/b8/Diet_of_Nuremberg.txt ../out/e2/b8/Diet_of_Nuremberg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/54/Audio_signal_processing.txt ../out/e3/54/Audio_signal_processing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/f9/Apollo_1.txt ../out/e3/f9/Apollo_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/cd/Cyanide.txt ../out/e4/cd/Cyanide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/54/Cyclades.txt ../out/e5/54/Cyclades.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/ef/Cretaceous.txt ../out/e5/ef/Cretaceous.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/83/Bodes_law.txt ../out/e6/83/Bodes_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/7d/Channel_4.txt ../out/e7/7d/Channel_4.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/18/Bryozoa.txt ../out/e8/18/Bryozoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/b9/Allele.txt ../out/e8/b9/Allele.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/45/European_Free_Alliance.txt ../out/e9/45/European_Free_Alliance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/c5/Abiotic_stress.txt ../out/e9/c5/Abiotic_stress.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/2b/Cyprus.txt ../out/ea/2b/Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/fb/Chimera.txt ../out/ea/fb/Chimera.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/a4/Aimery_of_Cyprus.txt ../out/eb/a4/Aimery_of_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/7c/Colon_classification.txt ../out/ec/7c/Colon_classification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/4d/Automorphism.txt ../out/ed/4d/Automorphism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/c5/Design_Science_License.txt ../out/ed/c5/Design_Science_License.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/61/Louise_%C3%89lisabeth_Vig%C3%A9e_Le_Brun.txt ../out/ee/61/Louise_%C3%89lisabeth_Vig%C3%A9e_Le_Brun.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/02/Amyl_nitrite.txt ../out/ef/02/Amyl_nitrite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/99/Allophone.txt ../out/ef/99/Allophone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/34/Burhanuddin_Rabbani.txt ../out/f0/34/Burhanuddin_Rabbani.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/f0/Adder.txt ../out/f0/f0/Adder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/d5/Transport_in_Egypt.txt ../out/f1/d5/Transport_in_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/98/Crimean_war.txt ../out/f2/98/Crimean_war.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/79/Aon_Insurance.txt ../out/f3/79/Aon_Insurance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/4a/Digamma.txt ../out/f4/4a/Digamma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/20/The_Evil_Dead.txt ../out/f5/20/The_Evil_Dead.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/c9/Mouthwash.txt ../out/f5/c9/Mouthwash.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/8a/Evolutionary_tree%2FChordata.txt ../out/f6/8a/Evolutionary_tree%2FChordata.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/08/Hit_by_pitch.txt ../out/f7/08/Hit_by_pitch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/8a/Bangladesh.txt ../out/f7/8a/Bangladesh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/79/Albedo.txt ../out/f8/79/Albedo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/f7/Biostatistics.txt ../out/f8/f7/Biostatistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/5c/Dots_and_Boxes.txt ../out/f9/5c/Dots_and_Boxes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/02/Czech_Republic%2FTransnational_issues.txt ../out/fa/02/Czech_Republic%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/7b/Computer_monitor.txt ../out/fa/7b/Computer_monitor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/33/Economy_of_Denmark.txt ../out/fb/33/Economy_of_Denmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/e3/Aircraft_carrier.txt ../out/fb/e3/Aircraft_carrier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/cb/Alternate_History.txt ../out/fc/cb/Alternate_History.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/74/Council_of_the_European_Union.txt ../out/fd/74/Council_of_the_European_Union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/3d/Abd-ar-rahman.txt ../out/fe/3d/Abd-ar-rahman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/e0/AMOS_%28programming_language%29.txt ../out/fe/e0/AMOS_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/60/Brass.txt ../out/ff/60/Brass.xml
