php ./wiki2xml/php/wiki2xml_command.php ../out/00/9d/Downy_O%27Drake.txt ../out/00/9d/Downy_O%27Drake.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/3e/Epimenides_paradox.txt ../out/01/3e/Epimenides_paradox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/dc/Big_Bang.txt ../out/01/dc/Big_Bang.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/b2/Adam_Weishaupt.txt ../out/02/b2/Adam_Weishaupt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/49/Calculus.txt ../out/03/49/Calculus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/ef/Anglican.txt ../out/03/ef/Anglican.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/6d/Transport_in_Angola.txt ../out/04/6d/Transport_in_Angola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/1b/Carbamazepine.txt ../out/05/1b/Carbamazepine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/8b/Babylon_5.txt ../out/05/8b/Babylon_5.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/1f/Dino_Zoff.txt ../out/06/1f/Dino_Zoff.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/d2/Arthur_Schopenhauer.txt ../out/06/d2/Arthur_Schopenhauer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/7b/Abertillery.txt ../out/07/7b/Abertillery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/49/Ahmed_III.txt ../out/08/49/Ahmed_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/d3/De_jure.txt ../out/08/d3/De_jure.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/80/Bohr_Model.txt ../out/09/80/Bohr_Model.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/62/Carousel_%28musical%29.txt ../out/0a/62/Carousel_%28musical%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/c3/Achill_Island.txt ../out/0a/c3/Achill_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/89/Definition.txt ../out/0b/89/Definition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/f9/Bicycling.txt ../out/0b/f9/Bicycling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/9b/Charles_Evans_Hughes.txt ../out/0c/9b/Charles_Evans_Hughes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/73/Ansgar.txt ../out/0d/73/Ansgar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/2c/Constitution_of_Canada%2F1867_IV_Legislative_Power.txt ../out/0e/2c/Constitution_of_Canada%2F1867_IV_Legislative_Power.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/b6/Abydos_%28Hellespont%29.txt ../out/0e/b6/Abydos_%28Hellespont%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/64/Black_Russian.txt ../out/0f/64/Black_Russian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/36/Day_of_the_Tentacle.txt ../out/10/36/Day_of_the_Tentacle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/35/Boolean_satisfiability_problem.txt ../out/11/35/Boolean_satisfiability_problem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/c9/Bj%C3%B6rn_Borg.txt ../out/11/c9/Bj%C3%B6rn_Borg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/72/Antiparticle.txt ../out/12/72/Antiparticle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/04/Complex_number.txt ../out/13/04/Complex_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/80/Bombay_Sapphire.txt ../out/13/80/Bombay_Sapphire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/5d/Hostility_towards_America.txt ../out/14/5d/Hostility_towards_America.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/03/Antonio_Gaudi%2FSagrada_Familia.txt ../out/15/03/Antonio_Gaudi%2FSagrada_Familia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/7d/Common_chimpanzee.txt ../out/15/7d/Common_chimpanzee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/3d/Astronomy%2FHistory.txt ../out/16/3d/Astronomy%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/f5/DHEA.txt ../out/16/f5/DHEA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/bd/Antimicrobial_resistance.txt ../out/17/bd/Antimicrobial_resistance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/4e/Ester.txt ../out/18/4e/Ester.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/dc/Depth_of_field.txt ../out/18/dc/Depth_of_field.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/76/Column.txt ../out/19/76/Column.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/0e/Alaric_II.txt ../out/1a/0e/Alaric_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/a6/Alexander_technique.txt ../out/1a/a6/Alexander_technique.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/24/Bubblegum_Crisis.txt ../out/1b/24/Bubblegum_Crisis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/bc/Book_of_Alma.txt ../out/1b/bc/Book_of_Alma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/37/Telecommunications_in_the_British_Virgin_Islands.txt ../out/1c/37/Telecommunications_in_the_British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/c8/Alcopop.txt ../out/1c/c8/Alcopop.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/4c/Politics_of_Ecuador.txt ../out/1d/4c/Politics_of_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/f6/Dolmen.txt ../out/1d/f6/Dolmen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/95/Boleslav_I.txt ../out/1e/95/Boleslav_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/75/Abandonment_in_marine_insurance.txt ../out/1f/75/Abandonment_in_marine_insurance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/30/Electronic_oscillator.txt ../out/20/30/Electronic_oscillator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/dc/Diesel_engine.txt ../out/20/dc/Diesel_engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/6e/BQ-7_Aphrodite.txt ../out/21/6e/BQ-7_Aphrodite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/5c/Call_Of_Cthulhu.txt ../out/22/5c/Call_Of_Cthulhu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/01/Cardiology_diagnostic_tests_and_procedures.txt ../out/23/01/Cardiology_diagnostic_tests_and_procedures.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/b4/Denarius.txt ../out/23/b4/Denarius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/41/Almond.txt ../out/24/41/Almond.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/e6/Dhy%C4%81na.txt ../out/24/e6/Dhy%C4%81na.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/ca/Crank.txt ../out/25/ca/Crank.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/44/Bundestag.txt ../out/26/44/Bundestag.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/00/Carlo_Goldoni.txt ../out/27/00/Carlo_Goldoni.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/9c/Barratry_%28common_law%29.txt ../out/27/9c/Barratry_%28common_law%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/4a/Cathode.txt ../out/28/4a/Cathode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/c1/Election.txt ../out/28/c1/Election.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/79/ComputinG.txt ../out/29/79/ComputinG.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/23/Bicarbonate.txt ../out/2a/23/Bicarbonate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/ff/Costume.txt ../out/2a/ff/Costume.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/7f/Agesilaus_II.txt ../out/2b/7f/Agesilaus_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/31/BMI.txt ../out/2c/31/BMI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/b9/Beagle.txt ../out/2c/b9/Beagle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/79/Antonio_Vivaldi.txt ../out/2d/79/Antonio_Vivaldi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/2c/Administrative_law.txt ../out/2e/2c/Administrative_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/e3/Ampere.txt ../out/2e/e3/Ampere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/a6/Cytosol.txt ../out/2f/a6/Cytosol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/a9/Acts.txt ../out/30/a9/Acts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/22/Drum_and_bass.txt ../out/31/22/Drum_and_bass.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/14/Barbados.txt ../out/32/14/Barbados.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/cf/Dactylic_hexameter.txt ../out/32/cf/Dactylic_hexameter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/46/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FD.txt ../out/33/46/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/58/Albert_Spalding.txt ../out/34/58/Albert_Spalding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/f0/C._Northcote_Parkinson.txt ../out/34/f0/C._Northcote_Parkinson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/99/Albert_III.txt ../out/35/99/Albert_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/74/Ashmore_and_Cartier_Islands%2FGeography.txt ../out/36/74/Ashmore_and_Cartier_Islands%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/21/Bear.txt ../out/37/21/Bear.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/a5/Video_game.txt ../out/37/a5/Video_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/12/David_Angell.txt ../out/38/12/David_Angell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/b5/Arthur_Wellesley.txt ../out/38/b5/Arthur_Wellesley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/a8/ABM.txt ../out/39/a8/ABM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/29/Adhemar_de_Chabannes.txt ../out/3a/29/Adhemar_de_Chabannes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/a4/Bishop.txt ../out/3a/a4/Bishop.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/3e/Baldric.txt ../out/3b/3e/Baldric.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/bc/Centripetal_force.txt ../out/3b/bc/Centripetal_force.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/53/Chinese_buddhist_cuisine.txt ../out/3c/53/Chinese_buddhist_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/01/Erlang_%28programming_language%29.txt ../out/3d/01/Erlang_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/83/Delian_League.txt ../out/3d/83/Delian_League.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/43/Cotangent_space.txt ../out/3e/43/Cotangent_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/d9/Distance_education.txt ../out/3e/d9/Distance_education.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/3a/Epistle_to_Titus.txt ../out/3f/3a/Epistle_to_Titus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/fb/Audio_file_format.txt ../out/3f/fb/Audio_file_format.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/a2/Dwight_D._Eisenhower.txt ../out/40/a2/Dwight_D._Eisenhower.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/58/Brownie_McGhee.txt ../out/41/58/Brownie_McGhee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/cf/Demographic_statistics.txt ../out/41/cf/Demographic_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/2e/Alan_Kay.txt ../out/42/2e/Alan_Kay.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/bf/Cultural_evolution.txt ../out/42/bf/Cultural_evolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/7c/Utility_knife.txt ../out/43/7c/Utility_knife.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/28/Drexel_University.txt ../out/44/28/Drexel_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/96/Air_Transport.txt ../out/44/96/Air_Transport.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/39/April_7.txt ../out/45/39/April_7.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/f8/Court_of_appeals_%28disambiguation%29.txt ../out/45/f8/Court_of_appeals_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/79/Barney_Bubbles.txt ../out/46/79/Barney_Bubbles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/70/Cone_%28disambiguation%29.txt ../out/47/70/Cone_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/f2/Cahiers_du_cin%C3%A9ma.txt ../out/47/f2/Cahiers_du_cin%C3%A9ma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/c6/Alexios_III_Angelos.txt ../out/48/c6/Alexios_III_Angelos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/6d/EpistemOlogy.txt ../out/49/6d/EpistemOlogy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/f0/Centime.txt ../out/49/f0/Centime.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/a5/Computer%2FMultitasking.txt ../out/4a/a5/Computer%2FMultitasking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/40/Transport_in_Ivory_Coast.txt ../out/4b/40/Transport_in_Ivory_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/ed/BaltimoreRavens.txt ../out/4b/ed/BaltimoreRavens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/63/Eden_Phillpotts.txt ../out/4c/63/Eden_Phillpotts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/37/Borland.txt ../out/4d/37/Borland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/af/Co-NP.txt ../out/4d/af/Co-NP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/3b/Cyril_of_Jerusalem.txt ../out/4e/3b/Cyril_of_Jerusalem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/e8/Communists.txt ../out/4e/e8/Communists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/a0/Atom_probe.txt ../out/4f/a0/Atom_probe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/4b/Alcuin.txt ../out/50/4b/Alcuin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/0c/Electricity_generation.txt ../out/51/0c/Electricity_generation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/9e/Alfons_Maria_Jakob.txt ../out/51/9e/Alfons_Maria_Jakob.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/5f/Abijah.txt ../out/52/5f/Abijah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/ff/BPP_%28complexity%29.txt ../out/52/ff/BPP_%28complexity%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/96/Borough.txt ../out/53/96/Borough.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/17/Discounted_cash_flow.txt ../out/54/17/Discounted_cash_flow.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/9f/Bundle_theory.txt ../out/54/9f/Bundle_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/48/Capybara.txt ../out/55/48/Capybara.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/ed/Apollo_16.txt ../out/55/ed/Apollo_16.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/d5/Dative_case.txt ../out/56/d5/Dative_case.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/9d/Algebraic_geometry.txt ../out/57/9d/Algebraic_geometry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/43/Acts_of_the_Apostles.txt ../out/58/43/Acts_of_the_Apostles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/f8/Geography_of_Bassas_da_India.txt ../out/58/f8/Geography_of_Bassas_da_India.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/71/Country.txt ../out/59/71/Country.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/ff/Aung_San_Suu_Kyi.txt ../out/59/ff/Aung_San_Suu_Kyi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/8f/Ancus_Marcius.txt ../out/5a/8f/Ancus_Marcius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/3a/Didjeridu.txt ../out/5b/3a/Didjeridu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/d5/Academy_Award_for_Best_Production_Design.txt ../out/5b/d5/Academy_Award_for_Best_Production_Design.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/94/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29.txt ../out/5c/94/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/40/Bayer_designation.txt ../out/5d/40/Bayer_designation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/1f/Continuity_%28fiction%29.txt ../out/5e/1f/Continuity_%28fiction%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/9b/Claude_Shannon.txt ../out/5e/9b/Claude_Shannon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/3c/Buddhists.txt ../out/5f/3c/Buddhists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/16/Copyright.txt ../out/60/16/Copyright.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/ba/Double-ended_queue.txt ../out/60/ba/Double-ended_queue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/69/Economy_of_El_Salvador.txt ../out/61/69/Economy_of_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/f1/Demographics_of_Canada.txt ../out/61/f1/Demographics_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/c6/Assault_gun.txt ../out/62/c6/Assault_gun.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/92/Django_Reinhardt.txt ../out/63/92/Django_Reinhardt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/9a/Douglas_Engelbart.txt ../out/64/9a/Douglas_Engelbart.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/1b/Celebes_%28disambiguation%29.txt ../out/65/1b/Celebes_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/8e/Abatement.txt ../out/65/8e/Abatement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/13/Animal_%28disambiguation%29.txt ../out/66/13/Animal_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/ac/Dyslexia.txt ../out/66/ac/Dyslexia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/31/Constitution_of_Canada%2F1867_II_Union.txt ../out/67/31/Constitution_of_Canada%2F1867_II_Union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/f3/Electromagnetic_force.txt ../out/67/f3/Electromagnetic_force.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/7a/Executive_power.txt ../out/68/7a/Executive_power.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/51/Bicycling%2FRoad.txt ../out/69/51/Bicycling%2FRoad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/0c/Crowded_House.txt ../out/6a/0c/Crowded_House.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/97/Anaxarchus.txt ../out/6a/97/Anaxarchus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/07/Bohrium.txt ../out/6b/07/Bohrium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/be/Antianginal.txt ../out/6b/be/Antianginal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/4a/Telecommunications_in_the_Central_African_Republic.txt ../out/6c/4a/Telecommunications_in_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/d1/Centimetre%E2%80%93gram%E2%80%93second_system_of_units.txt ../out/6c/d1/Centimetre%E2%80%93gram%E2%80%93second_system_of_units.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/6d/Called_to_Common_Mission.txt ../out/6d/6d/Called_to_Common_Mission.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/ff/ComputerHardware.txt ../out/6d/ff/ComputerHardware.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/97/Afghanistan.txt ../out/6e/97/Afghanistan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/13/Balochistan%2C_Pakistan.txt ../out/6f/13/Balochistan%2C_Pakistan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/b7/Wikipedia%3AStatus_of_the_porting_of_the_CIA_World_Factbook.txt ../out/6f/b7/Wikipedia%3AStatus_of_the_porting_of_the_CIA_World_Factbook.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/93/Cauchy_distribution.txt ../out/70/93/Cauchy_distribution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/76/Azerbaijan.txt ../out/71/76/Azerbaijan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/13/Donald_Dewar.txt ../out/72/13/Donald_Dewar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/8d/Telecommunications_in_Dominica.txt ../out/72/8d/Telecommunications_in_Dominica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/6e/Einhard.txt ../out/73/6e/Einhard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/1e/Extropian.txt ../out/74/1e/Extropian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/7f/Blood.txt ../out/74/7f/Blood.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/1f/AlbaniaPeople.txt ../out/75/1f/AlbaniaPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/af/Anti-semitic.txt ../out/75/af/Anti-semitic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/7a/Canon.txt ../out/76/7a/Canon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/19/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F8.txt ../out/77/19/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F8.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/c1/Camelopardalis.txt ../out/77/c1/Camelopardalis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/80/Batman_%281989_film%29.txt ../out/78/80/Batman_%281989_film%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/ef/Bicycle.txt ../out/78/ef/Bicycle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/ae/Bundesrat.txt ../out/79/ae/Bundesrat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/50/August_15.txt ../out/7a/50/August_15.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/8f/Books_of_the_Bible.txt ../out/7a/8f/Books_of_the_Bible.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/36/Androphagi.txt ../out/7b/36/Androphagi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/f6/Extreme_poverty.txt ../out/7b/f6/Extreme_poverty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/c1/Coleco.txt ../out/7c/c1/Coleco.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/2e/Elliptic_integral.txt ../out/7d/2e/Elliptic_integral.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/ef/National_Alliance_%28Italy%29.txt ../out/7d/ef/National_Alliance_%28Italy%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/68/Equivalence_relation.txt ../out/7e/68/Equivalence_relation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/30/Chiropractic.txt ../out/7f/30/Chiropractic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/c5/A.txt ../out/7f/c5/A.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/2b/Corinth.txt ../out/80/2b/Corinth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/ba/Berthe_Morisot.txt ../out/80/ba/Berthe_Morisot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/7d/Doctrine_and_Covenants.txt ../out/81/7d/Doctrine_and_Covenants.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/08/Dmitri_Shostakovich.txt ../out/82/08/Dmitri_Shostakovich.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/f1/BuddHism.txt ../out/82/f1/BuddHism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/a9/Electronic_music.txt ../out/83/a9/Electronic_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/5c/Chemical_evolution.txt ../out/84/5c/Chemical_evolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/3b/Cuon_alpinus.txt ../out/85/3b/Cuon_alpinus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/9a/Economy_of_Djibouti.txt ../out/85/9a/Economy_of_Djibouti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/51/Barge.txt ../out/86/51/Barge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/e7/Ethical_non-naturalism.txt ../out/86/e7/Ethical_non-naturalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/91/Dacoity.txt ../out/87/91/Dacoity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/7b/Absolute_majority.txt ../out/88/7b/Absolute_majority.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/17/Darwin%2C_Northern_Territory.txt ../out/89/17/Darwin%2C_Northern_Territory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/b6/Ainu_people.txt ../out/89/b6/Ainu_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/2c/Chastity.txt ../out/8a/2c/Chastity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/13/Politics_of_Cyprus.txt ../out/8b/13/Politics_of_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/aa/Abba_Arika.txt ../out/8b/aa/Abba_Arika.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/70/Counter_%28digital%29.txt ../out/8c/70/Counter_%28digital%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/d7/BIOS.txt ../out/8c/d7/BIOS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/71/Charge_of_the_Goddess.txt ../out/8d/71/Charge_of_the_Goddess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/4c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FA2.txt ../out/8e/4c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FA2.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/31/Board_of_directors.txt ../out/8f/31/Board_of_directors.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/f3/Assistive_technology.txt ../out/8f/f3/Assistive_technology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/d3/Ecclesiastes.txt ../out/90/d3/Ecclesiastes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/36/List_of_cat_breeds.txt ../out/91/36/List_of_cat_breeds.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/72/Aland.txt ../out/92/72/Aland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/09/Davros.txt ../out/93/09/Davros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/9f/August_12.txt ../out/93/9f/August_12.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/83/Cardinal_vowels.txt ../out/94/83/Cardinal_vowels.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/36/Andr%C3%A9_de_Longjumeau.txt ../out/95/36/Andr%C3%A9_de_Longjumeau.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/c6/Boston_Globe.txt ../out/95/c6/Boston_Globe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/a4/Color_blindness.txt ../out/96/a4/Color_blindness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/3c/Abu_Nidal_Organization.txt ../out/97/3c/Abu_Nidal_Organization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/c3/Callisto_%28mythology%29.txt ../out/97/c3/Callisto_%28mythology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/47/Deception_Pass.txt ../out/98/47/Deception_Pass.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/e4/Amalric_of_Jerusalem.txt ../out/98/e4/Amalric_of_Jerusalem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/50/Domnall_mac_Ailp%C3%ADn.txt ../out/99/50/Domnall_mac_Ailp%C3%ADn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/d0/Binary_and.txt ../out/99/d0/Binary_and.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/69/Gautama_Buddha.txt ../out/9a/69/Gautama_Buddha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/f7/Carolina_Panthers.txt ../out/9a/f7/Carolina_Panthers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/96/Drug_Mix.txt ../out/9b/96/Drug_Mix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/21/Ezekiel.txt ../out/9c/21/Ezekiel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/b1/Cavitation.txt ../out/9c/b1/Cavitation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/3d/Alcoholism.txt ../out/9d/3d/Alcoholism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/d9/Austria%2FTransnational_issues.txt ../out/9d/d9/Austria%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/bc/Afghan_Hound.txt ../out/9e/bc/Afghan_Hound.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/72/Christianity.txt ../out/9f/72/Christianity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/01/Outline_of_entertainment.txt ../out/a0/01/Outline_of_entertainment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/c0/Airline.txt ../out/a0/c0/Airline.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/ae/Caber.txt ../out/a1/ae/Caber.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/66/Bistability.txt ../out/a2/66/Bistability.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/14/Chemical_equilibrium.txt ../out/a3/14/Chemical_equilibrium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/cd/Denis_Diderot.txt ../out/a3/cd/Denis_Diderot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/8f/Choctaws.txt ../out/a4/8f/Choctaws.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/f4/Binomial_distribution.txt ../out/a4/f4/Binomial_distribution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/69/April_6.txt ../out/a5/69/April_6.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/24/DaveGrohl.txt ../out/a6/24/DaveGrohl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/be/History_of_Eritrea.txt ../out/a6/be/History_of_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/4d/Altruism.txt ../out/a7/4d/Altruism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/46/Dual_polyhedron.txt ../out/a8/46/Dual_polyhedron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/f8/Allomorph.txt ../out/a8/f8/Allomorph.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/a0/Chervil.txt ../out/a9/a0/Chervil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/67/Balalaika.txt ../out/aa/67/Balalaika.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/c9/DanCe.txt ../out/aa/c9/DanCe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/57/Country_Liberal_Party.txt ../out/ab/57/Country_Liberal_Party.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/0b/Romantic_orientation.txt ../out/ac/0b/Romantic_orientation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/8f/Atari.txt ../out/ac/8f/Atari.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/e5/Book_of_Zechariah.txt ../out/ac/e5/Book_of_Zechariah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/eb/Anastasius_III.txt ../out/ad/eb/Anastasius_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/63/Corporation.txt ../out/ae/63/Corporation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/fe/Burma%2FGeography.txt ../out/ae/fe/Burma%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/93/Arithmetic%2FMultiplication.txt ../out/af/93/Arithmetic%2FMultiplication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/1c/Declaration_of_Arbroath.txt ../out/b0/1c/Declaration_of_Arbroath.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/e4/Acid_rain.txt ../out/b0/e4/Acid_rain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/81/Cairo.txt ../out/b1/81/Cairo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/e0/Geography_of_Cameroon.txt ../out/b1/e0/Geography_of_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/91/Foreign_relations_of_Azerbaijan.txt ../out/b2/91/Foreign_relations_of_Azerbaijan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/a5/Black_letter_law.txt ../out/b3/a5/Black_letter_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/42/Classical_period_%28music%29.txt ../out/b4/42/Classical_period_%28music%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/a8/Aberavon_%28UK_Parliament_constituency%29.txt ../out/b4/a8/Aberavon_%28UK_Parliament_constituency%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/fa/Adrian_IV.txt ../out/b4/fa/Adrian_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/6c/Bertrand_Andrieu.txt ../out/b5/6c/Bertrand_Andrieu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/f8/Dinosaurs.txt ../out/b5/f8/Dinosaurs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/c7/Alcaeus_of_Mytilene.txt ../out/b6/c7/Alcaeus_of_Mytilene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/9d/Transport_in_the_Central_African_Republic.txt ../out/b7/9d/Transport_in_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/20/P_versus_NP_problem.txt ../out/b8/20/P_versus_NP_problem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/a5/Cheshire.txt ../out/b8/a5/Cheshire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/a4/Cornet.txt ../out/b9/a4/Cornet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/21/Degree_Confluence_Project.txt ../out/ba/21/Degree_Confluence_Project.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/cc/Computer_games.txt ../out/ba/cc/Computer_games.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/76/DMCA.txt ../out/bb/76/DMCA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/ec/Cladistics.txt ../out/bb/ec/Cladistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/7d/Carbohydrate.txt ../out/bc/7d/Carbohydrate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/5d/Agatha_Christie.txt ../out/bd/5d/Agatha_Christie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/16/Bolventor.txt ../out/be/16/Bolventor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/cf/Cable_television.txt ../out/be/cf/Cable_television.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/64/Outback.txt ../out/bf/64/Outback.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/22/Concrete.txt ../out/c0/22/Concrete.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/d2/Bernard_of_Clairvaux.txt ../out/c0/d2/Bernard_of_Clairvaux.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/7d/Galjoen.txt ../out/c1/7d/Galjoen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/5a/Biome.txt ../out/c2/5a/Biome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/16/Hercule_Poirot.txt ../out/c3/16/Hercule_Poirot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/c1/Czech_Republic%2FSacrum.txt ../out/c3/c1/Czech_Republic%2FSacrum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/4e/Charleston.txt ../out/c4/4e/Charleston.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/f4/Baptists.txt ../out/c4/f4/Baptists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/f5/December_15.txt ../out/c5/f5/December_15.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/88/Beer.txt ../out/c6/88/Beer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/45/Capetian_dynasty.txt ../out/c7/45/Capetian_dynasty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/f5/British.txt ../out/c7/f5/British.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/d4/Charles_Chaplin.txt ../out/c8/d4/Charles_Chaplin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/67/Crime.txt ../out/c9/67/Crime.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/e8/Aarau.txt ../out/c9/e8/Aarau.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/7d/Spain_in_Flames.txt ../out/ca/7d/Spain_in_Flames.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/61/Engineering_statistics.txt ../out/cb/61/Engineering_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/1e/Commutator.txt ../out/cc/1e/Commutator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/ec/Aegeus.txt ../out/cc/ec/Aegeus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/6e/Chronic_Fatigue_Syndrome%2FDay_to_day_patterns.txt ../out/cd/6e/Chronic_Fatigue_Syndrome%2FDay_to_day_patterns.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/2d/Eureka_Rebellion.txt ../out/ce/2d/Eureka_Rebellion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/04/Dryope.txt ../out/cf/04/Dryope.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/9b/Bipolar_spectrum.txt ../out/cf/9b/Bipolar_spectrum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/50/Alpha_decay.txt ../out/d0/50/Alpha_decay.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/24/Compressors.txt ../out/d1/24/Compressors.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/a8/Aromatic_compound.txt ../out/d1/a8/Aromatic_compound.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/94/Color%2FBlack.txt ../out/d2/94/Color%2FBlack.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/16/Doctor_Syn.txt ../out/d3/16/Doctor_Syn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/b8/Alexander_VII.txt ../out/d3/b8/Alexander_VII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/95/Declination.txt ../out/d4/95/Declination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/1d/Ansible.txt ../out/d5/1d/Ansible.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/d0/Epoch.txt ../out/d5/d0/Epoch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/7f/Clarence_Brown.txt ../out/d6/7f/Clarence_Brown.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/05/Descending_chain_condition.txt ../out/d7/05/Descending_chain_condition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/90/Bone.txt ../out/d7/90/Bone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/62/British_Standards.txt ../out/d8/62/British_Standards.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/07/A._J._Ayer.txt ../out/d9/07/A._J._Ayer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/bd/Analog_magazine.txt ../out/d9/bd/Analog_magazine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/83/Chronic_Fatigue_Syndrome%2FDemographics.txt ../out/da/83/Chronic_Fatigue_Syndrome%2FDemographics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/fb/Disaster.txt ../out/da/fb/Disaster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/92/Celestial_globe.txt ../out/db/92/Celestial_globe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/33/Arithmetic_mean.txt ../out/dc/33/Arithmetic_mean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/b7/Admiralty.txt ../out/dc/b7/Admiralty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/81/Alkali_metal.txt ../out/dd/81/Alkali_metal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/f1/Cryptozoology.txt ../out/dd/f1/Cryptozoology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/c2/Chlorophyll.txt ../out/de/c2/Chlorophyll.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/77/British_Commonwealth.txt ../out/df/77/British_Commonwealth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/2e/Brighton_University.txt ../out/e0/2e/Brighton_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/2a/Military_of_Bouvet_Island.txt ../out/e1/2a/Military_of_Bouvet_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/b4/Child_Online_Privacy_Protection_Act.txt ../out/e1/b4/Child_Online_Privacy_Protection_Act.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/73/Politics_of_Eritrea.txt ../out/e2/73/Politics_of_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/17/Atari_Jaguar.txt ../out/e3/17/Atari_Jaguar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/a1/Abbot.txt ../out/e3/a1/Abbot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/59/Diophantus.txt ../out/e4/59/Diophantus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/16/Differential_topology.txt ../out/e5/16/Differential_topology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/be/Chord.txt ../out/e5/be/Chord.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/40/Ahenobarbus.txt ../out/e6/40/Ahenobarbus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/13/Dione.txt ../out/e7/13/Dione.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/e1/Erfurt.txt ../out/e7/e1/Erfurt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/85/Cable_car_%28railway%29.txt ../out/e8/85/Cable_car_%28railway%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/fd/E._E._Smith.txt ../out/e8/fd/E._E._Smith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/89/Glossary_of_country_dance_terms.txt ../out/e9/89/Glossary_of_country_dance_terms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/06/Constructible_number.txt ../out/ea/06/Constructible_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/ba/Bretwalda.txt ../out/ea/ba/Bretwalda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/4d/Alphonso_IX.txt ../out/eb/4d/Alphonso_IX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/35/Transport_in_Denmark.txt ../out/ec/35/Transport_in_Denmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/fc/CommonSenseAndTheDiallelus.txt ../out/ec/fc/CommonSenseAndTheDiallelus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/95/Americans_with_Disabilities_Act_of_1990%2FFindings_and_Purposes.txt ../out/ed/95/Americans_with_Disabilities_Act_of_1990%2FFindings_and_Purposes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/16/Berlin.txt ../out/ee/16/Berlin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/b9/David_Bowman_%28Space_Odyssey%29.txt ../out/ee/b9/David_Bowman_%28Space_Odyssey%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/5b/Alfonso_Ar%C3%A1u.txt ../out/ef/5b/Alfonso_Ar%C3%A1u.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/ed/Everway.txt ../out/ef/ed/Everway.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/9f/English_Channel.txt ../out/f0/9f/English_Channel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/6f/Arcology.txt ../out/f1/6f/Arcology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/53/Ammonius_Hermiae.txt ../out/f2/53/Ammonius_Hermiae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/34/DefinitionofBibleTerms.txt ../out/f3/34/DefinitionofBibleTerms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/d6/Bay_of_Quinte.txt ../out/f3/d6/Bay_of_Quinte.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/bc/Lockheed_C-130_Hercules.txt ../out/f4/bc/Lockheed_C-130_Hercules.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/a1/Double_stops.txt ../out/f5/a1/Double_stops.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/35/Barter.txt ../out/f6/35/Barter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/d4/December_25.txt ../out/f6/d4/December_25.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/54/Andreas_Schl%C3%BCter.txt ../out/f7/54/Andreas_Schl%C3%BCter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/3d/Dan_DeCarlo.txt ../out/f8/3d/Dan_DeCarlo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/c8/Andrew_Tridgell.txt ../out/f8/c8/Andrew_Tridgell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/2c/Charles_Messier.txt ../out/f9/2c/Charles_Messier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/d8/Chuck_Jones.txt ../out/f9/d8/Chuck_Jones.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/3e/Cat.txt ../out/fa/3e/Cat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/fb/Binary_relation.txt ../out/fa/fb/Binary_relation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/86/Cactus.txt ../out/fb/86/Cactus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/1f/Transport_in_Cameroon.txt ../out/fc/1f/Transport_in_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/55/Military_of_the_Cayman_Islands.txt ../out/fd/55/Military_of_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/d8/Biennial_plant.txt ../out/fd/d8/Biennial_plant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/b1/Foreign_relations_of_Egypt.txt ../out/fe/b1/Foreign_relations_of_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/39/Earth_%28classical_element%29.txt ../out/ff/39/Earth_%28classical_element%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/92/Buckminister_Fuller.txt ../out/ff/92/Buckminister_Fuller.xml
