php ./wiki2xml/php/wiki2xml_command.php ../out/00/07/Brahui_language.txt ../out/00/07/Brahui_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/00/db/Anastasius_I.txt ../out/00/db/Anastasius_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/90/Blade_Runner.txt ../out/01/90/Blade_Runner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/1c/Consciousness.txt ../out/02/1c/Consciousness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/d5/School_voucher.txt ../out/02/d5/School_voucher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/72/Day.txt ../out/03/72/Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/04/Akihabara.txt ../out/04/04/Akihabara.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/87/Dukkha.txt ../out/04/87/Dukkha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/30/B_%28programming_language%29.txt ../out/05/30/B_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/af/Computer-generated_art.txt ../out/05/af/Computer-generated_art.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/32/CallOfCthulhuGame.txt ../out/06/32/CallOfCthulhuGame.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/ee/Colette.txt ../out/06/ee/Colette.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/a3/Communication.txt ../out/07/a3/Communication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/6d/Berkelium.txt ../out/08/6d/Berkelium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/e5/Continuity_Irish_Republican_Army.txt ../out/08/e5/Continuity_Irish_Republican_Army.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/a4/Alexandria%2C_Romania.txt ../out/09/a4/Alexandria%2C_Romania.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/82/Calvin_and_Hobbes.txt ../out/0a/82/Calvin_and_Hobbes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/ec/ErnestHemingway%2FThingsTurnSour.txt ../out/0a/ec/ErnestHemingway%2FThingsTurnSour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/97/Bus_%28computing%29.txt ../out/0b/97/Bus_%28computing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/0f/Telecommunications_in_Equatorial_Guinea.txt ../out/0c/0f/Telecommunications_in_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/d7/Diagnostic_and_Statistical_Manual_of_Mental_Disorders.txt ../out/0c/d7/Diagnostic_and_Statistical_Manual_of_Mental_Disorders.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/a0/Computer_program.txt ../out/0d/a0/Computer_program.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/36/Clairvoyance.txt ../out/0e/36/Clairvoyance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/d6/Christian_Doppler.txt ../out/0e/d6/Christian_Doppler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/7a/Biopolymer.txt ../out/0f/7a/Biopolymer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/7d/Battle_of_Agincourt.txt ../out/10/7d/Battle_of_Agincourt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/48/Boltzmann_distribution.txt ../out/11/48/Boltzmann_distribution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/d9/Geography_of_Burundi.txt ../out/11/d9/Geography_of_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/88/Collectivism.txt ../out/12/88/Collectivism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/27/Albion%2C_Michigan.txt ../out/13/27/Albion%2C_Michigan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/ac/Arizona_Cardinals.txt ../out/13/ac/Arizona_Cardinals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/81/Demographics_of_American_Samoa.txt ../out/14/81/Demographics_of_American_Samoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/14/Afro-asiatic_languages.txt ../out/15/14/Afro-asiatic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/c7/Closeted_person.txt ../out/15/c7/Closeted_person.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/5b/Constantine_Kanaris.txt ../out/16/5b/Constantine_Kanaris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/0d/Afrikaans.txt ../out/17/0d/Afrikaans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/e7/Caffeine.txt ../out/17/e7/Caffeine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/77/Columbus%2C_Indiana.txt ../out/18/77/Columbus%2C_Indiana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/06/E.B._White.txt ../out/19/06/E.B._White.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/86/Constitution_of_Canada%2F1867_VIII_Revenues_Debts_Assets_Taxation.txt ../out/19/86/Constitution_of_Canada%2F1867_VIII_Revenues_Debts_Assets_Taxation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/1f/Cello.txt ../out/1a/1f/Cello.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/ae/Casimir_III_the_Great.txt ../out/1a/ae/Casimir_III_the_Great.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/30/CPR_%28disambiguation%29.txt ../out/1b/30/CPR_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/d4/Running_amok.txt ../out/1b/d4/Running_amok.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/51/Christmas_Island.txt ../out/1c/51/Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/e0/Destry_Rides_Again.txt ../out/1c/e0/Destry_Rides_Again.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/59/Cumulative_distribution_function.txt ../out/1d/59/Cumulative_distribution_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/11/Electromagnetic_spectroscopy.txt ../out/1e/11/Electromagnetic_spectroscopy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/a4/CITES.txt ../out/1e/a4/CITES.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/a4/Dr._Suess.txt ../out/1f/a4/Dr._Suess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/43/Comic_books_and_strips.txt ../out/20/43/Comic_books_and_strips.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/f0/Beast_of_Bodmin.txt ../out/20/f0/Beast_of_Bodmin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/9c/E_%28mathematical_constant%29.txt ../out/21/9c/E_%28mathematical_constant%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/6e/Blade_Runner_3%3A_Replicant_Night.txt ../out/22/6e/Blade_Runner_3%3A_Replicant_Night.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/0a/Aedesius.txt ../out/23/0a/Aedesius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/bf/Bovril.txt ../out/23/bf/Bovril.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/55/ErnestHemingway%2FForWhomtheBellTolls.txt ../out/24/55/ErnestHemingway%2FForWhomtheBellTolls.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/12/Cary_Elwes.txt ../out/25/12/Cary_Elwes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/ea/Alfonso_Jordan.txt ../out/25/ea/Alfonso_Jordan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/64/Capoeira.txt ../out/26/64/Capoeira.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/09/Bavaria.txt ../out/27/09/Bavaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/b9/Anti-semitism.txt ../out/27/b9/Anti-semitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/5d/August_8.txt ../out/28/5d/August_8.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/db/Chemical_affinity.txt ../out/28/db/Chemical_affinity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/89/Bahamas%2FTransnational_issues.txt ../out/29/89/Bahamas%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/3d/The_Amazing_Criswell.txt ../out/2a/3d/The_Amazing_Criswell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/1f/Book.txt ../out/2b/1f/Book.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/bc/Demographics_of_Croatia.txt ../out/2b/bc/Demographics_of_Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/56/Crete_Senesi.txt ../out/2c/56/Crete_Senesi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/e5/Advertising.txt ../out/2c/e5/Advertising.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/9f/Bacillus.txt ../out/2d/9f/Bacillus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/4e/Cognate.txt ../out/2e/4e/Cognate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/14/Contras.txt ../out/2f/14/Contras.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/cb/Ayn_Rand.txt ../out/2f/cb/Ayn_Rand.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/c1/Checkers.txt ../out/30/c1/Checkers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/4f/California_Department_of_Transportation.txt ../out/31/4f/California_Department_of_Transportation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/28/Cupola.txt ../out/32/28/Cupola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/dd/Creature_of_statute.txt ../out/32/dd/Creature_of_statute.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/96/Alan_Garner.txt ../out/33/96/Alan_Garner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/88/Aramaic.txt ../out/34/88/Aramaic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/0b/Antoine_Thomson_d%27Abbadie.txt ../out/35/0b/Antoine_Thomson_d%27Abbadie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/bc/Ecclesia.txt ../out/35/bc/Ecclesia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/7e/Aelian.txt ../out/36/7e/Aelian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/45/Decnet.txt ../out/37/45/Decnet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/c3/Canterbury_%28disambiguation%29.txt ../out/37/c3/Canterbury_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/22/Action_Film.txt ../out/38/22/Action_Film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/d0/Ambrose.txt ../out/38/d0/Ambrose.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/ae/Ephesus.txt ../out/39/ae/Ephesus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/4c/Book_of_Counted_Sorrows.txt ../out/3a/4c/Book_of_Counted_Sorrows.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/b6/Ceylon.txt ../out/3a/b6/Ceylon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/5c/European_Conference_of_Postal_and_Telecommunications_Administrations.txt ../out/3b/5c/European_Conference_of_Postal_and_Telecommunications_Administrations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/c2/Bronx%2C_New_York.txt ../out/3b/c2/Bronx%2C_New_York.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/6d/Clive_Anderson.txt ../out/3c/6d/Clive_Anderson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/1c/Darwinian.txt ../out/3d/1c/Darwinian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/ba/Chrysler.txt ../out/3d/ba/Chrysler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/82/Euro.txt ../out/3e/82/Euro.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/f6/Bristol_City_F.C..txt ../out/3e/f6/Bristol_City_F.C..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/56/Foreign_relations_of_Dominica.txt ../out/3f/56/Foreign_relations_of_Dominica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/0c/Cytosine.txt ../out/40/0c/Cytosine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/c3/Education_reform.txt ../out/40/c3/Education_reform.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/7d/BASE_jumping.txt ../out/41/7d/BASE_jumping.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/d6/Data_compression%2FMP3.txt ../out/41/d6/Data_compression%2FMP3.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/39/Black_metal.txt ../out/42/39/Black_metal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/f1/First_Epistle_to_the_Thessalonians.txt ../out/42/f1/First_Epistle_to_the_Thessalonians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/90/Eukaryotic_cell.txt ../out/43/90/Eukaryotic_cell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/4c/Antiarrhythmic_medication.txt ../out/44/4c/Antiarrhythmic_medication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/9b/Anubis.txt ../out/44/9b/Anubis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/4b/Ammonia.txt ../out/45/4b/Ammonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/07/Dianetics.txt ../out/46/07/Dianetics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/b4/Piter_De_Vries.txt ../out/46/b4/Piter_De_Vries.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/76/Alphonsus_a_Sancta_Maria.txt ../out/47/76/Alphonsus_a_Sancta_Maria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/51/Eridanus.txt ../out/48/51/Eridanus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/ee/Expected_value.txt ../out/48/ee/Expected_value.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/a1/Andalusia.txt ../out/49/a1/Andalusia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/45/Batman.txt ../out/4a/45/Batman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/c8/Acoustic_theory.txt ../out/4a/c8/Acoustic_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/54/Comic_fantasy.txt ../out/4b/54/Comic_fantasy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/fc/Ahmad_Shah_Massoud.txt ../out/4b/fc/Ahmad_Shah_Massoud.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/7b/Carmichael_number.txt ../out/4c/7b/Carmichael_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/59/Bruin.txt ../out/4d/59/Bruin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/d3/Colonized.txt ../out/4d/d3/Colonized.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/77/Cedar_Falls%2C_Iowa.txt ../out/4e/77/Cedar_Falls%2C_Iowa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/f7/Dollar.txt ../out/4e/f7/Dollar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/d4/Acores.txt ../out/4f/d4/Acores.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/77/Dagome_iudex.txt ../out/50/77/Dagome_iudex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/3b/Transport_in_Colombia.txt ../out/51/3b/Transport_in_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/be/Central_Pacific_Railroad.txt ../out/51/be/Central_Pacific_Railroad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/71/Dejima.txt ../out/52/71/Dejima.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/07/Circe.txt ../out/53/07/Circe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/a6/Ether.txt ../out/53/a6/Ether.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/27/Digital_cinema.txt ../out/54/27/Digital_cinema.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/a6/Ernest_Thayer.txt ../out/54/a6/Ernest_Thayer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/7e/Atomic.txt ../out/55/7e/Atomic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/0d/Croatia.txt ../out/56/0d/Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/14/Geography_of_Chad.txt ../out/57/14/Geography_of_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/bc/Chomsky_%28surname%29.txt ../out/57/bc/Chomsky_%28surname%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/4c/AnnaKournikova.txt ../out/58/4c/AnnaKournikova.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/13/Armadillo.txt ../out/59/13/Armadillo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/a7/Accidental_property.txt ../out/59/a7/Accidental_property.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/3c/Congregationalist_polity.txt ../out/5a/3c/Congregationalist_polity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/c3/Albertus_Magnus.txt ../out/5a/c3/Albertus_Magnus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/61/National_Anthem_of_Chile.txt ../out/5b/61/National_Anthem_of_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/f0/Cyrix_6x86.txt ../out/5b/f0/Cyrix_6x86.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/b2/Cricket_%28disambiguation%29.txt ../out/5c/b2/Cricket_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/84/Battle_of_Adrianople_%28disambiguation%29.txt ../out/5d/84/Battle_of_Adrianople_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/47/AynRand.txt ../out/5e/47/AynRand.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/b8/Argument_from_morality.txt ../out/5e/b8/Argument_from_morality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/8f/Brain_abscess.txt ../out/5f/8f/Brain_abscess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/23/Carnivore.txt ../out/60/23/Carnivore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/e3/Blowfish_%28disambiguation%29.txt ../out/60/e3/Blowfish_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/7d/Communications_in_Burundi.txt ../out/61/7d/Communications_in_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/1c/AsWeMayThink.txt ../out/62/1c/AsWeMayThink.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/dd/Exchange_particle.txt ../out/62/dd/Exchange_particle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/c0/The_Triumph_of_Time.txt ../out/63/c0/The_Triumph_of_Time.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/bc/Academy_Awards.txt ../out/64/bc/Academy_Awards.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/2b/Chief_Minister_of_the_Northern_Territory.txt ../out/65/2b/Chief_Minister_of_the_Northern_Territory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/af/Economy_of_the_Bahamas.txt ../out/65/af/Economy_of_the_Bahamas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/2c/Dominican_Republic.txt ../out/66/2c/Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/e2/Belgian_%28disambiguation%29.txt ../out/66/e2/Belgian_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/4b/Transport_in_Cuba.txt ../out/67/4b/Transport_in_Cuba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/01/Associative_property.txt ../out/68/01/Associative_property.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/b3/Baptist_church.txt ../out/68/b3/Baptist_church.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/78/European_Environment_Agency.txt ../out/69/78/European_Environment_Agency.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/2c/Albrecht_Achilles.txt ../out/6a/2c/Albrecht_Achilles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/b1/Dolly_Parton.txt ../out/6a/b1/Dolly_Parton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/0e/DonegalFiddleTradition.txt ../out/6b/0e/DonegalFiddleTradition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/cf/Geography_of_Brazil.txt ../out/6b/cf/Geography_of_Brazil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/4e/Della_Thelma_Duck.txt ../out/6c/4e/Della_Thelma_Duck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/e9/Binary.txt ../out/6c/e9/Binary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/87/Actors_and_Actresses.txt ../out/6d/87/Actors_and_Actresses.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/12/Bse.txt ../out/6e/12/Bse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/a8/Foreign_relations_of_Belarus.txt ../out/6e/a8/Foreign_relations_of_Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/24/Ancyra_%28genus%29.txt ../out/6f/24/Ancyra_%28genus%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/ef/Erwin_Schr%C3%B6dinger.txt ../out/6f/ef/Erwin_Schr%C3%B6dinger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/ae/Derivative.txt ../out/70/ae/Derivative.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/84/BrainEvent.txt ../out/71/84/BrainEvent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/1b/The_Time_in_Between.txt ../out/72/1b/The_Time_in_Between.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/b7/Cyrus.txt ../out/72/b7/Cyrus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/95/Electromagnetic_coil.txt ../out/73/95/Electromagnetic_coil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/39/Alphons.txt ../out/74/39/Alphons.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/81/Banach_Tarski_Paradoxical_Decomposition.txt ../out/74/81/Banach_Tarski_Paradoxical_Decomposition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/3d/Blue_Streak_%28missile%29.txt ../out/75/3d/Blue_Streak_%28missile%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/f8/Bash_%28Unix_shell%29.txt ../out/75/f8/Bash_%28Unix_shell%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/9e/Helsing%C3%B8r.txt ../out/76/9e/Helsing%C3%B8r.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/41/List_of_Dune_characters.txt ../out/77/41/List_of_Dune_characters.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/ec/ACF_Fiorentina.txt ../out/77/ec/ACF_Fiorentina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/b1/Societas_Europaea.txt ../out/78/b1/Societas_Europaea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/14/Naive_set_theory.txt ../out/79/14/Naive_set_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/bc/EcheloN.txt ../out/79/bc/EcheloN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/5b/Bryce_Canyon.txt ../out/7a/5b/Bryce_Canyon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/a4/Albert_the_Degenerate.txt ../out/7a/a4/Albert_the_Degenerate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/4f/Database_normalization.txt ../out/7b/4f/Database_normalization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/05/AOL_Instant_Messenger.txt ../out/7c/05/AOL_Instant_Messenger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/d3/Albrecht_D%C3%BCrer.txt ../out/7c/d3/Albrecht_D%C3%BCrer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/41/Abadeh.txt ../out/7d/41/Abadeh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/09/Politics_of_Botswana.txt ../out/7e/09/Politics_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/81/BooksOfTheBible.txt ../out/7e/81/BooksOfTheBible.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/4b/Biotic.txt ../out/7f/4b/Biotic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/cf/Bromine.txt ../out/7f/cf/Bromine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/38/Existentialism.txt ../out/80/38/Existentialism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/e7/Convex_uniform_honeycomb.txt ../out/80/e7/Convex_uniform_honeycomb.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/8b/Conservation_%28cultural_heritage%29.txt ../out/81/8b/Conservation_%28cultural_heritage%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/40/Dachau.txt ../out/82/40/Dachau.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/29/Computer_Science.txt ../out/83/29/Computer_Science.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/bc/Common_Desktop_Environment.txt ../out/83/bc/Common_Desktop_Environment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/a3/AbeceDarians.txt ../out/84/a3/AbeceDarians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/41/Dublin_Core.txt ../out/85/41/Dublin_Core.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/b1/Ara_Pacis_Augustae.txt ../out/85/b1/Ara_Pacis_Augustae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/70/Alfred.txt ../out/86/70/Alfred.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/fc/Cyril_Kornbluth.txt ../out/86/fc/Cyril_Kornbluth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/ae/Debit_card.txt ../out/87/ae/Debit_card.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/95/Albert_the_Bear.txt ../out/88/95/Albert_the_Bear.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/3b/Divination.txt ../out/89/3b/Divination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/d4/Binomial_theorem.txt ../out/89/d4/Binomial_theorem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/5f/Common_sense_and_the_Diallelus.txt ../out/8a/5f/Common_sense_and_the_Diallelus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/24/Alfred_Korzybski.txt ../out/8b/24/Alfred_Korzybski.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/c6/Augustine_of_Hippo.txt ../out/8b/c6/Augustine_of_Hippo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/7a/Bletchley_Park.txt ../out/8c/7a/Bletchley_Park.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/f1/Andronicus.txt ../out/8c/f1/Andronicus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/8b/Ameboid_stage.txt ../out/8d/8b/Ameboid_stage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/72/Ann_Arbor%2C_Michigan.txt ../out/8e/72/Ann_Arbor%2C_Michigan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/5d/December_1.txt ../out/8f/5d/December_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/07/Cosmic_Background_Radiation.txt ../out/90/07/Cosmic_Background_Radiation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/d5/Casimir_IV_Jagiello.txt ../out/90/d5/Casimir_IV_Jagiello.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/6a/Coca-Cola.txt ../out/91/6a/Coca-Cola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/8a/Alph.txt ../out/92/8a/Alph.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/2d/Amitabh_Bachchan.txt ../out/93/2d/Amitabh_Bachchan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/e4/Conjunction_introduction.txt ../out/93/e4/Conjunction_introduction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/da/Ethiopian_cuisine.txt ../out/94/da/Ethiopian_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/63/Artemis.txt ../out/95/63/Artemis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/fa/C._L._Berthollet.txt ../out/95/fa/C._L._Berthollet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/b3/Coitus.txt ../out/96/b3/Coitus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/49/Afghanistan%2FPeople.txt ../out/97/49/Afghanistan%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/d7/Block_cipher.txt ../out/97/d7/Block_cipher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/54/Adversarial_system.txt ../out/98/54/Adversarial_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/fb/Andrew_Johnson.txt ../out/98/fb/Andrew_Johnson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/7a/Data_compression%2FHuffman_coding.txt ../out/99/7a/Data_compression%2FHuffman_coding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/f2/Epsilon.txt ../out/99/f2/Epsilon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/75/Akkadian_Empire.txt ../out/9a/75/Akkadian_Empire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/1d/Battle_of_El_Alamein.txt ../out/9b/1d/Battle_of_El_Alamein.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/bd/Accounting.txt ../out/9b/bd/Accounting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/36/Drake_equation.txt ../out/9c/36/Drake_equation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/c9/Bipolar_disorder.txt ../out/9c/c9/Bipolar_disorder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/62/Christology.txt ../out/9d/62/Christology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/04/Arabian_Sea.txt ../out/9e/04/Arabian_Sea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/cf/Brainfuck.txt ../out/9e/cf/Brainfuck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/8e/Outline_of_dance.txt ../out/9f/8e/Outline_of_dance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/19/Disc_jockey.txt ../out/a0/19/Disc_jockey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/df/Bronze.txt ../out/a0/df/Bronze.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/be/Abersychan.txt ../out/a1/be/Abersychan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/8e/Batman%3A_Year_One.txt ../out/a2/8e/Batman%3A_Year_One.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/24/Christadelphians.txt ../out/a3/24/Christadelphians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/db/Rhyming_slang.txt ../out/a3/db/Rhyming_slang.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/aa/Canada_Day.txt ../out/a4/aa/Canada_Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/16/History_of_the_Cook_Islands.txt ../out/a5/16/History_of_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/86/Cheers.txt ../out/a5/86/Cheers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/37/Antigonid_dynasty.txt ../out/a6/37/Antigonid_dynasty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/f0/Bordeaux.txt ../out/a6/f0/Bordeaux.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/84/Antarctic_Treaty_System.txt ../out/a7/84/Antarctic_Treaty_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/5f/Ciconiiformes.txt ../out/a8/5f/Ciconiiformes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/04/Ben_Bova.txt ../out/a9/04/Ben_Bova.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/01/Cetaceans.txt ../out/aa/01/Cetaceans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/7d/December_14.txt ../out/aa/7d/December_14.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/e8/Conectiva.txt ../out/aa/e8/Conectiva.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/84/Erewhon.txt ../out/ab/84/Erewhon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/1f/Direct_Connect.txt ../out/ac/1f/Direct_Connect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/9f/Dahomey.txt ../out/ac/9f/Dahomey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/1c/Recreational_use_of_dextromethorphan.txt ../out/ad/1c/Recreational_use_of_dextromethorphan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/ef/Economy_of_the_Cayman_Islands.txt ../out/ad/ef/Economy_of_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/81/Abakan.txt ../out/ae/81/Abakan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/1e/Dose.txt ../out/af/1e/Dose.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/99/Beryl.txt ../out/af/99/Beryl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/3f/Diffie%E2%80%93Hellman_key_exchange.txt ../out/b0/3f/Diffie%E2%80%93Hellman_key_exchange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/ff/Arthur_Miller.txt ../out/b0/ff/Arthur_Miller.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/98/Bruce_Perens.txt ../out/b1/98/Bruce_Perens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/f1/ComputerSoftware.txt ../out/b1/f1/ComputerSoftware.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/bf/Annual_plant.txt ../out/b2/bf/Annual_plant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/b0/Induhvidual.txt ../out/b3/b0/Induhvidual.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/51/CDC.txt ../out/b4/51/CDC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/af/Alexander_of_Aphrodisias.txt ../out/b4/af/Alexander_of_Aphrodisias.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/12/Fern_Hill.txt ../out/b5/12/Fern_Hill.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/8d/Comic_strip.txt ../out/b5/8d/Comic_strip.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/24/Extreme_unction.txt ../out/b6/24/Extreme_unction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/fe/David_Deutsch.txt ../out/b6/fe/David_Deutsch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/af/Analysis_of_variance%2FRandom_effects_models.txt ../out/b7/af/Analysis_of_variance%2FRandom_effects_models.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/46/Battleship.txt ../out/b8/46/Battleship.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/c9/Blackadder.txt ../out/b8/c9/Blackadder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/b4/AK-47.txt ../out/b9/b4/AK-47.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/3b/Andrei_Tarkovsky.txt ../out/ba/3b/Andrei_Tarkovsky.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/f4/Creutzfeld-Jacob_Disease.txt ../out/ba/f4/Creutzfeld-Jacob_Disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/7f/Dead_Sea.txt ../out/bb/7f/Dead_Sea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/10/December_31.txt ../out/bc/10/December_31.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/a5/Design_pattern.txt ../out/bc/a5/Design_pattern.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/7a/Dancing_music.txt ../out/bd/7a/Dancing_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/42/Diplomatic_immunity.txt ../out/be/42/Diplomatic_immunity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/f3/AfghanistanCommunications.txt ../out/be/f3/AfghanistanCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/9f/Agglutinative.txt ../out/bf/9f/Agglutinative.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/55/Costume_jewelry.txt ../out/c0/55/Costume_jewelry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/30/Ahriman.txt ../out/c1/30/Ahriman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/ab/Northern_bobwhite.txt ../out/c1/ab/Northern_bobwhite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/68/Nepeta.txt ../out/c2/68/Nepeta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/4b/Catholicism%2FCouncils.txt ../out/c3/4b/Catholicism%2FCouncils.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/c8/Corroborating_evidence.txt ../out/c3/c8/Corroborating_evidence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/5d/AGM-65_Maverick.txt ../out/c4/5d/AGM-65_Maverick.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/02/Ergonomics.txt ../out/c5/02/Ergonomics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/0d/Charles_Alston.txt ../out/c6/0d/Charles_Alston.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/cf/Company_%28disambiguation%29.txt ../out/c6/cf/Company_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/6d/Diaspora_Studies.txt ../out/c7/6d/Diaspora_Studies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/2b/AutoCAD.txt ../out/c8/2b/AutoCAD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/02/Alexander_I_of_Scotland.txt ../out/c9/02/Alexander_I_of_Scotland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/90/Major_League_Baseball_Rookie_of_the_Year_Award.txt ../out/c9/90/Major_League_Baseball_Rookie_of_the_Year_Award.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/07/Comet_Hale%E2%80%93Bopp.txt ../out/ca/07/Comet_Hale%E2%80%93Bopp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/9c/Tramlink.txt ../out/ca/9c/Tramlink.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/76/Aphrodite.txt ../out/cb/76/Aphrodite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/5b/Euglenozoa.txt ../out/cc/5b/Euglenozoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/fe/Chamaeleon.txt ../out/cc/fe/Chamaeleon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/99/Elliptic_curve_cryptography.txt ../out/cd/99/Elliptic_curve_cryptography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/56/Al-Quabail_Mountains.txt ../out/ce/56/Al-Quabail_Mountains.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/13/Brisbane_Lions.txt ../out/cf/13/Brisbane_Lions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/cd/Civil_war.txt ../out/cf/cd/Civil_war.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/7f/Dhamma.txt ../out/d0/7f/Dhamma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/47/Diffraction.txt ../out/d1/47/Diffraction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/0b/Baldr.txt ../out/d2/0b/Baldr.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/ac/List_of_confederations_of_Germanic_tribes.txt ../out/d2/ac/List_of_confederations_of_Germanic_tribes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/40/Diedrich_Hermann_Westermann.txt ../out/d3/40/Diedrich_Hermann_Westermann.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/d6/Apollinarism.txt ../out/d3/d6/Apollinarism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/ab/Amazons.txt ../out/d4/ab/Amazons.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/56/Aliens.txt ../out/d5/56/Aliens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/e5/Geography_of_Europa_Island.txt ../out/d5/e5/Geography_of_Europa_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/92/A._E._Housman.txt ../out/d6/92/A._E._Housman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/2d/Brown_bear.txt ../out/d7/2d/Brown_bear.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/a6/Andes.txt ../out/d7/a6/Andes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/9a/Communications_in_the_Cocos_%28Keeling%29_Islands.txt ../out/d8/9a/Communications_in_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/0b/Anal_intercourse.txt ../out/d9/0b/Anal_intercourse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/d0/Economy_of_Cyprus.txt ../out/d9/d0/Economy_of_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/8c/Demographics_of_Eritrea.txt ../out/da/8c/Demographics_of_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/18/Aircraft_spotting.txt ../out/db/18/Aircraft_spotting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/bf/Agnosticism.txt ../out/db/bf/Agnosticism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/56/Epistle_to_the_Hebrews.txt ../out/dc/56/Epistle_to_the_Hebrews.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/0b/Constitution_of_Chile.txt ../out/dd/0b/Constitution_of_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/8f/Delphinus.txt ../out/dd/8f/Delphinus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/6c/Biomedical_engineering.txt ../out/de/6c/Biomedical_engineering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/ec/Area.txt ../out/de/ec/Area.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/9b/Dave_Winer.txt ../out/df/9b/Dave_Winer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/57/Baku.txt ../out/e0/57/Baku.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/32/Christian_%28disambiguation%29.txt ../out/e1/32/Christian_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/c7/Wikipedia%3AHistorical_Wikipedia_pages%2FChalkboard_candidates.txt ../out/e1/c7/Wikipedia%3AHistorical_Wikipedia_pages%2FChalkboard_candidates.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/8e/Alexander_VI.txt ../out/e2/8e/Alexander_VI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/30/Algeria%2FPeople.txt ../out/e3/30/Algeria%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/d0/Convention_of_Kanagawa.txt ../out/e3/d0/Convention_of_Kanagawa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/88/Geography_of_Croatia.txt ../out/e4/88/Geography_of_Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/23/Asia_Minor_%28disambiguation%29.txt ../out/e5/23/Asia_Minor_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/cf/Bedrock_Records.txt ../out/e5/cf/Bedrock_Records.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/57/Casimir_effect.txt ../out/e6/57/Casimir_effect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/3e/Do_Not_Adjust_Your_Set.txt ../out/e7/3e/Do_Not_Adjust_Your_Set.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/05/Conspiracy_theory.txt ../out/e8/05/Conspiracy_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/98/Biathlon_World_Championships.txt ../out/e8/98/Biathlon_World_Championships.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/21/Ashmore_And_Cartier_Islands.txt ../out/e9/21/Ashmore_And_Cartier_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/a1/Blind_Blake.txt ../out/e9/a1/Blind_Blake.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/17/Balboa.txt ../out/ea/17/Balboa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/d6/Autonomous_building.txt ../out/ea/d6/Autonomous_building.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/5e/C_language.txt ../out/eb/5e/C_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/54/Casuistry.txt ../out/ec/54/Casuistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/1a/Bill_Oddie.txt ../out/ed/1a/Bill_Oddie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/a7/Outline_of_education.txt ../out/ed/a7/Outline_of_education.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/3c/Electronics.txt ../out/ee/3c/Electronics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/c2/Politics_of_the_Cook_Islands.txt ../out/ee/c2/Politics_of_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/8c/List_of_basic_classics_topics.txt ../out/ef/8c/List_of_basic_classics_topics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/0e/Calista_Flockhart.txt ../out/f0/0e/Calista_Flockhart.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/cb/Personal_computer_hardware.txt ../out/f0/cb/Personal_computer_hardware.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/8f/Detroit_River.txt ../out/f1/8f/Detroit_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/61/Eigenvalue.txt ../out/f2/61/Eigenvalue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/59/Canidae.txt ../out/f3/59/Canidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/fa/Erin_Brockovich.txt ../out/f3/fa/Erin_Brockovich.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/f5/Creation_myth.txt ../out/f4/f5/Creation_myth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/a8/Bishkek.txt ../out/f5/a8/Bishkek.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/58/American_Telephone_and_Telegraph_Company.txt ../out/f6/58/American_Telephone_and_Telegraph_Company.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/ec/December_9.txt ../out/f6/ec/December_9.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/6c/Book_of_Isaiah.txt ../out/f7/6c/Book_of_Isaiah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/4f/DesigningExperiments.txt ../out/f8/4f/DesigningExperiments.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/de/Circumference.txt ../out/f8/de/Circumference.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/41/American_Football_League.txt ../out/f9/41/American_Football_League.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/e8/Contraction_mapping.txt ../out/f9/e8/Contraction_mapping.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/54/College_of_the_City_of_New_York.txt ../out/fa/54/College_of_the_City_of_New_York.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/18/Exoplanet.txt ../out/fb/18/Exoplanet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/c1/Anaximander.txt ../out/fb/c1/Anaximander.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/b3/Bernoulli_number.txt ../out/fc/b3/Bernoulli_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/70/August_6.txt ../out/fd/70/August_6.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/08/Abkhasia.txt ../out/fe/08/Abkhasia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/d0/Electronegativity.txt ../out/fe/d0/Electronegativity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/45/Coin.txt ../out/ff/45/Coin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/bf/Bobby_Charlton.txt ../out/ff/bf/Bobby_Charlton.xml
