php ./wiki2xml/php/wiki2xml_command.php ../out/00/40/Chipmunk.txt ../out/00/40/Chipmunk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/04/Barbara_Olson.txt ../out/01/04/Barbara_Olson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/b7/Cryptography%2FKey.txt ../out/01/b7/Cryptography%2FKey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/41/D._B._Cooper.txt ../out/02/41/D._B._Cooper.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/0c/Aberdeenshire.txt ../out/03/0c/Aberdeenshire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/b1/Amyntas_III_of_Macedon.txt ../out/03/b1/Amyntas_III_of_Macedon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/4c/Arachnophobia.txt ../out/04/4c/Arachnophobia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/c9/Anglicanism.txt ../out/04/c9/Anglicanism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/56/Creutzfeldt%E2%80%93Jakob_disease.txt ../out/05/56/Creutzfeldt%E2%80%93Jakob_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/d6/Boron.txt ../out/05/d6/Boron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/83/Conjunction_elimination_%28version_2%29.txt ../out/06/83/Conjunction_elimination_%28version_2%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/25/Economy_of_Canada.txt ../out/07/25/Economy_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/f7/CD_%28disambiguation%29.txt ../out/07/f7/CD_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/96/Andronikos_III_Palaiologos.txt ../out/08/96/Andronikos_III_Palaiologos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/34/Ardal_O%27Hanlon.txt ../out/09/34/Ardal_O%27Hanlon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/0a/Logical_disjunction.txt ../out/0a/0a/Logical_disjunction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/97/Edmund_Stoiber.txt ../out/0a/97/Edmund_Stoiber.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/3a/Blue_crane.txt ../out/0b/3a/Blue_crane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/a8/National_League_Championship_Series.txt ../out/0b/a8/National_League_Championship_Series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/4c/Donald_Knuth.txt ../out/0c/4c/Donald_Knuth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/12/Capability_Maturity_Model.txt ../out/0d/12/Capability_Maturity_Model.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/c5/Military_of_Ivory_Coast.txt ../out/0d/c5/Military_of_Ivory_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/5a/Aristide_Maillol.txt ../out/0e/5a/Aristide_Maillol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/31/Adolphe_Sax.txt ../out/0f/31/Adolphe_Sax.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/dc/Foreign_relations_of_Cape_Verde.txt ../out/0f/dc/Foreign_relations_of_Cape_Verde.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/f5/Benedict_of_Nursia.txt ../out/10/f5/Benedict_of_Nursia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/8f/King_David_%28disambiguation%29.txt ../out/11/8f/King_David_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/3b/Alphonso_XIII.txt ../out/12/3b/Alphonso_XIII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/ba/Crystallographic_defect.txt ../out/12/ba/Crystallographic_defect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/69/Amblypoda.txt ../out/13/69/Amblypoda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/d0/Cult_film.txt ../out/13/d0/Cult_film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/c4/Clement_Martyn_Doke.txt ../out/14/c4/Clement_Martyn_Doke.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/33/Alessandro_Volta.txt ../out/15/33/Alessandro_Volta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/f6/Battle_of_%C5%9Awiecino.txt ../out/15/f6/Battle_of_%C5%9Awiecino.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/9f/Politics_of_Ivory_Coast.txt ../out/16/9f/Politics_of_Ivory_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/6e/Abandonment_of_an_action.txt ../out/17/6e/Abandonment_of_an_action.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/1e/Anoa.txt ../out/18/1e/Anoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/9f/Complexity_theory.txt ../out/18/9f/Complexity_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/3f/Ansbach.txt ../out/19/3f/Ansbach.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/bf/Boxing.txt ../out/19/bf/Boxing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/66/Cell.txt ../out/1a/66/Cell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/ef/Alphonso_VIII_of_Spain.txt ../out/1a/ef/Alphonso_VIII_of_Spain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/87/American_Quarter_Horse.txt ../out/1b/87/American_Quarter_Horse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/fe/Analog_Brothers.txt ../out/1b/fe/Analog_Brothers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/80/Botany.txt ../out/1c/80/Botany.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/07/Demographics_of_the_British_Indian_Ocean_Territory.txt ../out/1d/07/Demographics_of_the_British_Indian_Ocean_Territory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/ce/Anastasius.txt ../out/1d/ce/Anastasius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/53/AW.txt ../out/1e/53/AW.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/e2/Chaosium.txt ../out/1e/e2/Chaosium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/d5/BBC_Red_Button.txt ../out/1f/d5/BBC_Red_Button.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/81/Alexandrite.txt ../out/20/81/Alexandrite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/18/Benjamin_Lee_Whorf.txt ../out/21/18/Benjamin_Lee_Whorf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/f1/Automated_Alice%2FX.txt ../out/21/f1/Automated_Alice%2FX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/a2/Demographics_of_Burundi.txt ../out/22/a2/Demographics_of_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/4b/ActionFilm.txt ../out/23/4b/ActionFilm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/16/Borzoi.txt ../out/24/16/Borzoi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/a2/Christianity_and_homosexuality.txt ../out/24/a2/Christianity_and_homosexuality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/5c/Disc_golf.txt ../out/25/5c/Disc_golf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/12/Aeacus.txt ../out/26/12/Aeacus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/a0/Causant%C3%ADn_mac_Cin%C3%A1eda.txt ../out/26/a0/Causant%C3%ADn_mac_Cin%C3%A1eda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/4a/Apollo_15.txt ../out/27/4a/Apollo_15.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/f6/April_28.txt ../out/27/f6/April_28.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/88/Baltic_Sea%2FOdra.txt ../out/28/88/Baltic_Sea%2FOdra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/38/Ariel_Sharon.txt ../out/29/38/Ariel_Sharon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/f7/August_25.txt ../out/29/f7/August_25.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/74/%C3%86lle_of_Sussex.txt ../out/2a/74/%C3%86lle_of_Sussex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/57/AfricanAmericanPeople.txt ../out/2b/57/AfricanAmericanPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/da/AyersMusicPublishingCompany.txt ../out/2b/da/AyersMusicPublishingCompany.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/7d/%C3%86thelberht_of_Kent.txt ../out/2c/7d/%C3%86thelberht_of_Kent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/1f/Danny_Elfman.txt ../out/2d/1f/Danny_Elfman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/df/Amiga.txt ../out/2d/df/Amiga.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/8c/Boeing_B-17_Flying_Fortress.txt ../out/2e/8c/Boeing_B-17_Flying_Fortress.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/3f/Bob_Jones_University.txt ../out/2f/3f/Bob_Jones_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/3d/Alexanderplatz.txt ../out/30/3d/Alexanderplatz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/ef/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FS.txt ../out/30/ef/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/91/April_9.txt ../out/31/91/April_9.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/8a/Atomic_bomb.txt ../out/32/8a/Atomic_bomb.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/09/Ackermann_function.txt ../out/33/09/Ackermann_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/fd/DMA.txt ../out/33/fd/DMA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/c9/Central_American_Court_of_Justice.txt ../out/34/c9/Central_American_Court_of_Justice.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/63/Cluster_sampling.txt ../out/35/63/Cluster_sampling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/09/Euphemism.txt ../out/36/09/Euphemism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/ea/American_Civil_Liberties_Union.txt ../out/36/ea/American_Civil_Liberties_Union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/62/Abandonment_of_railways.txt ../out/37/62/Abandonment_of_railways.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/e1/Data_structure.txt ../out/37/e1/Data_structure.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/45/Anthropoides_paradisia.txt ../out/38/45/Anthropoides_paradisia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/58/Bruno_of_Querfurt.txt ../out/39/58/Bruno_of_Querfurt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/f3/America_Islands.txt ../out/39/f3/America_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/64/BiblE%2FAaron.txt ../out/3a/64/BiblE%2FAaron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/11/Dr._Strangelove.txt ../out/3b/11/Dr._Strangelove.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/85/Boston_Red_Sox.txt ../out/3b/85/Boston_Red_Sox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/ee/Balfour_Declaration.txt ../out/3b/ee/Balfour_Declaration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/bd/Ancient_civilization.txt ../out/3c/bd/Ancient_civilization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/54/Commentary.txt ../out/3d/54/Commentary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/04/Australian_Labor_Party.txt ../out/3e/04/Australian_Labor_Party.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/a3/Aegis.txt ../out/3e/a3/Aegis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/22/North_American_B-25_Mitchell.txt ../out/3f/22/North_American_B-25_Mitchell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/ab/Eug%C3%A8ne_Viollet-le-Duc.txt ../out/3f/ab/Eug%C3%A8ne_Viollet-le-Duc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/55/Mail_%28armour%29.txt ../out/40/55/Mail_%28armour%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/d8/Rail_transport_in_Great_Britain.txt ../out/40/d8/Rail_transport_in_Great_Britain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/aa/Charles_Sanders_Peirce.txt ../out/41/aa/Charles_Sanders_Peirce.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/f8/Bitter_ale.txt ../out/41/f8/Bitter_ale.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/77/Commodore_1570.txt ../out/42/77/Commodore_1570.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/32/Aberdare.txt ../out/43/32/Aberdare.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/b7/Cartesian_coordinates.txt ../out/43/b7/Cartesian_coordinates.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/74/Coded_orthogonal_frequency_division_modulation.txt ../out/44/74/Coded_orthogonal_frequency_division_modulation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/e5/Association_for_Computing_Machinery.txt ../out/44/e5/Association_for_Computing_Machinery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/95/Armed_Forces_of_Bosnia_and_Herzegovina.txt ../out/45/95/Armed_Forces_of_Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/36/Anthropology.txt ../out/46/36/Anthropology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/17/Epistle_of_Jude.txt ../out/47/17/Epistle_of_Jude.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/ac/Combination.txt ../out/47/ac/Combination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/83/Baseball_statistics.txt ../out/48/83/Baseball_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/15/Advanced_Chemistry.txt ../out/49/15/Advanced_Chemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/c3/Alphabet.txt ../out/49/c3/Alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/6b/Alcmene.txt ../out/4a/6b/Alcmene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/fb/Brian_De_Palma.txt ../out/4a/fb/Brian_De_Palma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/b4/Cordial.txt ../out/4b/b4/Cordial.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/2e/Christopher_Columbus.txt ../out/4c/2e/Christopher_Columbus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/c5/Eightfold_Path_%28policy_analysis%29.txt ../out/4c/c5/Eightfold_Path_%28policy_analysis%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/84/National_League_Division_Series.txt ../out/4d/84/National_League_Division_Series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/01/Computer_Film_Company.txt ../out/4e/01/Computer_Film_Company.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/b7/AsciiArt.txt ../out/4e/b7/AsciiArt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/3c/European_Community.txt ../out/4f/3c/European_Community.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/fc/Apple_II_series.txt ../out/4f/fc/Apple_II_series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/c2/Ada_Byron%27s_notes_on_the_analytical_engine.txt ../out/50/c2/Ada_Byron%27s_notes_on_the_analytical_engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/72/Charlie_Chaplin.txt ../out/51/72/Charlie_Chaplin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/02/ERP.txt ../out/52/02/ERP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/96/Community_emergency_response_team.txt ../out/52/96/Community_emergency_response_team.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/44/Book_of_Joel.txt ../out/53/44/Book_of_Joel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/dd/Colossus_computer.txt ../out/53/dd/Colossus_computer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/6a/AZ.txt ../out/54/6a/AZ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/fb/Arthur_St._Clair.txt ../out/54/fb/Arthur_St._Clair.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/b2/Alcidamas.txt ../out/55/b2/Alcidamas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/6a/Amaranth.txt ../out/56/6a/Amaranth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/4e/Cola.txt ../out/57/4e/Cola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/27/Citizen_Kane.txt ../out/58/27/Citizen_Kane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/9c/Cro-hook.txt ../out/58/9c/Cro-hook.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/33/Curry.txt ../out/59/33/Curry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/d0/Carolyn_Beug.txt ../out/59/d0/Carolyn_Beug.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/70/Cyrus_II_of_Persia.txt ../out/5a/70/Cyrus_II_of_Persia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/de/Buddhist_philosophy.txt ../out/5a/de/Buddhist_philosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/83/CityBerlin.txt ../out/5b/83/CityBerlin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/3c/Bernardino_Ochino.txt ../out/5c/3c/Bernardino_Ochino.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/f9/Clavichord.txt ../out/5c/f9/Clavichord.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/e4/Adam_Carolla.txt ../out/5d/e4/Adam_Carolla.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/60/Autocorrelation.txt ../out/5e/60/Autocorrelation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/db/Alan_Jay_Lerner.txt ../out/5e/db/Alan_Jay_Lerner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/e1/Bucket_argument.txt ../out/5f/e1/Bucket_argument.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/77/B-25.txt ../out/60/77/B-25.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/28/Biconditional_elimination.txt ../out/61/28/Biconditional_elimination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/a3/Politics_of_American_Samoa.txt ../out/61/a3/Politics_of_American_Samoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/42/Alyattes_of_Lydia.txt ../out/62/42/Alyattes_of_Lydia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/3f/Eight-bar_blues.txt ../out/63/3f/Eight-bar_blues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/22/Ablative_case.txt ../out/64/22/Ablative_case.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/e3/Bitter.txt ../out/64/e3/Bitter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/63/Economy_of_Bosnia_and_Herzegovina.txt ../out/65/63/Economy_of_Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/e8/Being.txt ../out/65/e8/Being.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/54/British_thermal_unit.txt ../out/66/54/British_thermal_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/02/Convention_%28norm%29.txt ../out/67/02/Convention_%28norm%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/af/Enniskillen.txt ../out/67/af/Enniskillen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/2f/Computer_multitasking.txt ../out/68/2f/Computer_multitasking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/ed/Games_played.txt ../out/68/ed/Games_played.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/ab/Annales_School.txt ../out/69/ab/Annales_School.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/55/Angst.txt ../out/6a/55/Angst.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/dc/Self-propelled_anti-aircraft_weapon.txt ../out/6a/dc/Self-propelled_anti-aircraft_weapon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/82/A.D.txt ../out/6b/82/A.D.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/16/Belgium.txt ../out/6c/16/Belgium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/7d/Cross-stitch.txt ../out/6c/7d/Cross-stitch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/16/Cardinal.txt ../out/6d/16/Cardinal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/bc/Economy_of_Bouvet_Island.txt ../out/6d/bc/Economy_of_Bouvet_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/5f/Apollo_12.txt ../out/6e/5f/Apollo_12.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/d1/Conservatism.txt ../out/6e/d1/Conservatism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/62/Aberdeen_Bestiary.txt ../out/6f/62/Aberdeen_Bestiary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/40/ErnestHemingway%2FTheDownwardSpiral.txt ../out/70/40/ErnestHemingway%2FTheDownwardSpiral.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/f9/Complex_analysis.txt ../out/70/f9/Complex_analysis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/c0/The_Alan_Parsons_Project.txt ../out/71/c0/The_Alan_Parsons_Project.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/54/The_Church_of_Jesus_Christ_of_Latter-day_Saints.txt ../out/72/54/The_Church_of_Jesus_Christ_of_Latter-day_Saints.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/0f/Electric_Charge.txt ../out/73/0f/Electric_Charge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/ed/Alexander_Anderson_%28mathematician%29.txt ../out/73/ed/Alexander_Anderson_%28mathematician%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/5b/Excalibur.txt ../out/74/5b/Excalibur.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/af/Estimating_parameters.txt ../out/74/af/Estimating_parameters.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/71/Capella_%28disambiguation%29.txt ../out/75/71/Capella_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/2e/Violence_and_Redemption.txt ../out/76/2e/Violence_and_Redemption.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/c5/Aga_Khan_I.txt ../out/76/c5/Aga_Khan_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/74/Cobble_Hill_Tunnel.txt ../out/77/74/Cobble_Hill_Tunnel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/3d/Ballroom_dance.txt ../out/78/3d/Ballroom_dance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/c2/Apache_Software_Foundation.txt ../out/78/c2/Apache_Software_Foundation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/72/Planned_economy.txt ../out/79/72/Planned_economy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/e1/Cervical_mucus_method.txt ../out/79/e1/Cervical_mucus_method.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/7f/Beauty.txt ../out/7a/7f/Beauty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/d0/Equation_of_state.txt ../out/7a/d0/Equation_of_state.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/a5/Ai.txt ../out/7b/a5/Ai.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/44/Deuterocanonical_books.txt ../out/7c/44/Deuterocanonical_books.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/06/Economy_of_Armenia.txt ../out/7d/06/Economy_of_Armenia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/7c/Cardinal_numbers.txt ../out/7d/7c/Cardinal_numbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/3b/Compactification_%28mathematics%29.txt ../out/7e/3b/Compactification_%28mathematics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/e4/April_3.txt ../out/7e/e4/April_3.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/9b/Arizona_State_University.txt ../out/7f/9b/Arizona_State_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/04/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F9.txt ../out/80/04/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F9.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/7a/Coral_Sea_Islands%2FGeography.txt ../out/80/7a/Coral_Sea_Islands%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/28/E._P._Thompson_on_Luddites.txt ../out/81/28/E._P._Thompson_on_Luddites.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/d1/Balkan_Wars.txt ../out/81/d1/Balkan_Wars.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/a3/CSS_%28disambiguation%29.txt ../out/82/a3/CSS_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/6a/C%2A-algebra.txt ../out/83/6a/C%2A-algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/02/Eugene%2C_Oregon.txt ../out/84/02/Eugene%2C_Oregon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/ef/Alfonso_IV_of_Aragon.txt ../out/84/ef/Alfonso_IV_of_Aragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/75/Direct_realism.txt ../out/85/75/Direct_realism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/08/Bombadier.txt ../out/86/08/Bombadier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/ac/Belgium%2FTransnational_issues.txt ../out/86/ac/Belgium%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/46/AIM-7_Sparrow.txt ../out/87/46/AIM-7_Sparrow.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/0a/Arahant.txt ../out/88/0a/Arahant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/d2/Cyclic_AMP.txt ../out/88/d2/Cyclic_AMP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/6a/Foreign_relations_of_Brazil.txt ../out/89/6a/Foreign_relations_of_Brazil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/fe/AbensbergGermany.txt ../out/89/fe/AbensbergGermany.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/b4/Bar_Kokhba_%28album%29.txt ../out/8a/b4/Bar_Kokhba_%28album%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/6a/Captain_America.txt ../out/8b/6a/Captain_America.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/16/Abila.txt ../out/8c/16/Abila.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/a9/Codec.txt ../out/8c/a9/Codec.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/20/Erotica.txt ../out/8d/20/Erotica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/06/Wikipedia%3ABuilding_Wikipedia_membership%2FAbout.com.txt ../out/8e/06/Wikipedia%3ABuilding_Wikipedia_membership%2FAbout.com.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/c5/Discordian.txt ../out/8e/c5/Discordian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/7a/Axon.txt ../out/8f/7a/Axon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/2f/ABC.txt ../out/90/2f/ABC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/06/Cannibalism.txt ../out/91/06/Cannibalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/d5/Wikipedia%3AArchaeology_basic_topics.txt ../out/91/d5/Wikipedia%3AArchaeology_basic_topics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/bb/Axiology.txt ../out/92/bb/Axiology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/76/Abbey.txt ../out/93/76/Abbey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/0d/Abbotsford_House.txt ../out/94/0d/Abbotsford_House.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/1c/Military_of_Chad.txt ../out/95/1c/Military_of_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/8f/Slalom_skiing.txt ../out/95/8f/Slalom_skiing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/4e/Art_Deco.txt ../out/96/4e/Art_Deco.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/04/DefinitioN.txt ../out/97/04/DefinitioN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/82/Allen_Ginsberg.txt ../out/97/82/Allen_Ginsberg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/26/Corona_Borealis.txt ../out/98/26/Corona_Borealis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/78/CelticMusic.txt ../out/98/78/CelticMusic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/22/Air_Pollution.txt ../out/99/22/Air_Pollution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/a0/Carabiner.txt ../out/99/a0/Carabiner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/41/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FJ.txt ../out/9a/41/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FJ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/93/Cyberspace.txt ../out/9a/93/Cyberspace.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/5e/Diana_%28mythology%29.txt ../out/9b/5e/Diana_%28mythology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/f2/Appellate_procedure_in_the_United_States.txt ../out/9b/f2/Appellate_procedure_in_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/75/Agma.txt ../out/9c/75/Agma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/09/Artificial_intelligence.txt ../out/9d/09/Artificial_intelligence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/83/Demiurge.txt ../out/9d/83/Demiurge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/15/Census.txt ../out/9e/15/Census.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/1a/Politics_of_Dominica.txt ../out/9f/1a/Politics_of_Dominica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/d8/Ernest_Rutherford.txt ../out/9f/d8/Ernest_Rutherford.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/61/Anthroposophy.txt ../out/a0/61/Anthroposophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/30/CD-R.txt ../out/a1/30/CD-R.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/27/Conventional_warfare.txt ../out/a2/27/Conventional_warfare.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/c9/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FN.txt ../out/a2/c9/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/8c/Equatorial_Guinea.txt ../out/a3/8c/Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/25/Atlantis.txt ../out/a4/25/Atlantis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/cc/CryptographY.txt ../out/a4/cc/CryptographY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/45/Andronicus_of_Rhodes.txt ../out/a5/45/Andronicus_of_Rhodes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/ae/Brachycephalic.txt ../out/a5/ae/Brachycephalic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/6b/Abatement_in_litigation.txt ../out/a6/6b/Abatement_in_litigation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/05/Clipperton_Island%2FGovernment.txt ../out/a7/05/Clipperton_Island%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/cd/Abiotic_factors.txt ../out/a7/cd/Abiotic_factors.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/98/Dewar_flask.txt ../out/a8/98/Dewar_flask.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/68/Chadic_languages.txt ../out/a9/68/Chadic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/29/Central_African_Republic.txt ../out/aa/29/Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/a4/Abduction.txt ../out/aa/a4/Abduction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/28/Cyber_sex.txt ../out/ab/28/Cyber_sex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/bf/Transport_in_the_Cayman_Islands.txt ../out/ab/bf/Transport_in_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/5a/Foreign_relations_of_Colombia.txt ../out/ac/5a/Foreign_relations_of_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/be/Aaliyah.txt ../out/ac/be/Aaliyah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/6d/Foreign_relations_of_Eritrea.txt ../out/ad/6d/Foreign_relations_of_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/1f/Afghanistan%2FMilitary.txt ../out/ae/1f/Afghanistan%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/bb/CountriesB.txt ../out/ae/bb/CountriesB.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/5e/Aardwolf.txt ../out/af/5e/Aardwolf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/ed/A.S._Roma.txt ../out/af/ed/A.S._Roma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/58/American_bias.txt ../out/b0/58/American_bias.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/2d/Beaumarchais.txt ../out/b1/2d/Beaumarchais.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/b4/Conrad_II_%28disambiguation%29.txt ../out/b1/b4/Conrad_II_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/25/Arizona_Diamondbacks.txt ../out/b2/25/Arizona_Diamondbacks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/39/Cracking.txt ../out/b3/39/Cracking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/e1/Carat_%28mass%29.txt ../out/b3/e1/Carat_%28mass%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/8d/Czech_language.txt ../out/b4/8d/Czech_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/ca/BeBox.txt ../out/b4/ca/BeBox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/32/Doctor_%28title%29.txt ../out/b5/32/Doctor_%28title%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/b3/Batavi_%28Germanic_tribe%29.txt ../out/b5/b3/Batavi_%28Germanic_tribe%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/4c/Egypt%2FHistory.txt ../out/b6/4c/Egypt%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/61/AmoeboidTaxa.txt ../out/b7/61/AmoeboidTaxa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/c9/Diatonic_scale.txt ../out/b7/c9/Diatonic_scale.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/65/ECHELON.txt ../out/b8/65/ECHELON.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/20/Daniel_Ortega_Saavedra.txt ../out/b9/20/Daniel_Ortega_Saavedra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/e3/Abraxas.txt ../out/b9/e3/Abraxas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/91/Choshu.txt ../out/ba/91/Choshu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/32/Blackwood_convention.txt ../out/bb/32/Blackwood_convention.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/c6/Digital_Private_Network_Signalling_System.txt ../out/bb/c6/Digital_Private_Network_Signalling_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/59/Computational_linguistics.txt ../out/bc/59/Computational_linguistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/e8/Cassiopeia.txt ../out/bc/e8/Cassiopeia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/b6/Arc_de_Triomphe.txt ../out/bd/b6/Arc_de_Triomphe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/75/Alex_Lifeson.txt ../out/be/75/Alex_Lifeson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/2e/Bermuda_Triangle.txt ../out/bf/2e/Bermuda_Triangle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/d8/Lists_of_universities_and_colleges.txt ../out/bf/d8/Lists_of_universities_and_colleges.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/95/Military_of_the_Comoros.txt ../out/c0/95/Military_of_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/54/Andriscus.txt ../out/c1/54/Andriscus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/ee/Blot.txt ../out/c1/ee/Blot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/c6/Coalition_government.txt ../out/c2/c6/Coalition_government.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/96/Crouching_Tiger%2C_Hidden_Dragon.txt ../out/c3/96/Crouching_Tiger%2C_Hidden_Dragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/17/Europa_Island%2FMilitary.txt ../out/c4/17/Europa_Island%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/96/List_of_classical_music_competitions.txt ../out/c4/96/List_of_classical_music_competitions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/80/Computer-generated_music.txt ../out/c5/80/Computer-generated_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/25/Definition_Of_Music.txt ../out/c6/25/Definition_Of_Music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/04/Constantine_II.txt ../out/c7/04/Constantine_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/a2/Branchiopoda.txt ../out/c7/a2/Branchiopoda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/6b/Adam_Smith.txt ../out/c8/6b/Adam_Smith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/3e/Arthur_Jensen.txt ../out/c9/3e/Arthur_Jensen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/b5/Automated_Alice%2FXII.txt ../out/c9/b5/Automated_Alice%2FXII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/3b/Argentine_cuisine.txt ../out/ca/3b/Argentine_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/17/ErnestHemingway%2FViolenceandRedemption.txt ../out/cb/17/ErnestHemingway%2FViolenceandRedemption.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/b8/Belle_and_Sebastian.txt ../out/cb/b8/Belle_and_Sebastian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/b6/Churchs_thesis.txt ../out/cc/b6/Churchs_thesis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/33/Deng_Xiaoping.txt ../out/cd/33/Deng_Xiaoping.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/be/Archimedes_screw.txt ../out/cd/be/Archimedes_screw.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/b3/Ahab.txt ../out/ce/b3/Ahab.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/4e/Alternative_algebra.txt ../out/cf/4e/Alternative_algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/fb/Cryogenics.txt ../out/cf/fb/Cryogenics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/ef/Archimedes.txt ../out/d0/ef/Archimedes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/5b/Collection.txt ../out/d1/5b/Collection.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/4b/Aegospotami.txt ../out/d2/4b/Aegospotami.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/c8/Arians.txt ../out/d2/c8/Arians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/77/Bulletin_board_system.txt ../out/d3/77/Bulletin_board_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/13/Colossae.txt ../out/d4/13/Colossae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/e2/Burn_card.txt ../out/d4/e2/Burn_card.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/8b/Bengal.txt ../out/d5/8b/Bengal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/35/Andrew_Jackson%2FFirst_Inaugural_Address.txt ../out/d6/35/Andrew_Jackson%2FFirst_Inaugural_Address.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/c5/Comets.txt ../out/d6/c5/Comets.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/45/Easter_egg.txt ../out/d7/45/Easter_egg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/11/Erasmus_Darwin.txt ../out/d8/11/Erasmus_Darwin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/e3/Charles_Lyell.txt ../out/d8/e3/Charles_Lyell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/8b/BSE.txt ../out/d9/8b/BSE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/07/Episcopi_vagantes.txt ../out/da/07/Episcopi_vagantes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/c1/Cheese%2FGruyere.txt ../out/da/c1/Cheese%2FGruyere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/32/Amplifier_figures_of_merit.txt ../out/db/32/Amplifier_figures_of_merit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/09/East_River.txt ../out/dc/09/East_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/8b/Des_Moines.txt ../out/dc/8b/Des_Moines.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/37/Canadian_Shield.txt ../out/dd/37/Canadian_Shield.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/c3/Bar.txt ../out/dd/c3/Bar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/7a/Education.txt ../out/de/7a/Education.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/1d/Cancer_Coast.txt ../out/df/1d/Cancer_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/00/Borsuk%E2%80%93Ulam_theorem.txt ../out/e0/00/Borsuk%E2%80%93Ulam_theorem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/b1/Armenian_language.txt ../out/e0/b1/Armenian_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/68/Colossians.txt ../out/e1/68/Colossians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/19/Foreign_relations_of_El_Salvador.txt ../out/e2/19/Foreign_relations_of_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/df/Bison.txt ../out/e2/df/Bison.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/61/List_of_Olympic_medalists_in_biathlon.txt ../out/e3/61/List_of_Olympic_medalists_in_biathlon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/0c/Alexandria%2C_Indiana.txt ../out/e4/0c/Alexandria%2C_Indiana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/e0/Book_of_Ruth.txt ../out/e4/e0/Book_of_Ruth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/66/Boston_Corbett.txt ../out/e5/66/Boston_Corbett.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/fc/London_Docklands.txt ../out/e5/fc/London_Docklands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/a4/Aliphatic_compound.txt ../out/e6/a4/Aliphatic_compound.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/8e/Khmer_language.txt ../out/e7/8e/Khmer_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/2b/Edentata.txt ../out/e8/2b/Edentata.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/db/Canadian_Constitution_Act.txt ../out/e8/db/Canadian_Constitution_Act.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/55/Distance_function.txt ../out/e9/55/Distance_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/c8/Basel_Convention.txt ../out/e9/c8/Basel_Convention.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/50/Defendant.txt ../out/ea/50/Defendant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/0c/Chain_rule.txt ../out/eb/0c/Chain_rule.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/c8/Ballpoint_pen.txt ../out/eb/c8/Ballpoint_pen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/80/EncycloPedia.txt ../out/ec/80/EncycloPedia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/6a/Dimona.txt ../out/ed/6a/Dimona.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/d8/On-base_percentage.txt ../out/ed/d8/On-base_percentage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/80/History_of_the_Comoros.txt ../out/ee/80/History_of_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/26/Asimov_%28disambiguation%29.txt ../out/ef/26/Asimov_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/a1/Apollo_9.txt ../out/ef/a1/Apollo_9.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/4a/Demographics_of_the_Democratic_Republic_of_the_Congo.txt ../out/f0/4a/Demographics_of_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/00/Bits.txt ../out/f1/00/Bits.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/e7/Buffalo%2C_New_York.txt ../out/f1/e7/Buffalo%2C_New_York.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/e6/EU.txt ../out/f2/e6/EU.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/a6/Britannica.txt ../out/f3/a6/Britannica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/74/Europa_Island%2FTransnational_issues.txt ../out/f4/74/Europa_Island%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/3c/Dean_Koontz.txt ../out/f5/3c/Dean_Koontz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/e2/Alarums_and_Excursions.txt ../out/f5/e2/Alarums_and_Excursions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/af/Buckingham_Palace.txt ../out/f6/af/Buckingham_Palace.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/1f/Bohdan_Khmelnytsky.txt ../out/f7/1f/Bohdan_Khmelnytsky.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/b1/Economy_%28disambiguation%29.txt ../out/f7/b1/Economy_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/92/Cist.txt ../out/f8/92/Cist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/fd/Alphonso_I_of_Spain.txt ../out/f8/fd/Alphonso_I_of_Spain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/79/Angela_Vincent.txt ../out/f9/79/Angela_Vincent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/0b/CuteFTP.txt ../out/fa/0b/CuteFTP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/a9/Aeclanum.txt ../out/fa/a9/Aeclanum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/4c/Carlos_Valderrama.txt ../out/fb/4c/Carlos_Valderrama.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/f0/Albert_Camus.txt ../out/fb/f0/Albert_Camus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/f8/History_of_Cambodia.txt ../out/fc/f8/History_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/97/Transport_in_the_Cook_Islands.txt ../out/fd/97/Transport_in_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/41/Amethyst.txt ../out/fe/41/Amethyst.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/ec/Anti-ballistic_missile.txt ../out/fe/ec/Anti-ballistic_missile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/6d/Dwight_Schultz.txt ../out/ff/6d/Dwight_Schultz.xml
