php ./wiki2xml/php/wiki2xml_command.php ../out/00/d8/List_of_cartoonists.txt ../out/00/d8/List_of_cartoonists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/7b/Chernobyl.txt ../out/01/7b/Chernobyl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/02/Computer_display%2FCRT.txt ../out/02/02/Computer_display%2FCRT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/c6/Alexius.txt ../out/02/c6/Alexius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/61/Daniel_C._Dennett.txt ../out/03/61/Daniel_C._Dennett.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/f6/Delroy_Lindo.txt ../out/03/f6/Delroy_Lindo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/87/CountriesL.txt ../out/04/87/CountriesL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/2c/Descartes.txt ../out/05/2c/Descartes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/ae/Discrete_probability_distribution.txt ../out/05/ae/Discrete_probability_distribution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/2d/Deus_Ex.txt ../out/06/2d/Deus_Ex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/ec/Cardinals.txt ../out/06/ec/Cardinals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/9f/Baroque.txt ../out/07/9f/Baroque.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/67/Celebrity.txt ../out/08/67/Celebrity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/e3/CharlestoN.txt ../out/08/e3/CharlestoN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/8e/Alkali.txt ../out/09/8e/Alkali.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/7d/Geography_of_Costa_Rica.txt ../out/0a/7d/Geography_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/db/Constantin_von_Tischendorf.txt ../out/0a/db/Constantin_von_Tischendorf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/90/Digraph.txt ../out/0b/90/Digraph.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/09/Cocos_%28Keeling%29_Islands.txt ../out/0c/09/Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/c0/Branch_Davidians.txt ../out/0c/c0/Branch_Davidians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/79/August_10.txt ../out/0d/79/August_10.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/32/Clanking_Replicator.txt ../out/0e/32/Clanking_Replicator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/c8/Cryptanalysis.txt ../out/0e/c8/Cryptanalysis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/72/EduCation.txt ../out/0f/72/EduCation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/71/Crash_%28J._G._Ballard_novel%29.txt ../out/10/71/Crash_%28J._G._Ballard_novel%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/41/Australian_Broadcasting_Corporation.txt ../out/11/41/Australian_Broadcasting_Corporation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/cb/CSS_Virginia.txt ../out/11/cb/CSS_Virginia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/74/Doubravka_of_Bohemia.txt ../out/12/74/Doubravka_of_Bohemia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/1e/Dry_beer.txt ../out/13/1e/Dry_beer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/9c/Dhole.txt ../out/13/9c/Dhole.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/72/Digital_data.txt ../out/14/72/Digital_data.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/12/CRT.txt ../out/15/12/CRT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/b5/Eigen_Vectors.txt ../out/15/b5/Eigen_Vectors.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/5b/Boleslaw_III.txt ../out/16/5b/Boleslaw_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/0d/Aborigines.txt ../out/17/0d/Aborigines.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/e1/Cyc.txt ../out/17/e1/Cyc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/67/Abd-el-Aziz_IV.txt ../out/18/67/Abd-el-Aziz_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/03/Abelian_group.txt ../out/19/03/Abelian_group.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/86/Birmingham_Small_Arms_Company.txt ../out/19/86/Birmingham_Small_Arms_Company.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/10/Clipperton_Island%2FCommunications.txt ../out/1a/10/Clipperton_Island%2FCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/a9/Geography_of_Ecuador.txt ../out/1a/a9/Geography_of_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/24/Venezuelan_Beaver_cheese.txt ../out/1b/24/Venezuelan_Beaver_cheese.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/ce/Blue_Jam.txt ../out/1b/ce/Blue_Jam.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/46/Anisotropy.txt ../out/1c/46/Anisotropy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/dd/Diego_de_Almagro.txt ../out/1c/dd/Diego_de_Almagro.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/59/AbiWord.txt ../out/1d/59/AbiWord.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/09/Cerebrospinal_fluid.txt ../out/1e/09/Cerebrospinal_fluid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/a2/Euler_-_Maclaurin_formula.txt ../out/1e/a2/Euler_-_Maclaurin_formula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/97/Euler%E2%80%93Maclaurin_formula.txt ../out/1f/97/Euler%E2%80%93Maclaurin_formula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/3e/Abbahu.txt ../out/20/3e/Abbahu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/ec/Bacterial_conjugation.txt ../out/20/ec/Bacterial_conjugation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/94/Carbonate.txt ../out/21/94/Carbonate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/6d/Churches_Uniting_in_Christ.txt ../out/22/6d/Churches_Uniting_in_Christ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/06/Amasis_I.txt ../out/23/06/Amasis_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/bd/Book_of_Haggai.txt ../out/23/bd/Book_of_Haggai.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/53/Disaccharide.txt ../out/24/53/Disaccharide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/0e/Multimedia_compression.txt ../out/25/0e/Multimedia_compression.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/d1/Euphoria_%28programming_language%29.txt ../out/25/d1/Euphoria_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/62/Dharma.txt ../out/26/62/Dharma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/07/Blu-Tack.txt ../out/27/07/Blu-Tack.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/b1/Dill.txt ../out/27/b1/Dill.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/59/Amygdalin.txt ../out/28/59/Amygdalin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/ca/Athlon.txt ../out/28/ca/Athlon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/88/Burma%2FGovernment.txt ../out/29/88/Burma%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/35/Bamberg.txt ../out/2a/35/Bamberg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/1d/Esther.txt ../out/2b/1d/Esther.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/83/Economy_of_Ecuador.txt ../out/2b/83/Economy_of_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/46/Asynchronous_communication.txt ../out/2c/46/Asynchronous_communication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/c8/Beastie_Boys.txt ../out/2c/c8/Beastie_Boys.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/9c/Politics_of_the_Czech_Republic.txt ../out/2d/9c/Politics_of_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/3b/Clown.txt ../out/2e/3b/Clown.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/09/AfghanistanGeography.txt ../out/2f/09/AfghanistanGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/c0/Continuity_property.txt ../out/2f/c0/Continuity_property.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/b5/Autpert_Ambrose.txt ../out/30/b5/Autpert_Ambrose.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/36/Military_of_Bassas_da_India.txt ../out/31/36/Military_of_Bassas_da_India.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/1e/A._I..txt ../out/32/1e/A._I..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/dd/American_Civil_War.txt ../out/32/dd/American_Civil_War.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/6f/Entertainment.txt ../out/33/6f/Entertainment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/85/Cornwall.txt ../out/34/85/Cornwall.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/f4/European_Federation_of_Green_Parties.txt ../out/34/f4/European_Federation_of_Green_Parties.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/b8/Endosymbiont.txt ../out/35/b8/Endosymbiont.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/7d/Dalhousie_University.txt ../out/36/7d/Dalhousie_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/44/Alcohol.txt ../out/37/44/Alcohol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/b9/Churnsike_Lodge.txt ../out/37/b9/Churnsike_Lodge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/17/Book_of_Proverbs.txt ../out/38/17/Book_of_Proverbs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/c7/Copernicus.txt ../out/38/c7/Copernicus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/ab/DSM-IV-TR.txt ../out/39/ab/DSM-IV-TR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/42/April_15.txt ../out/3a/42/April_15.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/b3/Extint_countries.txt ../out/3a/b3/Extint_countries.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/52/Cecil_B._Demille.txt ../out/3b/52/Cecil_B._Demille.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/c0/Alameda%2C_California.txt ../out/3b/c0/Alameda%2C_California.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/66/Foreign_relations_of_Brunei.txt ../out/3c/66/Foreign_relations_of_Brunei.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/0a/Da_capo.txt ../out/3d/0a/Da_capo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/ad/List_of_animated_television_series.txt ../out/3d/ad/List_of_animated_television_series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/7a/Armed_Forces_of_Belarus.txt ../out/3e/7a/Armed_Forces_of_Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/ed/Charge-coupled_device.txt ../out/3e/ed/Charge-coupled_device.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/45/CamelCase.txt ../out/3f/45/CamelCase.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/01/Cortez.txt ../out/40/01/Cortez.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/be/Apogee.txt ../out/40/be/Apogee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/70/Astrology.txt ../out/41/70/Astrology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/d4/Cook_Islands%2FMilitary.txt ../out/41/d4/Cook_Islands%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/34/Comoros.txt ../out/42/34/Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/f0/Evolution.txt ../out/42/f0/Evolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/85/RDX.txt ../out/43/85/RDX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/32/Cirth.txt ../out/44/32/Cirth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/98/Battle_of_Schwetz.txt ../out/44/98/Battle_of_Schwetz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/49/Bar%C4%B1%C5%9F_Man%C3%A7o.txt ../out/45/49/Bar%C4%B1%C5%9F_Man%C3%A7o.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/04/Davenport%2C_Iowa.txt ../out/46/04/Davenport%2C_Iowa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/ad/Ealdred_%28archbishop_of_York%29.txt ../out/46/ad/Ealdred_%28archbishop_of_York%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/74/Augustin-Jean_Fresnel.txt ../out/47/74/Augustin-Jean_Fresnel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/19/Chinese_numerals.txt ../out/48/19/Chinese_numerals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/e8/Cryonics.txt ../out/48/e8/Cryonics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/8f/Bernoulli%27s_inequality.txt ../out/49/8f/Bernoulli%27s_inequality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/1a/Abiathar.txt ../out/4a/1a/Abiathar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/ba/Ban_on_assault_rifles.txt ../out/4a/ba/Ban_on_assault_rifles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/4e/Advanced_Mobile_Phone_System.txt ../out/4b/4e/Advanced_Mobile_Phone_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/f8/Cardinal_%28Catholicism%29.txt ../out/4b/f8/Cardinal_%28Catholicism%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/77/Boiling_point.txt ../out/4c/77/Boiling_point.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/4b/Eliezer_S._Yudkowsky.txt ../out/4d/4b/Eliezer_S._Yudkowsky.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/c6/December_12.txt ../out/4d/c6/December_12.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/61/Foreign_relations_of_Costa_Rica.txt ../out/4e/61/Foreign_relations_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/ee/Emission_line.txt ../out/4e/ee/Emission_line.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/bb/Active_Directory.txt ../out/4f/bb/Active_Directory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/65/Dartmouth_College_case.txt ../out/50/65/Dartmouth_College_case.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/16/American_Airlines_flight_11.txt ../out/51/16/American_Airlines_flight_11.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/a1/Telecommunications_in_Chad.txt ../out/51/a1/Telecommunications_in_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/6b/Charles_F._Hockett.txt ../out/52/6b/Charles_F._Hockett.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/01/Delphi_programming_language.txt ../out/53/01/Delphi_programming_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/a5/Abracadabra.txt ../out/53/a5/Abracadabra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/27/Alexandrists.txt ../out/54/27/Alexandrists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/a6/Apple_III.txt ../out/54/a6/Apple_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/73/ActressesS.txt ../out/55/73/ActressesS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/0d/Countable_set.txt ../out/56/0d/Countable_set.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/fe/Albino.txt ../out/56/fe/Albino.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/ae/Definition_of_music.txt ../out/57/ae/Definition_of_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/46/Antarctic_Circumpolar_Current.txt ../out/58/46/Antarctic_Circumpolar_Current.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/04/College_Football.txt ../out/59/04/College_Football.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/99/Broadway_%28Manhattan%29.txt ../out/59/99/Broadway_%28Manhattan%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/36/Antinomy.txt ../out/5a/36/Antinomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/be/Dalai_Lama.txt ../out/5a/be/Dalai_Lama.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/5d/Base_on_balls.txt ../out/5b/5d/Base_on_balls.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/e2/Durrani_Empire.txt ../out/5b/e2/Durrani_Empire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/a9/CountrY.txt ../out/5c/a9/CountrY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/5c/Politics_of_Burundi.txt ../out/5d/5c/Politics_of_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/36/Automated_Alice%2FI.txt ../out/5e/36/Automated_Alice%2FI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/ab/Alexander_I.txt ../out/5e/ab/Alexander_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/6f/Benoit_B._Mandelbrot.txt ../out/5f/6f/Benoit_B._Mandelbrot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/1f/Alexey_Pajitnov.txt ../out/60/1f/Alexey_Pajitnov.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/d9/Ericaceae.txt ../out/60/d9/Ericaceae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/76/Appalachian_Dulcimer.txt ../out/61/76/Appalachian_Dulcimer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/0f/AlbaniaCommunications.txt ../out/62/0f/AlbaniaCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/dd/Anton_Diabelli.txt ../out/62/dd/Anton_Diabelli.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/bf/CultFilm.txt ../out/63/bf/CultFilm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/a8/Car_%28disambiguation%29.txt ../out/64/a8/Car_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/24/British_National_Party.txt ../out/65/24/British_National_Party.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/9d/Politics_of_the_Comoros.txt ../out/65/9d/Politics_of_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/18/Diet.txt ../out/66/18/Diet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/b8/Abac%C3%A1.txt ../out/66/b8/Abac%C3%A1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/48/Cultural_movement.txt ../out/67/48/Cultural_movement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/fd/Band.txt ../out/67/fd/Band.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/88/Eric_Raymond_%28disambiguation%29.txt ../out/68/88/Eric_Raymond_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/5f/Amazonite.txt ../out/69/5f/Amazonite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/1c/Topics_of_note_in_Atlas_Shrugged.txt ../out/6a/1c/Topics_of_note_in_Atlas_Shrugged.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/9e/Doublespeak.txt ../out/6a/9e/Doublespeak.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/0e/Avery_Hopwood.txt ../out/6b/0e/Avery_Hopwood.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/c5/Transport_in_Djibouti.txt ../out/6b/c5/Transport_in_Djibouti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/4b/EigenVectors.txt ../out/6c/4b/EigenVectors.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/dc/International_Atomic_Time.txt ../out/6c/dc/International_Atomic_Time.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/85/Astronomical_unit.txt ../out/6d/85/Astronomical_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/11/District_of_Ajmere.txt ../out/6e/11/District_of_Ajmere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/a4/Chocolate.txt ../out/6e/a4/Chocolate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/15/Dardanelles.txt ../out/6f/15/Dardanelles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/ec/Andrew_S._Tanenbaum.txt ../out/6f/ec/Andrew_S._Tanenbaum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/ac/Bill_Walsh_%28American_football_coach%29.txt ../out/70/ac/Bill_Walsh_%28American_football_coach%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/82/Book_of_Lamentations.txt ../out/71/82/Book_of_Lamentations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/19/Cabo_Verdean_Armed_Forces.txt ../out/72/19/Cabo_Verdean_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/97/Commodore.txt ../out/72/97/Commodore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/7e/Critical_philosophy.txt ../out/73/7e/Critical_philosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/27/Awk.txt ../out/74/27/Awk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/80/Alder.txt ../out/74/80/Alder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/3a/Computer_Vision.txt ../out/75/3a/Computer_Vision.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/de/Coronary_artery_disease.txt ../out/75/de/Coronary_artery_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/93/Baltic_languages.txt ../out/76/93/Baltic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/28/Civilian_Conservation_Corps.txt ../out/77/28/Civilian_Conservation_Corps.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/d5/Bill_Schelter.txt ../out/77/d5/Bill_Schelter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/b0/Amateur.txt ../out/78/b0/Amateur.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/02/Church_of_Christ%2C_Scientist.txt ../out/79/02/Church_of_Christ%2C_Scientist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/b4/Abhorrers.txt ../out/79/b4/Abhorrers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/56/Calendar_date.txt ../out/7a/56/Calendar_date.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/a2/Delft.txt ../out/7a/a2/Delft.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/40/Breast_reconstruction.txt ../out/7b/40/Breast_reconstruction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/fc/Cassandra.txt ../out/7b/fc/Cassandra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/cd/Desmond_Morris.txt ../out/7c/cd/Desmond_Morris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/3d/Daphne_Duck.txt ../out/7d/3d/Daphne_Duck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/f1/Christian_of_Oliva.txt ../out/7d/f1/Christian_of_Oliva.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/77/Dr._Doom.txt ../out/7e/77/Dr._Doom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/37/Argument_%28disambiguation%29.txt ../out/7f/37/Argument_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/ce/David_Rice_Atchison.txt ../out/7f/ce/David_Rice_Atchison.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/35/Daniel_Jones_%28phonetician%29.txt ../out/80/35/Daniel_Jones_%28phonetician%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/c5/Chaim_Topol.txt ../out/80/c5/Chaim_Topol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/86/Antoine_de_Saint-Exupery.txt ../out/81/86/Antoine_de_Saint-Exupery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/33/December.txt ../out/82/33/December.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/28/Damon_Runyon.txt ../out/83/28/Damon_Runyon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/b0/MessagePad.txt ../out/83/b0/MessagePad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/99/Foreign_relations_of_Ethiopia.txt ../out/84/99/Foreign_relations_of_Ethiopia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/41/BoMis.txt ../out/85/41/BoMis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/ac/Argentina%2FForeign_relations.txt ../out/85/ac/Argentina%2FForeign_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/58/Armour.txt ../out/86/58/Armour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/ef/ConLang.txt ../out/86/ef/ConLang.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/ac/Centaurus.txt ../out/87/ac/Centaurus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/88/Dialect.txt ../out/88/88/Dialect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/33/Dark_matter_problem.txt ../out/89/33/Dark_matter_problem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/d0/Military_Forces_of_Colombia.txt ../out/89/d0/Military_Forces_of_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/41/Economy_of_Chad.txt ../out/8a/41/Economy_of_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/1e/Corcovado.txt ../out/8b/1e/Corcovado.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/c2/The_Endless_Dark_Nothingness.txt ../out/8b/c2/The_Endless_Dark_Nothingness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/74/A_Wizard_of_Earthsea.txt ../out/8c/74/A_Wizard_of_Earthsea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/f0/Cytochrome.txt ../out/8c/f0/Cytochrome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/83/Addictive.txt ../out/8d/83/Addictive.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/5b/Fire_%28classical_element%29.txt ../out/8e/5b/Fire_%28classical_element%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/5c/Abugida.txt ../out/8f/5c/Abugida.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/01/City_of_London.txt ../out/90/01/City_of_London.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/d5/Alexander_Aetolus.txt ../out/90/d5/Alexander_Aetolus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/58/Curtiss_P-40_Warhawk.txt ../out/91/58/Curtiss_P-40_Warhawk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/7b/Birka.txt ../out/92/7b/Birka.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/1b/Europa_Island%2FPeople.txt ../out/93/1b/Europa_Island%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/cc/Alfonso_VI.txt ../out/93/cc/Alfonso_VI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/92/Bicameral_mind.txt ../out/94/92/Bicameral_mind.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/4f/Daniel_Ortega.txt ../out/95/4f/Daniel_Ortega.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/e8/Category_theory.txt ../out/95/e8/Category_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/a8/Federal_Chancellor.txt ../out/96/a8/Federal_Chancellor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/47/Constellation.txt ../out/97/47/Constellation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/d4/Church_%28building%29.txt ../out/97/d4/Church_%28building%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/4f/Wireless_broadband.txt ../out/98/4f/Wireless_broadband.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/ee/BalticSea.txt ../out/98/ee/BalticSea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/79/Telecommunications_in_Estonia.txt ../out/99/79/Telecommunications_in_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/e4/Broch.txt ../out/99/e4/Broch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/71/Dense.txt ../out/9a/71/Dense.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/14/AnEnquiryConcerningHumanUnderstanding.txt ../out/9b/14/AnEnquiryConcerningHumanUnderstanding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/b0/Basal_body_temperature_method.txt ../out/9b/b0/Basal_body_temperature_method.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/2a/Chief_Executive_Officer.txt ../out/9c/2a/Chief_Executive_Officer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/c6/American_Film_Institute.txt ../out/9c/c6/American_Film_Institute.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/49/Demographics_of_Estonia.txt ../out/9d/49/Demographics_of_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/fc/Armoured_fighting_vehicle.txt ../out/9d/fc/Armoured_fighting_vehicle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/c5/Demographics_of_Ethiopia.txt ../out/9e/c5/Demographics_of_Ethiopia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/7e/Carolingian_renaissance.txt ../out/9f/7e/Carolingian_renaissance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/10/Automated_Alice%2FII.txt ../out/a0/10/Automated_Alice%2FII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/cf/Baby_Boom.txt ../out/a0/cf/Baby_Boom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/b7/BinaryOperation.txt ../out/a1/b7/BinaryOperation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/76/History_of_the_Dominican_Republic.txt ../out/a2/76/History_of_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/24/Azad_Kashmir.txt ../out/a3/24/Azad_Kashmir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/d9/Accelerated_Graphics_Port.txt ../out/a3/d9/Accelerated_Graphics_Port.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/a8/Equivalence_class.txt ../out/a4/a8/Equivalence_class.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/04/Amorphous_solid.txt ../out/a5/04/Amorphous_solid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/80/Edmund_Spenser.txt ../out/a5/80/Edmund_Spenser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/34/Allotropes.txt ../out/a6/34/Allotropes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/d0/Transport_in_Eritrea.txt ../out/a6/d0/Transport_in_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/80/Book_of_Amos.txt ../out/a7/80/Book_of_Amos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/5e/Alexander_Agassiz.txt ../out/a8/5e/Alexander_Agassiz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/02/Dundee.txt ../out/a9/02/Dundee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/e2/Abaddon.txt ../out/a9/e2/Abaddon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/7c/Conditioning.txt ../out/aa/7c/Conditioning.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/da/Alfonso_IV.txt ../out/aa/da/Alfonso_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/7f/Anti-Ballistic_Missile.txt ../out/ab/7f/Anti-Ballistic_Missile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/11/Dictator.txt ../out/ac/11/Dictator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/9f/Apocrypha.txt ../out/ac/9f/Apocrypha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/0b/Blue_Velvet_%28film%29.txt ../out/ad/0b/Blue_Velvet_%28film%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/ec/David_Huffman.txt ../out/ad/ec/David_Huffman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/80/Computer_Storage.txt ../out/ae/80/Computer_Storage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/0d/Computer_Monitor.txt ../out/af/0d/Computer_Monitor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/98/Bioinformatics.txt ../out/af/98/Bioinformatics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/34/AcademyAwards%2FBestPicture.txt ../out/b0/34/AcademyAwards%2FBestPicture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/eb/Double_jeopardy.txt ../out/b0/eb/Double_jeopardy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/95/Calf.txt ../out/b1/95/Calf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/ec/Allan_Dwan.txt ../out/b1/ec/Allan_Dwan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/a6/Antipsychotic.txt ../out/b2/a6/Antipsychotic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/aa/Albert_III%2C_Elector_of_Saxony.txt ../out/b3/aa/Albert_III%2C_Elector_of_Saxony.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/43/Cebidae.txt ../out/b4/43/Cebidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/ae/Black_cow.txt ../out/b4/ae/Black_cow.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/10/Complaint.txt ../out/b5/10/Complaint.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/7b/Bauhaus.txt ../out/b5/7b/Bauhaus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/07/Bride_of_the_Monster.txt ../out/b6/07/Bride_of_the_Monster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/fc/Danzig.txt ../out/b6/fc/Danzig.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/a7/Alexander.txt ../out/b7/a7/Alexander.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/40/Dana_Rohrabacher.txt ../out/b8/40/Dana_Rohrabacher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/bc/Denaturation_%28biochemistry%29.txt ../out/b8/bc/Denaturation_%28biochemistry%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/ac/December_22.txt ../out/b9/ac/December_22.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/29/Delaware.txt ../out/ba/29/Delaware.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/f0/Anno_Domini.txt ../out/ba/f0/Anno_Domini.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/7e/ArtificialLanguages.txt ../out/bb/7e/ArtificialLanguages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/10/Charles_Robert_Darwin.txt ../out/bc/10/Charles_Robert_Darwin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/84/April_13.txt ../out/bc/84/April_13.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/73/Auguste_and_Louis_Lumi%C3%A8re.txt ../out/bd/73/Auguste_and_Louis_Lumi%C3%A8re.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/2a/Ethernet.txt ../out/be/2a/Ethernet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/da/The_Beach_Boys.txt ../out/be/da/The_Beach_Boys.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/77/Deposition.txt ../out/bf/77/Deposition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/34/David_Abercromby.txt ../out/c0/34/David_Abercromby.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/0f/Transport_in_Cape_Verde.txt ../out/c1/0f/Transport_in_Cape_Verde.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/9b/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FO.txt ../out/c1/9b/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FO.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/67/Alexander_of_Hales.txt ../out/c2/67/Alexander_of_Hales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/42/Alan_Turing.txt ../out/c3/42/Alan_Turing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/c8/Ayatollah_Khomeini.txt ../out/c3/c8/Ayatollah_Khomeini.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/4f/STS-51-F.txt ../out/c4/4f/STS-51-F.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/f8/Adalbert_of_Prague.txt ../out/c4/f8/Adalbert_of_Prague.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/04/Chromatin.txt ../out/c6/04/Chromatin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/ae/Cryptology.txt ../out/c6/ae/Cryptology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/6b/List_of_explorations.txt ../out/c7/6b/List_of_explorations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/1a/Brewsters_angle.txt ../out/c8/1a/Brewsters_angle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/ef/Cipher.txt ../out/c8/ef/Cipher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/73/American_Registry_for_Internet_Numbers.txt ../out/c9/73/American_Registry_for_Internet_Numbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/07/Asyncronous_Transfer_Mode.txt ../out/ca/07/Asyncronous_Transfer_Mode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/9b/Devon.txt ../out/ca/9b/Devon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/71/Kingdom_of_Essex.txt ../out/cb/71/Kingdom_of_Essex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/3b/Demographics_of_El_Salvador.txt ../out/cc/3b/Demographics_of_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/fe/Ancylopoda.txt ../out/cc/fe/Ancylopoda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/98/Color%2Forange.txt ../out/cd/98/Color%2Forange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/3c/British_Virgin_Islands.txt ../out/ce/3c/British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/0d/Braveheart.txt ../out/cf/0d/Braveheart.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/a3/Anomalous_phenomenon.txt ../out/cf/a3/Anomalous_phenomenon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/60/December_28.txt ../out/d0/60/December_28.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/2e/AphexTwin.txt ../out/d1/2e/AphexTwin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/00/Anarchism.txt ../out/d2/00/Anarchism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/ab/2001_World_Series.txt ../out/d2/ab/2001_World_Series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/26/CCD.txt ../out/d3/26/CCD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/d2/Anti-realism.txt ../out/d3/d2/Anti-realism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/a9/Denis_Abramovich_Kaufman.txt ../out/d4/a9/Denis_Abramovich_Kaufman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/48/Deseret_alphabet.txt ../out/d5/48/Deseret_alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/dd/Chlorophyta.txt ../out/d5/dd/Chlorophyta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/86/Andre_Agassi.txt ../out/d6/86/Andre_Agassi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/22/AlbaniaHistory.txt ../out/d7/22/AlbaniaHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/a5/Alberta.txt ../out/d7/a5/Alberta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/77/Copernican_principle.txt ../out/d8/77/Copernican_principle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/0b/Afonso_VI_of_Portugal.txt ../out/d9/0b/Afonso_VI_of_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/ca/Analytic_geometry.txt ../out/d9/ca/Analytic_geometry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/88/Biological_warfare.txt ../out/da/88/Biological_warfare.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/0b/Abdera%2C_Spain.txt ../out/db/0b/Abdera%2C_Spain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/aa/History_of_Cuba.txt ../out/db/aa/History_of_Cuba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/53/Ezra.txt ../out/dc/53/Ezra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/f6/Dan_Bricklin.txt ../out/dc/f6/Dan_Bricklin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/8c/Famous_at_Twenty-Five_Thirty_a_Master.txt ../out/dd/8c/Famous_at_Twenty-Five_Thirty_a_Master.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/51/BBC%2FRadio_1.txt ../out/de/51/BBC%2FRadio_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/ca/Bud_Selig.txt ../out/de/ca/Bud_Selig.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/98/Babur.txt ../out/df/98/Babur.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/56/Benjamin_Franklin-class_submarine.txt ../out/e0/56/Benjamin_Franklin-class_submarine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/2c/Argumentum_ad_hominum.txt ../out/e1/2c/Argumentum_ad_hominum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/c2/Alcoba%C3%A7a%2C_Portugal.txt ../out/e1/c2/Alcoba%C3%A7a%2C_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/7c/Bigfoot.txt ../out/e2/7c/Bigfoot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/26/AbacuS.txt ../out/e3/26/AbacuS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/a6/Au_file_format.txt ../out/e3/a6/Au_file_format.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/68/Ascorbic_acid.txt ../out/e4/68/Ascorbic_acid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/1a/Afro_Celt_Sound_System.txt ../out/e5/1a/Afro_Celt_Sound_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/ce/Baseball_statistics%2FSLG.txt ../out/e5/ce/Baseball_statistics%2FSLG.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/51/Benzodiazepine.txt ../out/e6/51/Benzodiazepine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/2b/Telecommunications_in_the_Czech_Republic.txt ../out/e7/2b/Telecommunications_in_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/f9/Call_of_Cthulhu_%28role-playing_game%29.txt ../out/e7/f9/Call_of_Cthulhu_%28role-playing_game%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/92/Daily_rushes.txt ../out/e8/92/Daily_rushes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/0d/Black.txt ../out/e9/0d/Black.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/98/Herman_Boerhaave.txt ../out/e9/98/Herman_Boerhaave.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/0d/Dingus_McDuck.txt ../out/ea/0d/Dingus_McDuck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/d0/Arthur_Tudor.txt ../out/ea/d0/Arthur_Tudor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/56/Printer_%28computing%29.txt ../out/eb/56/Printer_%28computing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/3b/Burgess_Shale.txt ../out/ec/3b/Burgess_Shale.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/0f/Cultural_imperialism.txt ../out/ed/0f/Cultural_imperialism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/9b/Military_of_Burundi.txt ../out/ed/9b/Military_of_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/1c/Enlightenment.txt ../out/ee/1c/Enlightenment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/bd/BaruchSpinoza.txt ../out/ee/bd/BaruchSpinoza.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/88/BusinessSchools%2FAsia.txt ../out/ef/88/BusinessSchools%2FAsia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/fc/Elbing%2FElblag.txt ../out/ef/fc/Elbing%2FElblag.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/a5/Christine_de_Pizan.txt ../out/f0/a5/Christine_de_Pizan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/87/AmericA.txt ../out/f1/87/AmericA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/5f/Charlize_Theron.txt ../out/f2/5f/Charlize_Theron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/54/Alexander_II_of_Scotland.txt ../out/f3/54/Alexander_II_of_Scotland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/f5/%C3%86gir.txt ../out/f3/f5/%C3%86gir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/ee/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FG.txt ../out/f4/ee/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FG.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/a8/Bauxite.txt ../out/f5/a8/Bauxite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/51/Alain_de_Lille.txt ../out/f6/51/Alain_de_Lille.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/e2/Bulgarian_language.txt ../out/f6/e2/Bulgarian_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/69/Boat.txt ../out/f7/69/Boat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/4f/Craig_Charles.txt ../out/f8/4f/Craig_Charles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/de/Banda_Islands.txt ../out/f8/de/Banda_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/31/Agra_Canal.txt ../out/f9/31/Agra_Canal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/e8/Bronze_age.txt ../out/f9/e8/Bronze_age.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/4f/Antidorcas_marsupialis.txt ../out/fa/4f/Antidorcas_marsupialis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/08/Catherine_of_Aragon.txt ../out/fb/08/Catherine_of_Aragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/b3/Ajanta_Caves.txt ../out/fb/b3/Ajanta_Caves.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/50/Chemotaxis.txt ../out/fc/50/Chemotaxis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/67/CountriesM.txt ../out/fd/67/CountriesM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/01/Andrew_Carnegie.txt ../out/fe/01/Andrew_Carnegie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/c9/Celtic_languages.txt ../out/fe/c9/Celtic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/3f/Anagram.txt ../out/ff/3f/Anagram.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/a1/Characteristic_subgroup.txt ../out/ff/a1/Characteristic_subgroup.xml
