php ./wiki2xml/php/wiki2xml_command.php ../out/00/0f/Aurora_borealis.txt ../out/00/0f/Aurora_borealis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/00/e0/Zebrafish.txt ../out/00/e0/Zebrafish.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/a1/Bulgaria.txt ../out/01/a1/Bulgaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/34/Bill_Bixby.txt ../out/02/34/Bill_Bixby.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/e3/Alexander_Selkirk.txt ../out/02/e3/Alexander_Selkirk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/89/DA.txt ../out/03/89/DA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/18/Ernest_Hemingway%2FFor_Whom_the_Bell_Tolls.txt ../out/04/18/Ernest_Hemingway%2FFor_Whom_the_Bell_Tolls.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/8b/Civilization.txt ../out/04/8b/Civilization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/3d/Biochemistry.txt ../out/05/3d/Biochemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/b6/Codon.txt ../out/05/b6/Codon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/61/Aegadian_Islands.txt ../out/06/61/Aegadian_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/03/Casino.txt ../out/07/03/Casino.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/ba/Context-free_language.txt ../out/07/ba/Context-free_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/7c/Austin%2C_Texas.txt ../out/08/7c/Austin%2C_Texas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/f8/Children_of_Dune.txt ../out/08/f8/Children_of_Dune.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/b5/Argo_Navis.txt ../out/09/b5/Argo_Navis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/8b/Alligatoridae.txt ../out/0a/8b/Alligatoridae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/04/Antony_van_Leeuwenhook.txt ../out/0b/04/Antony_van_Leeuwenhook.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/a0/Folklore_of_the_United_States.txt ../out/0b/a0/Folklore_of_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/14/Afghanistan%2FGovernment.txt ../out/0c/14/Afghanistan%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/e9/Domino_effect.txt ../out/0c/e9/Domino_effect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/a4/Catherine_of_Siena.txt ../out/0d/a4/Catherine_of_Siena.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/4a/Dennis_Ritchie.txt ../out/0e/4a/Dennis_Ritchie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/ea/Canadian_Radio-television_and_Telecommunications_Commission.txt ../out/0e/ea/Canadian_Radio-television_and_Telecommunications_Commission.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/9f/Alemanni.txt ../out/0f/9f/Alemanni.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/af/Community_college.txt ../out/10/af/Community_college.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/56/Abbreviator.txt ../out/11/56/Abbreviator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/f0/BBC%2FOnline.txt ../out/11/f0/BBC%2FOnline.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/9a/C.E..txt ../out/12/9a/C.E..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/31/Chuck_D.txt ../out/13/31/Chuck_D.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/bb/Bipyramid.txt ../out/13/bb/Bipyramid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/94/Cycling.txt ../out/14/94/Cycling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/29/Edgar_Allan_Poe%2FThe_Black_Cat.txt ../out/15/29/Edgar_Allan_Poe%2FThe_Black_Cat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/d4/Automobile_racing.txt ../out/15/d4/Automobile_racing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/7d/Chicago_White_Sox.txt ../out/16/7d/Chicago_White_Sox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/5e/Outline_of_critical_theory.txt ../out/17/5e/Outline_of_critical_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/02/BritneySpears.txt ../out/18/02/BritneySpears.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/8b/Abdul_Alhazred.txt ../out/18/8b/Abdul_Alhazred.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/0c/Demand-pull_inflation.txt ../out/19/0c/Demand-pull_inflation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/a2/Agostino_Carracci.txt ../out/19/a2/Agostino_Carracci.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/38/Ada.txt ../out/1a/38/Ada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/b3/August_28.txt ../out/1a/b3/August_28.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/43/Comet_Shoemaker%E2%80%93Levy_9.txt ../out/1b/43/Comet_Shoemaker%E2%80%93Levy_9.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/e2/Cambridgeshire.txt ../out/1b/e2/Cambridgeshire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/5c/Dagger.txt ../out/1c/5c/Dagger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/e6/Daffodil.txt ../out/1c/e6/Daffodil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/7f/David_Letterman.txt ../out/1d/7f/David_Letterman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/29/Cartesian_coordinate_system.txt ../out/1e/29/Cartesian_coordinate_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/b3/Devonian.txt ../out/1e/b3/Devonian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/b0/Base_pair.txt ../out/1f/b0/Base_pair.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/4c/Abner_Duck.txt ../out/20/4c/Abner_Duck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/fb/Alexis_%28poet%29.txt ../out/20/fb/Alexis_%28poet%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/c0/Adiabatic_process.txt ../out/21/c0/Adiabatic_process.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/77/Dirigible.txt ../out/22/77/Dirigible.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/1a/Element.txt ../out/23/1a/Element.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/e0/Arithmetic_function.txt ../out/23/e0/Arithmetic_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/60/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FZ.txt ../out/24/60/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FZ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/1f/Ball_%28baseball_statistics%29.txt ../out/25/1f/Ball_%28baseball_statistics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/ed/Area_51.txt ../out/25/ed/Area_51.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/74/Casa_Mil%C3%A0.txt ../out/26/74/Casa_Mil%C3%A0.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/2c/Arabic.txt ../out/27/2c/Arabic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/e0/Agrippina_the_Elder.txt ../out/27/e0/Agrippina_the_Elder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/64/Dessert.txt ../out/28/64/Dessert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/f8/Antiderivative.txt ../out/28/f8/Antiderivative.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/9b/December_10.txt ../out/29/9b/December_10.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/4d/Additive_synthesis.txt ../out/2a/4d/Additive_synthesis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/39/Geography_of_the_Comoros.txt ../out/2b/39/Geography_of_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/c3/Australian_Democrats.txt ../out/2b/c3/Australian_Democrats.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/66/Cruise_Missile.txt ../out/2c/66/Cruise_Missile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/ff/Apiaceae.txt ../out/2c/ff/Apiaceae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/c6/Brown_University.txt ../out/2d/c6/Brown_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/60/Double-hulled_tanker.txt ../out/2e/60/Double-hulled_tanker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/25/Politics_of_Antigua_and_Barbuda.txt ../out/2f/25/Politics_of_Antigua_and_Barbuda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/13/Baltic_Sea.txt ../out/30/13/Baltic_Sea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/cd/Lists_of_people.txt ../out/30/cd/Lists_of_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/67/ASCII_art.txt ../out/31/67/ASCII_art.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/74/Endocarditis.txt ../out/32/74/Endocarditis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/e9/ELF_file_format.txt ../out/32/e9/ELF_file_format.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/ce/Differential_geometry.txt ../out/33/ce/Differential_geometry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/b0/Ailanthus.txt ../out/34/b0/Ailanthus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/20/Christian_Social_Union_in_Bavaria.txt ../out/35/20/Christian_Social_Union_in_Bavaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/c5/Military_of_Burkina_Faso.txt ../out/35/c5/Military_of_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/8b/Constellations_%28journal%29.txt ../out/36/8b/Constellations_%28journal%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/55/Coral_Sea_Islands%2FHistory.txt ../out/37/55/Coral_Sea_Islands%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/d1/Breathy_voice.txt ../out/37/d1/Breathy_voice.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/38/James_Danforth_Quayle.txt ../out/38/38/James_Danforth_Quayle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/ff/December_24.txt ../out/38/ff/December_24.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/c9/Computational_chemistry.txt ../out/39/c9/Computational_chemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/54/British_Indian_Ocean_Territory%2FMilitary.txt ../out/3a/54/British_Indian_Ocean_Territory%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/d3/Daniel_Defoe.txt ../out/3a/d3/Daniel_Defoe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/67/Bikini.txt ../out/3b/67/Bikini.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/d1/Emma_Goldman.txt ../out/3b/d1/Emma_Goldman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/79/Ballarat.txt ../out/3c/79/Ballarat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/25/History_of_Christmas_Island.txt ../out/3d/25/History_of_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/c3/Ghanaian_hip_hop.txt ../out/3d/c3/Ghanaian_hip_hop.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/91/Epistle_to_the_Ephesians.txt ../out/3e/91/Epistle_to_the_Ephesians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/05/Book_of_Daniel.txt ../out/3f/05/Book_of_Daniel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/81/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FU.txt ../out/3f/81/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FU.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/47/Artist.txt ../out/40/47/Artist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/c6/Alpha_compositing.txt ../out/40/c6/Alpha_compositing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/98/Early_Helladic.txt ../out/41/98/Early_Helladic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/db/Algernon_Swinburne.txt ../out/41/db/Algernon_Swinburne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/4e/Alessandro_Algardi.txt ../out/42/4e/Alessandro_Algardi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/ff/Charybdis.txt ../out/42/ff/Charybdis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/93/Transport_in_Costa_Rica.txt ../out/43/93/Transport_in_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/56/Athenian_Empire.txt ../out/44/56/Athenian_Empire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/a6/Conservatory.txt ../out/44/a6/Conservatory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/57/Chrominance.txt ../out/45/57/Chrominance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/0c/Benz.txt ../out/46/0c/Benz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/f2/Arabic_alphabet.txt ../out/46/f2/Arabic_alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/8b/Electronic_art_music.txt ../out/47/8b/Electronic_art_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/6e/Binary_prefix.txt ../out/48/6e/Binary_prefix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/f6/Brezhnev_Doctrine.txt ../out/48/f6/Brezhnev_Doctrine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/ab/Kolmogorov_complexity.txt ../out/49/ab/Kolmogorov_complexity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/4e/December_11.txt ../out/4a/4e/December_11.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/df/Aragonese_language.txt ../out/4a/df/Aragonese_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/74/Black_Flag.txt ../out/4b/74/Black_Flag.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/1a/Aurangzeb.txt ../out/4c/1a/Aurangzeb.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/82/Context_menu.txt ../out/4c/82/Context_menu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/5a/Accordion.txt ../out/4d/5a/Accordion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/e7/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FB.txt ../out/4d/e7/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FB.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/8c/Diesel_multiple_unit.txt ../out/4e/8c/Diesel_multiple_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/0e/AndorrA.txt ../out/4f/0e/AndorrA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/d9/Bouvet_Island%2FTransportation.txt ../out/4f/d9/Bouvet_Island%2FTransportation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/7c/Geography_of_the_Cayman_Islands.txt ../out/50/7c/Geography_of_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/53/Au.txt ../out/51/53/Au.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/d9/Anatoly_Karpov.txt ../out/51/d9/Anatoly_Karpov.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/83/Atle_Selberg.txt ../out/52/83/Atle_Selberg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/24/B.C..txt ../out/53/24/B.C..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/b9/Bali.txt ../out/53/b9/Bali.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/41/DreamCast.txt ../out/54/41/DreamCast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/ba/DirectX.txt ../out/54/ba/DirectX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/88/Bipolar_II.txt ../out/55/88/Bipolar_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/24/Discrete_math.txt ../out/56/24/Discrete_math.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/30/Bra%E2%80%93ket_notation.txt ../out/57/30/Bra%E2%80%93ket_notation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/d2/Transport_in_Bulgaria.txt ../out/57/d2/Transport_in_Bulgaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/77/Bliss_bibliographic_classification.txt ../out/58/77/Bliss_bibliographic_classification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/1c/Doom_%281993_video_game%29.txt ../out/59/1c/Doom_%281993_video_game%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/c2/Andrew_II_of_Hungary.txt ../out/59/c2/Andrew_II_of_Hungary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/49/Blythe_Danner.txt ../out/5a/49/Blythe_Danner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/c5/Anatolia.txt ../out/5a/c5/Anatolia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/66/Casey_at_the_Bat.txt ../out/5b/66/Casey_at_the_Bat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/24/ArgumentsForTheExistenceOfGod.txt ../out/5c/24/ArgumentsForTheExistenceOfGod.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/c2/Energy.txt ../out/5c/c2/Energy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/96/Cave_Tetra.txt ../out/5d/96/Cave_Tetra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/4d/Comparison_of_American_and_British_English.txt ../out/5e/4d/Comparison_of_American_and_British_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/bf/Agathocles_of_Syracuse.txt ../out/5e/bf/Agathocles_of_Syracuse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/a3/Crete.txt ../out/5f/a3/Crete.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/39/Compact_space.txt ../out/60/39/Compact_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/09/Arithmetic_and_logic_unit.txt ../out/61/09/Arithmetic_and_logic_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/8f/Dipole-dipole_bond.txt ../out/61/8f/Dipole-dipole_bond.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/23/Clara_Petacci.txt ../out/62/23/Clara_Petacci.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/1f/Anatomical_Therapeutic_Chemical_Classification_System.txt ../out/63/1f/Anatomical_Therapeutic_Chemical_Classification_System.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/e3/Conic_sections.txt ../out/63/e3/Conic_sections.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/c2/Affix.txt ../out/64/c2/Affix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/42/Belarus.txt ../out/65/42/Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/d5/Chromium.txt ../out/65/d5/Chromium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/34/Agis.txt ../out/66/34/Agis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/f5/Civilization_%28video_game%29.txt ../out/66/f5/Civilization_%28video_game%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/73/Bayesian_probability.txt ../out/67/73/Bayesian_probability.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/08/Algebraically_closed_field.txt ../out/68/08/Algebraically_closed_field.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/bf/Brewing.txt ../out/68/bf/Brewing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/8d/Charles_I_of_England.txt ../out/69/8d/Charles_I_of_England.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/39/Confucianism.txt ../out/6a/39/Confucianism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/b7/Animalia_%28book%29.txt ../out/6a/b7/Animalia_%28book%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/46/Baseball_statistics%2FBA.txt ../out/6b/46/Baseball_statistics%2FBA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/eb/Transport_in_Belgium.txt ../out/6b/eb/Transport_in_Belgium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/5f/Discrimination.txt ../out/6c/5f/Discrimination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/f2/Albania%2FPeople.txt ../out/6c/f2/Albania%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/98/Cornish_language.txt ../out/6d/98/Cornish_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/2f/Charles_Ancillon.txt ../out/6e/2f/Charles_Ancillon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/ab/Dispute_resolution.txt ../out/6e/ab/Dispute_resolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/2b/Transport_in_Chile.txt ../out/6f/2b/Transport_in_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/02/Caspar_David_Friedrich.txt ../out/70/02/Caspar_David_Friedrich.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/b6/AIM-54_Phoenix.txt ../out/70/b6/AIM-54_Phoenix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/9d/Software.txt ../out/71/9d/Software.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/20/CountriesW.txt ../out/72/20/CountriesW.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/de/List_of_anthropologists.txt ../out/72/de/List_of_anthropologists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/a0/Economy_of_Azerbaijan.txt ../out/73/a0/Economy_of_Azerbaijan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/4e/Chris_Morris_%28satirist%29.txt ../out/74/4e/Chris_Morris_%28satirist%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/9f/Druze.txt ../out/74/9f/Druze.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/54/AssistiveTechnology.txt ../out/75/54/AssistiveTechnology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/0b/Clipperton_Island%2FPeople.txt ../out/76/0b/Clipperton_Island%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/a4/Character.txt ../out/76/a4/Character.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/5a/Non-standard_adjectives_in_the_English_language.txt ../out/77/5a/Non-standard_adjectives_in_the_English_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/05/Analcim.txt ../out/78/05/Analcim.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/b4/Alfonso_V_of_Aragon.txt ../out/78/b4/Alfonso_V_of_Aragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/4e/Double-slit_experiment.txt ../out/79/4e/Double-slit_experiment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/d4/Exabyte.txt ../out/79/d4/Exabyte.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/77/Alopex_lagopus.txt ../out/7a/77/Alopex_lagopus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/b4/Desmodromic.txt ../out/7a/b4/Desmodromic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/61/Disjunction_elimination.txt ../out/7b/61/Disjunction_elimination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/25/Cold_fusion.txt ../out/7c/25/Cold_fusion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/de/BDSM.txt ../out/7c/de/BDSM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/59/Apuleius.txt ../out/7d/59/Apuleius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/11/Arne_Kaijser.txt ../out/7e/11/Arne_Kaijser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/ac/Amphetamine.txt ../out/7e/ac/Amphetamine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/71/BASIC_%28disambiguation%29.txt ../out/7f/71/BASIC_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/da/Cross-examination.txt ../out/7f/da/Cross-examination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/3d/Electron_microscope.txt ../out/80/3d/Electron_microscope.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/fc/Arithmetic%E2%80%93geometric_mean.txt ../out/80/fc/Arithmetic%E2%80%93geometric_mean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/a3/Saint_Titus.txt ../out/81/a3/Saint_Titus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/5d/Cameroonian_Armed_Forces.txt ../out/82/5d/Cameroonian_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/4d/EV.txt ../out/83/4d/EV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/d2/Digit.txt ../out/83/d2/Digit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/ae/Demographics_of_Antigua_and_Barbuda.txt ../out/84/ae/Demographics_of_Antigua_and_Barbuda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/51/Donna_Duck.txt ../out/85/51/Donna_Duck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/e7/Bursa.txt ../out/85/e7/Bursa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/7d/Commedia_del_arte.txt ../out/86/7d/Commedia_del_arte.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/22/Alchemy.txt ../out/87/22/Alchemy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/de/Alfred_Nobel.txt ../out/87/de/Alfred_Nobel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/a0/Extremophile.txt ../out/88/a0/Extremophile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/3f/Central_tendency.txt ../out/89/3f/Central_tendency.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/ec/Outline_of_biology.txt ../out/89/ec/Outline_of_biology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/8d/Dulcimer.txt ../out/8a/8d/Dulcimer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/4a/Geography_of_Baker_Island.txt ../out/8b/4a/Geography_of_Baker_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/f0/Cymbal.txt ../out/8b/f0/Cymbal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/95/Daugava_%28river%29.txt ../out/8c/95/Daugava_%28river%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/03/Ascending_chain_condition.txt ../out/8d/03/Ascending_chain_condition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/c9/Latin_American_Integration_Association.txt ../out/8d/c9/Latin_American_Integration_Association.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/9b/Benzoic_acid.txt ../out/8e/9b/Benzoic_acid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/63/Anthropic_principle.txt ../out/8f/63/Anthropic_principle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/0a/Catalan.txt ../out/90/0a/Catalan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/e7/Bankruptcy.txt ../out/90/e7/Bankruptcy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/86/Albert.txt ../out/91/86/Albert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/97/Apiales.txt ../out/92/97/Apiales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/63/List_of_computer_scientists.txt ../out/93/63/List_of_computer_scientists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/e9/Donald_A._Wollheim.txt ../out/93/e9/Donald_A._Wollheim.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/f7/Abdul_Hamid_I.txt ../out/94/f7/Abdul_Hamid_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/70/Telecommunications_in_Egypt.txt ../out/95/70/Telecommunications_in_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/1e/Allene.txt ../out/96/1e/Allene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/cb/Computational_Linguistics.txt ../out/96/cb/Computational_Linguistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/68/Backbone_cabal.txt ../out/97/68/Backbone_cabal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/ee/Bo%C3%B6tes.txt ../out/97/ee/Bo%C3%B6tes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/57/AmbientCalculiOnline.txt ../out/98/57/AmbientCalculiOnline.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/0c/Wikipedia%3AComplete_list_of_language_wikis_available.txt ../out/99/0c/Wikipedia%3AComplete_list_of_language_wikis_available.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/82/Military_of_Antarctica.txt ../out/99/82/Military_of_Antarctica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/fa/Astoria%2C_Oregon.txt ../out/99/fa/Astoria%2C_Oregon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/7e/Context-sensitive.txt ../out/9a/7e/Context-sensitive.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/23/Dune.txt ../out/9b/23/Dune.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/cb/Alexander_of_Pherae.txt ../out/9b/cb/Alexander_of_Pherae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/4e/Accrington.txt ../out/9c/4e/Accrington.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/de/Azerbaijan%2FForeign_relations.txt ../out/9c/de/Azerbaijan%2FForeign_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/71/Book_of_Ezekiel.txt ../out/9d/71/Book_of_Ezekiel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/0c/Demographics_of_Denmark.txt ../out/9e/0c/Demographics_of_Denmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/dc/Comprehensive_Nuclear-Test-Ban_Treaty.txt ../out/9e/dc/Comprehensive_Nuclear-Test-Ban_Treaty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/a3/Euthanasia.txt ../out/9f/a3/Euthanasia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/2f/Adelaide.txt ../out/a0/2f/Adelaide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/06/CountriesU.txt ../out/a1/06/CountriesU.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/df/Americans_with_Disabilities_Act_of_1990%2FTitle_III.txt ../out/a1/df/Americans_with_Disabilities_Act_of_1990%2FTitle_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/98/Carl_von_Clausewitz.txt ../out/a2/98/Carl_von_Clausewitz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/34/DSM-III-R.txt ../out/a3/34/DSM-III-R.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/e7/Chlorinated_fluorocarbons.txt ../out/a3/e7/Chlorinated_fluorocarbons.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/bd/Amphipolis.txt ../out/a4/bd/Amphipolis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/17/Author.txt ../out/a5/17/Author.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/9b/Celtic_music.txt ../out/a5/9b/Celtic_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/42/Many-worlds_interpretation.txt ../out/a6/42/Many-worlds_interpretation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/f4/Arene_%28disambiguation%29.txt ../out/a6/f4/Arene_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/a6/Amyl_alcohol.txt ../out/a7/a6/Amyl_alcohol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/7f/Aedicula.txt ../out/a8/7f/Aedicula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/47/Atomic_theory.txt ../out/a9/47/Atomic_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/0d/Wu_Xing.txt ../out/aa/0d/Wu_Xing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/8a/Equation.txt ../out/aa/8a/Equation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/02/Engineering.txt ../out/ab/02/Engineering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/9a/Boiled_leather.txt ../out/ab/9a/Boiled_leather.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/2e/BCE_%28disambiguation%29.txt ../out/ac/2e/BCE_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/a5/BBC_Radio_1.txt ../out/ac/a5/BBC_Radio_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/23/Death_of_a_Hero.txt ../out/ad/23/Death_of_a_Hero.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/f9/Jean-Baptiste-Sim%C3%A9on_Chardin.txt ../out/ad/f9/Jean-Baptiste-Sim%C3%A9on_Chardin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/93/Constitution.txt ../out/ae/93/Constitution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/30/History_of_Croatia.txt ../out/af/30/History_of_Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/af/Critical_psychology.txt ../out/af/af/Critical_psychology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/4a/Developmental_psychology.txt ../out/b0/4a/Developmental_psychology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/09/Back-Cover_Texts.txt ../out/b1/09/Back-Cover_Texts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/a8/Alphabet_song.txt ../out/b1/a8/Alphabet_song.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/09/The_Bush_%28Alaska%29.txt ../out/b2/09/The_Bush_%28Alaska%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/d9/Dozenal_Society_of_Great_Britain.txt ../out/b2/d9/Dozenal_Society_of_Great_Britain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/c6/Des_Moines%2C_Iowa.txt ../out/b3/c6/Des_Moines%2C_Iowa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/65/Djbdns.txt ../out/b4/65/Djbdns.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/c5/Blazing_Saddles.txt ../out/b4/c5/Blazing_Saddles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/1b/Hanukkah.txt ../out/b5/1b/Hanukkah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/95/Adamic_language.txt ../out/b5/95/Adamic_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/34/Amazing_Grace.txt ../out/b6/34/Amazing_Grace.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/15/Democritus.txt ../out/b7/15/Democritus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/bc/Biological_membrane.txt ../out/b7/bc/Biological_membrane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/54/Background_radiation.txt ../out/b8/54/Background_radiation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/dc/Dying_Earth.txt ../out/b8/dc/Dying_Earth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/cb/Andrzej_Sapkowski.txt ../out/b9/cb/Andrzej_Sapkowski.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/61/Economy_of_Cuba.txt ../out/ba/61/Economy_of_Cuba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/07/Antimony.txt ../out/bb/07/Antimony.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/8e/August_13.txt ../out/bb/8e/August_13.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/2d/Banacek.txt ../out/bc/2d/Banacek.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/c2/Cretin.txt ../out/bc/c2/Cretin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/8e/Electronic_music%2FArt_music.txt ../out/bd/8e/Electronic_music%2FArt_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/59/Automated_Alice%2FXI.txt ../out/be/59/Automated_Alice%2FXI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/05/Deduction.txt ../out/bf/05/Deduction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/a9/Chloroplast.txt ../out/bf/a9/Chloroplast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/6f/Dennis_the_Menace.txt ../out/c0/6f/Dennis_the_Menace.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/36/Computer_Painting.txt ../out/c1/36/Computer_Painting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/bf/Couplet.txt ../out/c1/bf/Couplet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/85/List_of_contemporary_ethnic_groups.txt ../out/c2/85/List_of_contemporary_ethnic_groups.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/5c/Bass_guitar.txt ../out/c3/5c/Bass_guitar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/fd/Argument_from_common_consent.txt ../out/c3/fd/Argument_from_common_consent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/69/Algemeen_Nederlands_Studentenblad.txt ../out/c4/69/Algemeen_Nederlands_Studentenblad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/35/Canadian_Pacific_Railway.txt ../out/c5/35/Canadian_Pacific_Railway.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/13/Christkindlmarkt.txt ../out/c6/13/Christkindlmarkt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/dd/Cicero.txt ../out/c6/dd/Cicero.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/7c/Bohemian.txt ../out/c7/7c/Bohemian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/39/Dachshund.txt ../out/c8/39/Dachshund.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/16/Babelfish.txt ../out/c9/16/Babelfish.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/97/Blackjack.txt ../out/c9/97/Blackjack.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/18/Cruising_%28maritime%29.txt ../out/ca/18/Cruising_%28maritime%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/04/Dynamic_system.txt ../out/cb/04/Dynamic_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/87/Dilation_and_curettage.txt ../out/cb/87/Dilation_and_curettage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/83/Atom_Bomb.txt ../out/cc/83/Atom_Bomb.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/12/Conspiracy.txt ../out/cd/12/Conspiracy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/a7/Economy_of_the_Czech_Republic.txt ../out/cd/a7/Economy_of_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/88/Directed_set.txt ../out/ce/88/Directed_set.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/20/Aimaq_people.txt ../out/cf/20/Aimaq_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/df/Ancient_Greeks.txt ../out/cf/df/Ancient_Greeks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/a4/Declaration_of_independence.txt ../out/d0/a4/Declaration_of_independence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/52/Alexander_Rutskoi.txt ../out/d1/52/Alexander_Rutskoi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/0e/ElementalAllotropes.txt ../out/d2/0e/ElementalAllotropes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/b1/Politics_of_Croatia.txt ../out/d2/b1/Politics_of_Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/55/Anal_sex.txt ../out/d3/55/Anal_sex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/e8/Dorado.txt ../out/d3/e8/Dorado.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/bc/Ajmer.txt ../out/d4/bc/Ajmer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/62/Antidepressant.txt ../out/d5/62/Antidepressant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/09/Alfonso_Cuar%C3%B3n.txt ../out/d6/09/Alfonso_Cuar%C3%B3n.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/a4/Northern_cavefish.txt ../out/d6/a4/Northern_cavefish.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/34/Abd_ar-Rahman_II.txt ../out/d7/34/Abd_ar-Rahman_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/d6/AlbaniaEconomy.txt ../out/d7/d6/AlbaniaEconomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/a6/Cross-dressing.txt ../out/d8/a6/Cross-dressing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/54/Danish_language.txt ../out/d9/54/Danish_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/db/Erg.txt ../out/d9/db/Erg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/97/Outline_of_engineering.txt ../out/da/97/Outline_of_engineering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/1d/Binary_tree.txt ../out/db/1d/Binary_tree.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/cd/Covalent_bond.txt ../out/db/cd/Covalent_bond.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/5a/Bladder_%28disambiguation%29.txt ../out/dc/5a/Bladder_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/13/CountriesO.txt ../out/dd/13/CountriesO.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/96/Contrapositive.txt ../out/dd/96/Contrapositive.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/71/Consonant.txt ../out/de/71/Consonant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/0d/Citrate_cycle.txt ../out/df/0d/Citrate_cycle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/b4/Dual-tone_multi-frequency_signaling.txt ../out/df/b4/Dual-tone_multi-frequency_signaling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/7e/Epistle_to_the_Romans.txt ../out/e0/7e/Epistle_to_the_Romans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/50/Divine_right_of_kings.txt ../out/e1/50/Divine_right_of_kings.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/e8/Cyril_M._Kornbluth.txt ../out/e1/e8/Cyril_M._Kornbluth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/a2/Arabian_Prince.txt ../out/e2/a2/Arabian_Prince.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/3b/Dakar_Rallye.txt ../out/e3/3b/Dakar_Rallye.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/d9/DC_Comics.txt ../out/e3/d9/DC_Comics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/ac/BASIC.txt ../out/e4/ac/BASIC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/26/Debian_GNU%2FHurd.txt ../out/e5/26/Debian_GNU%2FHurd.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/dd/Aquila.txt ../out/e5/dd/Aquila.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/6b/Drop_kick.txt ../out/e6/6b/Drop_kick.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/69/BBS.txt ../out/e7/69/BBS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/15/Applied_statistics.txt ../out/e8/15/Applied_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/b6/Balmoral.txt ../out/e8/b6/Balmoral.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/3f/Creationist.txt ../out/e9/3f/Creationist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/ac/Collagen_helix.txt ../out/e9/ac/Collagen_helix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/29/BallroomDance.txt ../out/ea/29/BallroomDance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/e7/Chocolate_mousse.txt ../out/ea/e7/Chocolate_mousse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/67/Court_Jester.txt ../out/eb/67/Court_Jester.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/70/Central_America.txt ../out/ec/70/Central_America.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/1d/Dead_Kennedys.txt ../out/ed/1d/Dead_Kennedys.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/b0/Concorde.txt ../out/ed/b0/Concorde.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/54/Foreign_relations_of_Burundi.txt ../out/ee/54/Foreign_relations_of_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/ec/Transportation_in_Christmas_Island.txt ../out/ee/ec/Transportation_in_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/96/Transport_in_Bosnia_and_Herzegovina.txt ../out/ef/96/Transport_in_Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/2e/Atlas_%28disambiguation%29.txt ../out/f0/2e/Atlas_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/eb/Critical_temperature.txt ../out/f0/eb/Critical_temperature.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/aa/Aquilegia.txt ../out/f1/aa/Aquilegia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/7d/BritannicaPublicDomain.txt ../out/f2/7d/BritannicaPublicDomain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/6c/Double-barreled_shotgun.txt ../out/f3/6c/Double-barreled_shotgun.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/27/Continents.txt ../out/f4/27/Continents.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/1a/Amide.txt ../out/f5/1a/Amide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/ba/Ed_%28text_editor%29.txt ../out/f5/ba/Ed_%28text_editor%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/5f/Banana_daiquiri.txt ../out/f6/5f/Banana_daiquiri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/06/CIM-10_Bomarc.txt ../out/f7/06/CIM-10_Bomarc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/74/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FM.txt ../out/f7/74/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/5b/BC.txt ../out/f8/5b/BC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/e3/Claude_Piron.txt ../out/f8/e3/Claude_Piron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/59/Declaration_of_Independence.txt ../out/f9/59/Declaration_of_Independence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/f0/Electro_funk.txt ../out/f9/f0/Electro_funk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/77/Cellular_telephone.txt ../out/fa/77/Cellular_telephone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/29/Electric_Levantine.txt ../out/fb/29/Electric_Levantine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/c9/Bob_Frankston.txt ../out/fb/c9/Bob_Frankston.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/bd/Blood_alcohol_content.txt ../out/fc/bd/Blood_alcohol_content.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/72/Chris_Sarandon.txt ../out/fd/72/Chris_Sarandon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/11/Bipolar_I_disorder.txt ../out/fe/11/Bipolar_I_disorder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/d5/Battle_of_Pharsalus.txt ../out/fe/d5/Battle_of_Pharsalus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/4e/Alphonso_XI.txt ../out/ff/4e/Alphonso_XI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/ed/Capitol.txt ../out/ff/ed/Capitol.xml
