php ./wiki2xml/php/wiki2xml_command.php ../out/00/0a/Discrete_multitone_modulation.txt ../out/00/0a/Discrete_multitone_modulation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/00/db/AWK.txt ../out/00/db/AWK.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/9d/Electron_counting.txt ../out/01/9d/Electron_counting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/25/Acoustics.txt ../out/02/25/Acoustics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/db/Foreign_relations_of_Denmark.txt ../out/02/db/Foreign_relations_of_Denmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/7b/Alfonso_IX_of_Spain.txt ../out/03/7b/Alfonso_IX_of_Spain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/0b/Church%E2%80%93Turing_thesis.txt ../out/04/0b/Church%E2%80%93Turing_thesis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/89/List_of_comedians.txt ../out/04/89/List_of_comedians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/34/Chorded_keyboard.txt ../out/05/34/Chorded_keyboard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/b3/Black_hole.txt ../out/05/b3/Black_hole.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/57/Ericsson.txt ../out/06/57/Ericsson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/fc/CantorSet.txt ../out/06/fc/CantorSet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/ad/A_Little_Night_Music.txt ../out/07/ad/A_Little_Night_Music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/6e/Concord%2C_Michigan.txt ../out/08/6e/Concord%2C_Michigan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/e7/Antigua_And_Barbuda.txt ../out/08/e7/Antigua_And_Barbuda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/a8/Arthur_Aikin.txt ../out/09/a8/Arthur_Aikin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/84/DianeticS.txt ../out/0a/84/DianeticS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/f0/Archaeologist.txt ../out/0a/f0/Archaeologist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/9f/Arguments_for_the_existence_of_God.txt ../out/0b/9f/Arguments_for_the_existence_of_God.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/13/Complementary_DNA.txt ../out/0c/13/Complementary_DNA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/e5/Arabs.txt ../out/0c/e5/Arabs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/a3/Clean_Air_Act_%281970%29.txt ../out/0d/a3/Clean_Air_Act_%281970%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/36/Establishing_shot.txt ../out/0e/36/Establishing_shot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/de/Shogunate.txt ../out/0e/de/Shogunate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/94/Dziga_Vertov.txt ../out/0f/94/Dziga_Vertov.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/a0/CipheR.txt ../out/10/a0/CipheR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/48/Dada.txt ../out/11/48/Dada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/dc/Alexis_Korner.txt ../out/11/dc/Alexis_Korner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/93/Drosophila.txt ../out/12/93/Drosophila.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/2d/Motor_neuron_disease.txt ../out/13/2d/Motor_neuron_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/ba/Byzantine_fire.txt ../out/13/ba/Byzantine_fire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/82/Eyes_Wide_Shut.txt ../out/14/82/Eyes_Wide_Shut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/1d/Chromosome.txt ../out/15/1d/Chromosome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/ce/Douglas_Hofstadter.txt ../out/15/ce/Douglas_Hofstadter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/72/Executive_Order_9066.txt ../out/16/72/Executive_Order_9066.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/22/Alypius_of_Antioch.txt ../out/17/22/Alypius_of_Antioch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/fe/Backward_compatibility.txt ../out/17/fe/Backward_compatibility.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/7f/Amyntas_I_of_Macedon.txt ../out/18/7f/Amyntas_I_of_Macedon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/0c/December_27.txt ../out/19/0c/December_27.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/a0/Capitalism%2Fdifferent_meanings.txt ../out/19/a0/Capitalism%2Fdifferent_meanings.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/2a/Denis_Arkadievich_Kaufman.txt ../out/1a/2a/Denis_Arkadievich_Kaufman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/b1/Amphisbaena.txt ../out/1a/b1/Amphisbaena.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/3d/A_cappella.txt ../out/1b/3d/A_cappella.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/e1/Bayezid_II.txt ../out/1b/e1/Bayezid_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/54/ASL_%28disambiguation%29.txt ../out/1c/54/ASL_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/e3/Amstrad_CPC.txt ../out/1c/e3/Amstrad_CPC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/64/April_2.txt ../out/1d/64/April_2.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/21/Constitution_of_Canada%2F1867_X_Intercolonial_Railway.txt ../out/1e/21/Constitution_of_Canada%2F1867_X_Intercolonial_Railway.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/ac/Genetically_modified_maize.txt ../out/1e/ac/Genetically_modified_maize.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/a8/Battle_of_Adwa.txt ../out/1f/a8/Battle_of_Adwa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/44/DoubleStops.txt ../out/20/44/DoubleStops.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/fa/Constitution_of_Canada%2F1867_I_Preliminary.txt ../out/20/fa/Constitution_of_Canada%2F1867_I_Preliminary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/a7/Amasis_II.txt ../out/21/a7/Amasis_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/72/Nitrox.txt ../out/22/72/Nitrox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/10/Carbon_monoxide.txt ../out/23/10/Carbon_monoxide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/bf/Child_node.txt ../out/23/bf/Child_node.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/56/CryptologY.txt ../out/24/56/CryptologY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/17/Electronic_instruments.txt ../out/25/17/Electronic_instruments.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/ec/AM.txt ../out/25/ec/AM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/6b/Daniel_Gabriel_Fahrenheit.txt ../out/26/6b/Daniel_Gabriel_Fahrenheit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/0d/Comparative_law.txt ../out/27/0d/Comparative_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/ce/Discrete_mathematics.txt ../out/27/ce/Discrete_mathematics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/63/Bock.txt ../out/28/63/Bock.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/e6/Christians.txt ../out/28/e6/Christians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/9b/Boy_band.txt ../out/29/9b/Boy_band.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/46/Caesar_salad.txt ../out/2a/46/Caesar_salad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/39/Darwin_Awards.txt ../out/2b/39/Darwin_Awards.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/c1/Adrastea_%28moon%29.txt ../out/2b/c1/Adrastea_%28moon%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/5d/Axiom.txt ../out/2c/5d/Axiom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/fb/Bilskirnir.txt ../out/2c/fb/Bilskirnir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/a3/Copenhagen.txt ../out/2d/a3/Copenhagen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/58/Geography_of_the_British_Virgin_Islands.txt ../out/2e/58/Geography_of_the_British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/25/Ellis_Island.txt ../out/2f/25/Ellis_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/0d/Demon.txt ../out/30/0d/Demon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/c3/EuleR.txt ../out/30/c3/EuleR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/58/Articles_of_Confederation.txt ../out/31/58/Articles_of_Confederation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/5a/Agricultural_science.txt ../out/32/5a/Agricultural_science.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/e6/Anomalous_operation.txt ../out/32/e6/Anomalous_operation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/a6/ALGOL.txt ../out/33/a6/ALGOL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/a8/A_roll.txt ../out/34/a8/A_roll.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/0d/Stolen_base.txt ../out/35/0d/Stolen_base.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/be/European_Charter_for_Regional_or_Minority_Languages.txt ../out/35/be/European_Charter_for_Regional_or_Minority_Languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/86/Conductor.txt ../out/36/86/Conductor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/51/Answer.txt ../out/37/51/Answer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/cf/Appomattox.txt ../out/37/cf/Appomattox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/22/Volkssturm.txt ../out/38/22/Volkssturm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/f1/Monetary_policy_of_central_banks.txt ../out/38/f1/Monetary_policy_of_central_banks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/b7/Big_Dipper_%28disambiguation%29.txt ../out/39/b7/Big_Dipper_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/51/Actress.txt ../out/3a/51/Actress.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/c8/Crandall_University.txt ../out/3a/c8/Crandall_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/62/Chief_of_Naval_Operations.txt ../out/3b/62/Chief_of_Naval_Operations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/d0/Constitutional_law.txt ../out/3b/d0/Constitutional_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/70/Akita.txt ../out/3c/70/Akita.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/21/Avengers.txt ../out/3d/21/Avengers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/c2/Baptist_Church.txt ../out/3d/c2/Baptist_Church.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/8e/Elegiac_couplets.txt ../out/3e/8e/Elegiac_couplets.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/f7/Islamic_conquest_of_Afghanistan.txt ../out/3e/f7/Islamic_conquest_of_Afghanistan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/81/Branco_River.txt ../out/3f/81/Branco_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/36/History_of_Chile.txt ../out/40/36/History_of_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/c4/Domitius_Afer.txt ../out/40/c4/Domitius_Afer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/85/ALCS.txt ../out/41/85/ALCS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/d9/Coral_66.txt ../out/41/d9/Coral_66.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/4d/Classics.txt ../out/42/4d/Classics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/fc/Book_of_Nahum.txt ../out/42/fc/Book_of_Nahum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/91/Khmer_architecture.txt ../out/43/91/Khmer_architecture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/52/Antibiotics.txt ../out/44/52/Antibiotics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/a4/Doppler_effect.txt ../out/44/a4/Doppler_effect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/55/Air_show.txt ../out/45/55/Air_show.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/08/Electronic_mixer.txt ../out/46/08/Electronic_mixer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/ea/%C3%89variste_Galois.txt ../out/46/ea/%C3%89variste_Galois.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/76/The_Downward_Spiral.txt ../out/47/76/The_Downward_Spiral.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/52/Big_Dig.txt ../out/48/52/Big_Dig.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/f6/Anastasius_II.txt ../out/48/f6/Anastasius_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/a4/Eductor-jet_pump.txt ../out/49/a4/Eductor-jet_pump.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/4e/Conversion_of_units.txt ../out/4a/4e/Conversion_of_units.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/dc/Afghanistan_%281911_Encyclopedia%29.txt ../out/4a/dc/Afghanistan_%281911_Encyclopedia%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/70/Catalonia.txt ../out/4b/70/Catalonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/15/BOMARC.txt ../out/4c/15/BOMARC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/7f/Demographics_of_Dominica.txt ../out/4c/7f/Demographics_of_Dominica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/59/Cyclone_%28programming_language%29.txt ../out/4d/59/Cyclone_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/df/Capitalist.txt ../out/4d/df/Capitalist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/7e/Chinese_exclusion.txt ../out/4e/7e/Chinese_exclusion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/fa/American_Media_%28publisher%29.txt ../out/4e/fa/American_Media_%28publisher%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/d7/Alfred_the_Great.txt ../out/4f/d7/Alfred_the_Great.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/77/Doug_Engelbart.txt ../out/50/77/Doug_Engelbart.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/3e/Donald_E._Knuth.txt ../out/51/3e/Donald_E._Knuth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/ce/Ada_Lovelace.txt ../out/51/ce/Ada_Lovelace.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/77/Caribbean_Sea.txt ../out/52/77/Caribbean_Sea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/09/Elf.txt ../out/53/09/Elf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/b2/Elbing_%28disambiguation%29.txt ../out/53/b2/Elbing_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/28/Aedile.txt ../out/54/28/Aedile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/b8/Bert_Bell.txt ../out/54/b8/Bert_Bell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/84/Abatement_in_commerce.txt ../out/55/84/Abatement_in_commerce.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/11/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FH.txt ../out/56/11/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FH.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/1e/List_of_Atlas_Shrugged_characters.txt ../out/57/1e/List_of_Atlas_Shrugged_characters.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/d0/City.txt ../out/57/d0/City.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/66/Alexander_I_of_Serbia.txt ../out/58/66/Alexander_I_of_Serbia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/1c/Big_Brother_%28Nineteen_Eighty-Four%29.txt ../out/59/1c/Big_Brother_%28Nineteen_Eighty-Four%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/be/Economic_and_monetary_union.txt ../out/59/be/Economic_and_monetary_union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/40/Dallas_Cowboys.txt ../out/5a/40/Dallas_Cowboys.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/c4/Economy_of_Brunei.txt ../out/5a/c4/Economy_of_Brunei.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/63/Dsungaripterus.txt ../out/5b/63/Dsungaripterus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/17/BIND.txt ../out/5c/17/BIND.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/b9/Cement.txt ../out/5c/b9/Cement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/95/Cecilia_Beaux.txt ../out/5d/95/Cecilia_Beaux.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/4a/Cholistan_Desert.txt ../out/5e/4a/Cholistan_Desert.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/bc/Aedui.txt ../out/5e/bc/Aedui.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/97/Government_of_Belarus.txt ../out/5f/97/Government_of_Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/32/Duopoly.txt ../out/60/32/Duopoly.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/f4/Alexandrine.txt ../out/60/f4/Alexandrine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/7e/Carboniferous.txt ../out/61/7e/Carboniferous.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/1f/Constantin_Br%C3%A2ncu%C8%99i.txt ../out/62/1f/Constantin_Br%C3%A2ncu%C8%99i.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/18/Cosmological_argument.txt ../out/63/18/Cosmological_argument.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/cf/Digital_compositing.txt ../out/63/cf/Digital_compositing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/bf/ACN.txt ../out/64/bf/ACN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/34/Astounding_Science_Fiction.txt ../out/65/34/Astounding_Science_Fiction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/d3/Apple_Inc..txt ../out/65/d3/Apple_Inc..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/2e/Dedham%2C_Massachusetts.txt ../out/66/2e/Dedham%2C_Massachusetts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/ed/Abbess.txt ../out/66/ed/Abbess.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/72/Cold_War_%281947%E2%80%9353%29.txt ../out/67/72/Cold_War_%281947%E2%80%9353%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/02/Cayman_Islands.txt ../out/68/02/Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/b6/Ashmore_and_Cartier_Islands%2FPeople.txt ../out/68/b6/Ashmore_and_Cartier_Islands%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/86/Apoptosis.txt ../out/69/86/Apoptosis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/2d/Argument_by_lack_of_imagination.txt ../out/6a/2d/Argument_by_lack_of_imagination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/b6/Encyclopedia_Britannica.txt ../out/6a/b6/Encyclopedia_Britannica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/2f/Bell_Curve.txt ../out/6b/2f/Bell_Curve.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/e1/American_war_of_independence.txt ../out/6b/e1/American_war_of_independence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/5a/Dolores_Fuller.txt ../out/6c/5a/Dolores_Fuller.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/e9/Christopher_Alexander.txt ../out/6c/e9/Christopher_Alexander.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/96/Caddy.txt ../out/6d/96/Caddy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/21/Ethical_naturalism.txt ../out/6e/21/Ethical_naturalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/ab/Cardinality.txt ../out/6e/ab/Cardinality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/27/Ascorbic_Acid.txt ../out/6f/27/Ascorbic_Acid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/fe/American_Sign_Language.txt ../out/6f/fe/American_Sign_Language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/b2/Car_Talk.txt ../out/70/b2/Car_Talk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/9c/Complete_metric_space.txt ../out/71/9c/Complete_metric_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/1f/Brit_milah.txt ../out/72/1f/Brit_milah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/de/American_Revolution.txt ../out/72/de/American_Revolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/9e/Analysis.txt ../out/73/9e/Analysis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/4c/Boone%2C_North_Carolina.txt ../out/74/4c/Boone%2C_North_Carolina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/9f/Abattoir.txt ../out/74/9f/Abattoir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/3e/Aries_%28constellation%29.txt ../out/75/3e/Aries_%28constellation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/05/Transport_in_Cyprus.txt ../out/76/05/Transport_in_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/9f/Acorn_%28fruit_of_the_oak_tree%29.txt ../out/76/9f/Acorn_%28fruit_of_the_oak_tree%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/46/Consumption.txt ../out/77/46/Consumption.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/fa/Military_of_Christmas_Island.txt ../out/77/fa/Military_of_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/b3/Emily_Bront%C3%AB.txt ../out/78/b3/Emily_Bront%C3%AB.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/2b/Asgard.txt ../out/79/2b/Asgard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/c3/Euclidean_space.txt ../out/79/c3/Euclidean_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/61/Arthur_Wellesley%2C_1st_Duke_of_Wellington.txt ../out/7a/61/Arthur_Wellesley%2C_1st_Duke_of_Wellington.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/a4/Arthritis.txt ../out/7a/a4/Arthritis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/55/Adrian_VI.txt ../out/7b/55/Adrian_VI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/24/History_of_the_Cayman_Islands.txt ../out/7c/24/History_of_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/d5/Abbas_II_of_Egypt.txt ../out/7c/d5/Abbas_II_of_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/54/Economy_of_American_Samoa.txt ../out/7d/54/Economy_of_American_Samoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/0a/Chain_reaction.txt ../out/7e/0a/Chain_reaction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/9a/List_of_centuries.txt ../out/7e/9a/List_of_centuries.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/6a/August_27.txt ../out/7f/6a/August_27.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/d9/Demographics_of_Equatorial_Guinea.txt ../out/7f/d9/Demographics_of_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/3d/Albert_II.txt ../out/80/3d/Albert_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/ef/CNO_cycle.txt ../out/80/ef/CNO_cycle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/8d/DCM.txt ../out/81/8d/DCM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/54/Anemometer.txt ../out/82/54/Anemometer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/3c/Billy_Bob_Thornton.txt ../out/83/3c/Billy_Bob_Thornton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/cc/DegreeConfluenceProject.txt ../out/83/cc/DegreeConfluenceProject.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/ac/Bomber.txt ../out/84/ac/Bomber.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/43/Transport_in_Belarus.txt ../out/85/43/Transport_in_Belarus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/cb/Akio_Morita.txt ../out/85/cb/Akio_Morita.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/7c/Easter_Sunday.txt ../out/86/7c/Easter_Sunday.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/1a/Aberdeenshire%2FAberdeenshire1911.txt ../out/87/1a/Aberdeenshire%2FAberdeenshire1911.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/d3/Common_preference.txt ../out/87/d3/Common_preference.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/9a/Bunge_y_Born.txt ../out/88/9a/Bunge_y_Born.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/3e/Differentiability.txt ../out/89/3e/Differentiability.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/ec/And_did_those_feet_in_ancient_time.txt ../out/89/ec/And_did_those_feet_in_ancient_time.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/7d/Agapanthus_africanus.txt ../out/8a/7d/Agapanthus_africanus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/37/Unit_of_alcohol.txt ../out/8b/37/Unit_of_alcohol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/c7/Bohemia.txt ../out/8b/c7/Bohemia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/86/Beryllium.txt ../out/8c/86/Beryllium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/00/British_Indian_Ocean_Territory%2FTransportation.txt ../out/8d/00/British_Indian_Ocean_Territory%2FTransportation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/9f/AfghanistanTransportations.txt ../out/8d/9f/AfghanistanTransportations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/7a/Bioleaching.txt ../out/8e/7a/Bioleaching.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/60/Composers.txt ../out/8f/60/Composers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/08/Alfonso_the_Battler.txt ../out/90/08/Alfonso_the_Battler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/d8/Ballroom_dancing.txt ../out/90/d8/Ballroom_dancing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/84/Ardipithecus.txt ../out/91/84/Ardipithecus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/93/Bohr_model.txt ../out/92/93/Bohr_model.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/37/Cavalry.txt ../out/93/37/Cavalry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/e6/Eurovision_Song_Contest.txt ../out/93/e6/Eurovision_Song_Contest.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/f1/Cumberland_%28disambiguation%29.txt ../out/94/f1/Cumberland_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/66/Brian_Aldiss.txt ../out/95/66/Brian_Aldiss.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/11/Benjamin_Franklin.txt ../out/96/11/Benjamin_Franklin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/bc/Canon_law.txt ../out/96/bc/Canon_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/5e/Bombardier_Inc..txt ../out/97/5e/Bombardier_Inc..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/dc/Blackbeard.txt ../out/97/dc/Blackbeard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/56/Aa.txt ../out/98/56/Aa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/0a/Antioxidant.txt ../out/99/0a/Antioxidant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/7f/Common_Language_Infrastructure.txt ../out/99/7f/Common_Language_Infrastructure.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/f8/Carol_Kane.txt ../out/99/f8/Carol_Kane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/76/Dune_computer_and_video_games.txt ../out/9a/76/Dune_computer_and_video_games.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/20/Aluminium.txt ../out/9b/20/Aluminium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/c0/Basis.txt ../out/9b/c0/Basis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/36/EigenVector.txt ../out/9c/36/EigenVector.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/ce/Physical_cosmology.txt ../out/9c/ce/Physical_cosmology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/71/Ambrosians.txt ../out/9d/71/Ambrosians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/0a/Boeing_C-17_Globemaster_III.txt ../out/9e/0a/Boeing_C-17_Globemaster_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/d1/August_16.txt ../out/9e/d1/August_16.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/97/Al_Capone.txt ../out/9f/97/Al_Capone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/2c/Ethnology.txt ../out/a0/2c/Ethnology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/f5/Campus.txt ../out/a0/f5/Campus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/cf/Churchill.txt ../out/a1/cf/Churchill.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/96/Cube.txt ../out/a2/96/Cube.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/2a/Dragon_32%2F64.txt ../out/a3/2a/Dragon_32%2F64.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/e3/Commodore_%28rank%29.txt ../out/a3/e3/Commodore_%28rank%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/af/Coca_Cola.txt ../out/a4/af/Coca_Cola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/17/August_3.txt ../out/a5/17/August_3.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/8e/Alphonso_XII.txt ../out/a5/8e/Alphonso_XII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/3a/Brainfuck_programming_language%2FExamples.txt ../out/a6/3a/Brainfuck_programming_language%2FExamples.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/f3/American_Airlines_Flight_77.txt ../out/a6/f3/American_Airlines_Flight_77.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/87/Key_size.txt ../out/a7/87/Key_size.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/72/Epistle_to_the_Colossians.txt ../out/a8/72/Epistle_to_the_Colossians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/15/Customs_union.txt ../out/a9/15/Customs_union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/0c/Document_Editor.txt ../out/aa/0c/Document_Editor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/7f/Dianic_Wicca.txt ../out/aa/7f/Dianic_Wicca.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/f4/Telecommunications_in_Ethiopia.txt ../out/aa/f4/Telecommunications_in_Ethiopia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/8f/Computer_jargon.txt ../out/ab/8f/Computer_jargon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/2b/Castagna.txt ../out/ac/2b/Castagna.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/a2/Blues.txt ../out/ac/a2/Blues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/23/Airbus_A300.txt ../out/ad/23/Airbus_A300.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/f2/Casablanca.txt ../out/ad/f2/Casablanca.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/8e/Amaltheia.txt ../out/ae/8e/Amaltheia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/2d/Bead_weaving.txt ../out/af/2d/Bead_weaving.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/9c/Chrono_Cross.txt ../out/af/9c/Chrono_Cross.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/45/Anti-tank_vehicles.txt ../out/b0/45/Anti-tank_vehicles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/03/Artistic_License.txt ../out/b1/03/Artistic_License.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/9e/Extreme_Unction.txt ../out/b1/9e/Extreme_Unction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/fa/Transportation_in_Baker_Island.txt ../out/b1/fa/Transportation_in_Baker_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/d8/ARY_Group.txt ../out/b2/d8/ARY_Group.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/c2/CAMP.txt ../out/b3/c2/CAMP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/61/Epistle_to_Philemon.txt ../out/b4/61/Epistle_to_Philemon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/c2/Campaign_for_Real_Ale.txt ../out/b4/c2/Campaign_for_Real_Ale.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/15/Economy_of_Eritrea.txt ../out/b5/15/Economy_of_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/8e/Channel_Islands%2FJersey.txt ../out/b5/8e/Channel_Islands%2FJersey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/2c/Battle_of_Bouvines.txt ../out/b6/2c/Battle_of_Bouvines.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/0d/Enterprise_resource_planning.txt ../out/b7/0d/Enterprise_resource_planning.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/b4/ASA.txt ../out/b7/b4/ASA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/53/English_language%2FBritish_English.txt ../out/b8/53/English_language%2FBritish_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/d8/December_5.txt ../out/b8/d8/December_5.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/c6/Chardonnay_socialist.txt ../out/b9/c6/Chardonnay_socialist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/3d/Dennis_Hopper.txt ../out/ba/3d/Dennis_Hopper.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/06/Archery.txt ../out/bb/06/Archery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/8a/Cryptomonads.txt ../out/bb/8a/Cryptomonads.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/1e/Clarke%27s_three_laws.txt ../out/bc/1e/Clarke%27s_three_laws.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/b4/BMW.txt ../out/bc/b4/BMW.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/7b/Christian_persecution.txt ../out/bd/7b/Christian_persecution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/53/Chojn%C3%B3w.txt ../out/be/53/Chojn%C3%B3w.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/fe/Christine_Lavin.txt ../out/be/fe/Christine_Lavin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/a0/Telecommunications_in_the_Dominican_Republic.txt ../out/bf/a0/Telecommunications_in_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/64/Cult_Film.txt ../out/c0/64/Cult_Film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/35/BRP.txt ../out/c1/35/BRP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/b3/Dieting.txt ../out/c1/b3/Dieting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/82/Age_of_consent.txt ../out/c2/82/Age_of_consent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/5c/Algemeen_Nijmeegs_Studentenblad.txt ../out/c3/5c/Algemeen_Nijmeegs_Studentenblad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/d7/Alfonso_XIII_of_Spain.txt ../out/c3/d7/Alfonso_XIII_of_Spain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/5f/Allotrope.txt ../out/c4/5f/Allotrope.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/19/Blackridge%2C_Pennsylvania.txt ../out/c5/19/Blackridge%2C_Pennsylvania.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/0e/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FX.txt ../out/c6/0e/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/d3/Analgesic.txt ../out/c6/d3/Analgesic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/7a/Armor.txt ../out/c7/7a/Armor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/36/Bug.txt ../out/c8/36/Bug.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/08/DDR_SDRAM.txt ../out/c9/08/DDR_SDRAM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/95/Wikipedia%3ABuilding_Wikipedia_membership.txt ../out/c9/95/Wikipedia%3ABuilding_Wikipedia_membership.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/0d/Code.txt ../out/ca/0d/Code.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/eb/Concordat_of_Worms.txt ../out/ca/eb/Concordat_of_Worms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/81/Crokinole.txt ../out/cb/81/Crokinole.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/80/Computer_networking.txt ../out/cc/80/Computer_networking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/ff/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FB2.txt ../out/cc/ff/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FB2.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/a6/Antoine_Lavoisier.txt ../out/cd/a6/Antoine_Lavoisier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/5d/Color_space_encoding.txt ../out/ce/5d/Color_space_encoding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/1b/Why_It_Went_Wrong.txt ../out/cf/1b/Why_It_Went_Wrong.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/d3/Cardiovascular_system.txt ../out/cf/d3/Cardiovascular_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/a0/Economy_of_the_Central_African_Republic.txt ../out/d0/a0/Economy_of_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/50/Cell_biology.txt ../out/d1/50/Cell_biology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/0c/Colonna_family.txt ../out/d2/0c/Colonna_family.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/ae/Diamagnetism.txt ../out/d2/ae/Diamagnetism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/53/Caliph.txt ../out/d3/53/Caliph.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/dc/BE.txt ../out/d3/dc/BE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/ba/Computational_complexity.txt ../out/d4/ba/Computational_complexity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/59/Agate.txt ../out/d5/59/Agate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/fd/Dr._Dre.txt ../out/d5/fd/Dr._Dre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/98/Banda.txt ../out/d6/98/Banda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/32/Austria-Hungary.txt ../out/d7/32/Austria-Hungary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/c5/Etruscan_language.txt ../out/d7/c5/Etruscan_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/a2/Abacus.txt ../out/d8/a2/Abacus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/2c/Bill.txt ../out/d9/2c/Bill.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/d5/Arbor_Day.txt ../out/d9/d5/Arbor_Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/92/Demographics_of_Botswana.txt ../out/da/92/Demographics_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/19/Christopher_B%C3%A1thory.txt ../out/db/19/Christopher_B%C3%A1thory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/bf/Computer_expo.txt ../out/db/bf/Computer_expo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/58/Catan%3A_Cities_%26_Knights.txt ../out/dc/58/Catan%3A_Cities_%26_Knights.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/11/Eigenstate.txt ../out/dd/11/Eigenstate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/93/Computer_memory.txt ../out/dd/93/Computer_memory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/70/Colorado_Rockies.txt ../out/de/70/Colorado_Rockies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/fb/CCC.txt ../out/de/fb/CCC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/a7/Dyson_Sphere.txt ../out/df/a7/Dyson_Sphere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/67/Electrical_engineering.txt ../out/e0/67/Electrical_engineering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/40/Athens.txt ../out/e1/40/Athens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/e3/Acid%E2%80%93base_reaction.txt ../out/e1/e3/Acid%E2%80%93base_reaction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/9e/Battle_of_Marathon.txt ../out/e2/9e/Battle_of_Marathon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/36/Ancient_philosophy.txt ../out/e3/36/Ancient_philosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/d8/AlbaniaGovernment.txt ../out/e3/d8/AlbaniaGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/96/Congo.txt ../out/e4/96/Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/25/Chelsea_F.C..txt ../out/e5/25/Chelsea_F.C..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/d1/Alphorn.txt ../out/e5/d1/Alphorn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/6b/Brisbane_Broncos.txt ../out/e6/6b/Brisbane_Broncos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/47/Dancing.txt ../out/e7/47/Dancing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/11/Anti-Ballistic_Missile_Treaty.txt ../out/e8/11/Anti-Ballistic_Missile_Treaty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/a8/Equuleus.txt ../out/e8/a8/Equuleus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/28/Bolsheviks.txt ../out/e9/28/Bolsheviks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/a9/Cartzonna.txt ../out/e9/a9/Cartzonna.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/1b/BCPL.txt ../out/ea/1b/BCPL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/e2/Appellate_court.txt ../out/ea/e2/Appellate_court.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/66/Politics_of_Brazil.txt ../out/eb/66/Politics_of_Brazil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/5f/Cygwin.txt ../out/ec/5f/Cygwin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/1d/AfghanistanHistory.txt ../out/ed/1d/AfghanistanHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/ac/Cecil_B._DeMille.txt ../out/ed/ac/Cecil_B._DeMille.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/47/BioChemistry.txt ../out/ee/47/BioChemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/ce/Bluetooth_Special_Interest_Group.txt ../out/ee/ce/Bluetooth_Special_Interest_Group.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/8f/Auto_racing.txt ../out/ef/8f/Auto_racing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/2d/Azincourt.txt ../out/f0/2d/Azincourt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/cd/Carl_Linnaeus.txt ../out/f0/cd/Carl_Linnaeus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/a9/Baltic_Sea%2FElblag.txt ../out/f1/a9/Baltic_Sea%2FElblag.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/6b/ErnestHemingway%2FFamousatTwentyFiveThirtyaMaster.txt ../out/f2/6b/ErnestHemingway%2FFamousatTwentyFiveThirtyaMaster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/5b/ErnestHemingway%2FRobertJordan.txt ../out/f3/5b/ErnestHemingway%2FRobertJordan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/0a/Clanking_replicator.txt ../out/f4/0a/Clanking_replicator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/0b/Bouvet_Island%2FPeople.txt ../out/f5/0b/Bouvet_Island%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/ae/A._E._van_Vogt.txt ../out/f5/ae/A._E._van_Vogt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/5f/Albert_of_Brandenburg_Prussia.txt ../out/f6/5f/Albert_of_Brandenburg_Prussia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/f1/B.F._Skinner.txt ../out/f6/f1/B.F._Skinner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/74/Politics_of_Colombia.txt ../out/f7/74/Politics_of_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/57/Amiga_500_Plus.txt ../out/f8/57/Amiga_500_Plus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/e0/CDE.txt ../out/f8/e0/CDE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/43/Chang_San-feng.txt ../out/f9/43/Chang_San-feng.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/ea/British_Empire.txt ../out/f9/ea/British_Empire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/5a/Amalric.txt ../out/fa/5a/Amalric.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/24/Andrew_Jackson.txt ../out/fb/24/Andrew_Jackson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/c3/Bongo_%28antelope%29.txt ../out/fb/c3/Bongo_%28antelope%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/bc/Charles_S._Peirce.txt ../out/fc/bc/Charles_S._Peirce.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/71/Cardiology.txt ../out/fd/71/Cardiology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/0b/David_Beckham.txt ../out/fe/0b/David_Beckham.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/d4/Andhra_Pradesh.txt ../out/fe/d4/Andhra_Pradesh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/4a/Character_set.txt ../out/ff/4a/Character_set.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/cc/Alcamenes.txt ../out/ff/cc/Alcamenes.xml
