php ./wiki2xml/php/wiki2xml_command.php ../out/00/9a/Abatement_of_debts_and_legacies.txt ../out/00/9a/Abatement_of_debts_and_legacies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/3e/Disjunction_introduction.txt ../out/01/3e/Disjunction_introduction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/ce/Common_lisp.txt ../out/01/ce/Common_lisp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/a1/Geography_of_Antarctica.txt ../out/02/a1/Geography_of_Antarctica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/42/Alexander_IV.txt ../out/03/42/Alexander_IV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/e4/CLU_%28programming_language%29.txt ../out/03/e4/CLU_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/6d/Bandy.txt ../out/04/6d/Bandy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/11/Book_of_Esther.txt ../out/05/11/Book_of_Esther.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/78/Culture_of_Canada.txt ../out/05/78/Culture_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/06/Transport_in_Antarctica.txt ../out/06/06/Transport_in_Antarctica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/cf/AOLamer.txt ../out/06/cf/AOLamer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/73/Ernst_Mayr.txt ../out/07/73/Ernst_Mayr.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/34/Big_Audio_Dynamite.txt ../out/08/34/Big_Audio_Dynamite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/b7/Cipro.txt ../out/08/b7/Cipro.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/7f/Burns_supper.txt ../out/09/7f/Burns_supper.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/41/Armed_Forces_of_El_Salvador.txt ../out/0a/41/Armed_Forces_of_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/b3/Cholesterol.txt ../out/0a/b3/Cholesterol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/86/Amiga_1000.txt ../out/0b/86/Amiga_1000.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/df/Absolute_magnitude.txt ../out/0b/df/Absolute_magnitude.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/8a/Borromini%2C_Francesco.txt ../out/0c/8a/Borromini%2C_Francesco.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/6c/AtlasShruggedCompanies.txt ../out/0d/6c/AtlasShruggedCompanies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/25/Camelot.txt ../out/0e/25/Camelot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/b5/Dissolve.txt ../out/0e/b5/Dissolve.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/61/Amputees.txt ../out/0f/61/Amputees.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/31/Diatomic_molecule.txt ../out/10/31/Diatomic_molecule.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/22/Allah.txt ../out/11/22/Allah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/c6/Telecommunications_in_Bulgaria.txt ../out/11/c6/Telecommunications_in_Bulgaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/6d/Benjamin_Disraeli.txt ../out/12/6d/Benjamin_Disraeli.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/ff/Cthulhu_Mythos.txt ../out/12/ff/Cthulhu_Mythos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/7d/Cernunnos.txt ../out/13/7d/Cernunnos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/44/Connection_%28dance%29.txt ../out/14/44/Connection_%28dance%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/fd/Affray.txt ../out/14/fd/Affray.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/62/Continuum_Hypothesis..txt ../out/15/62/Continuum_Hypothesis..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/3b/Bare_particular.txt ../out/16/3b/Bare_particular.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/cb/Algebraic_closure.txt ../out/16/cb/Algebraic_closure.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/b7/Condom.txt ../out/17/b7/Condom.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/4e/Alexander_VIII.txt ../out/18/4e/Alexander_VIII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/d7/Extended_Industry_Standard_Architecture.txt ../out/18/d7/Extended_Industry_Standard_Architecture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/68/European_Council.txt ../out/19/68/European_Council.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/fe/Amine.txt ../out/19/fe/Amine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/9a/Clement_Attlee.txt ../out/1a/9a/Clement_Attlee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/15/Deep_Space_1.txt ../out/1b/15/Deep_Space_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/a7/Controlled_Substances_Act.txt ../out/1b/a7/Controlled_Substances_Act.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/33/European_Parliament.txt ../out/1c/33/European_Parliament.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/b0/Park_G%C3%BCell.txt ../out/1c/b0/Park_G%C3%BCell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/40/Edmund_Husserl.txt ../out/1d/40/Edmund_Husserl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/f1/Diaspora_studies.txt ../out/1d/f1/Diaspora_studies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/90/Buttfuck.txt ../out/1e/90/Buttfuck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/6d/Batman_%281966_film%29.txt ../out/1f/6d/Batman_%281966_film%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/25/Celestial_dynamics.txt ../out/20/25/Celestial_dynamics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/bc/Belize.txt ../out/20/bc/Belize.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/5c/Geography_of_Djibouti.txt ../out/21/5c/Geography_of_Djibouti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/59/ErnestHemingway%2FSureShotsTheSecondWorldWar.txt ../out/22/59/ErnestHemingway%2FSureShotsTheSecondWorldWar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/ef/Cannon.txt ../out/22/ef/Cannon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/90/DataEncryptionStandard.txt ../out/23/90/DataEncryptionStandard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/2f/History_of_the_Democratic_Republic_of_the_Congo.txt ../out/24/2f/History_of_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/de/Flag_of_Denmark.txt ../out/24/de/Flag_of_Denmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/c8/Central_Coast.txt ../out/25/c8/Central_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/36/Ernest_Hemingway%2FBibliography.txt ../out/26/36/Ernest_Hemingway%2FBibliography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/fb/Cow_tipping.txt ../out/26/fb/Cow_tipping.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/98/Banach_algebra.txt ../out/27/98/Banach_algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/31/Coral_Sea_Islands%2FTransportation.txt ../out/28/31/Coral_Sea_Islands%2FTransportation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/c0/Computing.txt ../out/28/c0/Computing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/78/Christopher_Houston.txt ../out/29/78/Christopher_Houston.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/21/Cantor_Fitzgerald.txt ../out/2a/21/Cantor_Fitzgerald.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/ef/Communications_in_Bouvet_Island.txt ../out/2a/ef/Communications_in_Bouvet_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/76/Cell_Cycle_%28journal%29.txt ../out/2b/76/Cell_Cycle_%28journal%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/28/Dragon_32.txt ../out/2c/28/Dragon_32.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/b4/Transport_in_Cambodia.txt ../out/2c/b4/Transport_in_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/54/Empedocles.txt ../out/2d/54/Empedocles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/16/Buckminster_Fuller.txt ../out/2e/16/Buckminster_Fuller.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/d6/Balfour_declaration.txt ../out/2e/d6/Balfour_declaration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/8b/Amplitude_modulation.txt ../out/2f/8b/Amplitude_modulation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/95/Circle.txt ../out/30/95/Circle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/1e/Blitz.txt ../out/31/1e/Blitz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/08/Catenary.txt ../out/32/08/Catenary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/cc/List_of_Anglo-Saxon_monarchs_and_kingdoms.txt ../out/32/cc/List_of_Anglo-Saxon_monarchs_and_kingdoms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/42/Dark_matter.txt ../out/33/42/Dark_matter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/52/AElfric.txt ../out/34/52/AElfric.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/e8/British_Indian_Ocean_Territory%2FTransnational_issues.txt ../out/34/e8/British_Indian_Ocean_Territory%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/8a/Derivative_%28finance%29.txt ../out/35/8a/Derivative_%28finance%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/72/Alexander_Solzhenitsyn.txt ../out/36/72/Alexander_Solzhenitsyn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/1f/Democide.txt ../out/37/1f/Democide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/a2/1903_World_Series.txt ../out/37/a2/1903_World_Series.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/0f/Cosmic_censorship_hypothesis.txt ../out/38/0f/Cosmic_censorship_hypothesis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/8c/Borel_measure.txt ../out/38/8c/Borel_measure.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/99/Apache_HTTP_Server.txt ../out/39/99/Apache_HTTP_Server.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/27/Cetacean.txt ../out/3a/27/Cetacean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/a4/B.C.txt ../out/3a/a4/B.C.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/35/Aldona_of_Lithuania.txt ../out/3b/35/Aldona_of_Lithuania.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/b7/Compiler.txt ../out/3b/b7/Compiler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/41/BSA.txt ../out/3c/41/BSA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/01/ALADI.txt ../out/3d/01/ALADI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/80/Alexander_Mackenzie.txt ../out/3d/80/Alexander_Mackenzie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/42/Demographics_of_Costa_Rica.txt ../out/3e/42/Demographics_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/d8/Comic.txt ../out/3e/d8/Comic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/33/Banquo.txt ../out/3f/33/Banquo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/e9/C._S._Lewis.txt ../out/3f/e9/C._S._Lewis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/9c/ChoosingSummaryStatistics.txt ../out/40/9c/ChoosingSummaryStatistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/4b/Aleister_Crowley.txt ../out/41/4b/Aleister_Crowley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/cc/Foreign_relations_of_Cambodia.txt ../out/41/cc/Foreign_relations_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/18/Computation.txt ../out/42/18/Computation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/a0/%C3%87evik_Bir.txt ../out/42/a0/%C3%87evik_Bir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/7c/Clock_wipe.txt ../out/43/7c/Clock_wipe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/0e/Things_Turn_Sour.txt ../out/44/0e/Things_Turn_Sour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/95/Coal_tar.txt ../out/44/95/Coal_tar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/34/Dennis_the_Menace%2FGnasher.txt ../out/45/34/Dennis_the_Menace%2FGnasher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/f6/Aage_Bohr.txt ../out/45/f6/Aage_Bohr.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/6d/Ambracia.txt ../out/46/6d/Ambracia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/4b/Anointing_of_the_Sick.txt ../out/47/4b/Anointing_of_the_Sick.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/ed/British_Indian_Ocean_Territory%2FGovernment.txt ../out/47/ed/British_Indian_Ocean_Territory%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/ac/Dementia_praecox.txt ../out/48/ac/Dementia_praecox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/55/Transportation_in_Canada.txt ../out/49/55/Transportation_in_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/e8/Coral_Sea_Islands.txt ../out/49/e8/Coral_Sea_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/a5/Calico_%28textile%29.txt ../out/4a/a5/Calico_%28textile%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/35/Chlorophyceae.txt ../out/4b/35/Chlorophyceae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/e2/Cameroon.txt ../out/4b/e2/Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/5a/Cow_%28disambiguation%29.txt ../out/4c/5a/Cow_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/32/Demographics_of_the_Cocos_%28Keeling%29_Islands.txt ../out/4d/32/Demographics_of_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/a8/Cheka.txt ../out/4d/a8/Cheka.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/36/Coral_Sea_Islands%2FEconomy.txt ../out/4e/36/Coral_Sea_Islands%2FEconomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/dc/Albert_Frederick%2C_Duke_of_Prussia.txt ../out/4e/dc/Albert_Frederick%2C_Duke_of_Prussia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/82/Autrefois_convict.txt ../out/4f/82/Autrefois_convict.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/49/Bill_Joy.txt ../out/50/49/Bill_Joy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/0c/A.D._Police%3A_Dead_End_City.txt ../out/51/0c/A.D._Police%3A_Dead_End_City.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/97/April%2C_May_and_June_Duck.txt ../out/51/97/April%2C_May_and_June_Duck.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/42/Citric_acid_cycle.txt ../out/52/42/Citric_acid_cycle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/fd/DirkJan.txt ../out/52/fd/DirkJan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/92/Dale_Chihuly.txt ../out/53/92/Dale_Chihuly.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/08/Democrat.txt ../out/54/08/Democrat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/98/Cyclops_%28disambiguation%29.txt ../out/54/98/Cyclops_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/23/Alternative_history.txt ../out/55/23/Alternative_history.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/ea/Chaitin%27s_constant.txt ../out/55/ea/Chaitin%27s_constant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/d5/Class_warfare.txt ../out/56/d5/Class_warfare.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/88/Bible.txt ../out/57/88/Bible.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/3f/Dragon.txt ../out/58/3f/Dragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/e7/Distributed_programming.txt ../out/58/e7/Distributed_programming.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/5a/Computational_complexity_theory.txt ../out/59/5a/Computational_complexity_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/f2/Bathyscaphe_Trieste.txt ../out/59/f2/Bathyscaphe_Trieste.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/85/Edward_Sapir.txt ../out/5a/85/Edward_Sapir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/17/Abenezra.txt ../out/5b/17/Abenezra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/c5/A_fortiori.txt ../out/5b/c5/A_fortiori.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/7e/Computer_vision.txt ../out/5c/7e/Computer_vision.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/38/AGM-88_HARM.txt ../out/5d/38/AGM-88_HARM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/0d/Carl_Meinhof.txt ../out/5e/0d/Carl_Meinhof.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/8f/Atlas_computer.txt ../out/5e/8f/Atlas_computer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/3b/Abatement_of_a_nuisance.txt ../out/5f/3b/Abatement_of_a_nuisance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/05/Apache_webserver.txt ../out/60/05/Apache_webserver.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/a6/Impact_crater.txt ../out/60/a6/Impact_crater.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/66/Electric_bus_%28disambiguation%29.txt ../out/61/66/Electric_bus_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/d4/Ceawlin_of_Wessex.txt ../out/61/d4/Ceawlin_of_Wessex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/ab/Collective_noun.txt ../out/62/ab/Collective_noun.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/92/Cartoonists.txt ../out/63/92/Cartoonists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/8f/Blitz_BASIC.txt ../out/64/8f/Blitz_BASIC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/19/Geography_of_Denmark.txt ../out/65/19/Geography_of_Denmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/7b/Division_ring.txt ../out/65/7b/Division_ring.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/0e/Ernst_Haeckel.txt ../out/66/0e/Ernst_Haeckel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/ab/Inflation_%28cosmology%29.txt ../out/66/ab/Inflation_%28cosmology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/28/Adventism.txt ../out/67/28/Adventism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/e4/Caesium.txt ../out/67/e4/Caesium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/78/Chianti.txt ../out/68/78/Chianti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/4b/Alpha_Centauri.txt ../out/69/4b/Alpha_Centauri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/01/Dictatorship.txt ../out/6a/01/Dictatorship.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/95/BusinessSchool.txt ../out/6a/95/BusinessSchool.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/00/Douglas_Adams.txt ../out/6b/00/Douglas_Adams.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/b3/Atari_2600.txt ../out/6b/b3/Atari_2600.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/40/Ajaccio.txt ../out/6c/40/Ajaccio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/c9/AU.txt ../out/6c/c9/AU.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/60/EquivalenceRelation.txt ../out/6d/60/EquivalenceRelation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/e8/CodE.txt ../out/6d/e8/CodE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/92/The_Bahamas.txt ../out/6e/92/The_Bahamas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/f3/Absolute_zero.txt ../out/6e/f3/Absolute_zero.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/b4/Applet.txt ../out/6f/b4/Applet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/93/Blissymbols.txt ../out/70/93/Blissymbols.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/5c/A_Clockwork_Orange.txt ../out/71/5c/A_Clockwork_Orange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/0b/Coming_out_of_the_closet.txt ../out/72/0b/Coming_out_of_the_closet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/82/Demographics_of_Burkina_Faso.txt ../out/72/82/Demographics_of_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/67/Eubulides.txt ../out/73/67/Eubulides.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/1c/Brain_event.txt ../out/74/1c/Brain_event.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/7d/Battle.txt ../out/74/7d/Battle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/18/The_Maritimes.txt ../out/75/18/The_Maritimes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/aa/Cimbri.txt ../out/75/aa/Cimbri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/72/Ampage.txt ../out/76/72/Ampage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/f8/Council_of_Trent.txt ../out/76/f8/Council_of_Trent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/b9/Digital_video_disc.txt ../out/77/b9/Digital_video_disc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/7a/Diogo_C%C3%A3o.txt ../out/78/7a/Diogo_C%C3%A3o.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/db/Cocos_Islands%2FEconomy.txt ../out/78/db/Cocos_Islands%2FEconomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/a9/Castello.txt ../out/79/a9/Castello.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/3a/House_of_della_Rovere.txt ../out/7a/3a/House_of_della_Rovere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/8f/Bloomfield%2C_Leonard.txt ../out/7a/8f/Bloomfield%2C_Leonard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/35/Atari_7800.txt ../out/7b/35/Atari_7800.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/f4/Book_of_Job.txt ../out/7b/f4/Book_of_Job.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/a6/Earth_Sciences_basic_topics.txt ../out/7c/a6/Earth_Sciences_basic_topics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/21/Aspergers_disorder.txt ../out/7d/21/Aspergers_disorder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/ef/Bluetooth.txt ../out/7d/ef/Bluetooth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/60/Auger_effect.txt ../out/7e/60/Auger_effect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/1b/Existence.txt ../out/7f/1b/Existence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/b3/Ajax_%28mythology%29.txt ../out/7f/b3/Ajax_%28mythology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/29/Transport_in_Burundi.txt ../out/80/29/Transport_in_Burundi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/b9/Austin_%28disambiguation%29.txt ../out/80/b9/Austin_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/7c/August_23.txt ../out/81/7c/August_23.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/02/Complex_instruction_set_computing.txt ../out/82/02/Complex_instruction_set_computing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/eb/Ambrosiaster.txt ../out/82/eb/Ambrosiaster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/a7/Early_Music.txt ../out/83/a7/Early_Music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/55/BuddhIsm.txt ../out/84/55/BuddhIsm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/39/BCD.txt ../out/85/39/BCD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/99/April_8.txt ../out/85/99/April_8.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/3b/Barry_Bonds.txt ../out/86/3b/Barry_Bonds.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/e5/Drag_racing.txt ../out/86/e5/Drag_racing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/6b/Bah%C3%A1%27%C3%AD_Faith.txt ../out/87/6b/Bah%C3%A1%27%C3%AD_Faith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/77/Ballu_tundu.txt ../out/88/77/Ballu_tundu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/10/EuroCurrency.txt ../out/89/10/EuroCurrency.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/a9/Anus.txt ../out/89/a9/Anus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/24/Draugr.txt ../out/8a/24/Draugr.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/0d/Bilateral_symmetry.txt ../out/8b/0d/Bilateral_symmetry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/a1/Bokken.txt ../out/8b/a1/Bokken.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/69/Domenico_Alberti.txt ../out/8c/69/Domenico_Alberti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/ca/Eskimo.txt ../out/8c/ca/Eskimo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/63/CND.txt ../out/8d/63/CND.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/3c/Cistron.txt ../out/8e/3c/Cistron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/2c/Cognitivism.txt ../out/8f/2c/Cognitivism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/cf/Anacreon_%28poet%29.txt ../out/8f/cf/Anacreon_%28poet%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/cd/Jews_as_the_chosen_people.txt ../out/90/cd/Jews_as_the_chosen_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/2d/Europe.txt ../out/91/2d/Europe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/6b/AFC_Ajax.txt ../out/92/6b/AFC_Ajax.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/08/British_public_houses.txt ../out/93/08/British_public_houses.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/9b/Democratic_Progressive_Party.txt ../out/93/9b/Democratic_Progressive_Party.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/7d/Christian_mythology.txt ../out/94/7d/Christian_mythology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/28/Category_of_being.txt ../out/95/28/Category_of_being.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/be/Algorithms_for_calculating_variance.txt ../out/95/be/Algorithms_for_calculating_variance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/92/Cross-country_skiing.txt ../out/96/92/Cross-country_skiing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/35/Expressive_aphasia.txt ../out/97/35/Expressive_aphasia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/c1/Burnt-in_timecode.txt ../out/97/c1/Burnt-in_timecode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/47/Cathode_ray_tube.txt ../out/98/47/Cathode_ray_tube.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/cf/Alfred_C._Kinsey.txt ../out/98/cf/Alfred_C._Kinsey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/4c/Body_substance_isolation.txt ../out/99/4c/Body_substance_isolation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/c8/Armed_Forces_of_Armenia.txt ../out/99/c8/Armed_Forces_of_Armenia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/65/Continuous_probability_distribution.txt ../out/9a/65/Continuous_probability_distribution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/e9/Calvin_Coolidge.txt ../out/9a/e9/Calvin_Coolidge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/96/Ajaigarh.txt ../out/9b/96/Ajaigarh.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/0e/Evolutionism.txt ../out/9c/0e/Evolutionism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/a2/European_Economic_Community.txt ../out/9c/a2/European_Economic_Community.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/3a/Conditional.txt ../out/9d/3a/Conditional.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/cc/Demographics_of_Djibouti.txt ../out/9d/cc/Demographics_of_Djibouti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/9e/BearShare.txt ../out/9e/9e/BearShare.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/60/Alberto_Giacometti.txt ../out/9f/60/Alberto_Giacometti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/01/Bach_%28disambiguation%29.txt ../out/a0/01/Bach_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/a9/Cleveland_Browns.txt ../out/a0/a9/Cleveland_Browns.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/a3/April_14.txt ../out/a1/a3/April_14.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/56/Breakdance.txt ../out/a2/56/Breakdance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/0c/AppliedStatistics.txt ../out/a3/0c/AppliedStatistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/b3/Caribbean_cuisine.txt ../out/a3/b3/Caribbean_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/82/Crystal.txt ../out/a4/82/Crystal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/f1/Claude_Oscar_Monet.txt ../out/a4/f1/Claude_Oscar_Monet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/68/Southeast_Alaska.txt ../out/a5/68/Southeast_Alaska.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/ec/Bornholm.txt ../out/a5/ec/Bornholm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/bc/Alured_of_Berkeley.txt ../out/a6/bc/Alured_of_Berkeley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/37/Denis_Leary.txt ../out/a7/37/Denis_Leary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/36/AbbeY.txt ../out/a8/36/AbbeY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/d0/Charles_Xavier_Joseph_De_Franque_Ville_Abancourt.txt ../out/a8/d0/Charles_Xavier_Joseph_De_Franque_Ville_Abancourt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/93/Boomeroid.txt ../out/a9/93/Boomeroid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/50/Telecommunications_in_Eritrea.txt ../out/aa/50/Telecommunications_in_Eritrea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/c5/Battle_of_Aboukir_Bay.txt ../out/aa/c5/Battle_of_Aboukir_Bay.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/51/Alexander_Fleming.txt ../out/ab/51/Alexander_Fleming.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/f9/Ambush.txt ../out/ab/f9/Ambush.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/87/Cetus.txt ../out/ac/87/Cetus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/e3/Bee.txt ../out/ac/e3/Bee.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/e7/Chinese_dominoes.txt ../out/ad/e7/Chinese_dominoes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/5f/Optical_aberration.txt ../out/ae/5f/Optical_aberration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/f8/Taiko.txt ../out/ae/f8/Taiko.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/90/Boii.txt ../out/af/90/Boii.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/19/Chinese_classics.txt ../out/b0/19/Chinese_classics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/c9/Demographics_of_Angola.txt ../out/b0/c9/Demographics_of_Angola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/69/Charles_d%27Abancour.txt ../out/b1/69/Charles_d%27Abancour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/dc/CommonSense.txt ../out/b1/dc/CommonSense.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/69/Amalasuntha.txt ../out/b2/69/Amalasuntha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/9a/Behavior.txt ../out/b3/9a/Behavior.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/3f/Alexander_I_of_Epirus.txt ../out/b4/3f/Alexander_I_of_Epirus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/a5/Dirk_Benedict.txt ../out/b4/a5/Dirk_Benedict.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/dd/Cogency.txt ../out/b4/dd/Cogency.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/64/Deccan_Traps.txt ../out/b5/64/Deccan_Traps.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/f6/Diameter.txt ../out/b5/f6/Diameter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/b8/ALICE.txt ../out/b6/b8/ALICE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/96/Epiphenomenalism.txt ../out/b7/96/Epiphenomenalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/1f/Bodhidarma.txt ../out/b8/1f/Bodhidarma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/a0/Central_Tendancy.txt ../out/b8/a0/Central_Tendancy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/a0/Anti-Globalization_Movement.txt ../out/b9/a0/Anti-Globalization_Movement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/21/Boeing_C-135.txt ../out/ba/21/Boeing_C-135.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/c5/Alexander_III_of_Russia.txt ../out/ba/c5/Alexander_III_of_Russia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/71/DSL_%28disambiguation%29.txt ../out/bb/71/DSL_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/eb/Calorimetry.txt ../out/bb/eb/Calorimetry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/7a/CPGM.txt ../out/bc/7a/CPGM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/55/Board_games.txt ../out/bd/55/Board_games.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/02/Character_encoding.txt ../out/be/02/Character_encoding.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/c6/AbbevilleFrance.txt ../out/be/c6/AbbevilleFrance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/5d/Basenji.txt ../out/bf/5d/Basenji.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/22/Act_of_Settlement_1701.txt ../out/c0/22/Act_of_Settlement_1701.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/c2/Adenylyl_cyclase.txt ../out/c0/c2/Adenylyl_cyclase.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/77/Executable_and_Linkable_Format.txt ../out/c1/77/Executable_and_Linkable_Format.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/46/Alphonso_VIII.txt ../out/c2/46/Alphonso_VIII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/14/Dia_%28software%29.txt ../out/c3/14/Dia_%28software%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/be/Dakinis.txt ../out/c3/be/Dakinis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/48/Transport_in_Estonia.txt ../out/c4/48/Transport_in_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/ea/Aurochs.txt ../out/c4/ea/Aurochs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/e6/Military_of_Bulgaria.txt ../out/c5/e6/Military_of_Bulgaria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/7f/Computer_animation.txt ../out/c6/7f/Computer_animation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/29/Didjeridoo.txt ../out/c7/29/Didjeridoo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/ee/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F6.txt ../out/c7/ee/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F6.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/b2/Battle_of_Gettysburg.txt ../out/c8/b2/Battle_of_Gettysburg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/5c/CCITT.txt ../out/c9/5c/CCITT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/e7/Concentration.txt ../out/c9/e7/Concentration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/72/Abandonment_of_an_easement.txt ../out/ca/72/Abandonment_of_an_easement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/5f/Color.txt ../out/cb/5f/Color.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/10/Bollywood.txt ../out/cc/10/Bollywood.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/e9/Chakra.txt ../out/cc/e9/Chakra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/6c/Boron_nitride.txt ../out/cd/6c/Boron_nitride.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/ff/Cuisine_of_the_United_States.txt ../out/cd/ff/Cuisine_of_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/ef/Conscription.txt ../out/ce/ef/Conscription.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/93/Electrochemistry.txt ../out/cf/93/Electrochemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/4e/Digitalis.txt ../out/d0/4e/Digitalis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/24/Automated_Alice%2FIII.txt ../out/d1/24/Automated_Alice%2FIII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/a2/Evil.txt ../out/d1/a2/Evil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/7e/Corporate_title.txt ../out/d2/7e/Corporate_title.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/10/Disbarment.txt ../out/d3/10/Disbarment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/b6/Ammon.txt ../out/d3/b6/Ammon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/90/Cervix.txt ../out/d4/90/Cervix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/15/Acceptance_testing.txt ../out/d5/15/Acceptance_testing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/bc/Bloody_Sunday.txt ../out/d5/bc/Bloody_Sunday.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/6e/Alexandria%2C_West_Dunbartonshire.txt ../out/d6/6e/Alexandria%2C_West_Dunbartonshire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/04/Born_again_%28Christianity%29.txt ../out/d7/04/Born_again_%28Christianity%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/8b/Brian_Boitano.txt ../out/d7/8b/Brian_Boitano.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/51/August_24.txt ../out/d8/51/August_24.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/fb/Andrey_Markov.txt ../out/d8/fb/Andrey_Markov.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/af/Discordianism.txt ../out/d9/af/Discordianism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/73/List_of_international_environmental_agreements.txt ../out/da/73/List_of_international_environmental_agreements.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/f2/DX_communication.txt ../out/da/f2/DX_communication.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/8e/Azerbaijan%2FPeople.txt ../out/db/8e/Azerbaijan%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/2b/Extreme_sport.txt ../out/dc/2b/Extreme_sport.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/b1/Blind_Lemon_Jefferson.txt ../out/dc/b1/Blind_Lemon_Jefferson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/7f/List_of_Governors_of_Alabama.txt ../out/dd/7f/List_of_Governors_of_Alabama.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/ed/Chronic_Fatigue_Syndrome%2FLong_term_course.txt ../out/dd/ed/Chronic_Fatigue_Syndrome%2FLong_term_course.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/b4/Dance_Dance_Revolution.txt ../out/de/b4/Dance_Dance_Revolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/62/Exponential_function.txt ../out/df/62/Exponential_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/2c/Chrono_Trigger.txt ../out/e0/2c/Chrono_Trigger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/15/Entamoeba.txt ../out/e1/15/Entamoeba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/b2/Anthem.txt ../out/e1/b2/Anthem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/68/August_18.txt ../out/e2/68/August_18.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/07/Database.txt ../out/e3/07/Database.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/a0/Barium.txt ../out/e3/a0/Barium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/51/American_political_scandals.txt ../out/e4/51/American_political_scandals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/09/Craven_Cottage.txt ../out/e5/09/Craven_Cottage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/b1/Clipperton_Island%2FTransportation.txt ../out/e5/b1/Clipperton_Island%2FTransportation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/2d/Beta_decay.txt ../out/e6/2d/Beta_decay.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/06/Disease.txt ../out/e7/06/Disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/c8/Behistun_Inscription.txt ../out/e7/c8/Behistun_Inscription.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/57/Transport_in_Ecuador.txt ../out/e8/57/Transport_in_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/fd/Aarhus.txt ../out/e8/fd/Aarhus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/81/Abd-ar-Rahman_III.txt ../out/e9/81/Abd-ar-Rahman_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/02/Chordate.txt ../out/ea/02/Chordate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/b1/CountriesOfTheWorld.txt ../out/ea/b1/CountriesOfTheWorld.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/4a/Daniel_Williamson.txt ../out/eb/4a/Daniel_Williamson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/32/Chapterhouse%3A_Dune.txt ../out/ec/32/Chapterhouse%3A_Dune.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/f9/Charlton_Athletic_F.C..txt ../out/ec/f9/Charlton_Athletic_F.C..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/8e/Ambient.txt ../out/ed/8e/Ambient.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/00/Beltane.txt ../out/ee/00/Beltane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/b6/Compressor.txt ../out/ee/b6/Compressor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/55/Affinity.txt ../out/ef/55/Affinity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/dc/AnAmericanInParis.txt ../out/ef/dc/AnAmericanInParis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/8d/Ad_hominem.txt ../out/f0/8d/Ad_hominem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/55/Dravidian.txt ../out/f1/55/Dravidian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/52/CountriesP.txt ../out/f2/52/CountriesP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/30/Cereal.txt ../out/f3/30/Cereal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/d5/Bilge_Khagan.txt ../out/f3/d5/Bilge_Khagan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/b5/Geography_of_Christmas_Island.txt ../out/f4/b5/Geography_of_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/9a/ConstitutioN.txt ../out/f5/9a/ConstitutioN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/23/D.txt ../out/f6/23/D.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/cf/Elephant.txt ../out/f6/cf/Elephant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/52/Connecticut.txt ../out/f7/52/Connecticut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/3b/Transport_in_Burkina_Faso.txt ../out/f8/3b/Transport_in_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/af/Consumer.txt ../out/f8/af/Consumer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/2b/CJD.txt ../out/f9/2b/CJD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/cb/Coptic_Orthodox_Church_of_Alexandria.txt ../out/f9/cb/Coptic_Orthodox_Church_of_Alexandria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/38/Commodore_1581.txt ../out/fa/38/Commodore_1581.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/f1/Aspirated_consonant.txt ../out/fa/f1/Aspirated_consonant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/82/BiJection.txt ../out/fb/82/BiJection.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/1a/Chagas_disease.txt ../out/fc/1a/Chagas_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/49/Eric_S._Raymond.txt ../out/fd/49/Eric_S._Raymond.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/d7/Brackish_water.txt ../out/fd/d7/Brackish_water.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/b0/Geography_of_Armenia.txt ../out/fe/b0/Geography_of_Armenia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/39/Bundaberg_Rum.txt ../out/ff/39/Bundaberg_Rum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/8c/Coal.txt ../out/ff/8c/Coal.xml
