php ./wiki2xml/php/wiki2xml_command.php ../out/00/6f/Christmas_in_Poland.txt ../out/00/6f/Christmas_in_Poland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/31/Cubic_feet.txt ../out/01/31/Cubic_feet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/c3/Elijah.txt ../out/01/c3/Elijah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/6d/County_Dublin.txt ../out/02/6d/County_Dublin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/2e/Al-Manamah.txt ../out/03/2e/Al-Manamah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/c9/Timeline_of_chemical_element_discoveries.txt ../out/03/c9/Timeline_of_chemical_element_discoveries.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/5a/Americium.txt ../out/04/5a/Americium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/f7/Atlantic_Ocean.txt ../out/04/f7/Atlantic_Ocean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/6b/Banca_d%27Italia.txt ../out/05/6b/Banca_d%27Italia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/ef/Ahmad_Shah_Durrani.txt ../out/05/ef/Ahmad_Shah_Durrani.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/c0/List_of_cryptographers.txt ../out/06/c0/List_of_cryptographers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/5a/Transport_in_Croatia.txt ../out/07/5a/Transport_in_Croatia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/19/Case.txt ../out/08/19/Case.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/a4/Bluescreen.txt ../out/08/a4/Bluescreen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/73/April_24.txt ../out/09/73/April_24.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/32/April_23.txt ../out/0a/32/April_23.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/a6/Aurora_australis.txt ../out/0a/a6/Aurora_australis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/77/Acacia.txt ../out/0b/77/Acacia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/ce/Clay_Mathematics_Institute.txt ../out/0b/ce/Clay_Mathematics_Institute.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/7a/Evangelist_%28Latter_Day_Saints%29.txt ../out/0c/7a/Evangelist_%28Latter_Day_Saints%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/36/Cantor_set.txt ../out/0d/36/Cantor_set.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/f2/Electron.txt ../out/0d/f2/Electron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/95/CountriesE.txt ../out/0e/95/CountriesE.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/45/Alpenhorn.txt ../out/0f/45/Alpenhorn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/0c/Celestines.txt ../out/10/0c/Celestines.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/09/Cable_TV.txt ../out/11/09/Cable_TV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/b9/Cleveland.txt ../out/11/b9/Cleveland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/58/Defense_Distinguished_Service_Medal.txt ../out/12/58/Defense_Distinguished_Service_Medal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/f3/Enola_Gay.txt ../out/12/f3/Enola_Gay.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/78/Balts.txt ../out/13/78/Balts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/25/EnroN.txt ../out/14/25/EnroN.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/e5/An_Enquiry_Concerning_Human_Understanding%2FText.txt ../out/14/e5/An_Enquiry_Concerning_Human_Understanding%2FText.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/5f/Berlin_Wall.txt ../out/15/5f/Berlin_Wall.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/37/Wikipedia%3ABiochemistry_basic_topics.txt ../out/16/37/Wikipedia%3ABiochemistry_basic_topics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/bf/Cultural_production_and_nationalism.txt ../out/16/bf/Cultural_production_and_nationalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/9c/Delaware_Corporation.txt ../out/17/9c/Delaware_Corporation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/32/Bubble_and_squeak.txt ../out/18/32/Bubble_and_squeak.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/ca/Disjunctive_syllogism.txt ../out/18/ca/Disjunctive_syllogism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/5c/Antarctic.txt ../out/19/5c/Antarctic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/ec/Contract_bridge.txt ../out/19/ec/Contract_bridge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/96/Binary_search_tree.txt ../out/1a/96/Binary_search_tree.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/fd/Dualism.txt ../out/1a/fd/Dualism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/99/Achduart.txt ../out/1b/99/Achduart.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/0e/Auroch.txt ../out/1c/0e/Auroch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/9f/Apollo_10.txt ../out/1c/9f/Apollo_10.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/32/Economy_of_the_Cook_Islands.txt ../out/1d/32/Economy_of_the_Cook_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/e7/Geography_of_Brunei.txt ../out/1d/e7/Geography_of_Brunei.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/88/Autumn_equinox.txt ../out/1e/88/Autumn_equinox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/43/Courtney_Love.txt ../out/1f/43/Courtney_Love.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/12/Emoticon.txt ../out/20/12/Emoticon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/97/Dubnium.txt ../out/20/97/Dubnium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/3f/Alabama.txt ../out/21/3f/Alabama.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/45/Protestant_Church_in_the_Netherlands.txt ../out/22/45/Protestant_Church_in_the_Netherlands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/dc/Expectation_operator.txt ../out/22/dc/Expectation_operator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/8d/Chemist.txt ../out/23/8d/Chemist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/22/Emanuel_Leutze.txt ../out/24/22/Emanuel_Leutze.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/d2/Alaric_I.txt ../out/24/d2/Alaric_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/a0/Amoxicillin.txt ../out/25/a0/Amoxicillin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/27/Condensed_matter_physics.txt ../out/26/27/Condensed_matter_physics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/d0/Citric_Acid_cycle.txt ../out/26/d0/Citric_Acid_cycle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/78/Druzism.txt ../out/27/78/Druzism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/28/Alexis_Carrel.txt ../out/28/28/Alexis_Carrel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/af/Enlil.txt ../out/28/af/Enlil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/66/Bandwidth_%28signal_processing%29.txt ../out/29/66/Bandwidth_%28signal_processing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/14/Bavarian.txt ../out/2a/14/Bavarian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/d9/List_of_city_listings_by_country.txt ../out/2a/d9/List_of_city_listings_by_country.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/5f/Foreign_relations_of_Estonia.txt ../out/2b/5f/Foreign_relations_of_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/24/Country_codes.txt ../out/2c/24/Country_codes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/a3/Contraceptive.txt ../out/2c/a3/Contraceptive.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/45/CPSU_%28disambiguation%29.txt ../out/2d/45/CPSU_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/10/Artificial_languages.txt ../out/2e/10/Artificial_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/c0/Cray_Research.txt ../out/2e/c0/Cray_Research.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/7c/Abraham_Lincoln.txt ../out/2f/7c/Abraham_Lincoln.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/78/Cl.txt ../out/30/78/Cl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/12/Andromeda_%28mythology%29.txt ../out/31/12/Andromeda_%28mythology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/d2/Cessna.txt ../out/31/d2/Cessna.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/c2/Conan_the_Barbarian.txt ../out/32/c2/Conan_the_Barbarian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/12/Bob_Knight.txt ../out/33/12/Bob_Knight.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/46/AustriaLanguage.txt ../out/34/46/AustriaLanguage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/e5/Riding_shotgun.txt ../out/34/e5/Riding_shotgun.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/72/Cape_Breton.txt ../out/35/72/Cape_Breton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/57/Aleut.txt ../out/36/57/Aleut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/1f/Aon_%28company%29.txt ../out/37/1f/Aon_%28company%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/76/Complete_normed_vector_space.txt ../out/37/76/Complete_normed_vector_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/0a/April_20.txt ../out/38/0a/April_20.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/6c/Currency.txt ../out/38/6c/Currency.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/6f/Diocletian.txt ../out/39/6f/Diocletian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/24/Antidiarrhoeal.txt ../out/3a/24/Antidiarrhoeal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/7c/Climate_Change-Kyoto_Protocol.txt ../out/3a/7c/Climate_Change-Kyoto_Protocol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/27/Czech_republic%2FPeople.txt ../out/3b/27/Czech_republic%2FPeople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/96/Cooking.txt ../out/3b/96/Cooking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/22/Abdominal_surgery.txt ../out/3c/22/Abdominal_surgery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/e4/Echidna_%28disambiguation%29.txt ../out/3c/e4/Echidna_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/73/European_Central_Bank.txt ../out/3d/73/European_Central_Bank.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/2c/Agarose_gel_electrophoresis.txt ../out/3e/2c/Agarose_gel_electrophoresis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/b8/Amsterdam.txt ../out/3e/b8/Amsterdam.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/29/Embroidery.txt ../out/3f/29/Embroidery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/de/Don%27t_ask%2C_don%27t_tell.txt ../out/3f/de/Don%27t_ask%2C_don%27t_tell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/88/Blaue_Reiter.txt ../out/40/88/Blaue_Reiter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/2b/Chaldea.txt ../out/41/2b/Chaldea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/be/Calendar_method.txt ../out/41/be/Calendar_method.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/15/American_%28word%29.txt ../out/42/15/American_%28word%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/8c/Andreas_Aagesen.txt ../out/42/8c/Andreas_Aagesen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/6a/Amphibian.txt ../out/43/6a/Amphibian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/c5/African_American.txt ../out/43/c5/African_American.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/91/Celibacy.txt ../out/44/91/Celibacy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/26/Business_Schools.txt ../out/45/26/Business_Schools.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/e6/Black_Death.txt ../out/45/e6/Black_Death.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/63/Alfred_Jarry.txt ../out/46/63/Alfred_Jarry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/28/Ethnocentrism.txt ../out/47/28/Ethnocentrism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/e3/Ecosystem.txt ../out/47/e3/Ecosystem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/9e/Alexander_V.txt ../out/48/9e/Alexander_V.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/2c/Geography_of_Cape_Verde.txt ../out/49/2c/Geography_of_Cape_Verde.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/d2/Baltic_Sea%2FTruso.txt ../out/49/d2/Baltic_Sea%2FTruso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/90/Book_of_Common_Prayer.txt ../out/4a/90/Book_of_Common_Prayer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/2d/Bodmin_Moor.txt ../out/4b/2d/Bodmin_Moor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/d0/Dative.txt ../out/4b/d0/Dative.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/4b/Anders_Celsius.txt ../out/4c/4b/Anders_Celsius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/2b/Binary-coded_decimal.txt ../out/4d/2b/Binary-coded_decimal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/96/Analysis_of_Variance.txt ../out/4d/96/Analysis_of_Variance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/1d/Bj%C3%B8rn_Lomborg.txt ../out/4e/1d/Bj%C3%B8rn_Lomborg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/c7/Dispersion.txt ../out/4e/c7/Dispersion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/7a/Beaver.txt ../out/4f/7a/Beaver.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/3d/Amblygonite.txt ../out/50/3d/Amblygonite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/02/Corona.txt ../out/51/02/Corona.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/80/Czech_Republic.txt ../out/51/80/Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/3e/Young_and_Innocent.txt ../out/52/3e/Young_and_Innocent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/f9/Dual_wield.txt ../out/52/f9/Dual_wield.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/79/A.E._van_Vogt.txt ../out/53/79/A.E._van_Vogt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/02/Alps.txt ../out/54/02/Alps.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/94/California_Institute_of_Technology.txt ../out/54/94/California_Institute_of_Technology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/14/Arnulf_of_Carinthia.txt ../out/55/14/Arnulf_of_Carinthia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/d2/Callisto.txt ../out/55/d2/Callisto.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/a1/Piano_Trios%2C_Op._70_%28Beethoven%29.txt ../out/56/a1/Piano_Trios%2C_Op._70_%28Beethoven%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/62/Antlia.txt ../out/57/62/Antlia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/36/Stab-in-the-back_myth.txt ../out/58/36/Stab-in-the-back_myth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/d7/Apostles%27_Creed.txt ../out/58/d7/Apostles%27_Creed.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/4d/Comedy_film.txt ../out/59/4d/Comedy_film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/e7/Politics_of_Ethiopia.txt ../out/59/e7/Politics_of_Ethiopia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/84/Ajmer-Merwara.txt ../out/5a/84/Ajmer-Merwara.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/f6/Politics_of_the_Democratic_Republic_of_the_Congo.txt ../out/5a/f6/Politics_of_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/bb/Dynamic_HTML.txt ../out/5b/bb/Dynamic_HTML.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/4b/Europa.txt ../out/5c/4b/Europa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/24/Albania%2FForeign_relations.txt ../out/5d/24/Albania%2FForeign_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/f8/Acupuncture.txt ../out/5d/f8/Acupuncture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/74/Constitution_of_Canada.txt ../out/5e/74/Constitution_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/1d/Cogito_ergo_sum.txt ../out/5f/1d/Cogito_ergo_sum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/f8/Christiania.txt ../out/5f/f8/Christiania.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/97/Death.txt ../out/60/97/Death.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/46/Casiquiare_canal.txt ../out/61/46/Casiquiare_canal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/c3/Adamnan.txt ../out/61/c3/Adamnan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/90/Transportation_on_Europa_Island.txt ../out/62/90/Transportation_on_Europa_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/75/Affidavit.txt ../out/63/75/Affidavit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/79/Eleanor_of_Aquitaine.txt ../out/64/79/Eleanor_of_Aquitaine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/03/Epistle_of_James.txt ../out/65/03/Epistle_of_James.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/79/Affirming_the_antecedent.txt ../out/65/79/Affirming_the_antecedent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/f5/Alabaster.txt ../out/65/f5/Alabaster.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/84/Baroque_dance.txt ../out/66/84/Baroque_dance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/18/Collectable_card_game.txt ../out/67/18/Collectable_card_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/da/Telecommunications_in_Anguilla.txt ../out/67/da/Telecommunications_in_Anguilla.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/6d/Burning_glass.txt ../out/68/6d/Burning_glass.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/25/Comparative_method_%28linguistics%29.txt ../out/69/25/Comparative_method_%28linguistics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/e5/Baudot_code.txt ../out/69/e5/Baudot_code.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/82/Geography_of_Cyprus.txt ../out/6a/82/Geography_of_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/fc/American_Chinese_cuisine.txt ../out/6a/fc/American_Chinese_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/96/Cambrian.txt ../out/6b/96/Cambrian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/2f/Combinatorics.txt ../out/6c/2f/Combinatorics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/a9/Telstar_%28game_console%29.txt ../out/6c/a9/Telstar_%28game_console%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/48/Wikipedia%3ABuilding_Wikipedia_membership%2FNewsgroups.txt ../out/6d/48/Wikipedia%3ABuilding_Wikipedia_membership%2FNewsgroups.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/dd/Aquarius_%28constellation%29.txt ../out/6d/dd/Aquarius_%28constellation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/84/Dumpster-diving.txt ../out/6e/84/Dumpster-diving.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/ed/AutoRacing.txt ../out/6e/ed/AutoRacing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/83/Couscous.txt ../out/6f/83/Couscous.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/78/Allosaurus.txt ../out/70/78/Allosaurus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/21/Bill_Mumy.txt ../out/71/21/Bill_Mumy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/eb/Citizenship.txt ../out/71/eb/Citizenship.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/80/Center_%28group_theory%29.txt ../out/72/80/Center_%28group_theory%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/42/International_Bureau_of_Weights_and_Measures.txt ../out/73/42/International_Bureau_of_Weights_and_Measures.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/15/BirthofaNation.txt ../out/74/15/BirthofaNation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/70/Automated_theorem_proving.txt ../out/74/70/Automated_theorem_proving.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/e4/Buddhist.txt ../out/74/e4/Buddhist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/92/Duke_Nukem_3D.txt ../out/75/92/Duke_Nukem_3D.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/5d/Languages_of_Europe.txt ../out/76/5d/Languages_of_Europe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/df/Electromagnetic_radiation.txt ../out/76/df/Electromagnetic_radiation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/a2/Desmothoracid.txt ../out/77/a2/Desmothoracid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/49/Debian_GNU%2FLinux.txt ../out/78/49/Debian_GNU%2FLinux.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/d1/Davy_lamp.txt ../out/78/d1/Davy_lamp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/8f/CountriesQ.txt ../out/79/8f/CountriesQ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/2b/List_of_companies_of_Canada.txt ../out/7a/2b/List_of_companies_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/8e/Cheirogaleidae.txt ../out/7a/8e/Cheirogaleidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/de/EiffelTower.txt ../out/7a/de/EiffelTower.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/f1/Data_warehouse.txt ../out/7b/f1/Data_warehouse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/90/Clipperton_Island%2FGeography.txt ../out/7c/90/Clipperton_Island%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/1c/Colonialism.txt ../out/7d/1c/Colonialism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/b4/Bras%C3%ADlia.txt ../out/7d/b4/Bras%C3%ADlia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/55/Inedia.txt ../out/7e/55/Inedia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/09/Central_bank.txt ../out/7f/09/Central_bank.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/aa/Adhemar_of_Le_Puy.txt ../out/7f/aa/Adhemar_of_Le_Puy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/13/Cambridge_University.txt ../out/80/13/Cambridge_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/a1/Arthur_Eddington.txt ../out/80/a1/Arthur_Eddington.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/52/Common_Lisp.txt ../out/81/52/Common_Lisp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/fc/Axayacatl.txt ../out/81/fc/Axayacatl.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/d9/Bipedalism.txt ../out/82/d9/Bipedalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/95/Condiment_for_seasoning_minestrone.txt ../out/83/95/Condiment_for_seasoning_minestrone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/4b/CDMA.txt ../out/84/4b/CDMA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/25/Data_set.txt ../out/85/25/Data_set.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/89/CEO.txt ../out/85/89/CEO.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/1f/Cous_cous.txt ../out/86/1f/Cous_cous.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/de/Demographics_of_Christmas_Island.txt ../out/86/de/Demographics_of_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/54/August_11.txt ../out/87/54/August_11.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/65/Digital_video.txt ../out/88/65/Digital_video.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/ef/Bodmin.txt ../out/88/ef/Bodmin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/90/Endocrinology.txt ../out/89/90/Endocrinology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/16/BdU.txt ../out/8a/16/BdU.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/d0/Geography_of_Equatorial_Guinea.txt ../out/8a/d0/Geography_of_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/74/Alain_Connes.txt ../out/8b/74/Alain_Connes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/57/Digital_synthesizer.txt ../out/8c/57/Digital_synthesizer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/be/List_of_football_clubs_in_the_Netherlands.txt ../out/8c/be/List_of_football_clubs_in_the_Netherlands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/2e/Actinide.txt ../out/8d/2e/Actinide.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/39/Cerebral_Spinal_Fluid.txt ../out/8e/39/Cerebral_Spinal_Fluid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/ff/Earned_value_management.txt ../out/8e/ff/Earned_value_management.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/b7/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FW.txt ../out/8f/b7/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FW.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/90/Abano_Terme.txt ../out/90/90/Abano_Terme.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/1d/Capsid.txt ../out/91/1d/Capsid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/21/Ankara.txt ../out/92/21/Ankara.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/dd/Ashmore_and_Cartier_Islands%2FGovernment.txt ../out/92/dd/Ashmore_and_Cartier_Islands%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/8e/Aal.txt ../out/93/8e/Aal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/61/Anode.txt ../out/94/61/Anode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/26/C-star_algebra.txt ../out/95/26/C-star_algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/ae/Atomic_weight.txt ../out/95/ae/Atomic_weight.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/80/Channel_Isles.txt ../out/96/80/Channel_Isles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/24/CountriesH.txt ../out/97/24/CountriesH.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/af/Digital_Enhanced_Cordless_Telecommunications.txt ../out/97/af/Digital_Enhanced_Cordless_Telecommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/41/Cash_register.txt ../out/98/41/Cash_register.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/c2/Altenberg.txt ../out/98/c2/Altenberg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/42/Black_Forest.txt ../out/99/42/Black_Forest.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/bf/Battle_of_Peleliu.txt ../out/99/bf/Battle_of_Peleliu.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/4a/Barcelonnette.txt ../out/9a/4a/Barcelonnette.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/c0/Committee_on_Data_for_Science_and_Technology.txt ../out/9a/c0/Committee_on_Data_for_Science_and_Technology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/88/Bill_Holbrook.txt ../out/9b/88/Bill_Holbrook.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/08/Discrete_Fourier_transform.txt ../out/9c/08/Discrete_Fourier_transform.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/8f/Aalborg_Municipality.txt ../out/9c/8f/Aalborg_Municipality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/27/AutoCAD_DXF.txt ../out/9d/27/AutoCAD_DXF.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/ac/Transport_in_Ethiopia.txt ../out/9d/ac/Transport_in_Ethiopia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/70/Benin.txt ../out/9e/70/Benin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/4f/Ceres_Brewery.txt ../out/9f/4f/Ceres_Brewery.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/ea/Rod_%28optics%29.txt ../out/9f/ea/Rod_%28optics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/a4/Economy_of_Estonia.txt ../out/a0/a4/Economy_of_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/67/Alfred_of_Beverley.txt ../out/a1/67/Alfred_of_Beverley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/49/Alessandro_Allori.txt ../out/a2/49/Alessandro_Allori.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/eb/Canal.txt ../out/a2/eb/Canal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/a0/Coercion.txt ../out/a3/a0/Coercion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/72/Catholic_church.txt ../out/a4/72/Catholic_church.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/ec/Event.txt ../out/a4/ec/Event.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/5c/Approximant_consonant.txt ../out/a5/5c/Approximant_consonant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/b7/ErnestHemingway%2FFromRealitytoFictionAFarewelltoArms.txt ../out/a5/b7/ErnestHemingway%2FFromRealitytoFictionAFarewelltoArms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/b9/AfghanistanMilitary.txt ../out/a6/b9/AfghanistanMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/2a/Danny_Kaye.txt ../out/a7/2a/Danny_Kaye.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/ff/Bill_Clinton.txt ../out/a7/ff/Bill_Clinton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/c5/Coral_Sea_Islands%2FMilitary.txt ../out/a8/c5/Coral_Sea_Islands%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/88/Elementary_algebra.txt ../out/a9/88/Elementary_algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/4c/Computable_number.txt ../out/aa/4c/Computable_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/b3/Aga.txt ../out/aa/b3/Aga.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/3d/Doonesbury.txt ../out/ab/3d/Doonesbury.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/de/Abati.txt ../out/ab/de/Abati.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/83/Armillary.txt ../out/ac/83/Armillary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/db/Broadcast_domain.txt ../out/ac/db/Broadcast_domain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/b7/Balance_of_trade.txt ../out/ad/b7/Balance_of_trade.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/54/China.txt ../out/ae/54/China.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/eb/Hermann_Kolbe.txt ../out/ae/eb/Hermann_Kolbe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/84/Central_processing_unit.txt ../out/af/84/Central_processing_unit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/12/Alabama_River.txt ../out/b0/12/Alabama_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/86/Color_code.txt ../out/b0/86/Color_code.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/53/Ampallang_piercing.txt ../out/b1/53/Ampallang_piercing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/da/Ammeter.txt ../out/b1/da/Ammeter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/55/Arteriovenous_malformation.txt ../out/b2/55/Arteriovenous_malformation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/8a/E.P.Thompson_on_Luddites.txt ../out/b3/8a/E.P.Thompson_on_Luddites.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/fd/...Baby_One_More_Time_%28album%29.txt ../out/b3/fd/...Baby_One_More_Time_%28album%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/a2/Asterism.txt ../out/b4/a2/Asterism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/d1/Backpacking.txt ../out/b4/d1/Backpacking.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/4d/Abbreviation.txt ../out/b5/4d/Abbreviation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/e7/Bihar_%28disambiguation%29.txt ../out/b5/e7/Bihar_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/9c/Data_compression%2Flossless.txt ../out/b6/9c/Data_compression%2Flossless.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/82/Academy_award.txt ../out/b7/82/Academy_award.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/10/Alcobaca.txt ../out/b8/10/Alcobaca.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/82/Canada%E2%80%93United_States_relations.txt ../out/b8/82/Canada%E2%80%93United_States_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/6f/Antipope_John_XXIII.txt ../out/b9/6f/Antipope_John_XXIII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/0e/Bill_Macy.txt ../out/ba/0e/Bill_Macy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/bc/Battle_of_Lostwithiel.txt ../out/ba/bc/Battle_of_Lostwithiel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/5d/CamelHumpedWord.txt ../out/bb/5d/CamelHumpedWord.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/e0/Daisy_cutter.txt ../out/bb/e0/Daisy_cutter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/6d/Externalization.txt ../out/bc/6d/Externalization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/24/Di_George%27s_syndrome.txt ../out/bd/24/Di_George%27s_syndrome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/e0/Bob_Costas.txt ../out/bd/e0/Bob_Costas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/bd/Ash.txt ../out/be/bd/Ash.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/4d/Charles_C._Krulak.txt ../out/bf/4d/Charles_C._Krulak.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/f1/Bundesregierung.txt ../out/bf/f1/Bundesregierung.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/b2/Encyclopedia.txt ../out/c0/b2/Encyclopedia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/6a/Sure_Shots_The_Second_World_War.txt ../out/c1/6a/Sure_Shots_The_Second_World_War.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/36/Anaheim_Angels.txt ../out/c2/36/Anaheim_Angels.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/07/Basil_%28plant%29.txt ../out/c3/07/Basil_%28plant%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/af/Analysis_of_variance.txt ../out/c3/af/Analysis_of_variance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/33/A-10_Warthog.txt ../out/c4/33/A-10_Warthog.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/ba/Ecuadorians.txt ../out/c4/ba/Ecuadorians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/d5/Bromeliales.txt ../out/c5/d5/Bromeliales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/79/Baltimore_Ravens.txt ../out/c6/79/Baltimore_Ravens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/22/Deimos.txt ../out/c7/22/Deimos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/e6/Bloody_Mary.txt ../out/c7/e6/Bloody_Mary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/8e/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F7.txt ../out/c8/8e/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F7.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/53/British_Museum.txt ../out/c9/53/British_Museum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/d9/Anarcho-capitalism.txt ../out/c9/d9/Anarcho-capitalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/5a/Asynchronous_Transfer_Mode.txt ../out/ca/5a/Asynchronous_Transfer_Mode.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/42/William_Kidd.txt ../out/cb/42/William_Kidd.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/06/Agrarianism.txt ../out/cc/06/Agrarianism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/cf/Britney_Spears.txt ../out/cc/cf/Britney_Spears.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/4b/Bipolar_Disorder.txt ../out/cd/4b/Bipolar_Disorder.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/e8/Eon_%28geology%29.txt ../out/cd/e8/Eon_%28geology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/df/Anguilla.txt ../out/ce/df/Anguilla.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/8f/Arctic_fox.txt ../out/cf/8f/Arctic_fox.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/2e/Plague_%28disease%29.txt ../out/d0/2e/Plague_%28disease%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/15/Cucurbitales.txt ../out/d1/15/Cucurbitales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/7c/Biology%2FAdditional_biology_topics_and_keywords.txt ../out/d1/7c/Biology%2FAdditional_biology_topics_and_keywords.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/6b/Common_Era.txt ../out/d2/6b/Common_Era.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/07/Boer.txt ../out/d3/07/Boer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/9c/Asparagales.txt ../out/d3/9c/Asparagales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/81/Charlemagne.txt ../out/d4/81/Charlemagne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/11/Charlotte_Bront%C3%AB.txt ../out/d5/11/Charlotte_Bront%C3%AB.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/ae/Country_code.txt ../out/d5/ae/Country_code.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/69/Duesberg_hypothesis.txt ../out/d6/69/Duesberg_hypothesis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/ed/Enzyme.txt ../out/d6/ed/Enzyme.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/8a/Book_of_Malachi.txt ../out/d7/8a/Book_of_Malachi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/36/Colorado_Front_Range.txt ../out/d8/36/Colorado_Front_Range.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/f4/Politics_of_Chad.txt ../out/d8/f4/Politics_of_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/a5/Convention_on_Biological_Diversity.txt ../out/d9/a5/Convention_on_Biological_Diversity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/67/Antony_van_Leeuwenhoek.txt ../out/da/67/Antony_van_Leeuwenhoek.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/ef/Dodecahedron.txt ../out/da/ef/Dodecahedron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/4f/Barry_Goldwater.txt ../out/db/4f/Barry_Goldwater.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/23/Alexios_I_Komnenos.txt ../out/dc/23/Alexios_I_Komnenos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/a6/Earthdawn.txt ../out/dc/a6/Earthdawn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/6f/Andrei_Sakharov.txt ../out/dd/6f/Andrei_Sakharov.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/d5/Crystal_Eastman.txt ../out/dd/d5/Crystal_Eastman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/a7/Aargau.txt ../out/de/a7/Aargau.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/58/Albrecht_Durer.txt ../out/df/58/Albrecht_Durer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/17/Military_of_Botswana.txt ../out/e0/17/Military_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/f2/Derek_Walcott.txt ../out/e0/f2/Derek_Walcott.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/9e/Civil_defense.txt ../out/e1/9e/Civil_defense.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/39/Brouwer_fixed-point_theorem.txt ../out/e2/39/Brouwer_fixed-point_theorem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/fe/Arthur_J._Stone.txt ../out/e2/fe/Arthur_J._Stone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/98/ErnestHemingway%2FFromBoytoManHemingwaysFirstWorldWar.txt ../out/e3/98/ErnestHemingway%2FFromBoytoManHemingwaysFirstWorldWar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/1c/Dalton_Trumbo.txt ../out/e4/1c/Dalton_Trumbo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/fc/David_Ricardo.txt ../out/e4/fc/David_Ricardo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/a3/Batch_job.txt ../out/e5/a3/Batch_job.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/0d/Aegisthus.txt ../out/e6/0d/Aegisthus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/f0/Commonwealth.txt ../out/e6/f0/Commonwealth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/b3/Copenhagen_interpretation.txt ../out/e7/b3/Copenhagen_interpretation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/4a/Columbia_River.txt ../out/e8/4a/Columbia_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/f3/Beer%E2%80%93Lambert_law.txt ../out/e8/f3/Beer%E2%80%93Lambert_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/7b/August_9.txt ../out/e9/7b/August_9.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/f9/Afterglow.txt ../out/e9/f9/Afterglow.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/7e/Bermuda%2FTransnational_issues.txt ../out/ea/7e/Bermuda%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/45/Causes_of_heterosexuality.txt ../out/eb/45/Causes_of_heterosexuality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/d7/Cross-compilation.txt ../out/eb/d7/Cross-compilation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/c3/Ashmore_and_Cartier_Islands%2FEconomy.txt ../out/ec/c3/Ashmore_and_Cartier_Islands%2FEconomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/84/Anti-globalisation_movement.txt ../out/ed/84/Anti-globalisation_movement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/fe/Andrea_Alciato.txt ../out/ed/fe/Andrea_Alciato.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/9d/Crane_shot.txt ../out/ee/9d/Crane_shot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/40/Covenant-breaker.txt ../out/ef/40/Covenant-breaker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/c9/Blindness.txt ../out/ef/c9/Blindness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/85/Blue_Steel_%28missile%29.txt ../out/f0/85/Blue_Steel_%28missile%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/41/Analytical_Engine.txt ../out/f1/41/Analytical_Engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/24/Apple_I.txt ../out/f2/24/Apple_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/29/Balkans.txt ../out/f3/29/Balkans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/d1/Politics_of_Equatorial_Guinea.txt ../out/f3/d1/Politics_of_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/a8/Bronze_Star_Medal.txt ../out/f4/a8/Bronze_Star_Medal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/72/Piano_Trio%2C_Op._97_%28Beethoven%29.txt ../out/f5/72/Piano_Trio%2C_Op._97_%28Beethoven%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/02/Czech_republic%2FMilitary.txt ../out/f6/02/Czech_republic%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/be/Transport_in_Armenia.txt ../out/f6/be/Transport_in_Armenia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/47/Afrobeat.txt ../out/f7/47/Afrobeat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/01/Antarctic-Environmental_Protocol.txt ../out/f8/01/Antarctic-Environmental_Protocol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/a4/Asymptote.txt ../out/f8/a4/Asymptote.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/11/Aeschylus.txt ../out/f9/11/Aeschylus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/b4/Government_of_the_Cocos_%28Keeling%29_Islands.txt ../out/f9/b4/Government_of_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/31/April_27.txt ../out/fa/31/April_27.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/bd/Central_Powers.txt ../out/fa/bd/Central_Powers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/6b/Church_of_the_Holy_Sepulchre.txt ../out/fb/6b/Church_of_the_Holy_Sepulchre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/16/Edgar_Rice_Burroughs.txt ../out/fc/16/Edgar_Rice_Burroughs.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/16/European_route_E4.txt ../out/fd/16/European_route_E4.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/ce/Divinity.txt ../out/fd/ce/Divinity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/8e/Countries_of_the_World.txt ../out/fe/8e/Countries_of_the_World.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/34/Cartridge.txt ../out/ff/34/Cartridge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/86/Color%2Fcyan.txt ../out/ff/86/Color%2Fcyan.xml
