php ./wiki2xml/php/wiki2xml_command.php ../out/00/d1/Centimetre.txt ../out/00/d1/Centimetre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/64/Cardinal_number.txt ../out/01/64/Cardinal_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/f8/Addition_of_natural_numbers.txt ../out/01/f8/Addition_of_natural_numbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/b3/Geography_of_Alabama.txt ../out/02/b3/Geography_of_Alabama.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/52/Dock.txt ../out/03/52/Dock.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/f2/C._S._Forester.txt ../out/03/f2/C._S._Forester.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/7f/Calreticulin.txt ../out/04/7f/Calreticulin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/20/Politics_of_Cape_Verde.txt ../out/05/20/Politics_of_Cape_Verde.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/ac/Ann_Druyan.txt ../out/05/ac/Ann_Druyan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/25/Automatic_telephone_exchange.txt ../out/06/25/Automatic_telephone_exchange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/df/Christian_alternative_rock.txt ../out/06/df/Christian_alternative_rock.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/91/AmericanFootball.txt ../out/07/91/AmericanFootball.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/4d/Cultural_anthropology.txt ../out/08/4d/Cultural_anthropology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/de/Emancipation_Proclamation.txt ../out/08/de/Emancipation_Proclamation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/87/Color_temperature.txt ../out/09/87/Color_temperature.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/74/Claudine_%28book_series%29.txt ../out/0a/74/Claudine_%28book_series%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/d2/Chinese_language.txt ../out/0a/d2/Chinese_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/8c/Charles_Evers.txt ../out/0b/8c/Charles_Evers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/01/Electrical_network.txt ../out/0c/01/Electrical_network.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/a4/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FV.txt ../out/0c/a4/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/76/Common_Gateway_Interface.txt ../out/0d/76/Common_Gateway_Interface.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/30/ArgumentForms.txt ../out/0e/30/ArgumentForms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/b7/Doctor_V64.txt ../out/0e/b7/Doctor_V64.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/68/Ethics.txt ../out/0f/68/Ethics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/49/Binomial_coefficient.txt ../out/10/49/Binomial_coefficient.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/3a/Baseball_positions.txt ../out/11/3a/Baseball_positions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/c9/Contra_dance.txt ../out/11/c9/Contra_dance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/73/Amara_Sinha.txt ../out/12/73/Amara_Sinha.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/1d/Andersonville.txt ../out/13/1d/Andersonville.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/93/Context-sensitive_language.txt ../out/13/93/Context-sensitive_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/70/Alois_Alzheimer.txt ../out/14/70/Alois_Alzheimer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/08/Ethical_egoism.txt ../out/15/08/Ethical_egoism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/aa/Chicano.txt ../out/15/aa/Chicano.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/4b/Canonization_of_Saints.txt ../out/16/4b/Canonization_of_Saints.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/f7/Cluny.txt ../out/16/f7/Cluny.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/d1/Billion_%28disambiguation%29.txt ../out/17/d1/Billion_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/57/Dr._Seuss.txt ../out/18/57/Dr._Seuss.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/f7/Ethylene.txt ../out/18/f7/Ethylene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/7a/British_Indian_Ocean_Territory%2FGeography.txt ../out/19/7a/British_Indian_Ocean_Territory%2FGeography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/0e/Caving.txt ../out/1a/0e/Caving.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/a6/Charles_Dickens.txt ../out/1a/a6/Charles_Dickens.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/24/Chaparral.txt ../out/1b/24/Chaparral.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/cc/Alphonso_X.txt ../out/1b/cc/Alphonso_X.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/3e/ComedyFilm.txt ../out/1c/3e/ComedyFilm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/cf/B.C.E.txt ../out/1c/cf/B.C.E.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/55/Electric_current.txt ../out/1d/55/Electric_current.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/fc/Charles_Edward_Jones.txt ../out/1d/fc/Charles_Edward_Jones.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/9d/Divergence.txt ../out/1e/9d/Divergence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/93/Dune%2FVideogames.txt ../out/1f/93/Dune%2FVideogames.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/35/Elbl%C4%85g.txt ../out/20/35/Elbl%C4%85g.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/e9/Demographics_of_Ivory_Coast.txt ../out/20/e9/Demographics_of_Ivory_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/76/Cloning.txt ../out/21/76/Cloning.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/61/Natural_history_of_Africa.txt ../out/22/61/Natural_history_of_Africa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/03/Carbine.txt ../out/23/03/Carbine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/bc/%C3%81ed_mac_Cin%C3%A1eda.txt ../out/23/bc/%C3%81ed_mac_Cin%C3%A1eda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/50/Geography_of_Bouvet_Island.txt ../out/24/50/Geography_of_Bouvet_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/f6/ErnestHemingway%2FBibliographY.txt ../out/24/f6/ErnestHemingway%2FBibliographY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/cf/American_Revolutionary_War.txt ../out/25/cf/American_Revolutionary_War.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/4b/A._A._Milne.txt ../out/26/4b/A._A._Milne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/04/Aerodynamics.txt ../out/27/04/Aerodynamics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/ae/Celts.txt ../out/27/ae/Celts.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/4f/Computer_science.txt ../out/28/4f/Computer_science.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/c4/History_of_Dominica.txt ../out/28/c4/History_of_Dominica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/79/Fairchild_Channel_F.txt ../out/29/79/Fairchild_Channel_F.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/2b/Canadian_whisky.txt ../out/2a/2b/Canadian_whisky.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/08/Catatonia.txt ../out/2b/08/Catatonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/81/Carbon_sink.txt ../out/2b/81/Carbon_sink.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/39/List_of_Major_League_Baseball_career_total_bases_leaders.txt ../out/2c/39/List_of_Major_League_Baseball_career_total_bases_leaders.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/c1/Astrobiology.txt ../out/2c/c1/Astrobiology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/99/Djinn.txt ../out/2d/99/Djinn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/30/Adrian_Lamo.txt ../out/2e/30/Adrian_Lamo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/ea/Burma%2FEconomy.txt ../out/2e/ea/Burma%2FEconomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/a7/Angles.txt ../out/2f/a7/Angles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/b2/AT_and_T.txt ../out/30/b2/AT_and_T.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/23/Anglican_Church.txt ../out/31/23/Anglican_Church.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/1a/Data_Compression%2Fsampling_frequency.txt ../out/32/1a/Data_Compression%2Fsampling_frequency.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/db/Anarcho-capitalists.txt ../out/32/db/Anarcho-capitalists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/64/Dairy_product.txt ../out/33/64/Dairy_product.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/6f/Actinium.txt ../out/34/6f/Actinium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/f4/DualisticInteractionism.txt ../out/34/f4/DualisticInteractionism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/b6/Erosion.txt ../out/35/b6/Erosion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/75/ArtificalLanguages.txt ../out/36/75/ArtificalLanguages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/33/Aveiro%2C_Portugal.txt ../out/37/33/Aveiro%2C_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/b2/E-commerce.txt ../out/37/b2/E-commerce.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/13/DNA_virus.txt ../out/38/13/DNA_virus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/c0/Cleopatra_%28disambiguation%29.txt ../out/38/c0/Cleopatra_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/ab/Archdiocese_for_the_Military_Services.txt ../out/39/ab/Archdiocese_for_the_Military_Services.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/3e/E.txt ../out/3a/3e/E.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/aa/Battle_of_Adrianopolis.txt ../out/3a/aa/Battle_of_Adrianopolis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/3e/Eden_Project.txt ../out/3b/3e/Eden_Project.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/bf/Colony.txt ../out/3b/bf/Colony.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/5f/Daniel_Dennett.txt ../out/3c/5f/Daniel_Dennett.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/07/List_of_artificial_intelligence_projects.txt ../out/3d/07/List_of_artificial_intelligence_projects.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/94/Badminton.txt ../out/3d/94/Badminton.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/72/Linear_filter.txt ../out/3e/72/Linear_filter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/dd/Alban_Berg.txt ../out/3e/dd/Alban_Berg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/40/Engines_of_creation.txt ../out/3f/40/Engines_of_creation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/00/Automated_Alice%2FV.txt ../out/40/00/Automated_Alice%2FV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/b0/Foreign_relations_of_Equatorial_Guinea.txt ../out/40/b0/Foreign_relations_of_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/5c/Don_Quixote.txt ../out/41/5c/Don_Quixote.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/d0/Amathus.txt ../out/41/d0/Amathus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/2e/Devanagari.txt ../out/42/2e/Devanagari.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/e7/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FY.txt ../out/42/e7/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FY.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/80/Axiomatic_Set_Theory.txt ../out/43/80/Axiomatic_Set_Theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/2a/Advanced_Encryption_Standard.txt ../out/44/2a/Advanced_Encryption_Standard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/98/August_22.txt ../out/44/98/August_22.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/40/Boney_M..txt ../out/45/40/Boney_M..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/f9/Database_management_system.txt ../out/45/f9/Database_management_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/aa/Arkansas.txt ../out/46/aa/Arkansas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/70/The_Big_O.txt ../out/47/70/The_Big_O.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/0b/Bubble_sort%2FC.txt ../out/48/0b/Bubble_sort%2FC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/ca/Alkyne.txt ../out/48/ca/Alkyne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/77/Abjuration.txt ../out/49/77/Abjuration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/01/%C3%87atalh%C3%B6y%C3%BCk.txt ../out/4a/01/%C3%87atalh%C3%B6y%C3%BCk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/b3/Bacterial_vaginosis.txt ../out/4a/b3/Bacterial_vaginosis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/45/Arcadius.txt ../out/4b/45/Arcadius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/ed/Dungeon_Master_%28disambiguation%29.txt ../out/4b/ed/Dungeon_Master_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/68/Circumcision_and_law.txt ../out/4c/68/Circumcision_and_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/3f/Albert_Speer.txt ../out/4d/3f/Albert_Speer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/b2/Bodhidharma.txt ../out/4d/b2/Bodhidharma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/4d/Aelbert_Cuyp.txt ../out/4e/4d/Aelbert_Cuyp.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/ed/Foreign_relations_of_Cuba.txt ../out/4e/ed/Foreign_relations_of_Cuba.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/ac/Colorado_Springs%2C_Colorado.txt ../out/4f/ac/Colorado_Springs%2C_Colorado.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/55/Armored_car_%28military%29.txt ../out/50/55/Armored_car_%28military%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/15/Bayern.txt ../out/51/15/Bayern.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/a1/Banjo.txt ../out/51/a1/Banjo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/66/Consul.txt ../out/52/66/Consul.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/01/Central_Plaza_%28Hong_Kong%29.txt ../out/53/01/Central_Plaza_%28Hong_Kong%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/9a/Blue_%C3%96yster_Cult.txt ../out/53/9a/Blue_%C3%96yster_Cult.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/24/Eulers_number.txt ../out/54/24/Eulers_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/a3/Arthur_William_%C3%A0_Beckett.txt ../out/54/a3/Arthur_William_%C3%A0_Beckett.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/67/Dennis_Hopper%2FFilmography.txt ../out/55/67/Dennis_Hopper%2FFilmography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/f6/Kennedy_family.txt ../out/55/f6/Kennedy_family.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/e3/Coral_Sea_Islands%2FGovernment.txt ../out/56/e3/Coral_Sea_Islands%2FGovernment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/a5/Chinese_philosophy.txt ../out/57/a5/Chinese_philosophy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/43/Adhesive.txt ../out/58/43/Adhesive.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/fd/Compost.txt ../out/58/fd/Compost.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/7d/Canada%2Fcities.txt ../out/59/7d/Canada%2Fcities.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/21/Blade_Runner_2%3A_The_Edge_of_Human.txt ../out/5a/21/Blade_Runner_2%3A_The_Edge_of_Human.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/b4/Choosing_summary_statistics.txt ../out/5a/b4/Choosing_summary_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/42/Blue_Angels.txt ../out/5b/42/Blue_Angels.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/dd/Bluetongue_disease.txt ../out/5b/dd/Bluetongue_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/a1/Chromatography.txt ../out/5c/a1/Chromatography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/4f/Conspiracy_theories.txt ../out/5d/4f/Conspiracy_theories.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/34/Elvis_Presley.txt ../out/5e/34/Elvis_Presley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/aa/Breton_language.txt ../out/5e/aa/Breton_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/63/Cetacea.txt ../out/5f/63/Cetacea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/18/Click_consonant.txt ../out/60/18/Click_consonant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/bb/Bulgarian.txt ../out/60/bb/Bulgarian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/74/Distilling.txt ../out/61/74/Distilling.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/fa/Museum_of_Work.txt ../out/61/fa/Museum_of_Work.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/cd/Autrefois_acquit.txt ../out/62/cd/Autrefois_acquit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/ba/Aarons_Rod.txt ../out/63/ba/Aarons_Rod.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/9c/Bangor.txt ../out/64/9c/Bangor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/20/Active_Server_Pages.txt ../out/65/20/Active_Server_Pages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/9b/CountriesC.txt ../out/65/9b/CountriesC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/13/Bragi.txt ../out/66/13/Bragi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/ae/Bakelite.txt ../out/66/ae/Bakelite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/37/Card_games.txt ../out/67/37/Card_games.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/fc/CountriesJ.txt ../out/67/fc/CountriesJ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/84/Military_of_Costa_Rica.txt ../out/68/84/Military_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/5e/Danish_Defence.txt ../out/69/5e/Danish_Defence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/0d/Alp_Arslan.txt ../out/6a/0d/Alp_Arslan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/97/Bin_Laden_%28disambiguation%29.txt ../out/6a/97/Bin_Laden_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/0a/Brian_Kernighan.txt ../out/6b/0a/Brian_Kernighan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/c5/Dot-com_bubble.txt ../out/6b/c5/Dot-com_bubble.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/4b/Adelaide_of_Italy.txt ../out/6c/4b/Adelaide_of_Italy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/d5/Botswana.txt ../out/6c/d5/Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/79/Abd_ar-Rahman_V.txt ../out/6d/79/Abd_ar-Rahman_V.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/0b/Conventional_insulinotherapy.txt ../out/6e/0b/Conventional_insulinotherapy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/9a/Alexei_Petrovich%2C_Tsarevich_of_Russia.txt ../out/6e/9a/Alexei_Petrovich%2C_Tsarevich_of_Russia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/14/Antipope_Felix_II.txt ../out/6f/14/Antipope_Felix_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/e8/Debian.txt ../out/6f/e8/Debian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/a3/Cauchy_sequences.txt ../out/70/a3/Cauchy_sequences.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/76/Cell_%28biology%29.txt ../out/71/76/Cell_%28biology%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/17/Athene_%28disambiguation%29.txt ../out/72/17/Athene_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/91/Chinese_element.txt ../out/72/91/Chinese_element.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/75/Collective_trauma.txt ../out/73/75/Collective_trauma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/24/Christiaan_Barnard.txt ../out/74/24/Christiaan_Barnard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/7f/Epic_poetry.txt ../out/74/7f/Epic_poetry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/33/Entorhinal_cortex.txt ../out/75/33/Entorhinal_cortex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/d5/African_National_Congress.txt ../out/75/d5/African_National_Congress.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/85/EastGermany.txt ../out/76/85/EastGermany.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/22/Dolichocephalic.txt ../out/77/22/Dolichocephalic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/ca/Dressed_to_Kill_%281980_film%29.txt ../out/77/ca/Dressed_to_Kill_%281980_film%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/a6/December_19.txt ../out/78/a6/December_19.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/01/American_English.txt ../out/79/01/American_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/b0/CountriesG.txt ../out/79/b0/CountriesG.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/51/Classification_of_finite_simple_groups.txt ../out/7a/51/Classification_of_finite_simple_groups.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/92/Assembly_line.txt ../out/7a/92/Assembly_line.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/36/Cytology.txt ../out/7b/36/Cytology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/fa/Engine.txt ../out/7b/fa/Engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/c7/Abortion.txt ../out/7c/c7/Abortion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/30/Hit_%28baseball%29.txt ../out/7d/30/Hit_%28baseball%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/f0/Austrian_School.txt ../out/7d/f0/Austrian_School.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/6d/Density.txt ../out/7e/6d/Density.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/35/CountriesI.txt ../out/7f/35/CountriesI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/cb/Extinction_event.txt ../out/7f/cb/Extinction_event.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/2e/Economy_of_Antarctica.txt ../out/80/2e/Economy_of_Antarctica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/c1/Ames%2C_Iowa.txt ../out/80/c1/Ames%2C_Iowa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/7e/Centriole.txt ../out/81/7e/Centriole.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/2d/George_Abbot_%28bishop%29.txt ../out/82/2d/George_Abbot_%28bishop%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/10/Dodo.txt ../out/83/10/Dodo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/ae/Bhangra_%28music%29.txt ../out/83/ae/Bhangra_%28music%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/6e/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F0.txt ../out/84/6e/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2F0.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/3f/Anaconda.txt ../out/85/3f/Anaconda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/a7/Foreign_relations_of_Angola.txt ../out/85/a7/Foreign_relations_of_Angola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/56/Chronometer.txt ../out/86/56/Chronometer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/ea/Catharine_of_Aragon.txt ../out/86/ea/Catharine_of_Aragon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/96/Ecology.txt ../out/87/96/Ecology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/82/Albategnius.txt ../out/88/82/Albategnius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/19/Ethnicity.txt ../out/89/19/Ethnicity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/bf/Copula_%28linguistics%29.txt ../out/89/bf/Copula_%28linguistics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/36/Albanians.txt ../out/8a/36/Albanians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/1c/Atlanta.txt ../out/8b/1c/Atlanta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/af/Economy_of_Cameroon.txt ../out/8b/af/Economy_of_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/72/Condition_number.txt ../out/8c/72/Condition_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/e9/British_Columbia.txt ../out/8c/e9/British_Columbia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/81/Ambiguity.txt ../out/8d/81/Ambiguity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/54/Agriculture.txt ../out/8e/54/Agriculture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/34/Dolphins.txt ../out/8f/34/Dolphins.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/f9/Calendar.txt ../out/8f/f9/Calendar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/d4/Politics_of_Egypt.txt ../out/90/d4/Politics_of_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/44/Robert_Bellarmine.txt ../out/91/44/Robert_Bellarmine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/72/Bosphorus.txt ../out/92/72/Bosphorus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/14/Aphelion.txt ../out/93/14/Aphelion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/ae/Common_law.txt ../out/93/ae/Common_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/87/The_Diary_of_Anne_Frank.txt ../out/94/87/The_Diary_of_Anne_Frank.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/38/DXF.txt ../out/95/38/DXF.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/c9/Ahmed_al-Haznawi.txt ../out/95/c9/Ahmed_al-Haznawi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/a6/Bosnia_and_Herzegovina.txt ../out/96/a6/Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/3f/Bangra.txt ../out/97/3f/Bangra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/ca/Abitibi.txt ../out/97/ca/Abitibi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/4a/Economy_of_Afghanistan.txt ../out/98/4a/Economy_of_Afghanistan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/eb/Chapter_11%2C_Title_11%2C_United_States_Code.txt ../out/98/eb/Chapter_11%2C_Title_11%2C_United_States_Code.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/74/Wikipedia%3ABuilding_Wikipedia_membership%2FBig_traffic_links_solicited.txt ../out/99/74/Wikipedia%3ABuilding_Wikipedia_membership%2FBig_traffic_links_solicited.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/e0/Abbe_number.txt ../out/99/e0/Abbe_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/6a/%C3%86lfheah_of_Canterbury.txt ../out/9a/6a/%C3%86lfheah_of_Canterbury.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/0b/Catholicism%2FSecond_Vatican_Council.txt ../out/9b/0b/Catholicism%2FSecond_Vatican_Council.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/ac/Claus_Sluter.txt ../out/9b/ac/Claus_Sluter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/24/Politics_of_Cameroon.txt ../out/9c/24/Politics_of_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/bf/Bitola.txt ../out/9c/bf/Bitola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/41/Benjamin_D._Santer.txt ../out/9d/41/Benjamin_D._Santer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/e1/Anthophyta.txt ../out/9d/e1/Anthophyta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/be/Economy_of_Chile.txt ../out/9e/be/Economy_of_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/7c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FC.txt ../out/9f/7c/Wikipedia%3AComplete_list_of_encyclopedia_topics_%28obsolete%29%2FC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/0a/Argentina%2FTransnational_issues.txt ../out/a0/0a/Argentina%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/c4/Argument_from_evolution.txt ../out/a0/c4/Argument_from_evolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/b5/Cutaway_%28filmmaking%29.txt ../out/a1/b5/Cutaway_%28filmmaking%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/72/Severus_Alexander.txt ../out/a2/72/Severus_Alexander.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/1d/Caldera.txt ../out/a3/1d/Caldera.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/d4/England_national_football_team.txt ../out/a3/d4/England_national_football_team.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/97/Eaglet_%28Alice%27s_Adventures_in_Wonderland%29.txt ../out/a4/97/Eaglet_%28Alice%27s_Adventures_in_Wonderland%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/f5/Cuboctahedron.txt ../out/a4/f5/Cuboctahedron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/7e/Catholics.txt ../out/a5/7e/Catholics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/29/Applesoft_BASIC.txt ../out/a6/29/Applesoft_BASIC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/c3/Apollo.txt ../out/a6/c3/Apollo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/6d/Double_boiler.txt ../out/a7/6d/Double_boiler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/4d/Alternative.txt ../out/a8/4d/Alternative.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/01/Politics_of_Angola.txt ../out/a9/01/Politics_of_Angola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/de/Amorphous.txt ../out/a9/de/Amorphous.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/69/CDP1802.txt ../out/aa/69/CDP1802.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/d4/Jacques-Louis_David.txt ../out/aa/d4/Jacques-Louis_David.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/68/Amazon_River.txt ../out/ab/68/Amazon_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/10/Body.txt ../out/ac/10/Body.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/9b/Algae.txt ../out/ac/9b/Algae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/f9/Acadia_University.txt ../out/ac/f9/Acadia_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/eb/Telecommunications_in_the_Cayman_Islands.txt ../out/ad/eb/Telecommunications_in_the_Cayman_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/68/Bundesland.txt ../out/ae/68/Bundesland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/06/Barnard%27s_Star.txt ../out/af/06/Barnard%27s_Star.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/98/Abstract_Algebra.txt ../out/af/98/Abstract_Algebra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/25/Elizabeth_Garrett_Anderson.txt ../out/b0/25/Elizabeth_Garrett_Anderson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/e7/Atari_ST.txt ../out/b0/e7/Atari_ST.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/8c/Convention_on_Fishing_and_Conservation_of_the_Living_Resources_of_the_High_Seas.txt ../out/b1/8c/Convention_on_Fishing_and_Conservation_of_the_Living_Resources_of_the_High_Seas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/e5/Ask_and_Embla.txt ../out/b1/e5/Ask_and_Embla.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/94/Cut-up_technique.txt ../out/b2/94/Cut-up_technique.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/a9/CN_Tower.txt ../out/b3/a9/CN_Tower.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/42/Erwin_Rommel.txt ../out/b4/42/Erwin_Rommel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/ad/Abensberg.txt ../out/b4/ad/Abensberg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/0a/August_4.txt ../out/b5/0a/August_4.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/6d/Cognitive_psychology.txt ../out/b5/6d/Cognitive_psychology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/04/Bhutan%2FTransnational_issues.txt ../out/b6/04/Bhutan%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/e6/Demographics_of_the_British_Virgin_Islands.txt ../out/b6/e6/Demographics_of_the_British_Virgin_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/9f/Constitution_of_Canada%2F1867_VII_Judicature.txt ../out/b7/9f/Constitution_of_Canada%2F1867_VII_Judicature.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/3e/Arbitration_in_the_United_States.txt ../out/b8/3e/Arbitration_in_the_United_States.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/b6/Crucifix.txt ../out/b8/b6/Crucifix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/a8/Comet.txt ../out/b9/a8/Comet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/26/Analog_television.txt ../out/ba/26/Analog_television.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/e7/April_25.txt ../out/ba/e7/April_25.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/77/Exile.txt ../out/bb/77/Exile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/f0/Canary_Islands.txt ../out/bb/f0/Canary_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/82/Banach_space.txt ../out/bc/82/Banach_space.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/65/Bluegrass.txt ../out/bd/65/Bluegrass.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/1c/Bayezid_I.txt ../out/be/1c/Bayezid_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/d4/Dynamic_Host_Configuration_Protocol.txt ../out/be/d4/Dynamic_Host_Configuration_Protocol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/6d/Communications_in_Colombia.txt ../out/bf/6d/Communications_in_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/29/Lockheed_AC-130.txt ../out/c0/29/Lockheed_AC-130.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/e6/Doctor_Who.txt ../out/c0/e6/Doctor_Who.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/93/Adrian.txt ../out/c1/93/Adrian.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/61/Anacharsis.txt ../out/c2/61/Anacharsis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/1a/Data_General_Nova.txt ../out/c3/1a/Data_General_Nova.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/c6/Burgundians.txt ../out/c3/c6/Burgundians.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/4e/Double_planet.txt ../out/c4/4e/Double_planet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/f7/Advance_Australia_Fair.txt ../out/c4/f7/Advance_Australia_Fair.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/f6/ActresseS.txt ../out/c5/f6/ActresseS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/9e/Dartmoor.txt ../out/c6/9e/Dartmoor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/5c/Greek_drachma.txt ../out/c7/5c/Greek_drachma.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/12/Buddhist_cuisine.txt ../out/c8/12/Buddhist_cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/d9/Arnold_Schwarzenegger.txt ../out/c8/d9/Arnold_Schwarzenegger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/6d/Apollo_14.txt ../out/c9/6d/Apollo_14.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/f2/Abeyance.txt ../out/c9/f2/Abeyance.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/96/British_Queen.txt ../out/ca/96/British_Queen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/6e/Arabic_numerals.txt ../out/cb/6e/Arabic_numerals.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/3a/Cholera.txt ../out/cc/3a/Cholera.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/f3/Blizzard.txt ../out/cc/f3/Blizzard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/92/Amr_Diab.txt ../out/cd/92/Amr_Diab.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/2e/Crony_capitalism.txt ../out/ce/2e/Crony_capitalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/0b/Education_vouchers.txt ../out/cf/0b/Education_vouchers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/9f/Analog_Science_Fiction.txt ../out/cf/9f/Analog_Science_Fiction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/60/American_Folklore.txt ../out/d0/60/American_Folklore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/2b/Cottingley_Fairies.txt ../out/d1/2b/Cottingley_Fairies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/ea/AccessibleComputing.txt ../out/d1/ea/AccessibleComputing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/a9/Angels_in_art.txt ../out/d2/a9/Angels_in_art.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/1a/Chariots_of_Fire.txt ../out/d3/1a/Chariots_of_Fire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/ba/The_World_Factbook.txt ../out/d3/ba/The_World_Factbook.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/a2/Cyclic_adenosine_monophosphate.txt ../out/d4/a2/Cyclic_adenosine_monophosphate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/3e/Geography_of_the_Central_African_Republic.txt ../out/d5/3e/Geography_of_the_Central_African_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/da/Castrato.txt ../out/d5/da/Castrato.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/80/Chalcolithic.txt ../out/d6/80/Chalcolithic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/20/Condensation_polymer.txt ../out/d7/20/Condensation_polymer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/9e/Business_statistics.txt ../out/d7/9e/Business_statistics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/71/Constantine.txt ../out/d8/71/Constantine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/07/CISC.txt ../out/d9/07/CISC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/c3/AfroAsiaticLanguages.txt ../out/d9/c3/AfroAsiaticLanguages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/87/Cut-and-cover.txt ../out/da/87/Cut-and-cover.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/fd/Drunk.txt ../out/da/fd/Drunk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/a3/Baker_Island.txt ../out/db/a3/Baker_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/42/Ectopia_%28medicine%29.txt ../out/dc/42/Ectopia_%28medicine%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/e8/Extinct_countries.txt ../out/dc/e8/Extinct_countries.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/89/Decipherment.txt ../out/dd/89/Decipherment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/f1/Geography_of_Dominica.txt ../out/dd/f1/Geography_of_Dominica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/ca/Aspect_ratio.txt ../out/de/ca/Aspect_ratio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/77/Cream.txt ../out/df/77/Cream.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/36/Chad.txt ../out/e0/36/Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/2b/Professional_certification.txt ../out/e1/2b/Professional_certification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/bf/Book_of_Jonah.txt ../out/e1/bf/Book_of_Jonah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/7c/Beta_sheet.txt ../out/e2/7c/Beta_sheet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/24/Adirondacks.txt ../out/e3/24/Adirondacks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/a5/Dylan_Thomas.txt ../out/e3/a5/Dylan_Thomas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/64/British_Indian_Ocean_Territory%2FCommunications.txt ../out/e4/64/British_Indian_Ocean_Territory%2FCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/17/Bagpipes.txt ../out/e5/17/Bagpipes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/c3/Commodore_64.txt ../out/e5/c3/Commodore_64.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/50/Buffy_the_Vampire_Slayer_%28film%29.txt ../out/e6/50/Buffy_the_Vampire_Slayer_%28film%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/21/Cross_section_%28physics%29.txt ../out/e7/21/Cross_section_%28physics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/f0/Politics_of_Estonia.txt ../out/e7/f0/Politics_of_Estonia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/8b/Disney_%28disambiguation%29.txt ../out/e8/8b/Disney_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/fe/Telecommunications_in_Botswana.txt ../out/e8/fe/Telecommunications_in_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/94/Clinker.txt ../out/e9/94/Clinker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/0a/December_8.txt ../out/ea/0a/December_8.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/cc/Dutch_West_India_Company.txt ../out/ea/cc/Dutch_West_India_Company.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/50/Ames_test.txt ../out/eb/50/Ames_test.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/37/Binding_arbitration.txt ../out/ec/37/Binding_arbitration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/0c/Aotus.txt ../out/ed/0c/Aotus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/98/Bit.txt ../out/ed/98/Bit.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/19/Telecommunications_in_the_Comoros.txt ../out/ee/19/Telecommunications_in_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/bb/Antiprism.txt ../out/ee/bb/Antiprism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/74/Central_African_Armed_Forces.txt ../out/ef/74/Central_African_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/f4/Chlamydia_infection.txt ../out/ef/f4/Chlamydia_infection.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/a1/Bj%C3%B6rn_Ulvaeus.txt ../out/f0/a1/Bj%C3%B6rn_Ulvaeus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/86/Automated_Alice%2FVIII.txt ../out/f1/86/Automated_Alice%2FVIII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/57/Augustine_of_Canterbury.txt ../out/f2/57/Augustine_of_Canterbury.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/47/Endometrium.txt ../out/f3/47/Endometrium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/ef/Beeb.txt ../out/f3/ef/Beeb.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/e0/Telecommunications_in_Ecuador.txt ../out/f4/e0/Telecommunications_in_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/a7/Bacteriophage.txt ../out/f5/a7/Bacteriophage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/4f/Backplane.txt ../out/f6/4f/Backplane.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/d5/Anne_Bront%C3%AB.txt ../out/f6/d5/Anne_Bront%C3%AB.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/68/Atomic_absorption_spectroscopy.txt ../out/f7/68/Atomic_absorption_spectroscopy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/44/Cell_cycle.txt ../out/f8/44/Cell_cycle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/cd/Economy_of_Botswana.txt ../out/f8/cd/Economy_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/31/Aare.txt ../out/f9/31/Aare.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/de/Creationism.txt ../out/f9/de/Creationism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/4c/Aeronautics.txt ../out/fa/4c/Aeronautics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/fc/Columbia_University.txt ../out/fa/fc/Columbia_University.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/a3/Brittonic_languages.txt ../out/fb/a3/Brittonic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/30/D._W._Griffith.txt ../out/fc/30/D._W._Griffith.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/64/Distinguished_Service_Medal_%28U.S._Army%29.txt ../out/fd/64/Distinguished_Service_Medal_%28U.S._Army%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/eb/Dutch_Limburg.txt ../out/fd/eb/Dutch_Limburg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/b6/Aalen.txt ../out/fe/b6/Aalen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/3d/Diaspora.txt ../out/ff/3d/Diaspora.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/93/Buckyball_%28molecule%29.txt ../out/ff/93/Buckyball_%28molecule%29.xml
