php ./wiki2xml/php/wiki2xml_command.php ../out/00/35/Avionics.txt ../out/00/35/Avionics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/00/f7/Amram.txt ../out/00/f7/Amram.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/b4/Bessel_function.txt ../out/01/b4/Bessel_function.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/3c/Cyan.txt ../out/02/3c/Cyan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/02/Transport_in_the_Cocos_%28Keeling%29_Islands.txt ../out/03/02/Transport_in_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/ae/Counter-Strike.txt ../out/03/ae/Counter-Strike.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/2e/Dave_Thomas_%28businessman%29.txt ../out/04/2e/Dave_Thomas_%28businessman%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/ab/Alzheimers_disease.txt ../out/04/ab/Alzheimers_disease.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/50/Bubble_Bobble.txt ../out/05/50/Bubble_Bobble.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/ce/Aegina.txt ../out/05/ce/Aegina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/7b/Cases_of_anthrax.txt ../out/06/7b/Cases_of_anthrax.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/0a/Andreas_Capellanus.txt ../out/07/0a/Andreas_Capellanus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/e2/Edlin.txt ../out/07/e2/Edlin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/91/Constitution_of_Canada%2F1867_XI_Admission_of_Other_Colonies.txt ../out/08/91/Constitution_of_Canada%2F1867_XI_Admission_of_Other_Colonies.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/2d/Desi_Arnaz.txt ../out/09/2d/Desi_Arnaz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/08/Afonso_IV_of_Portugal.txt ../out/0a/08/Afonso_IV_of_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/8e/Autobiography.txt ../out/0a/8e/Autobiography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/3a/Aleksandr_Isaevich_Solzhenitsyn.txt ../out/0b/3a/Aleksandr_Isaevich_Solzhenitsyn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/a7/Foreign_relations_of_the_Czech_Republic.txt ../out/0b/a7/Foreign_relations_of_the_Czech_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/42/Chinese_historiography.txt ../out/0c/42/Chinese_historiography.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/05/Commuter_rail.txt ../out/0d/05/Commuter_rail.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/c3/AbboT.txt ../out/0d/c3/AbboT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/54/Angolan_Armed_Forces.txt ../out/0e/54/Angolan_Armed_Forces.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/18/Eiffel_%28programming_language%29.txt ../out/0f/18/Eiffel_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/b3/Government_of_Europa_Island.txt ../out/0f/b3/Government_of_Europa_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/dc/BSD%2FLicense.txt ../out/10/dc/BSD%2FLicense.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/8e/Ephemeris_time.txt ../out/11/8e/Ephemeris_time.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/31/Cercopithecidae.txt ../out/12/31/Cercopithecidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/ad/Book_of_Jeremiah.txt ../out/12/ad/Book_of_Jeremiah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/5b/Cimabue.txt ../out/13/5b/Cimabue.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/ce/AcademicElitism.txt ../out/13/ce/AcademicElitism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/b2/Bildungsroman.txt ../out/14/b2/Bildungsroman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/31/Military_of_Cyprus.txt ../out/15/31/Military_of_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/e4/Colorado.txt ../out/15/e4/Colorado.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/90/Camel.txt ../out/16/90/Camel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/6a/Economy_of_Angola.txt ../out/17/6a/Economy_of_Angola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/1d/Carbon_nanotube.txt ../out/18/1d/Carbon_nanotube.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/99/Bernie_Federko.txt ../out/18/99/Bernie_Federko.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/22/BinomialDistribution%2FRevisited.txt ../out/19/22/BinomialDistribution%2FRevisited.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/b8/Foreign_relations_of_Ecuador.txt ../out/19/b8/Foreign_relations_of_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/5d/Albert_Sidney_Johnston.txt ../out/1a/5d/Albert_Sidney_Johnston.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/e3/Chairman_of_the_board_%28disambiguation%29.txt ../out/1a/e3/Chairman_of_the_board_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/68/Beatmatching.txt ../out/1b/68/Beatmatching.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/f1/Coyote.txt ../out/1b/f1/Coyote.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/7e/Bill_Bryson.txt ../out/1c/7e/Bill_Bryson.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/f1/From_Boy_to_Man_Hemingways_First_World_War.txt ../out/1c/f1/From_Boy_to_Man_Hemingways_First_World_War.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/c3/DragonMagazine.txt ../out/1d/c3/DragonMagazine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/43/Break_key.txt ../out/1e/43/Break_key.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/bf/Complex_numbers.txt ../out/1e/bf/Complex_numbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/b7/Edgar_Allen_Poe%2FThe_Black_Cat.txt ../out/1f/b7/Edgar_Allen_Poe%2FThe_Black_Cat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/7e/A.I..txt ../out/20/7e/A.I..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/0e/Donn.txt ../out/21/0e/Donn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/ec/Bacon_number.txt ../out/21/ec/Bacon_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/a1/David_Hayes_Agnew.txt ../out/22/a1/David_Hayes_Agnew.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/2b/Angola.txt ../out/23/2b/Angola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/13/Computer_display%2FLCD.txt ../out/24/13/Computer_display%2FLCD.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/8b/Computer_character.txt ../out/24/8b/Computer_character.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/58/Ediacaran.txt ../out/25/58/Ediacaran.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/03/Dr_Who.txt ../out/26/03/Dr_Who.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/9c/A_Vindication_of_the_Rights_of_Woman.txt ../out/26/9c/A_Vindication_of_the_Rights_of_Woman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/42/Ambroise.txt ../out/27/42/Ambroise.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/f2/Anaximenes_of_Lampsacus.txt ../out/27/f2/Anaximenes_of_Lampsacus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/81/Burkina_Faso.txt ../out/28/81/Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/2f/ATM.txt ../out/29/2f/ATM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/b2/Bob_Young_%28businessman%29.txt ../out/29/b2/Bob_Young_%28businessman%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/5e/Charles_Babbage.txt ../out/2a/5e/Charles_Babbage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/55/Demographics_of_the_Comoros.txt ../out/2b/55/Demographics_of_the_Comoros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/d7/Duke_Kahanamoku.txt ../out/2b/d7/Duke_Kahanamoku.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/74/Bunsen.txt ../out/2c/74/Bunsen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/1f/August_Horch.txt ../out/2d/1f/August_Horch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/db/Brandenburg.txt ../out/2d/db/Brandenburg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/89/Backgammon.txt ../out/2e/89/Backgammon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/3e/Bald_eagle.txt ../out/2f/3e/Bald_eagle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/3b/Deep_England.txt ../out/30/3b/Deep_England.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/e8/Dana_Plato.txt ../out/30/e8/Dana_Plato.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/8b/Steel-string_acoustic_guitar.txt ../out/31/8b/Steel-string_acoustic_guitar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/83/April_18.txt ../out/32/83/April_18.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/f7/Eclipse.txt ../out/32/f7/Eclipse.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/f0/April_19.txt ../out/33/f0/April_19.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/c8/A_priori_and_a_posterior_knowledge.txt ../out/34/c8/A_priori_and_a_posterior_knowledge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/58/Books_of_Samuel.txt ../out/35/58/Books_of_Samuel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/f7/Cross_cutting.txt ../out/35/f7/Cross_cutting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/e8/Dominatrix.txt ../out/36/e8/Dominatrix.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/61/Alaska_Interior.txt ../out/37/61/Alaska_Interior.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/db/Algorithms_%28journal%29.txt ../out/37/db/Algorithms_%28journal%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/43/European_Coal_and_Steel_Community.txt ../out/38/43/European_Coal_and_Steel_Community.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/48/Aa_River.txt ../out/39/48/Aa_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/e3/Bantu_languages.txt ../out/39/e3/Bantu_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/60/Clipperton_Island%2FMilitary.txt ../out/3a/60/Clipperton_Island%2FMilitary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/03/Chinese_food.txt ../out/3b/03/Chinese_food.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/82/Centillion.txt ../out/3b/82/Centillion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/eb/Dictionary.txt ../out/3b/eb/Dictionary.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/a1/Human_abdomen.txt ../out/3c/a1/Human_abdomen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/40/Bastard_Operator_From_Hell.txt ../out/3d/40/Bastard_Operator_From_Hell.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/02/Azerbaijan%2FCommunications.txt ../out/3e/02/Azerbaijan%2FCommunications.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/a1/Ethnic.txt ../out/3e/a1/Ethnic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/20/Blue_Tac.txt ../out/3f/20/Blue_Tac.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/a9/Battle_of_the_Nile.txt ../out/3f/a9/Battle_of_the_Nile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/54/Telecommunications_in_Brazil.txt ../out/40/54/Telecommunications_in_Brazil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/d8/ColecoVision.txt ../out/40/d8/ColecoVision.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/a7/Mogul_%28skiing%29.txt ../out/41/a7/Mogul_%28skiing%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/f4/History_of_Ecuador.txt ../out/41/f4/History_of_Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/58/Dr_Strangelove.txt ../out/42/58/Dr_Strangelove.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/26/Geography_of_the_Democratic_Republic_of_the_Congo.txt ../out/43/26/Geography_of_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/ad/Carina_%28constellation%29.txt ../out/43/ad/Carina_%28constellation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/70/Episome.txt ../out/44/70/Episome.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/e5/Arrangement.txt ../out/44/e5/Arrangement.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/7e/Al_Qaida.txt ../out/45/7e/Al_Qaida.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/33/BoethiuS.txt ../out/46/33/BoethiuS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/07/Camilla_Hall.txt ../out/47/07/Camilla_Hall.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/9d/England%2FFood_and_Drink.txt ../out/47/9d/England%2FFood_and_Drink.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/7a/Elbing%2FTruso.txt ../out/48/7a/Elbing%2FTruso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/0d/Archaeoastronomy.txt ../out/49/0d/Archaeoastronomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/bc/Edwin_Austin_Abbey.txt ../out/49/bc/Edwin_Austin_Abbey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/64/Christchurch_%28disambiguation%29.txt ../out/4a/64/Christchurch_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/fa/Algorithm.txt ../out/4a/fa/Algorithm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/a7/CountriesK.txt ../out/4b/a7/CountriesK.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/2a/Eucharist.txt ../out/4c/2a/Eucharist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/b5/Chrysler_Building.txt ../out/4c/b5/Chrysler_Building.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/63/History_of_The_Church_of_Jesus_Christ_of_Latter-day_Saints.txt ../out/4d/63/History_of_The_Church_of_Jesus_Christ_of_Latter-day_Saints.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/00/Foreign_relations_of_Burkina_Faso.txt ../out/4e/00/Foreign_relations_of_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/a5/Alkene.txt ../out/4e/a5/Alkene.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/28/Cobbler.txt ../out/4f/28/Cobbler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/f4/Dylan_%28programming_language%29.txt ../out/4f/f4/Dylan_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/a5/Economic_subjectivism.txt ../out/50/a5/Economic_subjectivism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/69/April_1.txt ../out/51/69/April_1.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/00/Adobe_Systems.txt ../out/52/00/Adobe_Systems.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/93/B_roll.txt ../out/52/93/B_roll.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/42/Classical_Element.txt ../out/53/42/Classical_Element.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/d7/Cue_sports.txt ../out/53/d7/Cue_sports.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/60/Colonial.txt ../out/54/60/Colonial.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/e4/Evolutionary_tree.txt ../out/54/e4/Evolutionary_tree.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/ac/Bundesmarine.txt ../out/55/ac/Bundesmarine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/35/Beavis_and_Butt-head.txt ../out/56/35/Beavis_and_Butt-head.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/4a/Eugenics.txt ../out/57/4a/Eugenics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/26/Edvard_Grieg.txt ../out/58/26/Edvard_Grieg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/85/Deconstructionism.txt ../out/58/85/Deconstructionism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/26/Compound_turbine.txt ../out/59/26/Compound_turbine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/cd/Chemical_engineering.txt ../out/59/cd/Chemical_engineering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/6e/Cape_Town.txt ../out/5a/6e/Cape_Town.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/db/West_Memphis_Three.txt ../out/5a/db/West_Memphis_Three.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/79/Death_metal.txt ../out/5b/79/Death_metal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/37/Claude_Monet.txt ../out/5c/37/Claude_Monet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/dd/Earth.txt ../out/5c/dd/Earth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/d4/Echo_and_the_Bunnymen.txt ../out/5d/d4/Echo_and_the_Bunnymen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/5d/Dhimmi.txt ../out/5e/5d/Dhimmi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/d3/Contraception.txt ../out/5e/d3/Contraception.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/dc/Cimbri%2FWaid.txt ../out/5f/dc/Cimbri%2FWaid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/61/Direct_examination.txt ../out/60/61/Direct_examination.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/26/Digital_signal_processing.txt ../out/61/26/Digital_signal_processing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/a0/Applied_discrete_math.txt ../out/61/a0/Applied_discrete_math.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/35/ErnestHemingway%2FFredericHenry.txt ../out/62/35/ErnestHemingway%2FFredericHenry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/38/Politics_of_Burkina_Faso.txt ../out/63/38/Politics_of_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/04/Andr%C3%A9_Weil.txt ../out/64/04/Andr%C3%A9_Weil.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/d9/CFA_franc.txt ../out/64/d9/CFA_franc.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/53/Albert_I_of_Hapsburg.txt ../out/65/53/Albert_I_of_Hapsburg.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/e5/Clodius.txt ../out/65/e5/Clodius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/53/Bermuda.txt ../out/66/53/Bermuda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/02/Conjecture.txt ../out/67/02/Conjecture.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/8d/Atomic_semantics.txt ../out/67/8d/Atomic_semantics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/28/Entscheidungsproblem.txt ../out/68/28/Entscheidungsproblem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/e6/Division_of_labour.txt ../out/68/e6/Division_of_labour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/a8/Bolshevik_Revolution.txt ../out/69/a8/Bolshevik_Revolution.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/51/Citadel.txt ../out/6a/51/Citadel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/da/Economy_of_Cambodia.txt ../out/6a/da/Economy_of_Cambodia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/69/Battle_of_Actium.txt ../out/6b/69/Battle_of_Actium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/11/Actrius.txt ../out/6c/11/Actrius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/7c/Canchim.txt ../out/6c/7c/Canchim.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/fc/Diablo_II.txt ../out/6c/fc/Diablo_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/bc/August_30.txt ../out/6d/bc/August_30.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/5d/Military_of_the_Dominican_Republic.txt ../out/6e/5d/Military_of_the_Dominican_Republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/ce/Berber_languages.txt ../out/6e/ce/Berber_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/59/Burwash_Hall.txt ../out/6f/59/Burwash_Hall.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/30/AdolfHitler.txt ../out/70/30/AdolfHitler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/de/Climate_Change.txt ../out/70/de/Climate_Change.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/bb/Brain.txt ../out/71/bb/Brain.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/50/Acquis_communautaire.txt ../out/72/50/Acquis_communautaire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/09/Claudius.txt ../out/73/09/Claudius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/ad/Amebas_%28pseudopod_protists%29.txt ../out/73/ad/Amebas_%28pseudopod_protists%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/57/Benchmark.txt ../out/74/57/Benchmark.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/ad/Challenger_Deep.txt ../out/74/ad/Challenger_Deep.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/6f/Dinosaur.txt ../out/75/6f/Dinosaur.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/29/Deconstruction.txt ../out/76/29/Deconstruction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/c3/BND.txt ../out/76/c3/BND.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/70/Transport_in_El_Salvador.txt ../out/77/70/Transport_in_El_Salvador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/2f/AnarchoCapitalism.txt ../out/78/2f/AnarchoCapitalism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/bf/Channel_Tunnel.txt ../out/78/bf/Channel_Tunnel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/71/Complexity.txt ../out/79/71/Complexity.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/df/Ark_of_the_Covenant.txt ../out/79/df/Ark_of_the_Covenant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/7e/EISA.txt ../out/7a/7e/EISA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/cf/Dracula.txt ../out/7a/cf/Dracula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/72/Attorney.txt ../out/7b/72/Attorney.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/3d/Dynamical_system.txt ../out/7c/3d/Dynamical_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/fa/Edda.txt ../out/7c/fa/Edda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/73/CGI.txt ../out/7d/73/CGI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/37/Black_Hand_%28Serbia%29.txt ../out/7e/37/Black_Hand_%28Serbia%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/e2/Ataxia.txt ../out/7e/e2/Ataxia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/94/Anglican_Communion.txt ../out/7f/94/Anglican_Communion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/fd/EartH.txt ../out/7f/fd/EartH.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/54/List_of_Byzantine_emperors.txt ../out/80/54/List_of_Byzantine_emperors.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/1e/Cytoplasm.txt ../out/81/1e/Cytoplasm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/ce/Carboxylic_acid.txt ../out/81/ce/Carboxylic_acid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/75/History_of_Costa_Rica.txt ../out/82/75/History_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/6a/Alfred_Hitchcocks_Rope.txt ../out/83/6a/Alfred_Hitchcocks_Rope.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/ed/Classical_Element%2FEther.txt ../out/83/ed/Classical_Element%2FEther.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/e0/DefinitionOfLogic.txt ../out/84/e0/DefinitionOfLogic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/70/Dendrite.txt ../out/85/70/Dendrite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/03/Aztlan_Underground.txt ../out/86/03/Aztlan_Underground.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/9e/Cerebral_arteriovenous_malformation.txt ../out/86/9e/Cerebral_arteriovenous_malformation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/36/Doris_Day.txt ../out/87/36/Doris_Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/06/Amber.txt ../out/88/06/Amber.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/bd/Cayuga_Lake.txt ../out/88/bd/Cayuga_Lake.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/5b/CountriesR.txt ../out/89/5b/CountriesR.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/fa/American_Football_Conference.txt ../out/89/fa/American_Football_Conference.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/ab/Diplomatic_mission.txt ../out/8a/ab/Diplomatic_mission.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/5f/Cambodian_Language.txt ../out/8b/5f/Cambodian_Language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/0a/Admiral_Doenitz.txt ../out/8c/0a/Admiral_Doenitz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/a5/The_Cider_House_Rules.txt ../out/8c/a5/The_Cider_House_Rules.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/1d/Anglo-Saxon_%28disambiguation%29.txt ../out/8d/1d/Anglo-Saxon_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/fe/The_Ashes.txt ../out/8d/fe/The_Ashes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/b5/Asa.txt ../out/8e/b5/Asa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/76/Diamond.txt ../out/8f/76/Diamond.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/27/Bell_curve.txt ../out/90/27/Bell_curve.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/f9/Con.txt ../out/90/f9/Con.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/c1/Afonso_III_of_Portugal.txt ../out/91/c1/Afonso_III_of_Portugal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/b4/Audi.txt ../out/92/b4/Audi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/75/Decimal.txt ../out/93/75/Decimal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/f7/E._E._Cummings.txt ../out/93/f7/E._E._Cummings.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/1b/Almoravid_dynasty.txt ../out/95/1b/Almoravid_dynasty.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/8d/Electromagnetic_field.txt ../out/95/8d/Electromagnetic_field.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/2c/Beachcomber_%28pen_name%29.txt ../out/96/2c/Beachcomber_%28pen_name%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/ed/Antacid.txt ../out/96/ed/Antacid.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/71/Cygnus_%28constellation%29.txt ../out/97/71/Cygnus_%28constellation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/14/Comedy_Film.txt ../out/98/14/Comedy_Film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/6a/Cucurbitaceae.txt ../out/98/6a/Cucurbitaceae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/1d/Convention_of_the_Metre.txt ../out/99/1d/Convention_of_the_Metre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/9f/Chemical_vapor_deposition.txt ../out/99/9f/Chemical_vapor_deposition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/32/Anyone_Can_Whistle.txt ../out/9a/32/Anyone_Can_Whistle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/8d/Mexican_tetra.txt ../out/9a/8d/Mexican_tetra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/3d/Amanda_Hesser.txt ../out/9b/3d/Amanda_Hesser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/f1/Cuzco_%28disambiguation%29.txt ../out/9b/f1/Cuzco_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/61/Dumbarton_Bridge_%28California%29.txt ../out/9c/61/Dumbarton_Bridge_%28California%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/00/Caltrans.txt ../out/9d/00/Caltrans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/83/Amalaric.txt ../out/9d/83/Amalaric.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/12/Communion.txt ../out/9e/12/Communion.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/15/Chuck_Yeager.txt ../out/9f/15/Chuck_Yeager.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/c6/EBCDIC.txt ../out/9f/c6/EBCDIC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/52/Artemus_Ward.txt ../out/a0/52/Artemus_Ward.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/28/Chris_Cunningham.txt ../out/a1/28/Chris_Cunningham.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/13/A_Doll%27s_House.txt ../out/a2/13/A_Doll%27s_House.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/c0/Establishing_Shot.txt ../out/a2/c0/Establishing_Shot.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/7b/Demographics_of_Egypt.txt ../out/a3/7b/Demographics_of_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/13/Conciliation.txt ../out/a4/13/Conciliation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/ca/Ecuador%E2%80%93United_States_relations.txt ../out/a4/ca/Ecuador%E2%80%93United_States_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/29/Communist.txt ../out/a5/29/Communist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/ab/Bannock.txt ../out/a5/ab/Bannock.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/5f/Disk_operating_system.txt ../out/a6/5f/Disk_operating_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/01/Dyson_sphere.txt ../out/a7/01/Dyson_sphere.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/cc/Bell_%28disambiguation%29.txt ../out/a7/cc/Bell_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/8f/Albania%2FHistory.txt ../out/a8/8f/Albania%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/64/Calcium.txt ../out/a9/64/Calcium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/23/Anton_Drexler.txt ../out/aa/23/Anton_Drexler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/9f/Alexander_III.txt ../out/aa/9f/Alexander_III.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/15/Geography_of_Ivory_Coast.txt ../out/ab/15/Geography_of_Ivory_Coast.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/ad/Unitary_patent.txt ../out/ab/ad/Unitary_patent.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/57/Chain_termination_method.txt ../out/ac/57/Chain_termination_method.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/b4/Asexual_reproduction.txt ../out/ac/b4/Asexual_reproduction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/56/Absolute_value.txt ../out/ad/56/Absolute_value.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/12/Brass_instrument.txt ../out/ae/12/Brass_instrument.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/a9/Basel.txt ../out/ae/a9/Basel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/47/Bob_Wills.txt ../out/af/47/Bob_Wills.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/d8/Agnostida.txt ../out/af/d8/Agnostida.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/54/Cenozoic.txt ../out/b0/54/Cenozoic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/20/Carsons_rule.txt ../out/b1/20/Carsons_rule.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/b0/DKW.txt ../out/b1/b0/DKW.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/23/Cryptographer.txt ../out/b2/23/Cryptographer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/f4/Demographics_of_Bosnia_and_Herzegovina.txt ../out/b2/f4/Demographics_of_Bosnia_and_Herzegovina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/db/Cushitic_languages.txt ../out/b3/db/Cushitic_languages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/8c/Book_of_Numbers.txt ../out/b4/8c/Book_of_Numbers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/c8/Class_%28computer_programming%29.txt ../out/b4/c8/Class_%28computer_programming%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/31/DataSeT.txt ../out/b5/31/DataSeT.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/a1/Baptism.txt ../out/b5/a1/Baptism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/3d/Telecommunications_in_the_Democratic_Republic_of_the_Congo.txt ../out/b6/3d/Telecommunications_in_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/35/Government_of_Bouvet_Island.txt ../out/b7/35/Government_of_Bouvet_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/c7/Longest_word_in_English.txt ../out/b7/c7/Longest_word_in_English.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/62/Durham_University_%28England%29.txt ../out/b8/62/Durham_University_%28England%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/1f/Abalone.txt ../out/b9/1f/Abalone.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/e1/Bronze_Age.txt ../out/b9/e1/Bronze_Age.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/8b/Chronic_Fatigue_Syndrome%2FThe_name.txt ../out/ba/8b/Chronic_Fatigue_Syndrome%2FThe_name.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/2c/Blowfish_%28cipher%29.txt ../out/bb/2c/Blowfish_%28cipher%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/9b/Celtic_tribes_of_the_British_Isles.txt ../out/bb/9b/Celtic_tribes_of_the_British_Isles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/57/Concept_album.txt ../out/bc/57/Concept_album.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/e4/Cadence.txt ../out/bc/e4/Cadence.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/b3/Clipperton_Island%2FHistory.txt ../out/bd/b3/Clipperton_Island%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/74/Affiliation_%28family_law%29.txt ../out/be/74/Affiliation_%28family_law%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/1e/Dona_Marina.txt ../out/bf/1e/Dona_Marina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/c5/Bryan_McLean.txt ../out/bf/c5/Bryan_McLean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/7e/Battleship_game.txt ../out/c0/7e/Battleship_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/52/Cerebrovascular_Accident.txt ../out/c1/52/Cerebrovascular_Accident.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/dc/Transport_in_Equatorial_Guinea.txt ../out/c1/dc/Transport_in_Equatorial_Guinea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/bb/Allotropy.txt ../out/c2/bb/Allotropy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/94/Automated_Alice%2FVI.txt ../out/c3/94/Automated_Alice%2FVI.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/0a/Customer_relationship_management.txt ../out/c4/0a/Customer_relationship_management.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/90/Astronomy_and_Astrophysics%2FHistory.txt ../out/c4/90/Astronomy_and_Astrophysics%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/6c/Capital.txt ../out/c5/6c/Capital.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/22/Demisesquicentennial.txt ../out/c6/22/Demisesquicentennial.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/f2/Arbitrage.txt ../out/c6/f2/Arbitrage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/92/Dipsacales.txt ../out/c7/92/Dipsacales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/4c/Control_theory.txt ../out/c8/4c/Control_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/33/Disk_storage.txt ../out/c9/33/Disk_storage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/af/Abraham.txt ../out/c9/af/Abraham.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/3a/Dalek.txt ../out/ca/3a/Dalek.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/11/Amplifier.txt ../out/cb/11/Amplifier.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/b5/Data_Encryption_Standard.txt ../out/cb/b5/Data_Encryption_Standard.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/a1/Dartmoor_wildlife.txt ../out/cc/a1/Dartmoor_wildlife.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/28/Body_mass_index.txt ../out/cd/28/Body_mass_index.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/b8/Abstract_data_type.txt ../out/cd/b8/Abstract_data_type.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/9f/Cursus_honorum.txt ../out/ce/9f/Cursus_honorum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/44/Ark_Royal.txt ../out/cf/44/Ark_Royal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/f6/Council_of_Chalcedon.txt ../out/cf/f6/Council_of_Chalcedon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/e9/Economy_of_Costa_Rica.txt ../out/d0/e9/Economy_of_Costa_Rica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/59/Approval_voting.txt ../out/d1/59/Approval_voting.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/35/Docetism.txt ../out/d2/35/Docetism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/c3/Aberdour.txt ../out/d2/c3/Aberdour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/74/Aron_Nimzowitsch.txt ../out/d3/74/Aron_Nimzowitsch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/f8/AZ_Alkmaar.txt ../out/d3/f8/AZ_Alkmaar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/db/A_E_Housman.txt ../out/d4/db/A_E_Housman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/72/Character_encodings_in_HTML.txt ../out/d5/72/Character_encodings_in_HTML.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/33/European_United_Left%E2%80%93Nordic_Green_Left.txt ../out/d6/33/European_United_Left%E2%80%93Nordic_Green_Left.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/b6/Animation.txt ../out/d6/b6/Animation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/43/December_3.txt ../out/d7/43/December_3.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/fb/Analysis_of_algorithms.txt ../out/d7/fb/Analysis_of_algorithms.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/e1/Geography_of_the_Cocos_%28Keeling%29_Islands.txt ../out/d8/e1/Geography_of_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/5a/Dictum_of_Kenilworth.txt ../out/d9/5a/Dictum_of_Kenilworth.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/03/December_20.txt ../out/da/03/December_20.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/b0/Bain-marie.txt ../out/da/b0/Bain-marie.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/2e/David_Fincher.txt ../out/db/2e/David_Fincher.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/07/Clive_Barker.txt ../out/dc/07/Clive_Barker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/89/Dmitry_Ivanovich_Mendeleev.txt ../out/dc/89/Dmitry_Ivanovich_Mendeleev.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/1a/Bronski_Beat.txt ../out/dd/1a/Bronski_Beat.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/b4/A.D..txt ../out/dd/b4/A.D..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/7a/Cuba_Libre.txt ../out/de/7a/Cuba_Libre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/1a/CD_ROM.txt ../out/df/1a/CD_ROM.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/00/Aberdovey.txt ../out/e0/00/Aberdovey.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/aa/Foreign_relations_of_Cyprus.txt ../out/e0/aa/Foreign_relations_of_Cyprus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/59/Alaska.txt ../out/e1/59/Alaska.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/0a/Bugzilla.txt ../out/e2/0a/Bugzilla.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/bc/DungeonMagazine.txt ../out/e2/bc/DungeonMagazine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/56/Angle_tribe.txt ../out/e3/56/Angle_tribe.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/04/Draco_%28lawgiver%29.txt ../out/e4/04/Draco_%28lawgiver%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/d7/Carolina_parakeet.txt ../out/e4/d7/Carolina_parakeet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/5f/Central_Dogma_Of_Genetics.txt ../out/e5/5f/Central_Dogma_Of_Genetics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/fa/Bitmap_font.txt ../out/e5/fa/Bitmap_font.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/97/Aston_Martin.txt ../out/e6/97/Aston_Martin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/8c/On-sight_climbing.txt ../out/e7/8c/On-sight_climbing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/2a/Economy_of_Christmas_Island.txt ../out/e8/2a/Economy_of_Christmas_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/c5/Dionysius_Thrax.txt ../out/e8/c5/Dionysius_Thrax.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/4e/Antonio_Canova.txt ../out/e9/4e/Antonio_Canova.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/c7/Columbus.txt ../out/e9/c7/Columbus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/50/ChrisMorris.txt ../out/ea/50/ChrisMorris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/ff/Daubentoniidae.txt ../out/ea/ff/Daubentoniidae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/b5/Chloramphenicol.txt ../out/eb/b5/Chloramphenicol.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/7d/Water_%28classical_element%29.txt ../out/ec/7d/Water_%28classical_element%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/54/Advanced_Power_Management.txt ../out/ed/54/Advanced_Power_Management.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/d7/Affection.txt ../out/ed/d7/Affection.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/79/Cyprinodontiformes.txt ../out/ee/79/Cyprinodontiformes.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/15/Browser.txt ../out/ef/15/Browser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/9d/Alexios_V_Doukas.txt ../out/ef/9d/Alexios_V_Doukas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/3a/Euphoria_%28disambiguation%29.txt ../out/f0/3a/Euphoria_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/f9/Archipelago.txt ../out/f0/f9/Archipelago.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/e7/Asterales.txt ../out/f1/e7/Asterales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/d3/Economy_of_the_Democratic_Republic_of_the_Congo.txt ../out/f2/d3/Economy_of_the_Democratic_Republic_of_the_Congo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/99/Transportation_in_American_Samoa.txt ../out/f3/99/Transportation_in_American_Samoa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/4e/Door.txt ../out/f4/4e/Door.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/25/Detroit_Lions.txt ../out/f5/25/Detroit_Lions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/dd/Absorption.txt ../out/f5/dd/Absorption.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/af/Bill_Haley.txt ../out/f6/af/Bill_Haley.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/1d/Hypothetical_types_of_biochemistry.txt ../out/f7/1d/Hypothetical_types_of_biochemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/ac/Book_of_Joshua.txt ../out/f7/ac/Book_of_Joshua.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/85/Economy_of_Colombia.txt ../out/f8/85/Economy_of_Colombia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/fb/Dodo_%28Alice%27s_Adventures_in_Wonderland%29.txt ../out/f8/fb/Dodo_%28Alice%27s_Adventures_in_Wonderland%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/5e/Birth_defect.txt ../out/f9/5e/Birth_defect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/08/Constantinople.txt ../out/fa/08/Constantinople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/91/Electronic_data_interchange.txt ../out/fa/91/Electronic_data_interchange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/3f/Danewerk.txt ../out/fb/3f/Danewerk.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/eb/Carbon.txt ../out/fb/eb/Carbon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/cf/Carnivora.txt ../out/fc/cf/Carnivora.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/92/Computer_worm.txt ../out/fd/92/Computer_worm.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/3f/Cuitl%C3%A1huac.txt ../out/fe/3f/Cuitl%C3%A1huac.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/e6/Aelia_Capitolina.txt ../out/fe/e6/Aelia_Capitolina.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/68/The_Birth_of_a_Nation.txt ../out/ff/68/The_Birth_of_a_Nation.xml
