php ./wiki2xml/php/wiki2xml_command.php ../out/00/13/Ca_plus_plus_antagonist.txt ../out/00/13/Ca_plus_plus_antagonist.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/00/ef/Corrodo_Gini.txt ../out/00/ef/Corrodo_Gini.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/01/a5/Euler%27s_formula.txt ../out/01/a5/Euler%27s_formula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/35/Albert_Gore.txt ../out/02/35/Albert_Gore.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/02/ee/Automated_Alice%2FIX.txt ../out/02/ee/Automated_Alice%2FIX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/03/8a/Standard_works.txt ../out/03/8a/Standard_works.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/1c/Andrea_Andreani.txt ../out/04/1c/Andrea_Andreani.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/04/a3/Devangari_alphabet.txt ../out/04/a3/Devangari_alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/43/Casino_games.txt ../out/05/43/Casino_games.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/05/bd/Cow_story.txt ../out/05/bd/Cow_story.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/06/64/AI-complete.txt ../out/06/64/AI-complete.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/03/History_of_Djibouti.txt ../out/07/03/History_of_Djibouti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/07/bd/Colleges_and_universities%2FOldList.txt ../out/07/bd/Colleges_and_universities%2FOldList.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/7f/Anazarbus.txt ../out/08/7f/Anazarbus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/08/fb/Deprogramming.txt ../out/08/fb/Deprogramming.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/09/d0/History_of_Botswana.txt ../out/09/d0/History_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0a/8c/Efficient_markets_theory.txt ../out/0a/8c/Efficient_markets_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/05/Bede.txt ../out/0b/05/Bede.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0b/a1/Cell_nucleus.txt ../out/0b/a1/Cell_nucleus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/18/Clitoridectomy.txt ../out/0c/18/Clitoridectomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0c/f4/Ababda_people.txt ../out/0c/f4/Ababda_people.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0d/be/Agathon.txt ../out/0d/be/Agathon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/4c/Ab.txt ../out/0e/4c/Ab.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0e/eb/Boxing_Day.txt ../out/0e/eb/Boxing_Day.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/0f/a9/Antares.txt ../out/0f/a9/Antares.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/10/b3/Boudica.txt ../out/10/b3/Boudica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/59/Aesthetic.txt ../out/11/59/Aesthetic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/11/f7/DFLP.txt ../out/11/f7/DFLP.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/12/a5/Chiapas.txt ../out/12/a5/Chiapas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/3f/Foreign_relations_of_Chad.txt ../out/13/3f/Foreign_relations_of_Chad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/13/bb/Dao.txt ../out/13/bb/Dao.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/14/96/Black_Sox_scandal.txt ../out/14/96/Black_Sox_scandal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/2c/Countably_infinite.txt ../out/15/2c/Countably_infinite.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/15/d7/Abstract_concept.txt ../out/15/d7/Abstract_concept.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/16/89/Andorra%2FTransnational_issues.txt ../out/16/89/Andorra%2FTransnational_issues.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/17/5f/David_Janssen.txt ../out/17/5f/David_Janssen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/08/List_of_games_based_on_Dune.txt ../out/18/08/List_of_games_based_on_Dune.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/18/90/Dual_Alliance_%281879%29.txt ../out/18/90/Dual_Alliance_%281879%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/11/Canadian_Unitarian_Council.txt ../out/19/11/Canadian_Unitarian_Council.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/19/ae/Aswan.txt ../out/19/ae/Aswan.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/47/Albinism.txt ../out/1a/47/Albinism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1a/b4/Anthropological_classification_of_homosexuality.txt ../out/1a/b4/Anthropological_classification_of_homosexuality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/5e/Budweiser.txt ../out/1b/5e/Budweiser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1b/e6/Processor_design.txt ../out/1b/e6/Processor_design.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/65/Antenna_theory.txt ../out/1c/65/Antenna_theory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1c/f0/Caapi.txt ../out/1c/f0/Caapi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1d/8f/Abadan%2C_Iran.txt ../out/1d/8f/Abadan%2C_Iran.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/35/Autumn.txt ../out/1e/35/Autumn.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1e/b7/B.C.E..txt ../out/1e/b7/B.C.E..xml
php ./wiki2xml/php/wiki2xml_command.php ../out/1f/b6/Ayahuasca.txt ../out/1f/b6/Ayahuasca.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/20/4f/Caravaggio.txt ../out/20/4f/Caravaggio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/06/Clockwork_Orange.txt ../out/21/06/Clockwork_Orange.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/21/cd/Amu_Darya.txt ../out/21/cd/Amu_Darya.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/22/94/Congressional_Medal_of_Honour.txt ../out/22/94/Congressional_Medal_of_Honour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/26/RUR-5_ASROC.txt ../out/23/26/RUR-5_ASROC.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/23/e5/Air_engine.txt ../out/23/e5/Air_engine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/24/65/Cracking_joints.txt ../out/24/65/Cracking_joints.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/1f/Corporatocracy.txt ../out/25/1f/Corporatocracy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/25/f2/Bay_leaf.txt ../out/25/f2/Bay_leaf.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/26/76/Encyclop%C3%A6dia_Britannica.txt ../out/26/76/Encyclop%C3%A6dia_Britannica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/2e/Era.txt ../out/27/2e/Era.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/27/e5/Assyria.txt ../out/27/e5/Assyria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/6b/Confucius.txt ../out/28/6b/Confucius.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/28/f9/Demeter.txt ../out/28/f9/Demeter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/29/a3/Afonso_de_Albuquerque.txt ../out/29/a3/Afonso_de_Albuquerque.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2a/58/EnglishChannel.txt ../out/2a/58/EnglishChannel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/44/Canis_Minor.txt ../out/2b/44/Canis_Minor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2b/c6/Democracy.txt ../out/2b/c6/Democracy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2c/6c/Canadian_football.txt ../out/2c/6c/Canadian_football.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/0a/Borneo.txt ../out/2d/0a/Borneo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2d/c7/Documentary_Film.txt ../out/2d/c7/Documentary_Film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2e/65/Chile.txt ../out/2e/65/Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/2f/3b/Cricket_World_Cup.txt ../out/2f/3b/Cricket_World_Cup.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/1b/Government_of_Antarctica.txt ../out/30/1b/Government_of_Antarctica.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/30/d7/Abzyme.txt ../out/30/d7/Abzyme.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/31/70/Cognitive_science.txt ../out/31/70/Cognitive_science.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/7b/Australian_Army.txt ../out/32/7b/Australian_Army.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/32/ef/Boeing_Vertol_CH-46_Sea_Knight.txt ../out/32/ef/Boeing_Vertol_CH-46_Sea_Knight.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/33/de/Computer_data_storage.txt ../out/33/de/Computer_data_storage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/34/b0/Aramaic_alphabet.txt ../out/34/b0/Aramaic_alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/3d/Ball.txt ../out/35/3d/Ball.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/35/d4/Diego_Garcia.txt ../out/35/d4/Diego_Garcia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/36/be/Bifr%C3%B6st.txt ../out/36/be/Bifr%C3%B6st.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/56/Extractor_%28mathematics%29.txt ../out/37/56/Extractor_%28mathematics%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/37/d7/Athenian_democracy.txt ../out/37/d7/Athenian_democracy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/38/40/Commodores.txt ../out/38/40/Commodores.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/38/Barnabas.txt ../out/39/38/Barnabas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/39/cb/Ethan_Allen.txt ../out/39/cb/Ethan_Allen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/58/Damages.txt ../out/3a/58/Damages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3a/d8/Geography_of_Egypt.txt ../out/3a/d8/Geography_of_Egypt.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/7d/Book_of_Exodus.txt ../out/3b/7d/Book_of_Exodus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3b/d3/History_of_Cameroon.txt ../out/3b/d3/History_of_Cameroon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3c/7d/The_American_Prisoner.txt ../out/3c/7d/The_American_Prisoner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/34/Battle_of_Waterloo.txt ../out/3d/34/Battle_of_Waterloo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3d/dd/Foreign_relations_of_Chile.txt ../out/3d/dd/Foreign_relations_of_Chile.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3e/99/DravidianLanguages.txt ../out/3e/99/DravidianLanguages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/0a/Earned_run.txt ../out/3f/0a/Earned_run.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/3f/88/Baku_%28spirit%29.txt ../out/3f/88/Baku_%28spirit%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/49/Drink.txt ../out/40/49/Drink.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/40/ce/Czech_republic.txt ../out/40/ce/Czech_republic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/9f/Alismatales.txt ../out/41/9f/Alismatales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/41/e6/APL_%28programming_language%29.txt ../out/41/e6/APL_%28programming_language%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/42/4e/Attribution_of_recent_climate_change.txt ../out/42/4e/Attribution_of_recent_climate_change.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/08/Explorers_program.txt ../out/43/08/Explorers_program.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/43/a2/Drum.txt ../out/43/a2/Drum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/6e/Government_of_Baker_Island.txt ../out/44/6e/Government_of_Baker_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/44/a8/AfricA.txt ../out/44/a8/AfricA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/45/72/Daily_Planet.txt ../out/45/72/Daily_Planet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/10/Archaeology%2FBroch.txt ../out/46/10/Archaeology%2FBroch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/46/f8/Denver_Broncos.txt ../out/46/f8/Denver_Broncos.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/47/98/Arraignment.txt ../out/47/98/Arraignment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/76/Alloys.txt ../out/48/76/Alloys.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/48/f8/Control_engineering.txt ../out/48/f8/Control_engineering.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/49/ac/Ariane_5.txt ../out/49/ac/Ariane_5.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/58/Angus.txt ../out/4a/58/Angus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4a/e4/Concrete_music.txt ../out/4a/e4/Concrete_music.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4b/7b/Detective_fiction.txt ../out/4b/7b/Detective_fiction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/1c/Archaeopteryx.txt ../out/4c/1c/Archaeopteryx.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4c/90/Alexandretta.txt ../out/4c/90/Alexandretta.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/5d/Ecuador.txt ../out/4d/5d/Ecuador.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4d/fc/DARPA.txt ../out/4d/fc/DARPA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4e/91/Cofinality.txt ../out/4e/91/Cofinality.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/1b/Blizzard_Entertainment.txt ../out/4f/1b/Blizzard_Entertainment.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/4f/dd/Archeopteryx.txt ../out/4f/dd/Archeopteryx.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/50/7f/Drama_film.txt ../out/50/7f/Drama_film.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/5d/Bagpuss.txt ../out/51/5d/Bagpuss.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/51/de/Politics_of_Canada.txt ../out/51/de/Politics_of_Canada.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/52/90/Electromagnetism.txt ../out/52/90/Electromagnetism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/29/Crochet.txt ../out/53/29/Crochet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/53/c3/Castle_of_the_Winds.txt ../out/53/c3/Castle_of_the_Winds.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/42/%C3%89douard_Manet.txt ../out/54/42/%C3%89douard_Manet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/54/d2/Curl_Contents_Language.txt ../out/54/d2/Curl_Contents_Language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/55/8b/Draupnir.txt ../out/55/8b/Draupnir.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/56/2e/Ailuropoda_melanoleuca.txt ../out/56/2e/Ailuropoda_melanoleuca.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/32/Adenosine_triphosphate.txt ../out/57/32/Adenosine_triphosphate.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/57/e1/Abae.txt ../out/57/e1/Abae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/58/7a/Croquet.txt ../out/58/7a/Croquet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/1f/Deduction_and_induction.txt ../out/59/1f/Deduction_and_induction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/59/c5/Atom%2FBohr_model.txt ../out/59/c5/Atom%2FBohr_model.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/55/Butterfly_effect.txt ../out/5a/55/Butterfly_effect.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5a/d1/Board_game.txt ../out/5a/d1/Board_game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5b/6e/Agar.txt ../out/5b/6e/Agar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/33/Alexander_Jagiellon.txt ../out/5c/33/Alexander_Jagiellon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5c/db/British_Open_%28disambiguation%29.txt ../out/5c/db/British_Open_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5d/97/Garbage_collection_%28computer_science%29.txt ../out/5d/97/Garbage_collection_%28computer_science%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/51/ArgoUML.txt ../out/5e/51/ArgoUML.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5e/c6/Albert_Brooks.txt ../out/5e/c6/Albert_Brooks.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/5f/c1/Ashmore_and_Cartier_Islands.txt ../out/5f/c1/Ashmore_and_Cartier_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/60/3b/Auriga.txt ../out/60/3b/Auriga.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/0a/Automated_Alice%2FVII.txt ../out/61/0a/Automated_Alice%2FVII.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/61/98/AtlasShrugged.txt ../out/61/98/AtlasShrugged.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/62/30/Ahimsa.txt ../out/62/30/Ahimsa.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/23/Ani_DiFranco.txt ../out/63/23/Ani_DiFranco.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/63/e4/Extension.txt ../out/63/e4/Extension.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/64/c9/Compactron.txt ../out/64/c9/Compactron.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/44/Cincinnati_Reds.txt ../out/65/44/Cincinnati_Reds.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/65/df/Cornish_Nationalist_Party.txt ../out/65/df/Cornish_Nationalist_Party.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/39/Atomic_number.txt ../out/66/39/Atomic_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/66/f6/Corvus.txt ../out/66/f6/Corvus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/67/74/Clarinet.txt ../out/67/74/Clarinet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/1d/Actinopterygii.txt ../out/68/1d/Actinopterygii.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/68/bf/Dutch.txt ../out/68/bf/Dutch.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/69/90/Acephali.txt ../out/69/90/Acephali.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/3a/Aeolus.txt ../out/6a/3a/Aeolus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6a/bd/Constitution_of_Canada%2F1867_Preamble.txt ../out/6a/bd/Constitution_of_Canada%2F1867_Preamble.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/49/Arsenic.txt ../out/6b/49/Arsenic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6b/fa/Environmental_Modification.txt ../out/6b/fa/Environmental_Modification.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/65/Alvar_Aalto.txt ../out/6c/65/Alvar_Aalto.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6c/f4/Dayton%2C_Ohio.txt ../out/6c/f4/Dayton%2C_Ohio.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6d/a8/Concord%2C_New_Hampshire.txt ../out/6d/a8/Concord%2C_New_Hampshire.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/4b/Bus.txt ../out/6e/4b/Bus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6e/b4/Vladimir_Harkonnen.txt ../out/6e/b4/Vladimir_Harkonnen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/6f/34/Booch_method.txt ../out/6f/34/Booch_method.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/1a/Cortex.txt ../out/70/1a/Cortex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/70/bf/Digital_television.txt ../out/70/bf/Digital_television.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/71/b5/Denis_Auguste_Affre.txt ../out/71/b5/Denis_Auguste_Affre.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/47/Non-independent_areas.txt ../out/72/47/Non-independent_areas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/72/f0/Blind_Cave_Tetra.txt ../out/72/f0/Blind_Cave_Tetra.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/73/a2/Aldebaran.txt ../out/73/a2/Aldebaran.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/56/Endangered_Species.txt ../out/74/56/Endangered_Species.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/74/a3/Albert_Schweitzer.txt ../out/74/a3/Albert_Schweitzer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/75/60/Albert_Einstein.txt ../out/75/60/Albert_Einstein.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/0d/DaoDeJing.txt ../out/76/0d/DaoDeJing.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/76/ac/Tank_destroyer.txt ../out/76/ac/Tank_destroyer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/77/5b/Diophantine_equation.txt ../out/77/5b/Diophantine_equation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/21/Amati.txt ../out/78/21/Amati.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/78/b5/Deutschlandlied.txt ../out/78/b5/Deutschlandlied.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/62/Frederic_Henry.txt ../out/79/62/Frederic_Henry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/79/d5/ClearType.txt ../out/79/d5/ClearType.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/77/Astronomer.txt ../out/7a/77/Astronomer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7a/cc/Classical_Kuiper_belt_object.txt ../out/7a/cc/Classical_Kuiper_belt_object.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7b/6f/Darwin%27s_Dangerous_Idea.txt ../out/7b/6f/Darwin%27s_Dangerous_Idea.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/32/Erbium.txt ../out/7c/32/Erbium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7c/f1/Diacritic.txt ../out/7c/f1/Diacritic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7d/61/Community.txt ../out/7d/61/Community.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/1e/Economics.txt ../out/7e/1e/Economics.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7e/c1/Angula.txt ../out/7e/c1/Angula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/8e/Diarists.txt ../out/7f/8e/Diarists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/7f/e1/Colloids.txt ../out/7f/e1/Colloids.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/80/4e/Economic_calculation_problem.txt ../out/80/4e/Economic_calculation_problem.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/0e/Array_data_structure.txt ../out/81/0e/Array_data_structure.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/81/af/Battle_of_Ardrianople.txt ../out/81/af/Battle_of_Ardrianople.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/82/61/Christoph_Ludwig_Agricola.txt ../out/82/61/Christoph_Ludwig_Agricola.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/52/Chicago_Bears.txt ../out/83/52/Chicago_Bears.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/83/de/Bela_Lugosi.txt ../out/83/de/Bela_Lugosi.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/84/cf/Chemistry.txt ../out/84/cf/Chemistry.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/68/William_M._Tweed.txt ../out/85/68/William_M._Tweed.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/85/eb/Carl_Rogers.txt ../out/85/eb/Carl_Rogers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/86/7f/DES_%28disambiguation%29.txt ../out/86/7f/DES_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/24/Books_of_Chronicles.txt ../out/87/24/Books_of_Chronicles.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/87/e0/Ajax_the_Lesser.txt ../out/87/e0/Ajax_the_Lesser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/88/a8/Roman_censor.txt ../out/88/a8/Roman_censor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/47/CountriesX.txt ../out/89/47/CountriesX.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/89/f3/Checksum.txt ../out/89/f3/Checksum.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8a/91/Czes%C5%82aw_Mi%C5%82osz.txt ../out/8a/91/Czes%C5%82aw_Mi%C5%82osz.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8b/53/Amdahl%27s_law.txt ../out/8b/53/Amdahl%27s_law.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/03/Clitoris.txt ../out/8c/03/Clitoris.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8c/9d/Boomerang.txt ../out/8c/9d/Boomerang.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/17/Decade_%28Neil_Young_album%29.txt ../out/8d/17/Decade_%28Neil_Young_album%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8d/ca/Code_coverage.txt ../out/8d/ca/Code_coverage.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8e/9d/General_Conference_on_Weights_and_Measures.txt ../out/8e/9d/General_Conference_on_Weights_and_Measures.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/8f/69/Violin_Sonata_No._5_%28Beethoven%29.txt ../out/8f/69/Violin_Sonata_No._5_%28Beethoven%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/22/Demographics_of_Cape_Verde.txt ../out/90/22/Demographics_of_Cape_Verde.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/90/e9/History_of_the_term_%22Catholic%22.txt ../out/90/e9/History_of_the_term_%22Catholic%22.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/91/92/CoBoL.txt ../out/91/92/CoBoL.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/92/98/Amy_Grant.txt ../out/92/98/Amy_Grant.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/65/Demographics_of_Baker_Island.txt ../out/93/65/Demographics_of_Baker_Island.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/93/f2/Arabic_%28disambiguation%29.txt ../out/93/f2/Arabic_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/94/f8/Baltic_language.txt ../out/94/f8/Baltic_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/95/7b/Africa%2FHistory.txt ../out/95/7b/Africa%2FHistory.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/23/ErnestHemingway%2FTheTimeinBetween.txt ../out/96/23/ErnestHemingway%2FTheTimeinBetween.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/96/db/Abigail.txt ../out/96/db/Abigail.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/97/6d/Analog_computer.txt ../out/97/6d/Analog_computer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/04/B52_%28disambiguation%29.txt ../out/98/04/B52_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/98/5d/Affirmation_%28declaration_of_truth%29.txt ../out/98/5d/Affirmation_%28declaration_of_truth%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/0d/Abana_River.txt ../out/99/0d/Abana_River.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/99/95/Boehmen.txt ../out/99/95/Boehmen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/18/European_Union.txt ../out/9a/18/European_Union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9a/82/Caste.txt ../out/9a/82/Caste.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/24/On-base_plus_slugging.txt ../out/9b/24/On-base_plus_slugging.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9b/d8/Class.txt ../out/9b/d8/Class.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/4e/DavidFriedman.txt ../out/9c/4e/DavidFriedman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9c/fa/Chicago.txt ../out/9c/fa/Chicago.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9d/77/Asymmetrical_relationship.txt ../out/9d/77/Asymmetrical_relationship.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9e/0d/Prince_Eugene_of_Savoy.txt ../out/9e/0d/Prince_Eugene_of_Savoy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/01/Clifford_Adams.txt ../out/9f/01/Clifford_Adams.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/9f/b0/Box-cutter_knives.txt ../out/9f/b0/Box-cutter_knives.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a0/50/CountriesZ.txt ../out/a0/50/CountriesZ.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/1d/Battle_of_Berestechko.txt ../out/a1/1d/Battle_of_Berestechko.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a1/ee/Carnatic.txt ../out/a1/ee/Carnatic.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a2/98/Crowley_on_egolessness.txt ../out/a2/98/Crowley_on_egolessness.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/42/Anchor.txt ../out/a3/42/Anchor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a3/fa/August_Wilhelm_Ambros.txt ../out/a3/fa/August_Wilhelm_Ambros.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a4/bd/Darwin.txt ../out/a4/bd/Darwin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/18/Disperser.txt ../out/a5/18/Disperser.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a5/9e/Deutsches_Institut_f%C3%BCr_Normung.txt ../out/a5/9e/Deutsches_Institut_f%C3%BCr_Normung.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/47/Erd%C5%91s_number.txt ../out/a6/47/Erd%C5%91s_number.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a6/fa/Politics_of_Djibouti.txt ../out/a6/fa/Politics_of_Djibouti.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a7/b5/Dinosauria.txt ../out/a7/b5/Dinosauria.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a8/86/Baader-Meinhof-Gang.txt ../out/a8/86/Baader-Meinhof-Gang.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/a9/4a/Archbishop_of_Canterbury.txt ../out/a9/4a/Archbishop_of_Canterbury.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/10/Carl_Menger.txt ../out/aa/10/Carl_Menger.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/aa/93/British_and_Irish_Lions.txt ../out/aa/93/British_and_Irish_Lions.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/0f/Eindhoven_University_of_Technology.txt ../out/ab/0f/Eindhoven_University_of_Technology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ab/9a/Dyne.txt ../out/ab/9a/Dyne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/31/Military_of_the_Cocos_%28Keeling%29_Islands.txt ../out/ac/31/Military_of_the_Cocos_%28Keeling%29_Islands.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ac/a6/Ally_McBeal.txt ../out/ac/a6/Ally_McBeal.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ad/39/Domination_and_submission.txt ../out/ad/39/Domination_and_submission.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/0d/CumulativeDistributionFunction.txt ../out/ae/0d/CumulativeDistributionFunction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ae/96/Bjarne_Stroustrup.txt ../out/ae/96/Bjarne_Stroustrup.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/39/Wikipedia%3AAdding_Wikipedia_articles_to_Nupedia.txt ../out/af/39/Wikipedia%3AAdding_Wikipedia_articles_to_Nupedia.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/af/cf/Continental_drift.txt ../out/af/cf/Continental_drift.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b0/4d/BeOS.txt ../out/b0/4d/BeOS.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/0f/Enya.txt ../out/b1/0f/Enya.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b1/af/Parallel_ATA.txt ../out/b1/af/Parallel_ATA.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/0d/Buendnis_90_-_Die_Gruenen.txt ../out/b2/0d/Buendnis_90_-_Die_Gruenen.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b2/e0/Ecumenical_council.txt ../out/b2/e0/Ecumenical_council.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b3/d2/Chomsky_normal_form.txt ../out/b3/d2/Chomsky_normal_form.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/67/Atlanta_Braves.txt ../out/b4/67/Atlanta_Braves.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b4/c6/Bundesrepublik_Deutschland.txt ../out/b4/c6/Bundesrepublik_Deutschland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/2d/Descending_Chain_Condition.txt ../out/b5/2d/Descending_Chain_Condition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b5/95/AV.txt ../out/b5/95/AV.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b6/35/Acts_of_Union_1707.txt ../out/b6/35/Acts_of_Union_1707.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/23/August_21.txt ../out/b7/23/August_21.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b7/bf/Dimensional_analysis.txt ../out/b7/bf/Dimensional_analysis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/58/Daedalus.txt ../out/b8/58/Daedalus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b8/f2/Bayonne.txt ../out/b8/f2/Bayonne.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/b9/cc/Buffer_overflow.txt ../out/b9/cc/Buffer_overflow.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ba/71/Ahmed_al-Nami.txt ../out/ba/71/Ahmed_al-Nami.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/13/Application_program.txt ../out/bb/13/Application_program.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bb/91/Beatrix_Potter.txt ../out/bb/91/Beatrix_Potter.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/2d/Electronic_Music%2FJungle.txt ../out/bc/2d/Electronic_Music%2FJungle.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bc/ca/HM_Prison_Dartmoor.txt ../out/bc/ca/HM_Prison_Dartmoor.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bd/93/AustroAsiaticLanguages.txt ../out/bd/93/AustroAsiaticLanguages.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/be/63/Catalysis.txt ../out/be/63/Catalysis.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/0b/Abbas_Mirza.txt ../out/bf/0b/Abbas_Mirza.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/bf/aa/Alternative_medicine.txt ../out/bf/aa/Alternative_medicine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c0/70/Argument_form.txt ../out/c0/70/Argument_form.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/45/Datura.txt ../out/c1/45/Datura.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c1/c7/Deflation_%28disambiguation%29.txt ../out/c1/c7/Deflation_%28disambiguation%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c2/88/Computer_system.txt ../out/c2/88/Computer_system.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c3/5f/Analcime.txt ../out/c3/5f/Analcime.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/00/Aspirin.txt ../out/c4/00/Aspirin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c4/7b/Don_Delillo.txt ../out/c4/7b/Don_Delillo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c5/3a/Cell_Incubator.txt ../out/c5/3a/Cell_Incubator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/18/Cotton_Mather.txt ../out/c6/18/Cotton_Mather.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c6/e9/Digital_Equipment_Corporation.txt ../out/c6/e9/Digital_Equipment_Corporation.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c7/83/Air_transport.txt ../out/c7/83/Air_transport.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c8/3e/Chinese_Cuisine.txt ../out/c8/3e/Chinese_Cuisine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/23/Akira_Toriyama.txt ../out/c9/23/Akira_Toriyama.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/c9/97/Cross_ownership.txt ../out/c9/97/Cross_ownership.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ca/31/Anah.txt ../out/ca/31/Anah.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/04/Economy_of_Burkina_Faso.txt ../out/cb/04/Economy_of_Burkina_Faso.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cb/93/Ammonius_Saccas.txt ../out/cb/93/Ammonius_Saccas.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cc/84/Calculator.txt ../out/cc/84/Calculator.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/1a/DeMoivresFormula.txt ../out/cd/1a/DeMoivresFormula.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cd/ad/Aromatic_hydrocarbon.txt ../out/cd/ad/Aromatic_hydrocarbon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ce/8a/Email.txt ../out/ce/8a/Email.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/2c/Chymotrypsin.txt ../out/cf/2c/Chymotrypsin.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/cf/e2/Chalcedonian_Definition.txt ../out/cf/e2/Chalcedonian_Definition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d0/bd/Alexandria%2C_Louisiana.txt ../out/d0/bd/Alexandria%2C_Louisiana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d1/53/Communist_Party_of_the_Soviet_Union.txt ../out/d1/53/Communist_Party_of_the_Soviet_Union.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/13/Bean.txt ../out/d2/13/Bean.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d2/bc/America%27s_National_Game.txt ../out/d2/bc/America%27s_National_Game.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/56/Denormalization.txt ../out/d3/56/Denormalization.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d3/f5/Brunei.txt ../out/d3/f5/Brunei.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d4/c4/Black_and_Tans.txt ../out/d4/c4/Black_and_Tans.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d5/69/County_Mayo.txt ../out/d5/69/County_Mayo.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/13/A_priori_and_a_posteriori_knowledge.txt ../out/d6/13/A_priori_and_a_posteriori_knowledge.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d6/b0/Armageddon.txt ../out/d6/b0/Armageddon.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/39/Dorothy_Parker.txt ../out/d7/39/Dorothy_Parker.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d7/de/Abbon_of_Fleury.txt ../out/d7/de/Abbon_of_Fleury.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d8/d2/Dioscoreales.txt ../out/d8/d2/Dioscoreales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/55/Carme_%28moon%29.txt ../out/d9/55/Carme_%28moon%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/d9/f0/Boeing_767.txt ../out/d9/f0/Boeing_767.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/da/9f/Alvin_Toffler.txt ../out/da/9f/Alvin_Toffler.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/1e/Dominican_Order.txt ../out/db/1e/Dominican_Order.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/db/e2/Africa_Alphabet.txt ../out/db/e2/Africa_Alphabet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dc/5c/Abstract_%28law%29.txt ../out/dc/5c/Abstract_%28law%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/15/All_Quiet_on_the_Western_Front.txt ../out/dd/15/All_Quiet_on_the_Western_Front.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/dd/9e/EricHoffer.txt ../out/dd/9e/EricHoffer.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/de/75/Lists_of_composers.txt ../out/de/75/Lists_of_composers.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/0f/Classical_guitar.txt ../out/df/0f/Classical_guitar.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/df/e6/Colour.txt ../out/df/e6/Colour.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e0/80/Anatomy.txt ../out/e0/80/Anatomy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e1/58/Brassicaceae.txt ../out/e1/58/Brassicaceae.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/03/David_D._Friedman.txt ../out/e2/03/David_D._Friedman.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e2/ac/Corsican_language.txt ../out/e2/ac/Corsican_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/53/Dolly_%28sheep%29.txt ../out/e3/53/Dolly_%28sheep%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e3/ea/Commodore_1541.txt ../out/e3/ea/Commodore_1541.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e4/b4/Abjad.txt ../out/e4/b4/Abjad.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/41/Claude_Debussy.txt ../out/e5/41/Claude_Debussy.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e5/ee/Commandant_of_the_Marine_Corps.txt ../out/e5/ee/Commandant_of_the_Marine_Corps.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e6/80/Application_layer_firewalls.txt ../out/e6/80/Application_layer_firewalls.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e7/6b/Cross.txt ../out/e7/6b/Cross.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/15/Codex.txt ../out/e8/15/Codex.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e8/b8/Arecales.txt ../out/e8/b8/Arecales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/41/Blood_libel.txt ../out/e9/41/Blood_libel.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/e9/be/Britain_and_Ireland.txt ../out/e9/be/Britain_and_Ireland.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/29/Celtic_language.txt ../out/ea/29/Celtic_language.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ea/ec/Bank_of_China_Tower_%28Hong_Kong%29.txt ../out/ea/ec/Bank_of_China_Tower_%28Hong_Kong%29.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/eb/82/Curium.txt ../out/eb/82/Curium.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ec/75/Circuit_Park_Zandvoort.txt ../out/ec/75/Circuit_Park_Zandvoort.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/42/Anomalous_cognition.txt ../out/ed/42/Anomalous_cognition.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ed/be/Cross-examine.txt ../out/ed/be/Cross-examine.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/5f/Chinese_room.txt ../out/ee/5f/Chinese_room.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ee/ed/Authoritarinism.txt ../out/ee/ed/Authoritarinism.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ef/97/Abstraction.txt ../out/ef/97/Abstraction.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/34/Apple_II.txt ../out/f0/34/Apple_II.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f0/ee/Abandonment_of_wife_and_children.txt ../out/f0/ee/Abandonment_of_wife_and_children.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f1/ad/Bunsen_burner.txt ../out/f1/ad/Bunsen_burner.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f2/8f/April_22.txt ../out/f2/8f/April_22.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f3/70/Astronomers_and_Astrophysicists.txt ../out/f3/70/Astronomers_and_Astrophysicists.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f4/2e/Astronomical_aberration.txt ../out/f4/2e/Astronomical_aberration.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/1c/Foreign_relations_of_Botswana.txt ../out/f5/1c/Foreign_relations_of_Botswana.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f5/bf/Albert_of_Brandenburg-Ansbach.txt ../out/f5/bf/Albert_of_Brandenburg-Ansbach.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f6/64/Abatement_of_freehold.txt ../out/f6/64/Abatement_of_freehold.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/08/Ananda.txt ../out/f7/08/Ananda.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f7/89/Eureka%2C_Missouri.txt ../out/f7/89/Eureka%2C_Missouri.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/70/ALF_Tales.txt ../out/f8/70/ALF_Tales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f8/e8/Coldcut.txt ../out/f8/e8/Coldcut.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/5b/Adrian_I.txt ../out/f9/5b/Adrian_I.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/f9/fe/Catullus.txt ../out/f9/fe/Catullus.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fa/78/Chalmers_University_of_Technology.txt ../out/fa/78/Chalmers_University_of_Technology.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/31/Currency_code.txt ../out/fb/31/Currency_code.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fb/d9/Digitizing_tablet.txt ../out/fb/d9/Digitizing_tablet.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fc/be/Commelinales.txt ../out/fc/be/Commelinales.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fd/73/Cahn%E2%80%93Ingold%E2%80%93Prelog_priority_rules.txt ../out/fd/73/Cahn%E2%80%93Ingold%E2%80%93Prelog_priority_rules.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/28/Ellensburg%2C_Washington.txt ../out/fe/28/Ellensburg%2C_Washington.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/fe/d7/Camp_David.txt ../out/fe/d7/Camp_David.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/56/Belgium%2FForeign_relations.txt ../out/ff/56/Belgium%2FForeign_relations.xml
php ./wiki2xml/php/wiki2xml_command.php ../out/ff/fe/Cellulose.txt ../out/ff/fe/Cellulose.xml
